### ISSUE TITLE
How to achieve geometric optimization of orthographic projection?

### ISSUE THREAD

**Issue by ejtwe** [mitsuba-renderer/mitsuba3#1001]
## Summary
Hello, thank you very much for seeing this question and answering it. When I try to use orthographic projection to optimize geometry, the following error is reported:
RuntimeError: ​[Endpoint] OrthographicCamera::sample_direction(): not implemented!
Therefore, I refer to the perspective type to implement the sample_direction function in orthographic.cpp. 
But the geometry is poorly optimized, and the loss goes up instead of down.
So, how to use orthographic projection to optimize geometry?

## Steps to reproduce

1. Setting sensor type: 'orthographic'; integrator type: 'direct_reparam',
2. I refer to the perspective type to implement the sample_direction() function in orthographic.cpp, as follows:

          std::pair<DirectionSample3f, Spectrum>
                   sample_direction(const Interaction3f& it, const Point2f& /*sample*/,
                       Mask active) const override {
                   // Transform the reference point into the local coordinate system
                   Transform4f trafo = m_to_world.value();
                   Point3f ref_p = trafo.inverse().transform_affine(it.p);
          
                   // Check if it is outside of the clip range
                   DirectionSample3f ds = dr::zeros<DirectionSample3f>();
                   ds.pdf = 0.f;
                   active &= (ref_p.z() >= m_near_clip) && (ref_p.z() <= m_far_clip);
                   if (dr::none_or<false>(active))
                       return { ds, dr::zeros<Spectrum>() };
          
                   // Assuming m_film is the film or image plane
                   Point3f screen_sample = m_camera_to_sample * ref_p;
                  
                   // Calculate UV coordinates
                   ds.uv = Point2f(screen_sample.x(), screen_sample.y()); //???
          
                   active &= (ds.uv.x() >= 0) && (ds.uv.x() <= 1) && (ds.uv.y() >= 0) &&
                       (ds.uv.y() <= 1);
                   if (dr::none_or<false>(active))
                       return { ds, dr::zeros<Spectrum>() };
          
                   ds.uv *= m_resolution;
          
                   Vector3f local_d(ref_p);
                   Float dist = local_d.z();
                   Float inv_dist = dr::rcp(dist);
                   local_d *= inv_dist;
          
                   Vector3f d = m_to_world.value().transform_affine(Vector3f{ 0.f, 0.f, 1.f });
                   ds.p = trafo.transform_affine(m_sample_to_camera * Point3f(screen_sample.x(), screen_sample.y(), 0.0f));
                   ds.d = (ds.p - it.p) * inv_dist;
                   ds.dist = dist;
                   ds.n = trafo * Vector3f(0.0f, 0.0f, 1.0f);
                   ds.pdf = dr::select(active, Float(1.f), Float(0.f));
          
                   return { ds, Spectrum(importance(local_d) * inv_dist * inv_dist) };
               }
          
               Float importance(const Vector3f& d) const {
                   Float ct = Frame3f::cos_theta(d);
          
                   // Compute the position on the plane at distance 1
                   Point2f p(d.x(), d.y());
          
                   /* Check if the point lies to the front and inside the
                      chosen crop rectangle */
                   Mask valid = ct > 0 && m_image_rect.contains(p);
          
                   return dr::select(valid, m_normalization, 0.f);
               }

Thank you again！

**Comment by njroussel** [comment]
Hi @ejtwe

This is not supported.

There is an implicit assumption that the sensor follows a pinhole model in the `reparam` integrators. If you are familiar with reparameterziations, [this snippet of code](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/python/python/ad/reparam.py#L85-L89) is where we generate the auxiliary rays. As you can see they all share the same origin, whereas they should be parallel and disjoint in the case of an `orthographic` sensor.


This will be made more explicit in a next version,
