### ISSUE TITLE
forwarding direct_projective

### ISSUE THREAD

**Issue by zichenwang01** [mitsuba-renderer/mitsuba3#1028]
Hi,

I was trying out the new `direct_projective` integrator and my program halted when I forwarded a single translation parameter to the rendered image. I attached a simple reproducer ([code.zip](https://github.com/mitsuba-renderer/mitsuba3/files/13878013/code.zip)), including the Python script, the scene XML, and the OBJ file. Thanks!

I was running on the CUDA backend using an RTX A6000.

**Comment by ziyi-zhang** [comment]
Hi, 
I cannot reproduce the error with the latest public mitsuba. The gradient image is rendered and looks reasonable to me -- I can see some small bias with the default param, which is gone when using more samples, eg setting `proj_seed_spp = 512 * 4` (set `scatter_inc=True` if out of memory).

Could you provide more information about the crash?

**Comment by zichenwang01** [comment]
Hi Ziyi,

Thanks for the helpful information. After some further debugging it turned out that the program stopped responding at `mi.util.write_bitmap("grad.exr", grad)` . I could transform `grad` to numpy array and save it or convert it to `mi.Bitmap` and save a png, but I was having problems saving the exr. 

I was running this in a new conda environment. All I installed are numpy, drjit, mitsuba, matplotlib, seaborn, pandas. 

Let me know if you need any further information from me.

**Comment by wjakob** [comment]
@zichenwang01 , are you rebased onto the latest version of Mitsuba? In December last year, we pushed some multithread synchronization-related fixes that could be related to potential issues with `write_bitmap`.

**Comment by wjakob** [comment]
(If you are using the projective integrator, then you should have those fixes already. I am asking since you potentially have a custom version of Mitsuba that incorporates different changesets).
