### ISSUE TITLE
How to convert Float into int?

### ISSUE THREAD

**Issue by free7187** [mitsuba-renderer/mitsuba3#1030]
## Summary

 I want to convert the Float in the template into an int variable. I tried to use dr::floor2int(),but failed.

## System configuration

System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
  GPU: NVIDIA GeForce RTX 4090
  Python: 3.10.9 | packaged by Anaconda, Inc. | (main, Mar  1 2023, 18:18:15) [MSC v.1916 64 bit (AMD64)]
  NVidia driver: 536.25
  CUDA: 11.8.89
  LLVM: 15.-1.-1

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? False
     Compiled with: MSVC 19.37.32822.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description
I created a very simple function, after initializing Spectrum R[MAX_NUM] and assigning value. Get the corresponding array subscript according to the input Float distance. But because the array subscript should be of type int, this involves conversion from Float to int. In scalar mode it is simply float to int. But when compiled in cuda_ad_rgb mode, it becomes drjit::DiffArray<drjit::CUDAArray<float>>>. I tried to use dr::floor2int(), but it showed that there was no matching overloaded function.

**Comment by free7187** [comment]
Hi @rtabbara
Thank you for your patient responses. But I still don't understand the meaning of "Additionally, for JIT-variants...",and it seems that I met other bugs. Here takes my code as example:
```c++
Spectrum R[N_R]; 
Spectrum RValue(Float r) const{
        auto v_r = r / DELTA_R;
        UInt32 imin = v_r; 
        auto imax = imin + 1;
        Float t = v_r - imin;
        
        auto value_min = dr::gather<Spectrum>(R, imin);
        auto value_max = dr::gather<Spectrum>(R, imax);

        return dr::lerp(value_min, value_max, t); 
    }
```
I try to use this simple function to return the corresponding values in `R[N_R];`. Running this code in `cuda_ad_rgb` and `llvm_ad_rgb` mode ,it throws "Caught a critical exception: Not implemented, please use gather() variant that takes a array source argument."  In  `scalar_rgb` mode, it comes another bug : if my R[0] is [0,1,2], R[1] is [3,4,5] and so on; when accessing R[1] using `gather`, it will return [nan,3,4].The addresses of elements in R do not appear to be contiguous; there is a gap of one address between every two consecutive elements.

**Comment by rtabbara** [comment]
Hi @free7187,

For JIT-variants (cuda, llvm), `Float` here corresponds to a JitArray type, and the function `RValue` is vectorized. e.g.

```cpp
// Float with width 4
Float a -> [x1, x2, x3, x4]

// For RGB variants Spectrum = Color<Float,3>
// which is a structure of arrays. 
Color<Float, 3> x = RValue(a);

// Each R, G, B channel is a Float type (JitArray)
x.r() -> [r1, r2, r3, r4];
x.g() -> [g1, g2, g3, g4];
x.b() -> [b1, b2, b3, b4];
```

So `Spectrum R[N_R]` corresponds to a C-array of `Color<Float, 3>` which if you look at the unpacking above isn't want you want. 

Instead, for JIT-variants, you can store R as a single `Spectrum` variable

```cpp
float r_scalar[] = {r1, r2, ... , rN};
float g_scalar[] = {g1, g2, ... , gN};
float b_scalar[] = {b1, b2, ... , bN};

Float r = dr::load<Float>(r_scalar, N_R);
Float g = dr::load<Float>(g_scalar, N_R);
Float b = dr::load<Float>(b_scalar, N_R);

auto R = Color<Float, 3>(r, g, b);
```

Then when you perform a vectorized gather, you would get

```cpp
// imin here is a UInt32  which is also a JitArray type
// In this example, it similarly has a width of 4
Spectrum value_min = dr::gather<Spectrum>(R, imin);
value_min.r() -> [r1', r2', r3', r4']
value_min.g() -> [g1', g2', g3', g4']
value_min.b() -> [b1', b2', b3', b4']
```

**Comment by free7187** [comment]
Hi @rtabbara
Thank you very much for your answer, I am now completely clear.
