### ISSUE TITLE
Extended find_package support

### ISSUE THREAD

**Issue by SomeoneSerge** [mitsuba-renderer/mitsuba3#1035]
...or: "consider switching to `install`+`find_package`+`FetchContent`"

## Summary

Hi! Mitsuba3's CMake build currently relies on git submodules and `add_subdirectory` and/or `include(${PATH_TO_A_SUBMODULE})` to manage external dependencies, including other components of the project (e.g. `drjit-core`) and their transitive dependencies (e.g. `cmake-defaults`).

While possibly convenient for development, this may sometimes be an obstacle for deployment: for example, if the user wanted to apply a patch to one of the dependencies, they'd have to manually infer a deeply nested path (possibly several) inside the project and apply it there. Similarly, substituting one of the component with a different revision is cumbersome.

Git-submodules serve two functions: that of a lock file, i.e. they pin the dependencies, and secondly they automatically provision them when one checks out the repository or pulls the newer changes.

You could satisfy both of these needs, as well as make it easier to substitute and patch individual components, by making your projects (more consistently) compatible with `find_package`, and by using `FetchContent` to pin and provision the default versions of the dependencies. By using `FetchContent_MakeAvailable` with the `FIND_PACKAGE_ARGS` flag you would ensure that `find_package` is always attempted first, before CMake falls back to FetchContent's side-effects. This all would also require adding the "missing" `install` targets and `XXXXConfig.cmake` files into `drjit-core`, `cmake-defaults`, etc.

Deviating from the business for a moment, it's not hard to notice that `find_package` is a primitive "dependency injection" system (it makes your `CMakeLists.txt` a "constructor" and declares its arguments that the user needs to supply), whereas `FetchContent_MakeAvailalbe(... FIND_PACKAGE_ARGS ...)` serves to supply the parameters with default values.

One last argument against using git-submodules to provision the dependencies is that (without extra care) it's effectively another form of vendoring[ of dependencies]:  it lumps all of the dependencies together and tries to fetch everything in a single phase. This may seem innocuous but it might actually matter in other project depending on their goals and environments. For a specific example, I had attempted packaging mitsbua3 in Nixpgks back in November: https://github.com/NixOS/nixpkgs/pull/269378. The Nixpkgs project models a bunch of opensource software as pure data in a certain functional language, and its promise is that you can always inspect the full supply chain of a program, and you can always substitute any individual component somewhere deep in the dependency graph, or make all of the closure use the same version of a particular dependency (e.g. when you apply security patches) in a provable-by-construction manner. However, when we do something like `git clone --recursive` we have to treat the whole thing as a black box, and even if we tried to hand mitsuba3 a different version of nanobind, we couldn't prove it had used our version because it may have had access to something else.

## System configuration

System information:

<details>

  OS: `Linux 6.1.69, NixOS, 24.05 (Uakari), 24.05.20231224.5f64a12``
  CPU: `AMD Ryzen 9 5900X 12-Core Processor`
  GPU: `NVIDIA GeForce RTX 3090`
  Python version: 3.11
  LLVM version: 16.0.6
  CUDA version: 11.8
  NVidia driver: `545.29.06`

  Dr.Jit version: 2023-10-21
  Mitsuba version: a HEAD from 2023-11-23
     Compiled with: `-DMI_USE_SUBMODULES:BOOL=FALSE -DMI_ENABLE_EMBREE:BOOL=FALSE -DMI_DEFAULT_VARIANTS:STRING=scalar_rgb`, cf. https://gist.github.com/SomeoneSerge/782eda6be678188fb32930a51e0e9621
     Variants compiled: `scalar_rgb`

</details>

Thanks!

**Comment by wjakob** [comment]
Hi Serge,

unfortunately we aren't able to switch away from Git submodules. This is basically our version of a monorepository, split up into more fine-grained set of repositories. Almost all of them have heavy modifications needed to adapt them to Mitsuba. The security point of view you mentioned related to Nix is unfortunately not something we can consider. You should never use Mitsuba where it can be an attack surface. Our official deployment mechanism of Mitsuba is through PyPI, and we unfortunately cannot support others.

Wenzel

**Comment by SomeoneSerge** [comment]
Hi again! I acknowledge that you've made a decision, but I'll add a few more comments, at least in case this issue comes up in search results

> unfortunately we aren't able to switch away from Git submodules. This is basically our version of a monorepository, split up into more fine-grained set of repositories. Almost all of them have heavy modifications needed to adapt them to Mitsuba

I'd like to emphasize that FetchContent isn't inconsistent with e.g. applying custom patches or using your own forks of dependencies. Just one example: https://github.com/microsoft/onnxruntime/commit/87744e55faa8c7570d17f29f54f2ffdb8b702d04

> The security point of view ...

Is just one example. There are many reasons to modify/substitute dependencies at the user site, including e.g. compilation for unsupported platforms which might require slightly different patch sets. That said, you have made the scope of the project clear
