### ISSUE TITLE
Scaling an area light with params.update() after loading the scene

### ISSUE THREAD

**Issue by zengyf131** [mitsuba-renderer/mitsuba3#1047]
## Summary

I'm trying to scale an area light using params.update(), after loading the scene. But it seems that doing so will cause the brightness of the light source to behave weirdly. 

## System configuration

System information:

  OS: Windows 11
  CPU: i9-12900K
  GPU: RTX 3090
  Python version: 3.10.13
  LLVM version: ...
  CUDA version: 11.3.1
  NVidia driver: ...

  Dr.Jit version: 0.4.4
  Mitsuba version: 3.5.0
     Compiled with: ...
     Variants compiled: ...

## Description

I was following your [Object pose estimation tutorial](https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/object_pose_estimation.html), and was able to render the correct reference image. 
![img_normal](https://github.com/mitsuba-renderer/mitsuba3/assets/102571077/32b2bb02-aa27-43c9-9a18-b4bc857f7c9f)

However, when I tried to scale down the light source using `params.update()` after loading the scene instead of setting the 'to_world' parameter, the result image was different, and the scene became extremely bright. 
![img_bright](https://github.com/mitsuba-renderer/mitsuba3/assets/102571077/f68da4fd-db08-4982-9f96-526a3e9774bf)

## Steps to reproduce

1. code for reproducing this issue:
```
import drjit as dr
import mitsuba as mi

mi.set_variant('cuda_ad_rgb')

integrator = {
    'type': 'direct_projective',
}

from mitsuba.scalar_rgb import Transform4f as T

scene = mi.load_dict({
    'type': 'scene',
    'integrator': integrator,
    'sensor':  {
        'type': 'perspective',
        'to_world': T.look_at(
                        origin=(0, 0, 2),
                        target=(0, 0, 0),
                        up=(0, 1, 0)
                    ),
        'fov': 60,
        'film': {
            'type': 'hdrfilm',
            'width': 64,
            'height': 64,
            'rfilter': { 'type': 'gaussian' },
            'sample_border': True
        },
    },
    'wall': {
        'type': 'obj',
        'filename': '../scenes/meshes/rectangle.obj',
        'to_world': T.translate([0, 0, -2]).scale(2.0),
        'face_normals': True,
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (0.5, 0.5, 0.5) },
        }
    },
    'bunny': {
        'type': 'ply',
        'filename': '../scenes/meshes/bunny.ply',
        'to_world': T.scale(6.5),
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (0.3, 0.3, 0.75) },
        },
    },
    'light': {
        'type': 'obj',
        'filename': '../scenes/meshes/sphere.obj',
        'emitter': {
            'type': 'area',
            'radiance': {'type': 'rgb', 'value': [1e3, 1e3, 1e3]}
        },
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (0.3, 0.3, 0.75) },
        },
        # 'to_world': T.translate([2.5, 2.5, 7.0]).scale(0.25)
    }
})

params = mi.traverse(scene)
verts = dr.unravel(mi.Point3f, params['light.vertex_positions'])
t = mi.Transform4f.translate([2.5, 2.5, 7.0]).scale(0.25)
params['light.vertex_positions'] = dr.ravel(t @ verts)
params.update()

img_ref = mi.render(scene, seed=0, spp=1024)

mi.util.convert_to_bitmap(img_ref)
```
2. So this code is basically the same as the one in the tutorial, except that I commented out the 'to_world' setting of the light, and updated the 'vertex_positions' of the light after loading the scene. After some testing, I found that doing translation after loading the scene won't cause any issue, so it should only be related to scaling.
3. You could try different values for scaling, and it seems that only when no scaling is applied, the image would look the same as the one using 'to_world' setting .

**Comment by ziyi-zhang** [comment]
In `mesh.cpp`, the area pmf is not updated when the vertices are modified. The normalization value of m_area_pmf is the reciprocal area of the shape, which is multiplied when sampling the shape as an emitter.
By forcing a pmf re-build on `parameters_changed()`, the rendering is aligned with trafo the shape in xml.

@njroussel @rtabbara Shall we always re-build area pmf on vertex change? Surprising that the build function is a scalar for-loop over all faces.

**Comment by njroussel** [comment]
Thank you for looking into this @ziyi-zhang, I somehow completely missed this issue.

I remember seeing this logic when working on the projective sampling stuff, I thought this was properly supported. Anyway, I'll have a look at it now.
