### ISSUE TITLE
Radiance Field Reconstruction example doesn't work

### ISSUE THREAD

**Issue by efeklisov** [mitsuba-renderer/mitsuba3#1074]
## Summary

Radiance Field Reconstruction example doesn't work

## System configuration

  OS: Ubuntu 22.04.3 LTS
  CPU: AMD Ryzen 9 7900X 12-Core Processor
  GPU: NVIDIA GeForce RTX 4090
  Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
  NVidia driver: 545.23.08
  CUDA: 11.8.89
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Some cells error out. "Setting up the optimization scene" first cells gives `ValueError: too many values to unpack (expected 3)`; "Optimization" second cells gives `Exception: loop_process_state(): one of the supplied loop state variables of type Float is uninitialized!`

## Steps to reproduce

1. Download notebook
2. Run cells in order

**Comment by njroussel** [comment]
Hi @efeklisov 

Sorry, this is an issue on our end. The tutorial download link always points to `master` and we have pushed updates which are no longer compatible with the most recent PyPI release.

[Here is the diff of the commit](https://github.com/mitsuba-renderer/mitsuba-tutorials/commit/42fffc6d85bb8b2423baca26b811b7662444ffe7) that broke that tutorial. You basically just need to remove the empty list initializer from the return statement in the `sample` function.
Alternatively, you can just download the old version of the file: https://github.com/mitsuba-renderer/mitsuba-tutorials/blob/e5dd59d743ba24a14516041c6db050ed73445b2c/inverse_rendering/radiance_field_reconstruction.ipynb

Thank you for pointing this out.
