### ISSUE TITLE
Object pose estimation tutorial not converging on a good solution

### ISSUE THREAD

**Issue by lopsided** [mitsuba-renderer/mitsuba3#1077]
## Summary

I've been trying to get the object pose estimation tutorial code running locally. It runs fine but the error just increases and the results are bad. I have just copied and pasted all the code from the tutorial page into a python script. I've tried with `cuda_ad_rgb` and `llvm_ad_rgb` variants and `direct_projective` and `prb_projective` integrators. All combinations give pretty much the same result.
https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/object_pose_estimation.html

## System configuration

System information:

  OS: Fedora 38
  CPU: 13th Gen Intel(R) Core(TM) i9-13950HX
  GPU: NVIDIA GeForce RTX 4090 Laptop GPU
  Python: 3.9.18 | packaged by conda-forge | (main, Dec 23 2023, 16:33:10) [GCC 12.3.0]
  NVidia driver: 545.29.06
  LLVM: 16.0.6

  Dr.Jit: 0.4.4
  Mitsuba: 3.5.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Putting the full script here for completion:

````
import drjit as dr
import matplotlib.pyplot as plt
import mitsuba as mi

mi.set_variant('cuda_ad_rgb')
# mi.set_variant('llvm_ad_rgb')

from mitsuba.scalar_rgb import Transform4f as T

def pose_estimation():
    integrator = {
        'type': 'direct_projective',
    }

    scene = mi.load_dict({
        'type': 'scene',
        'integrator': integrator,
        'sensor': {
            'type': 'perspective',
            'to_world': T.look_at(
                origin=(0, 0, 2),
                target=(0, 0, 0),
                up=(0, 1, 0)
            ),
            'fov': 60,
            'film': {
                'type': 'hdrfilm',
                'width': 64,
                'height': 64,
                'rfilter': {'type': 'gaussian'},
                'sample_border': True
            },
        },
        'wall': {
            'type': 'obj',
            'filename': str(SCENE_PATH / 'meshes'/ 'rectangle.obj'),
            'to_world': T.translate([0, 0, -2]).scale(2.0),
            'face_normals': True,
            'bsdf': {
                'type': 'diffuse',
                'reflectance': {'type': 'rgb', 'value': (0.5, 0.5, 0.5)},
            }
        },
        'bunny': {
            'type': 'ply',
            'filename': str(SCENE_PATH / 'meshes'/ 'bunny.ply'),
            'to_world': T.scale(6.5),
            'bsdf': {
                'type': 'diffuse',
                'reflectance': {'type': 'rgb', 'value': (0.3, 0.3, 0.75)},
            },
        },
        'light': {
            'type': 'obj',
            'filename': str(SCENE_PATH / 'meshes'/ 'sphere.obj'),
            'emitter': {
                'type': 'area',
                'radiance': {'type': 'rgb', 'value': [1e3, 1e3, 1e3]}
            },
            'to_world': T.translate([2.5, 2.5, 7.0]).scale(0.25)
        }
    })

    img_ref = mi.render(scene, seed=0, spp=1024)
    mi.util.convert_to_bitmap(img_ref)
    params = mi.traverse(scene)
    initial_vertex_positions = dr.unravel(mi.Point3f, params['bunny.vertex_positions'])

    opt = mi.ad.Adam(lr=0.025)
    opt['angle'] = mi.Float(0.25)
    opt['trans'] = mi.Point2f(0.1, -0.25)

    def apply_transformation(params, opt):
        opt['trans'] = dr.clamp(opt['trans'], -0.5, 0.5)
        opt['angle'] = dr.clamp(opt['angle'], -0.5, 0.5)

        trafo = mi.Transform4f.translate([opt['trans'].x, opt['trans'].y, 0.0]).rotate([0, 1, 0], opt['angle'] * 100.0)

        params['bunny.vertex_positions'] = dr.ravel(trafo @ initial_vertex_positions)
        params.update()

    apply_transformation(params, opt)
    img_init = mi.render(scene, seed=0, spp=1024)

    iteration_count = 50
    spp = 32

    loss_hist = []
    for i in range(iteration_count):
        # Apply the mesh transformation
        apply_transformation(params, opt)

        # Perform a differentiable rendering
        img = mi.render(scene, params, seed=i, spp=spp)

        # Evaluate the objective function
        loss = dr.sum(dr.sqr(img - img_ref)) / len(img)

        # Backpropagate through the rendering process
        dr.backward(loss)

        # Optimizer: take a gradient descent step
        opt.step()

        loss_hist.append(loss)
        print(f"Iteration {i:02d}: error={loss[0]:6f}, angle={opt['angle'][0]:.4f}, "
              f"trans=[{opt['trans'].x[0]:.4f}, {opt['trans'].y[0]:.4f}]")

    fig, axs = plt.subplots(2, 2, figsize=(10, 10))
    axs[0][0].plot(loss_hist)
    axs[0][0].set_xlabel('iteration')
    axs[0][0].set_ylabel('Loss')
    axs[0][0].set_title('Parameter error plot')
    axs[0][1].imshow(mi.util.convert_to_bitmap(img_init))
    axs[0][1].axis('off')
    axs[0][1].set_title('Initial Image')
    axs[1][0].imshow(mi.util.convert_to_bitmap(mi.render(scene, spp=1024)))
    axs[1][0].axis('off')
    axs[1][0].set_title('Optimized image')
    axs[1][1].imshow(mi.util.convert_to_bitmap(img_ref))
    axs[1][1].axis('off')
    axs[1][1].set_title('Reference Image')
    plt.show()

if __name__ == '__main__':
    pose_estimation()

````

## Steps to reproduce
Run the script above.

![image](https://github.com/mitsuba-renderer/mitsuba3/assets/1258160/00fd7e2b-9149-4ae4-b7f3-ac142a429608)

**Comment by njroussel** [comment]
Hi @lopsided 

I've just ran it 20 times without any issues on both the latest PyPI release and the `master` branch  :disappointed:.

If your initial pose is matches the reference, does it still diverge?
Do the other tutorials work just fine? How about the shape reconstruction tutorial?

**Comment by lopsided** [comment]
Hi @njroussel thanks for the quick reply. I just tested with the initial pose matching the reference, still diverges:
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/1258160/a2d9747f-f09d-4803-bd88-65f3cbfbb09c)

I'll try the shape optimisation tutorial now...

**Comment by njroussel** [comment]
Could you try using this file for the mesh: https://github.com/mitsuba-renderer/mitsuba-tutorials/blob/master/scenes/meshes/bunny.ply

**Comment by lopsided** [comment]
Success!
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/1258160/37fc5b0b-9c3e-4f67-b6b1-3ba3a2bdfab0)

Any idea why this mesh works when the other one doesn't? Could you reproduce the problem with the mesh from https://rgl.s3.eu-central-1.amazonaws.com/scenes/tutorials/scenes.zip ?

**Comment by njroussel** [comment]
Yes, we'll be updating this ASAP.

The bunny in the file you originally used was described as a triangle soup. Basically, it's just a list of disjoint triangles. The protective sampling method has some minor assumptions about the structure of the mesh: it needs to know how to move from one triangle face to its neighbours.
