### ISSUE TITLE
Cannot create emissive meshes using mi.Mesh construction

### ISSUE THREAD

**Issue by futscdav** [mitsuba-renderer/mitsuba3#1089]
Running
```python
import numpy as np
import mitsuba as mi

mi.set_variant('llvm_ad_rgb')

texture = np.linspace(0.2, 1, 4)[:, None] * np.linspace(0.2, 1, 4)[None, :]
texture = np.repeat(np.atleast_3d(texture), 3, axis=-1)
texture[..., 1] = np.abs(np.sin(3 * texture[..., 1]))
texture[..., 2] = np.abs(np.cos(3 * texture[..., 1]))

mesh_props = mi.Properties()
mesh_props['bsdf'] = mi.load_dict({
    'type': 'diffuse',
    'reflectance': 1.0,
})
mesh_props['emitter'] = mi.load_dict({
    'type': 'area',
    'radiance': {
        'type': 'bitmap',
        'bitmap': mi.Bitmap(texture),
    }
})
mi_mesh = mi.Mesh(
  'mesh',
  vertex_count=10,
  face_count=5,
  has_vertex_normals=False,
  has_vertex_texcoords=True,
  props=mesh_props,
)
```
throws
`RuntimeError: ​[distr_1d.h:257] DiscreteDistribution: no probability mass found!`

I believe the issue stems from calling this initialize (which attempts to build the pmf) right after zero-initializing the vertices and faces https://github.com/mitsuba-renderer/mitsuba3/blob/acf9af07984040b4aa1a06757476c21759f215c7/src/render/mesh.cpp#L56

The current workaround seems to be writing an obj or ply file and re-reading from that using the plugins, which isn't ideal, but works.

**Comment by njroussel** [comment]
Thank you for the bug report @futscdav, it was fixed in #1096.
