### ISSUE TITLE
Missing `use_grid_bbox` parameter in gridvolume documentation

### ISSUE THREAD

**Issue by MarkYu98** [mitsuba-renderer/mitsuba3#1106]
Hi,

I have previously used Mitsuba2 for volume rendering, and I have found the parameter `use_grid_bbox` ([Mitsuba2 doc](https://eradiate-kernel.readthedocs.io/en/latest/generated/plugins.html#spectral-grid-gridvolume-spectral)) very useful when dealing with the transformation of the grid volumes. Yet I found this parameter is missing from the Mitsuba3 documentation, but apparently it is still supported as I have tried it with the latest version. 

I suggest adding the description of this parameter again in the document (as well as documenting the current default behavior of scaling the grid volume coordinates to [0,0,0]-[1,1,1]) to help users understand how to transform their grid volumes.

Thanks!

**Comment by njroussel** [comment]
Thank you @MarkYu98 

I've documented it in https://github.com/mitsuba-renderer/mitsuba3/commit/77eafddc04fb030a219b31882abedb5362147e7c.
