### ISSUE TITLE
Ninja - "no such file or directory" regarding drjit/__init__.py

### ISSUE THREAD

**Issue by bakastronaut** [mitsuba-renderer/mitsuba3#1119]
## Summary

I'm having issues compiling mitsuba3 for C++ development. I'm a bit new to build and compile troubleshooting as I am hoping to improve my C++ development skills, so please bare with me. I followed the steps on the website under "Developer's Guide," but I keep getting an error when generating a .pyi file associated with drjit. One thing odd I noticed when getting my system configuration is that I received a ModuleNotFoundError for mitsuba. But when I am following the compile directions, I don't see a step anywhere that mentions a separate installation. 

I tried installing drjit via `pip install drjit`, but that did not work.
I tried running the ninja command again after `pip install mitsuba`, but that did not fix the issue.
I also tried deleting CMakeCache.txt and trying again, but that did not fix it.
Finally, I changed the variants to include llvm_ad_rgb and received the same error.

 I am lost on what to do next after a few days of troubleshooting, so some help would be greatly appreciated.

## System configuration

```
miniconda3/envs/mitsuba3/bin/python: Error while finding module specification for 'mitsuba.sys_info' (ModuleNotFoundError: No module named 'mitsuba')
```

System information:

  OS: MacOS Sonoma (14.3.1)
  CPU: M1
  GPU: Apple Silicon
  Python version: 3.9.19
  LLVM version: 17.0.6_1

  Dr.Jit version: 0.4.4
  Mitsuba version: 3.5.0
     Compiled with: ninja
     Variants compiled: scalar_rgb, scalar_mono

## Description

```
[808/818] Generating ../../python/drjit/__init__.pyi
FAILED: python/drjit/__init__.pyi mitsuba3/build/python/drjit/__init__.pyi 
cd "mitsuba3/build/src/python" && /opt/homebrew/Cellar/cmake/3.29.0/bin/cmake -E env PYTHONPATH=mitsuba3/build/python: miniconda3/envs/mitsuba3/bin/python3.9 -Xutf8 mitsuba3/src/python/../../ext/drjit/resources/generate_stub_files.py mitsuba3/build/python/drjit
no such file or directory
[815/818] Building CXX object src/python/CMakeFiles/...a_llvm_ad_rgb_ext.dir/__/render/python/shape_v.cpp.
ninja: build stopped: subcommand failed.
```

## Steps to reproduce
*recursive repo clone*
`cd mitsuba3`
`mkdir build`
`cd build`
`cmake -GNinja ..`
*change mitsuba.conf such that "enabled": ["scalar_rgb", "scalar_mono"]*
`ninja`

**Comment by njroussel** [comment]
Hi @bakastronaut 

This is just a guess: you might be running an x86 version of Python whereas Mitsuba will build a ARM wheel. Make sure that you're not using Rosetta, you should be running an ARM build of Python. 
I think I've seen this a few times before.

**Comment by sujoyrc** [comment]
so what to do on a x86 machine?

**Comment by merlinND** [comment]
Hi @sujoyrc,

There shouldn't be any issue on an x86 machine, what @njroussel suggested above was an issue specific to Macs where you can accidentally build for x86, which would end up being emulated, instead of directly for ARM.

**Comment by njroussel** [comment]
I'll close this, we haven't heard back from the original poster.

> where you can accidentally build for x86, which would end up being emulated, instead of directly for ARM.

This is slightly incorrect: it's the other way around. The build process will always figure out the actual hardware architecture and build for that. So, on a ARM-basec Mac you'd get an ARM build - no matter what. The issue is if you try to import that `mitsuba` inside of an emulated shell/python, because now the process is expecting to only handle x86-targeted code, but `mitsuba` will issue ARM instructions.

**Comment by merlinND** [comment]
Thanks for the clarification @njroussel!
