### ISSUE TITLE
Intrinsics camera matrix from Mitsuba 3 sensor

### ISSUE THREAD

**Issue by HeyLongHoang** [mitsuba-renderer/mitsuba3#1124]
Hi, does anyone know how to get back the intrinsics camera matrix K from sensor object in Mitsuba 3. When I tried mi.traverse(sensor), it gives back principle point offsets in the x and y directions but not the focal length 'f'. I know I can get back 'f' from FOV parameter but that doesn't seem like the best way. Thanks for your help! 🙏
<img width="879" alt="Screenshot 2024-04-01 at 13 11 50" src="https://github.com/mitsuba-renderer/mitsuba3/assets/79366791/26b2ff87-7168-4108-948d-658a0b53a621">
.
<img width="1277" alt="Screenshot 2024-04-01 at 13 11 42" src="https://github.com/mitsuba-renderer/mitsuba3/assets/79366791/6b75b2e2-a482-4853-ae95-6ea6eb06cae9">

**Comment by Speierers** [comment]
Hi @HeyLongHoang ,

Indeed, computing the focal length from the `x_fov` field is the way to go.

**Comment by njroussel** [comment]
Hi @HeyLongHoang 

@Speierers  is right, we don't provide any other way do this currently.
