### ISSUE TITLE
Compiling Problem

### ISSUE THREAD

**Issue by HuixianZhong** [mitsuba-renderer/mitsuba3#1143]
System information:

  OS: Windows11
  CPU: 13th Gen Intel(R) Core(TM) i9-13900HX   2.20 GHz
  GPU: NVIDIA GeForce RTX 4060
  Python version: 3.11.7
  CUDA version: V12.1.105

  Mitsuba version: 3
     Compiled with: VS 2022 Community
 
## Description

Firstly, I follow along the tutorial :"git clone --recursive https://github.com/mitsuba-renderer/mitsuba3" to get the source code.
And then, I modified the variant named "cuda_rgb_polarized" I needed in the file.
After that, I run "cmake -G "Visual Studio 17 2022" -A x64 -B build". There are some details.
[cmake.txt](https://github.com/mitsuba-renderer/mitsuba3/files/15031658/cmake.txt)

I opened "mitsuba.sln" file to build the release x64. But it didn't work out.
[log.txt](https://github.com/mitsuba-renderer/mitsuba3/files/15031669/log.txt)
[errors.txt](https://github.com/mitsuba-renderer/mitsuba3/files/15031670/errors.txt)

steps to follow in order to reproduce the issue -->
I'm not very familiar with this compilation, and all the process logs are shown in the file above.

**Comment by merlinND** [comment]
Hello @HuixianZhong,

Could you please try compiling again, but keeping the `scalar_rgb` variant included in your `mitsuba.conf`?

**Comment by HuixianZhong** [comment]
> Hello @HuixianZhong,
> 
> Could you please try compiling again, but keeping the `scalar_rgb` variant included in your `mitsuba.conf`?

Thanks! I have just tried, but the compilation still didn't work out. It is now displayed ” C1356: cannot find mspdbcore.dll.","C1060",and so on. 

Could you send me a compiled file with this variant? Thank you so much.

**Comment by merlinND** [comment]
Hello @HuixianZhong,

Sorry, I am not able to provide pre-compiled binaries. However the Windows build should definitely work, as it is tested regularly on our CI.

Please delete all of the build and cache directories in order to do a fresh build, and enable the following variants in `mitsuba.conf`:

- `scalar_rgb`
- `cuda_ad_rgb`
- `cuda_rgb_polarized`

Then, start a fresh build, making sure to build *all* targets.

**Comment by HuixianZhong** [comment]
> Hello @HuixianZhong,
> 
> Sorry, I am not able to provide pre-compiled binaries. However the Windows build should definitely work, as it is tested regularly on our CI.
> 
> Please delete all of the build and cache directories in order to do a fresh build, and enable the following variants in `mitsuba.conf`:
> 
> * `scalar_rgb`
> * `cuda_ad_rgb`
> * `cuda_rgb_polarized`
> 
> Then, start a fresh build, making sure to build _all_ targets.
> 
> If the build does not work, please share the full build log.

Thank you very much! I've compiled successfully. The reason for the failure was that the compilation heap space was insufficient, and I finished compiling after trying to apply for virtual memory.

**Comment by merlinND** [comment]
Great to hear! And thank you for explaining your fix.
