### ISSUE TITLE
Performance issue in accessing primary index after ray intersect

### ISSUE THREAD

**Issue by AndreaMaestri18** [mitsuba-renderer/mitsuba3#1145]
## Summary

After performing ray_intersect_preliminary for more than 1e6 points, I want to store the index of the faces that are hit by the rays, so that I can assign later on materials to all of them. The problem that I am facing is related to performance. After finding the scene intersect, I want to access the `prim_index` to store that in a set. The problem is that doing simply `myset.add(si.prim_index)` is not sufficient (they are all unique if not accessing the elements inside `prim_index`), and I have to access `si.prim_index[0]` to store the unique ones. Here is where the performance of the system slows down by a lot. For 1000 ray intersection the time that the process takes to run it goes from 2.4s to 9.2s. 

## Description

Hi everyone, I am working on a mapping system from 2D points to a 3D scene. After doing photogrammetry to create the 3D model I know all the poses of the camera in the scene, and I am able to successfully project a point from a picture to the 3D model. The problem that I am now facing is related to the performance of the system. 

The system relies heavily on the ray_intersect function, since from the picture and the camera I am able to identify the direction, and the only thing that is missing is the distance camera scene along that direction. 

After performing ray_intersect_preliminary for more than 1e6 points, I want to store the index of the faces that are hit by the rays, so that I can assign later on materials to all of them. The problem that I am facing is related to performance. After finding the scene intersect, I want to access the `prim_index` to store that in a set. The problem is that doing simply `myset.add(si.prim_index)` is not sufficient (they are all unique if not accessing the elements inside `prim_index`), and I have to access `si.prim_index[0]` to store the unique ones. Here is where the performance of the system slows down by a lot. For 1000 ray intersection the time that the process takes to run it goes from 2.4s to 9.2s which makes it unsustainable for all the points that I have to project.

Is there a way to fix this problem? For example projecting from the same origin to multiple directions at the same time, and storing all the indexes, or simply to only get the index of the face that has been hit, instead of the result of `scene.ray_intersect_preliminary(ray)`. 

Or alternatively, do you have a better way to achieve that using the functionalities from Mitsuba? I tried to dig into the documentation but I couldn't find much about this topic.

Thanks a lot in advance.

## my code for one single point, t is in common
```
t = [x,y,z]
p_img = [x_coord,y_coord, 1] #3rd coordinate is a placeholder
cam_origin = mi.Point3f(t)
direction = find_direction_from_img(t, p_img, Minv)
dp_mitsuba = mi.Point3f(direction)
ray = mi.Ray3f(o=cam_origin, d=dp_mitsuba)
si = scene.ray_intersect_preliminary(ray)
index = si.prim_index
```

**Comment by AndreaMaestri18** [comment]
I solved by defining origin and vector of directions, the computing the rays and the surface interaction for all fo them:

```
N = 1000000
o = np.array([0,0,0])
d = np.array([np.zeros(3) for _ in range(N)])
rays = mi.Ray3f(mi.Vector3f(o), mi.Vector3f(d))
si = scene.ray_intersect(rays)
index_set = set(si.prim_index)
```

This basically takes the time to compute the index of the faces that are hit by the rays to 0

**Comment by merlinND** [comment]
Hello @AndreaMaestri18,

I'm not sure which variant you are using, but note that if `si.prim_index` is stored on the GPU (e.g. when using the `cuda_rgb` variant), the expression `set(si.prim_index)` could potentially be very inefficient. This is because it might be transfering entries of the array one by one from the GPU memory to the CPU memory.
A much faster way would be to transfer them all at once, and then build a set from the entries, e.g. `set(si.prim_index.numpy())`.

**Comment by AndreaMaestri18** [comment]
Thanks a lot @merlinND! I really have little to no knowledge about these things, thanks for the feedback!
