### ISSUE TITLE
.usd format (Universal Scene Description) support.

### ISSUE THREAD

**Issue by lastbasket** [mitsuba-renderer/mitsuba3#1194]
Could you add support for Pixar's [.usd](https://openusd.org/release/index.html) format? Thanks.

**Comment by joeylitalien** [comment]
I would strongly recommend you use their [Blender add-on](https://github.com/mitsuba-renderer/mitsuba-blender) to convert USD to Mitsuba XML. My understanding is that scene parsing in Mitsuba is already quite complicated; there's not really a good incentive to have USD support right now.

**Comment by njroussel** [comment]
Hi @lastbasket 

@joeylitalien  is correct, we have no plan to support USD -- it doesn't seem worthwhile to us. As he pointed out, the Blender add-on is our only door to external/third-party scene representations.
