### ISSUE TITLE
How to tune the hyperparameters of `prb_projective`

### ISSUE THREAD

**Issue by Jijiang1234** [mitsuba-renderer/mitsuba3#1199]
Hi, there. Our work was build on your previous version mitsuba3.3.0, and we use your `prb_reparam` but when I update for the latest version, this integrator was not support yet. So I must use your newly excellent work `prb_projective` integrator to solve for the discontinous visibility effects. But seems like I do not use the correct hyperparameters of this integrator for our scenes, the performance not good as the previous `prb_reparam` for our scenes, So if I want to use the new version your work. Would you kindly like to tell me how to tune the hyperparameters of  `prb_projective`  to handle our scenes. Thanks

**Comment by ziyi-zhang** [comment]
Hi, could you elaborate a bit on the use case? An example scene would be even better.
There are many hyperparams in that integrator. A good test case would be to set the guiding to 'uniform' and use many rounds. This would be almost equivalent to the `https://psdr-cuda.readthedocs.io/en/latest/` implementation and is a good entry point to analyze the performance / bias / variance.
