### ISSUE TITLE
RuntimeError: resource deadlock would occur: resource deadlock would occur

### ISSUE THREAD

**Issue by ioissss** [mitsuba-renderer/mitsuba3#1201]
I'm following the tutorial and writing the appropriate code, but in the very first step of editing the scene, when I run params.update() I get this error: RuntimeError: resource deadlock would occur: resource deadlock would occur. i don't know How to solve this problem.
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/91249397/b1e3f7f2-1de0-44f8-afa0-cf9946db5c6f)

**Comment by ziyi-zhang** [comment]
Hi, 
It would be easier for us to understand the error if you could provide more information or a full reproducer.
Best

**Comment by njroussel** [comment]
Hi  @ioissss 

Please follow and fill the issue template when opening new issues.

Try `mi.load_file("./scenes/simple.xml", parallel=False)`. Does it also happen outside of a Jupyter notebook?

**Comment by merlinND** [comment]
Hello @ioissss,

Please have a look at this solution for the same error encountered by another user on Windows:
https://github.com/mitsuba-renderer/mitsuba3/issues/1105#issuecomment-1999041203

**Comment by ioissss** [comment]
I have solve this problem by modifying DRJIT_LIBLLVM_PATH environment variable.
from: C:\Program Files\LLVM\bin
to: C:\Program Files\LLVM\bin\LLVM-C.dll
the solution proposed in #1105 (comment)

**Comment by njroussel** [comment]
I completely forgot about that one :exploding_head:, thanks @merlinND !

Great to here that it fixed it for you @ioissss !
