### ISSUE TITLE
countless errors in compiling

### ISSUE THREAD

**Issue by EarlyForGimlet** [mitsuba-renderer/mitsuba3#1202]
## Description

**I clone the whole project and use the following command "cmake -G "Visual Studio 17 2022" -A x64 -B build", it was built successfully i suppose with this:**
 -- Selecting Windows SDK version 10.0.22621.0 to target Windows 10.0.22631.
-- Mitsuba v3.5.0
-- Mitsuba: targeting the native CPU architecture (specify MI_NATIVE_FLAGS to change this).
-- Mitsuba: building the following variants:
--  * scalar_rgb
--  * scalar_spectral
--  * cuda_ad_rgb
--  * llvm_ad_rgb
--  * cuda_spectral_polarized
--  * cuda_mono_polarized
--  * cuda_mono_polarized_double
--  * cuda_spectral_polarized_double
--  * cuda_ad_spectral_polarized
--  * cuda_ad_spectral_polarized_double
--  * llvm_spectral_polarized
--  * llvm_mono_polarized
-- Dr.Jit v0.4.2
-- Dr.Jit: building the CUDA backend.
-- Dr.Jit: building the LLVM backend.
-- Dr.Jit-Core: LLVM will be loaded dynamically at runtime.
-- Dr.Jit-Core: CUDA will be loaded dynamically at runtime.
-- Dr.Jit-Core: OptiX support enabled.
-- Dr.Jit-Core: OptiX debug and validation flags disabled.
-- Dr.Jit: building the Python plugin.
CMake Deprecation Warning at ext/embree/CMakeLists.txt:19 (CMAKE_MINIMUM_REQUIRED):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- MSVC detected
CMake Deprecation Warning at ext/zlib/CMakeLists.txt:1 (cmake_minimum_required):
  Compatibility with CMake < 3.5 will be removed from a future version of
  CMake.

  Update the VERSION argument <min> value or use a ...<max> suffix to tell
  CMake that the project does not need compatibility with older versions.

-- Configure ILMBASE Version: 2.5.5 Lib API: 25.0.4
-- Configure OpenEXR Version: 2.5.5 Lib API: 25.0.4
-- Tests are disabled. Set FASTFLOAT_TEST to ON to run tests.
-- Mitsuba: using OptiX for GPU ray tracing.
-- Mitsuba: using Embree for CPU ray tracing.
-- Mitsuba: OptiX debug and validation flags disabled.
-- Configuring done (4.2s)
-- Generating done (12.8s)
-- Build files have been written to: D:/Download/Study/Code/mitsuba3/build

**Then i started to compile it in visio studio but have met huge number of errors and warnings
such as :**
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	LNK2019	无法解析的外部符号 "__declspec(dllimport) public: __cdecl mitsuba::PropertiesV<float>::PropertiesV<float>(void)" (__imp_??0?$PropertiesV@M@mitsuba@@QEAA@XZ)，函数 "private: static struct _object * __cdecl <lambda_28e6391588148f0fbec231e5f4ba3e0c>::<lambda_invoker_cdecl>(void *,struct _object * *,unsigned char *,enum nanobind::rv_policy,struct nanobind::detail::cleanup_list *)" (?<lambda_invoker_cdecl>@<lambda_28e6391588148f0fbec231e5f4ba3e0c>@@CAPEAU_object@@PEAXPEAPEAU2@PEAEW4rv_policy@nanobind@@PEAUcleanup_list@detail@4@@Z) 中引用了该符号	scalar_spectral	D:\Download\Study\Code\mitsuba3\build\src\python\properties_v.obj	1		
**which means i have some problems in xxx.obj i think** 
**and other one single error as:**
严重性	代码	说明	项目	文件	行	禁止显示状态	详细信息
错误	C1083	无法打开包括文件: “drjit-core/jit.h”: No such file or directory	mitsuba_alias	D:\Download\Study\Code\mitsuba3\include\mitsuba\core\fwd.h	4

**Comment by njroussel** [comment]
Hi @EarlyForGimlet 

The `master` branch is undergoing a lot of work as mentionned in the README. As you might have seen our CI is currently not passing.

Checkout `v5.3.2.` or `stable` until further notice.

**Comment by EarlyForGimlet** [comment]
> Hi @EarlyForGimlet
> 
> The `master` branch is undergoing a lot of work as mentionned in the README. As you might have seen our CI is currently not passing.
> 
> Checkout `v5.3.2.` or `stable` until further notice.

**I appreciate your answer, thanks a lot**
