### ISSUE TITLE
Is there an official Python implementation of path tracing?

### ISSUE THREAD

**Issue by free7187** [mitsuba-renderer/mitsuba3#1206]
## Description

I'm looking to incorporate my own trained neural network into path tracing. Is there an official Python implementation of path tracing available?

**Comment by merlinND** [comment]
Hello @free7187,

The integrators implemented in Python are located in this directory: https://github.com/mitsuba-renderer/mitsuba3/tree/master/src/python/python/ad/integrators

The simplest starting points would likely be [`prb_basic`](https://github.com/mitsuba-renderer/mitsuba3/blob/9a813333a6a8190308f10486ad1f44b294729170/src/python/python/ad/integrators/prb_basic.py) or [`prb`](https://github.com/mitsuba-renderer/mitsuba3/blob/9a813333a6a8190308f10486ad1f44b294729170/src/python/python/ad/integrators/prb.py).
