### ISSUE TITLE
Large Steps Incompatible dimension Dr.Jit Exception

### ISSUE THREAD

**Issue by A0405u** [mitsuba-renderer/mitsuba3#1220]
## Summary

Dr.Jit exception while using LargeSteps

## System configuration

  CPU: AMD Ryzen 7 5700G with Radeon Graphics
  GPU: NVIDIA GeForce RTX 2080
  Python: 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0]
  NVidia driver: 552.44
  LLVM: 14.0.6

  Dr.Jit: 0.4.6
  Mitsuba: 3.5.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Got a Dr.Jit exception in step 12 while trying to reproduce the code from Shape optimization tutorial. 

Notebook output:
```
---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
File ~/.local/lib/python3.11/site-packages/drjit/detail.py:243, in array_init(self, args)
    242 if not dim1 == dim2 and not (dim1 == dim2 + 1 and self.IsDynamic):
--> 243     raise _dr.Exception("Incompatible dimension!")
    244 for i in reversed(range(dim2)):

Exception: Incompatible dimension!

The above exception was the direct cause of the following exception:

TypeError                                 Traceback (most recent call last)
Cell In[11], line 2
      1 lambda_ = 25.0
----> 2 ls = mi.ad.LargeSteps(params['shape.vertex_positions'], params['shape.faces'], lambda_)

File ~/.local/lib/python3.11/site-packages/mitsuba/python/ad/largesteps.py:108, in LargeSteps.__init__(self, verts, faces, lambda_)
    105 # inverse_v = inverse_v.flatten()
    107 self.index = mi.UInt(index_v)
--> 108 self.inverse = mi.UInt(inverse_v)
    109 self.n_verts = v_unique.shape[0]
    111 # Solver expects matrices without duplicate entries as input, so we need to sum them manually

File ~/.local/lib/python3.11/site-packages/drjit/detail.py:292, in array_init(self, args)
    290 if err is not None:
    291     if dynamic:
--> 292         raise TypeError("%s constructor expects: arbitrarily many values "
    293                         "of type \"%s\", a matching list/tuple, or a NumPy/"
    294                         "PyTorch/TF/Jax array." % (type(self).__name__,
    295                                                    value_type.__name__)) from err
    296     else:
    297         raise TypeError("%s constructor expects: %s%i values "
    298                         "of type \"%s\", a matching list/tuple, or a NumPy/"
    299                         "PyTorch/TF/Jax array." % (type(self).__name__, "" if
    300                                                    size == 1 else "1 or ", size,
    301                                                    value_type.__name__)) from err

TypeError: UInt constructor expects: arbitrarily many values of type "int", a matching list/tuple, or a NumPy/PyTorch/TF/Jax array.
```
I was able to solve the issue by adding the following string at 105 line of `largesteps.py`:
```
inverse_v = inverse_v.flatten()
```

`inverse_v` array generated at 102 line with np.unique(...) contained many Arrays of a single UInts. Mentioned solution makes it just an Array of UInts, instead of Array of Arrays of UInts. I tested the result end everything seems working normally.

## Steps to reproduce

1. Install Mitsuba
2. Launch the notebook provided on page: 
https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/shape_optimization.html
3. Get an error.

**Comment by pixelsandpointers** [comment]
I encountered the exact same problem and have not yet find a fix for it.

**Comment by njroussel** [comment]
Hi @A0405u  and @pixelsandpointers 

Looks like a change in numpy's behavior since v2.0.0. See the release notes:
https://numpy.org/devdocs/release/2.0.0-notes.html#np-unique-return-inverse-shape-for-multi-dimensional-inputs

If possible, you can simply downgrade your numpy version. If not, I think the fix @A0405u suggests is correct, you'll need to apply it directly in your local install directory (`.../site-packages/mitsuba/python/ad/largesteps.py`).

I'll push a similar fix to `master`.
