### ISSUE TITLE
forward-mode differentiation for volume path

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/mitsuba3#1246]
Hi,
I try to evaluate the correctness of volpath or prbvolpath's gradient using gradient image.
However, it seems forward-mode differentiation for volume path is never supported. Is there any technical reason for that?
Is there any suggestion on how to evaluate the correctness of gradient for volume rendering?
Thanks!

**Comment by njroussel** [comment]
Hi @andyyankai 

I don't think that there is any technical limitation, we just never got around to doing it.

I think that validating with forward gradients is good for volume rendering too. However, due to inherent noise/variance I can imagine that this might be annoying to observe small discrepancies.
@bathal1 do you have any other suggestions?

**Comment by bathal1** [comment]
I usually define a toy problem with a single parameter, e.g. a global scaling factor for the volume density, and a dummy loss, e.g. the L2 norm of the rendering. In this setting, both forward and reverse-mode AD produce the same derivative.

You can then easily compare the result to finite differences.

It is worth mentioning that when you validate gradients, you should try to always use the L2 error if possible, as other losses will introduce bias which may be confusing. Another option to avoid that is to render a single pixel.

**Comment by andyyankai** [comment]
Thanks for the suggestion Nicolas and Baptiste! I currently do something similar by backpropagating each individual pixel, although it is very slow (I need to backpropagate 512*512 times for a 512x512 image). I think a forward mode AD for volume might be a nice feature to include, which is quite necessary for paper comparison. Is there any plan for that? If not, I might try to do it myself.

I tried to use forward AD for volpath and volpathmis, and it seems both give me the correct gradient. However, there appears to be some memory leak after using forward AD.
```
jit_shutdown(): detected variable leaks:
 - variable r10 is still being referenced! (ref=1, ref_se=0, type=float32, size=95, stmt="<null>", dep=[7, 3, 0, 0])
 - variable r20 is still being referenced! (ref=1, ref_se=0, type=float32, size=95, stmt="<null>", dep=[17, 1, 14, 0])
 - variable r17 is still being referenced! (ref=1, ref_se=0, type=float32, size=1, stmt="<value>", dep=[0, 0, 0, 0])
```

I also try a little modification on prbvolpath.py, simply remove the assertion. It seems adding the forwardAD for prbvolume isn't hard. However, I try to print `δL` outside the drjit.Loop even I replace [line29](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/python/python/ad/integrators/prbvolpath.py#L290) into `δL += dr.detach(Lo)` by doing:
```
        if mode == dr.ADMode.Forward:
            print(δL)
            exit()
```
the following error appear:
![image](https://github.com/user-attachments/assets/da9ac704-c6fd-4d92-b9b9-518552c40b01)

If I replace the drjit.loop into a regular for loop it would work well... Is there any dirty evaluation might happen somewhere inside the loop for prbVPT?

Thank you very much!

**Comment by andyyankai** [comment]
nvm, simply add δL to dr::loop state solve the issue...

**Comment by njroussel** [comment]
> just write a forward version after all `if mode == dr.ADMode.Backward`

That's what I would have expected, good to know that it is indeed the case! Thanks @andyyankai

**Comment by andyyankai** [comment]
Hi @njroussel @bathal1 
Do you know if this seems like a correct way for the forward mode on prb transmission at https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/python/python/ad/integrators/prbvolpath.py#L411?
from `dr.backward(tr_multiplier * dr.detach(dr.select(active_adj, δL * adj_emitted / tr_multiplier, 0.0)))`
into
```
if mode == dr.ADMode.Backward: 
    dr.backward(tr_multiplier * dr.detach(dr.select(active_adj, δL * adj_emitted / tr_multiplier, 0.0)))
elif mode == dr.ADMode.Forward:
    grad_val += dr.forward_to(dr.detach(dr.select(active_adj, adj_emitted / tr_multiplier, 0.0))*tr_multiplier)
```
There are some mismatch in the final result.
Thanks!

**Comment by andyyankai** [comment]
actually there might have some potential bug in the old drjit (pybind version)
let me reopen a new issue later
