### ISSUE TITLE
 [🔨 compilation issue] Unable to install mitsuba and drjit using pip for Google Colab

### ISSUE THREAD

**Issue by kaustubh-sadekar** [mitsuba-renderer/mitsuba3#125]
## Summary

Unable to pip install mitsuba and drjit on Google Colab

## Description

`pip install mitsuba` and `pip install drjit` not working for Google Colab. 

Sharing a screenshot for reference: 

![image](https://user-images.githubusercontent.com/42736936/180394448-a7d19ad9-35bf-42ec-9a66-524123729ead.png)

Please let me know if I am missing something here.

_P.S. Thank you very much for the amazing library! Mitsuba 3, just like its previous versions, is a significant contribution to the community. Using it in colab would make exploring this library easier and more convenient._

**Comment by wjakob** [comment]
Colab runs on Python 3.7, and Mitsuba requires 3.8. That's a hard requirement that we will not be able to reduce. This isn't really an issue with Mitsuba, please open questions in the 'Discussions' tab in the future.
