### ISSUE TITLE
`std::bad_cast` when passing invalid-shaped NumPy array to plugin

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#1253]
The following code produces `std::bad_cast` on the new master branch. This used to work in the previous version. Note that the shape of the NumPy array does not have the right shape here, so some form of error might be the right thing to do here. But maybe a more informative message could be thrown, pointing to the user to the source of error ("invalid shape")?
```py
import mitsuba as mi 
import numpy as np
mi.set_variant('llvm_ad_rgb')

mi.load_dict({'type': 'rgb', 'value': np.array([[1.0,0.5,0.3]])})
```

**Comment by njroussel** [comment]
~Fixed in #1267.
