### ISSUE TITLE
feature request: Prebuilt binary releases?

### ISSUE THREAD

**Issue by oscarbg** [mitsuba-renderer/mitsuba3#127]
Hi,

would want to test new Mitsuba 3 release..
would like prebuilt binaries if possible for three platforms: Windows 11,Ubuntu 22.04 and MacOS 12.6..
at least for Windows..

thanks..

**Comment by alhirzel** [comment]
Did you already try to `pip install mitsuba`?

**Comment by wjakob** [comment]
Let's keep the 'issue' tab for actual issues with the system. As @alhirzel mentioned, binaries are distributed via `PyPI`. They include the `mitsuba` command line binary as well, though you will get most mileage out of Mitsuba 3 by using it via Python.
