### ISSUE TITLE
[❔ other question] Plugin param name inconsistency between spectrum plugins

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba3#132]
## Description

Both the `uniform` and `regular` plugins take wavelength range parameters. However, `uniform` uses the `wavelength_min` and `wavelength_max` names, while `regular` uses `lambda_min` and `lambda_max`.

For consistency (also with the rest of the code), I would suggest to align both to `wavelength_min` and `wavelength_max`; but this is a disruptive change. What is your opinion on that?

**Comment by njroussel** [comment]
Hi @leroyvn 

Thank you, this makes sense.

I've just changed it in 9d3487c4846c5e9cc2a247afd30c4bbf3cbaae46. It will be available in the next release.
