### ISSUE TITLE
❔ other question Geometric Phase Function interface

### ISSUE THREAD

**Issue by dnakath** [mitsuba-renderer/mitsuba3#134]
## Summary

I am currently about to implement new phase functions, and I have a question regarding the interpretation of the (geometric) phase function interface.

I think, you evaluate $\theta$ in what I call *computer-graphics* convention (both vectors pointing away from the interaction point), but compute the sampled vector $\omega_o$ in *physics* $\theta'$ convention, is this correct?

![g1211](https://user-images.githubusercontent.com/56871727/180779559-217f576b-d93a-4543-a90f-4d2690585b25.png)
[Adopted from PBR book](https://pbr-book.org/3ed-2018/Volume_Scattering/Phase_Functions#)

## Description

This is a consistent interpretation, when I look at the HG-phase function implementation in [MTS2](https://github.com/mitsuba-renderer/mitsuba2/blob/master/src/phase/hg.cpp).

You evaluate in *computer graphics-convention* according to 
$$p(\cos \theta) = \frac{1}{4\pi} \frac{1-g^2}{(1+g^2+2g(\cos\theta)) ^{3/2} }$$

But sample in *physics* convention
$$\cos \theta = \frac{1}{2g} (1+g^2 - (\frac{1-g^2}{1-g+2g  \xi}))$$

So I came up with this interpretation of the local geometry,
![g1011](https://user-images.githubusercontent.com/56871727/180777093-db0258f8-d5f1-4e83-ad53-018b7c499642.png)

where you eval $\theta$ but sample $\theta'$ and the blue vectors are the local frame in which we sample from a spherical coordinate system with its pole aligned with n. Is this correct?

In [MITS3s HG](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/phase/hg.cpp) you still evaluate in  *computer-graphics* convention and sample $\theta$ in the *physics* convention, but now you flip $\cos \theta$ in line [83](https://github.com/mitsuba-renderer/mitsuba3/blob/98a8ecb2390ebf35ef5f54f28cccaf9ab267ea48/src/phase/hg.cpp#L83).

Is this the correct way to sample in *physics* convention ? Or cant we just operate with the inversely sampled $\cos \theta$ here?

Similarly in [tabphase](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/phase/tabphase.cpp), I assume that you sample consistently with the [eval()](https://github.com/mitsuba-renderer/mitsuba3/blob/98a8ecb2390ebf35ef5f54f28cccaf9ab267ea48/src/phase/tabphase.cpp#L91) methods from a *ContinuousDistribution*, why do you call eval with $-\cos \theta$ here? 
 
Thank you very much for clarifying everything, I could create a (modest) PR for this if necessary ..

**Comment by dnakath** [comment]
I digged a little further into the local coordinates of MTS3 and I understand now, that you changed the directionality of the local spherical coordinates like so: 
![image](https://user-images.githubusercontent.com/56871727/180993298-ca670c86-efba-4cb3-800e-dd2606f41a08.png)

What I furthermore understand now is: 

MTS2 HG: 

- *eval* in *computer-graphics* convention
- *sample* $\theta$ in *physics* convention
  - compute pdf with $-\cos \theta$  
  - compute $w_o$ in *physics* convention

MTS3 HG: 

- *eval* in *computer-graphics* convention
- *sample* $\theta$ in *physics* convention
  - compute pdf with $-\cos \theta$  
  - compute $w_o$ in *computer-graphics* convention by using $- \cos \theta$ when constructing the cartesian $w_o$
 
However I still don't understand the sampling of

MTS3 tabphase: 

- *eval* in *physics* convention by [defining forward scattering to be $\cos \theta =1$](https://github.com/mitsuba-renderer/mitsuba3/blob/54af0f4c2dab6f92c47285308328079230df3079/src/phase/tabphase.cpp#L29)
  - interface to MTS by computing $\cos \theta$ as dot$(w_o,w_i)$ but eval $\cos \theta$
- sample $\cos \theta$ in ?-convention
  - [compute pdf](https://github.com/mitsuba-renderer/mitsuba3/blob/54af0f4c2dab6f92c47285308328079230df3079/src/phase/tabphase.cpp#L91) with $-\cos \theta$ => this would be coherent if the sampling is in *computer-graphics* convention
  - compute $w_o$ in MTS III new local frame (*computer-graphics* convention) but return [*-mi.to_world(wo);*](https://github.com/mitsuba-renderer/mitsuba3/blob/54af0f4c2dab6f92c47285308328079230df3079/src/phase/tabphase.cpp#L91) ==> this would be consistent if the sampling is in *physics-convention*


Maybe you don't catch this incoherence in your chi2-Test as the adapters set the pdf to a hard 0 or 1 in the [sample_functor](https://github.com/mitsuba-renderer/mitsuba3/blob/54af0f4c2dab6f92c47285308328079230df3079/src/python/python/chi2.py#L620)?

Or am I not getting some peculiarity from the *Continous Distribution* here?

**Comment by dvicini** [comment]
Hi,
These conventions are always a bit confusing, but I think you agree that the current implementation of HG samples and evaluates correctly, right?

I am not so familiar with the `tabphase` plugin. Maybe @leroyvn (who authored that plugin) has some insights?

**Comment by leroyvn** [comment]
Hi all, I

**Comment by leroyvn** [comment]
Hi @dnakath, when I wrote the `tabphase` plugin, I indeed used the physics convention for the data layout as you pointed out (I found this parametrisation intuitive, likely due to my background as a physicist).

To be honest, I was not aware that different conventions were used in the different parts of the plugin. I wrote it comparing systematically its results to what the `hg` plugin would output in a similar situation based on the assumption that the most important is to have a correct behaviour at the interface level. I wrote this initially as a Mitsuba 2 plugin, outside the Mitsuba 2 codebase. During the update to Mitsuba 3, I indeed noticed that something had changed with directions because the chi2-test failed. Flipping the direction made the test succeed; I did this in a rush and I might have overlooked some details.

I'd be very happy if this could be clarified / fixed. Did you try and update the plugin already?

**Comment by leroyvn** [comment]
I took a look and tried to clarify things in `tabphase`. It indeed turns out that there is an inconsistency between direction sampling and PDF computation. Indeed this is not detected by the chi2 test. I'll open a PR now, feedback is welcome.

I actually had a similar issue with a BSDF plugin for which the computed value was inconsistent with the rest of the plugin; the mistake was not detected by the chi2 test. Could the chi2 test infrastructure be extended to detect such issues, or is it beyond its scope?

**Comment by dvicini** [comment]
What went wrong in the chi2 test? All the test can do is pick up inconsistencies between PDF and sampling. It won't check the `eval` function and also cannot check conventions (i.e., the orientation of the coordinate frame). For some of these things it's easier to just write specialized tests I think

**Comment by leroyvn** [comment]
**[Off topic comment]** In the case of the issue I had with the BSDF plugin, I made a mistake setting the second returned value of `BSDF.sample()` (equal to `eval()` divided by the PDF and multiplied by $\cos \theta$). AFAIK, it should be consistent with the rest of the plugin, *i.e.*, assuming that `BSDF.eval()` and `BSDF.pdf()` are correct, this could be checked systematically. Similarly, I think `eval_pdf()` could be checked systematically for consistency. 

I understand this not within the scope of the chi2 test; but automating such basic checks would be very helpful, especially for people getting started with BSDF plugin development.

**Comment by dvicini** [comment]
I see, let's keep that in mind yes. Some of these tests might be tricky to do, e.g. checking the sample value returned by BSDF.sample() is not just a matter of comparing it to eval() / pdf() (this would for example break for the `dielectric` plugin)

**Comment by dnakath** [comment]
Hi @dvicini and @leroyvn 

Thank you very much for the detailed discussion and the clarifications. Very much appreciated!

@dvicini yes, after I understood that you flipped the local coordinate system in MTS3 I find that the HG behaves consistently with my interpretations, which I hope you confirmed in your previous comment with this statement

> It is true that at some point we decided to swap the conventions, but the affected plugins should have been updated.

In addition #140 fixes the `tabphase` such that it internally coherently works with the *physics* convention and interfaces cleanly to MTS3s *computer graphics* convention. (I will update my comment above)

I also support @leroyvn in that the internal call to `eval()` in the `sample()` function call should be checked too. In my understanding chi2 checks the correctness of the internal eval/sample implementation plus the interface of `eval()` and the $w_o$ part of the `sample()` interface. So its possible to pass the test despite returning a wrong pdf in `sample()`, which is what happened in `tabphase`

Wouldn't the following pseudoish approach be a general test for this ? 

1. wo, pdf_s = phase_function.sample ()
2. pdf_e = phase_function.eval(wo)
3. assert( allclose(pdf_s,pdf_e))

If you think that is the case, I could open a PR for `tabphase` and `hg` for a start.

**Comment by dnakath** [comment]
@dvicini as we're so happily chatting: I have a follow up-question for clarification. 

I often read the PBR book to understand Mitsuba, as you often follow the general concepts laid out there. However again, for the phase functions we have in general $\omega$, $\omega'$, and specifically $\omega_o$ as well as $\omega_i$. 

Again, I am confused about the directionality here:
In the [PBR-Book](https://pbr-book.org/3ed-2018/Light_Transport_II_Volume_Rendering/Sampling_Volume_Scattering#SamplingPhaseFunctions) the `sampling()` function gets $\omega_o$ and returns $\omega_i$

However, e.g., in Mitsubas [HG](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/phase/hg.cpp), we get $\omega_i$ (encapsuled in the Medium Interaction) and return $\omega_o$.

Could you kindly elaborate on the differences in the naming conventions here?

**Comment by dnakath** [comment]
@leroyvn another a follow up for you in your capacity as a physicist: 

what kind of numbers do you expect for your tabulated phase function saying

> parametrized by a lookup table giving values of the phase function as a
function of the cosine of the scattering angle.

As I understand a phase function should be [normalized to one over the unit sphere](https://www.pbr-book.org/3ed-2018/Volume_Scattering/Volume_Scattering_Processes#In-scattering)

$$  \int_{S^2}^{}  p(\omega,\omega') d\omega'  =1$$

Do you expect values like this ? If yes, why do you additionally multiply your pdf in `sample` + `eval` by $\frac{1}{2\pi}$, the e.g., latter being:

```c++
Float pdf = m_distr.eval_pdf_normalized(-cos_theta, active) * dr::InvTwoPi<ScalarFloat>;
```

which feels like an additional factor for the phi dimension (which is maybe already included?).

The Background is that I'd like to implement a phase function with a closed form solution in `eval` but numerical sampling. Currently I am tending towards skipping that factor in my implementation, is that correct?

**Comment by dvicini** [comment]
There are generally few guarantees that the sampling function's PDF will match the re-evaluation of the PDF. We cannot assume this is generally the case. However, if this works for HG and `tabphase` we might it indeed want to add some tests (in the phase function specific test files). 

And you are right that the convention regarding wo/wi are confusing. The naming is swapped in Mitsuba. I think we copied the convention of Mitsuba 0.6, which does not match the standard notation of PBRT.

**Comment by leroyvn** [comment]
The normalisation of the input data doesn't matter: it's then normalised by the underlying `ContinuousDistribution` such that

$$
\int_{-1}^1 p(\mu) \mathrm{d} \mu = 1
$$

where $\mu = \cos =\theta$ (in the *physics* convention). Actually, the data I use in Eradiate oddly normalises to 2 on the [-1, 1] interval (not my decision!).

Now, to integrate over the entire sphere, you will also integrate over the $\phi$ space. From this follows that 

$$
\int_{\mathcal{S}^2} p(\omega, \omega') \mathrm{d} \omega' = 2 \pi
$$

hence the division by 2π.

**Comment by dnakath** [comment]
Thank you very much for the discussion, it untwisted a lot of knots wrt. phase functions and especially their interfaces and conventions. 

I will try to add a small PR for the `hg` and `tabphase`-specific tests  in the next days.

(Which still remains entangled is the cross over definition of $\omega_i$ and $\omega_o$ between Mitsuba and the PBRT book -- but at least I know that I can just ignore that in the future ;)
