### ISSUE TITLE
Why don't the "shutter_open" and "shutter_close" work in the mitsuba3 ?

### ISSUE THREAD

**Issue by erqihuang** [mitsuba-renderer/mitsuba3#1343]
Why don't the "shutter_open" and "shutter_close" work in the sensor of mitsuba3 ?

  'type': 'perspective',
  'shutter_open': 1.0,
  'shutter_close': 10.0,

**Comment by rtabbara** [comment]
Hi @erqihuang,

I'm interpreting the question as why you don't visualise motion blur in your rendered scene?

The `shutter_open` and `shutter_close` parameters will generate time-specific rays when sampling from a sensor but Mitsuba 3 currently doesn't have plugins (shapes, bsdfs etc.) that utilise this information. For example, for a shape in the scene, you may want to specify the change in the shape's world transform between the shutter open and close time interval. In theory, you could create your own custom plugins to support this but at least in the short term we don't have any plans to internally add this feature.
