### ISSUE TITLE
Python 3.13 Version

### ISSUE THREAD

**Issue by LinasBeres** [mitsuba-renderer/mitsuba3#1384]
Can we please get a Python 3.13 version please?

Currently the latest one available is Python 3.12 (https://pypi.org/project/mitsuba/#files).

**Comment by rtabbara** [comment]
Hi @LinasBeres ,

The upcoming new release of Mitsuba and Dr.Jit will both include wheels additionally supporting Python 3.13 as well as the Python stable ABI. I can't give you an exact date of release but it should be very soon.
