### ISSUE TITLE
Question about XML scene format

### ISSUE THREAD

**Issue by domef** [mitsuba-renderer/mitsuba3#1388]
Does mitsuba3 provides an XML Schema (or somethig similar) that can provide linting during the scene definition?

**Comment by njroussel** [comment]
Hi @domef 

Mitsuba 0.6 used to provide one ([here](https://github.com/mitsuba-renderer/mitsuba/blob/master/data/schema/scene.xsd)). For Mitsuba 3, we currently don't have one. I'd be happy to help out on a PR if anyone wanted to implement this feature.

**Comment by domef** [comment]
> Hi @njroussel
> 
> I'm wondering if you would also accept Python-based scene building (which allows for autocompletion) without the need to fiddle with dictionary values?
> 
> I tinkered with it in an under-development library, so if there's demand for this, I can extract it and start a PR.

My question was in fact about having the autocompletion since now (with both XML and python dict) is very difficult to setup a new scene.

**Comment by pixelsandpointers** [comment]
> HI @pixelsandpointers 
> 
> 
> 
> What does "Python-based scene building" look like ? Like a builder pattern, with a bunch of methods like `add_bsdf()`/`add_shape()`, etc. ?
> 
> 
> 
> More generally, I think we don't have the means to maintain yet another way to build scenes ourselves. But I'd be happy to have a look at what you've done. Feel free to share it whenever you want over here: https://github.com/mitsuba-renderer/mitsuba3/discussions.

Exactly like this, with a general Scene container able to export to different targets: `to_dict()/to_xml()`. 

Let me open a discussion in a few days. Currently busy with some other things.

**Comment by DonovanKits** [comment]
Hi @njroussel @domef @pixelsandpointers

I have loaded an .xml file and want to customize a sensor in python dict. I want to merge the two into the same scene.Specifically, a sensor has been defined in the .xml file, and I want to customize an irradiancemeter to measure the irradiance value somewhere in the scene. I don't know how to accomplish this task. Do you have a good method? Thank you！

**Comment by merlinND** [comment]
Hello @DonovanKits,

Please open a new discussion so that your question is easier to find in the future.

**Comment by pixelsandpointers** [comment]
I just created a new discussion for the API I've been working on, see: [#1708](https://github.com/mitsuba-renderer/mitsuba3/discussions/1708)
