### ISSUE TITLE
[❔ other question] Differentiability of polarized rendering

### ISSUE THREAD

**Issue by holmes969** [mitsuba-renderer/mitsuba3#139]
I noticed in the documentation that differentiability of polarization-based rendering is supported by Mitsuba 3. It is a good news as this feature was not previously provided by Mitsuba 2. However, given that only one simple example (filter rotation) is provided in the tutorial, I am not sure how much capability Mitsuba 3 (differentiable) polarized renderer can provide in terms of differentiability. For example:
(1) Is geometry differentiation fully supported? For example, am I allowed to compute the derivative of individual mesh vertices?
(2) Is differentiation with respect to BSDF parameters supported?
If such features are supported, any optimization/validation script is appreciated.

**Comment by dvicini** [comment]
Hi Cheng,

There is currently no integrator supporting polarization + discontinuities. Our main integrator supporting discontinuities is `prb_reparam`, but path replay (PRB) is incompatible with polarization, at least in its current form. You should be able to optimize BSDF parameters with the `path` integrator, but that one does not support discontinuities.

We don't yet have an efficient integrator that supports polarization + discontinuities.

Best,
Delio
