### ISSUE TITLE
[Bug] Spot light source emitter not showing

### ISSUE THREAD

**Issue by grindash** [mitsuba-renderer/mitsuba3#1392]
## Summary

"Spot light" emitters are not produced in the scene when their xyz position contains floating numbers.

## System configuration

OS : Windows 10
Python version : Python 3.9.10
Mitsuba 2.1.0
Compiled variants: scalar_rgb

Mitsuba is run with pycharm

## Description
I'm making  a scene with multiple light source. The spot light emitters were used and they only produce light when their xyz position don't have a decimal.

## Steps to reproduce
Here is a scene with 3 spots, the following parameters are used :
`<emitter type="spot">`
` 	<transform name="to_world">`
`		<lookat origin="3, 3, -2" target="3, 0, -2" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
`<emitter type="spot">`
`	<transform name="to_world">`
`		<lookat origin="3, 3, -4" target="3, 0, -4" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
`<emitter type="spot">`
`	<transform name="to_world">`
`		<lookat origin="3, 3, -7" target="3, 0, -7" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
![illu 1](https://github.com/user-attachments/assets/1dbe8224-1ddf-4583-a3df-1c3a18c41812)

Then a second scene is made with the middle spot using decimals:
`<emitter type="spot">`
` 	<transform name="to_world">`
`		<lookat origin="3, 3, -2" target="3, 0, -2" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
`<emitter type="spot">`
`	<transform name="to_world">`
`		<lookat origin="3.4, 2.51, -4.42" target="3.4, 0, -4.42" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
`<emitter type="spot">`
`	<transform name="to_world">`
`		<lookat origin="3, 3, -7" target="3, 0, -7" up="0, 0, 1"/>`
`	</transform>`
`	<rgb name="intensity" value="100.0"/>`
`</emitter>`
![illu 2](https://github.com/user-attachments/assets/c29b5068-3fa2-4532-b841-b96b29efc8f0)

Do you know how to fix this problem ?
Thanks

**Comment by njroussel** [comment]
Hi @grindash 

Are you using Mitsuba 3 or Mitsuba 2? Your "system configuration" section is missing some important infromation. If you're using Mitsuba3, please run `python -m mitsuba.sys_info` and copy the full output.

Could you also provide us with a full scene description?

**Comment by rtabbara** [comment]
Hi @grindash ,

I'm going to close this off due to inactivity. Without the scene description we can't help you.
