### ISSUE TITLE
Dr.jit has no wrap function

### ISSUE THREAD

**Issue by XiongFenghhh** [mitsuba-renderer/mitsuba3#1400]
Hello, I installed mitsuba3 with pip and I followed this [tutorial](https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/pytorch_mitsuba_interoperability.html). Then I encountered thie error 

> AttributeError: module 'drjit' has no attribute 'wrap'

Then I tried to compile mitsuba3 myself  according to [this](https://mitsuba.readthedocs.io/en/latest/src/developer_guide/compiling.html), but I still got the same problem.

How can I fix this problem?

**Comment by ziyi-zhang** [comment]
Hi,
When you compile Mitsuba from the source code, which commit are you using? There have been many changes recently.
Does this error only occur with `dr.wrap`? Could you try to run other tutorial?
Best

**Comment by merlinND** [comment]
Hi @XiongFenghhh,

As a quick note, the tutorial that you linked is expected to work with the latest Mitsuba `master` branch.
For a version of the same tutorial that should work with the latest _released_ Mitsuba version (i.e. what you can install from `pip`), see: https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html

**Comment by XiongFenghhh** [comment]
> > I'm attempting to use the latest Mitsuba
> 
> If you're attempting to use the latest Mitsuba (= upcoming version, not released yet), then you should compile `master`. The commit you pointed to should work with the older version of the tutorial that I linked above.

@merlinND  @ziyi-zhang  I pulled the latest commit of mitsuba( and its submodule), recompiled it, and the drjit.wrap works normally  now as in the tutorial . 

Thanks!
