### ISSUE TITLE
Simple scene renders black when camera is positioned exactly in x-y plane

### ISSUE THREAD

**Issue by brambozz** [mitsuba-renderer/mitsuba3#1408]
## Summary

A simple scene with a diffuse checkerboard plane renders black when a camera is positioned at (x, y) = (0, 0), but successfully renders when slightly shifting the camera to (x,y)=(1E-7, 1E-7).

I think this might have to do with the `to_world` transform?

## System configuration

System information:

  OS: EndeavourOS Linux
  CPU: 13th Gen Intel(R) Core(TM) i7-1355U
  Python: 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0]
  LLVM: 18.1.8

  Dr.Jit: 0.4.6
  Mitsuba: 3.5.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

I was struggling to render some images in simple test scenes and I noticed that when I position a camera exactly in the x-y plane, I get black images. When I instead slightly shift the camera position, the image renders normally.

Unless I understand wrongly, I think the example case below should render successfully in both cases.

## Steps to reproduce

1. Run the following script

```py
import mitsuba as mi

mi.set_variant("scalar_spectral")

diffuse_checkerboard = {
        "type": "diffuse",
        "reflectance": {
            "type": "checkerboard",
            "to_uv": mi.ScalarTransform4f.scale([20, 20, 1]),
        },
}
plane = {
    "type": "rectangle",
    "to_world": mi.ScalarTransform4f.translate([0, 0, 0]),
    "material": diffuse_checkerboard
}

directional_light = {
    "type": "directional",
    "direction": [0.0, 0.0, -1],
    "irradiance": {
        "type": "spectrum",
        "value": 1,
    },
}
perspective_camera = {
    "type": "perspective",
    "to_world": mi.ScalarTransform4f.look_at(
        origin=[0, 0, 1],
        target=[0, 0, 0],
        up=[0, 0, 1],
    ),
}
perspective_camera_shifted = {
    "type": "perspective",
    "to_world": mi.ScalarTransform4f.look_at(
        origin=[1E-7, 1E-7, 1],
        target=[0, 0, 0],
        up=[0, 0, 1],
    ),
}

path_integrator = {"type": "path"}

# Scene
scene = mi.load_dict(
    {
        "type": "scene",
        "integrator": path_integrator,
        "light": directional_light,
        "sensor": perspective_camera,
        "background": plane,
    }
)

image = mi.render(scene, sensor=mi.load_dict(perspective_camera))
mi.util.write_bitmap("/tmp/debug.png", image)

image = mi.render(scene, sensor=mi.load_dict(perspective_camera_shifted))
mi.util.write_bitmap("/tmp/debug_shifted.png", image)
```

2. `/tmp/debug.png` is completely black, `/tmp/debug_shifted.png` shows a checkerboard.

Here are my rendered images for reference:

**debug.png**
![debug](https://github.com/user-attachments/assets/e857b186-038c-453d-8844-d484f652e3d9)

**debug_shifted.png**
![debug_shifted](https://github.com/user-attachments/assets/0b9579e5-cae7-45be-9098-fe97a8e18359)

**Comment by DanielPSchenk** [comment]
this is because the origin-target vector is linearly dependent on the up vector (both have only z components), so `look_at` can not construct a valid camera transformation. Offsetting the camera position even slightly breaks the linear dependence. Choose a valid up vector.

**Comment by brambozz** [comment]
Ah great thanks for that explanation! I see now also that in the non-shifted one, the transformation matrix has `nan` entries.

I changed it to this, and now it works as expected:

```py
perspective_camera = {
    "type": "perspective",
    "to_world": mi.ScalarTransform4f.look_at(
        origin=[0, 0, 1],
        target=[0, 0, 0],
        up=[0, 1, 0],
    ),
}
```
