### ISSUE TITLE
Low gray value via camera capture

### ISSUE THREAD

**Issue by guge2** [mitsuba-renderer/mitsuba3#1426]
# Low gray value via camera capture

## description

I use mitsuba3 to simulate a structured light system: a photo with a predefined pattern was projected via `emitter:projector`, and integrator type is `prb_projective`, then use camera `thinlens` to capture light from lightened object, now I get a png.

If use plt to show this png, it is normalized and seem pretty good, so all of the `to_world` are setting correctly, but acturally the gray values in photo are from 0 to 0.00..1+, I'm comfirm that my photo input to projector is right for gray value from 0 to 255, why?

![normalized_png](https://github.com/user-attachments/assets/ad94c94a-19f4-47d5-865b-377ac4a5a887)

If set `projector.scale` to 10000 rather than 1, the capture gray value rise to `min==0, max==0.00..1*10000`, but it's not the correct way to simulate, isn't it?

## my `scene` structure

```python
Scene[
  children = [
    OBJMesh[
      name = "shapes.obj",
      bbox = BoundingBox3f[
        min = [-100, -49.9895, -35.7005],
        max = [50, 100.212, 5.22445]
      ],
      vertex_count = 76691,
      vertices = [1.76 MiB of vertex data],
      face_count = 117590,
      faces = [1.35 MiB of face data],
      face_normals = 0
    ],
    BitmapTexture[
      name = "img_20.png",
      resolution = "[1920, 1080]",
      raw = 0,
      mean = [0.5],
      transform = Transform[
        matrix=[[1, 0, 0],
                [0, 1, 0],
                [0, 0, 1]],
        inverse_transpose=[[1, 0, 0],
                           [0, 1, 0],
                           [0, 0, 1]]
      ]
    ],
    Projector[
      x_fov = 32,
      irradiance = BitmapTexture[
        name = "img_20.png",
        resolution = "[1920, 1080]",
        raw = 0,
        mean = [0.5],
        transform = Transform[
          matrix=[[1, 0, 0],
                  [0, 1, 0],
                  [0, 0, 1]],
          inverse_transpose=[[1, 0, 0],
                             [0, 1, 0],
                             [0, 0, 1]]
        ]
      ],
      intensity_scale = [100],
      to_world = [[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, -250],
       [0, 0, 0, 1]]
    ],
    PathProjectiveIntegrator[max_depth = 64, rr_depth = 5],
    ThinLensCamera[
      x_fov = [24],
      near_clip = 0.01,
      far_clip = 10000,
      focus_distance = [250],
      film = HDRFilm[
        size = [1280, 800],
        crop_size = [1280, 800],
        crop_offset = [0, 0],
        sample_border = 0,
        compensate = 0,
        filter = GaussianFilter[stddev=0.50, radius=2.00],
        file_format = OpenEXR,
        pixel_format = y,
        component_format = float16,
      ],
      sampler = IndependentSampler[
        base_seed = 0
        sample_count = 64
        samples_per_wavefront = 1
        wavefront_size = 0
      ],
      resolution = [1280, 800],
      shutter_open = 0,
      shutter_open_time = 0,
      to_world = [[0.994522, 0, -0.104528, 30],
       [0, 1, 0, 2],
       [0.104528, 0, 0.994522, -250],
       [0, 0, 0, 1]]
    ]
  ]
]
```

## System configuration
- ubuntu(WSL)
- python 3
- mitsuba 3.6.0

**Comment by njroussel** [comment]
Hi @guge2 

I'm not sure I understand your questions. Are you expecting the result to be in [0, 255] ? This has to do with how you decide to store/save the film. In most use cases the `Bitmap` object will use a `float32` representation for the data, and will use that save representation when storing it to a file. You can convert to other formats using [`Bitmap.convert()`](https://mitsuba.readthedocs.io/en/stable/src/api_reference.html#mitsuba.Bitmap.convert).

**Comment by guge2** [comment]
> Hi @guge2
> 
> I'm not sure I understand your questions. Are you expecting the result to be in [0, 255] ? This has to do with how you decide to store/save the film. In most use cases the `Bitmap` object will use a `float32` representation for the data, and will use that save representation when storing it to a file. You can convert to other formats using [`Bitmap.convert()`](https://mitsuba.readthedocs.io/en/stable/src/api_reference.html#mitsuba.Bitmap.convert).

yes, I'm expecting the result to be in [0, 255], but not doing image processing, after capture light from object and show in image, it should get a photo that the gray value to be in [0, 255].

I might something wrong in the configure, but I can't find out, thank you for help.

**Comment by njroussel** [comment]
Let me maybe clarify the process: 
The image that you select as the texture to be projected by the `projector` emitter, gets read and converted to linear color space for rendering. The set of defaults, will assume that the input image values are in the [0,1] range and do computations on that scale. If you want to use a different scale, you will need to provide a `scale` parameter that you originally pointed out.

**Comment by guge2** [comment]
> Let me maybe clarify the process: The image that you select as the texture to be projected by the `projector` emitter, gets read and converted to linear color space for rendering. The set of defaults, will assume that the input image values are in the [0,1] range and do computations on that scale. If you want to use a different scale, you will need to provide a `scale` parameter that you originally pointed out.

ummm, I'm not sure: is it always use meter rather than millimeter in mitsuba3?
I use millimeter in obj and I put projector 250mm away from my object (along z axis),  put camera 0.25m away from  my object (along z axis), and then my camera captured a png with max gray value: 0.005;

then I set `scale_to_meter = 0.001`, `proj_transform = mi.ScalarTransform4f().translate([0, 0, -1*object_mean_distance])`, put projector 0.25m away from  my object (along z axis),  put camera 0.25m away from  my object (along z axis), and then my camera captured a png with max gray value: 5000, this is my code:

```python
# Define scene parameters
scale_to_meter = 0.001
spp = 64
max_depth = 64
cam_width = 424
cam_height = 400
OAIA = 6.0 # Optical Axis Intersection Angle between camera and projector
fov_cam = 24
fov_proj = 32
cam_aperture = 0.00016
object_mean_distance = 250 * scale_to_meter
mat_ior = 1.0634878252015734
mat_alpha = 0.22
mat_diff = 0.91
proj_transform = mi.ScalarTransform4f().translate([0, 0, -1*object_mean_distance])

obj_abs_root = str(data_root / "meshes/shapes_center_0.5.obj")
photo_abs_root = str(data_root / "patterns/white/img_00.png")
print(f"\033[32mThe obj root is {obj_abs_root}\033[0m")
print(f"\033[32mThe photo root is {photo_abs_root}\033[0m")

sensors = [] 
for i in range(2):
    # Create a sensor
    sensors.append({
        "type": "thinlens",
        "far_clip": 1e4,
        "aperture_radius": cam_aperture,
        "fov": fov_cam,
        "focus_distance": object_mean_distance,
        "to_world": (mi.ScalarTransform4f().translate([-30.0*(2*i-1)* scale_to_meter, 2.0* scale_to_meter, -object_mean_distance]) @
                     mi.ScalarTransform4f().rotate(axis=(0, 1, 0), angle=OAIA*(2*i-1))),
        "sampler": {
            "type": "independent",
            "sample_count": spp
        },
        "film": {
            "type": "hdrfilm",
            "width": cam_width,
            "height": cam_height,
            "file_format": "openexr",
            "pixel_format": "luminance",
            "component_format": "float32",
            "sample_border": False,
            "rfilter": {
                "type": "gaussian"
            }
        }
    })
# Define the scene parameters as a dictionary
scene_dict = {
    "type": "scene",
    
    "integrator": {
        "type": "prb_projective",
        "max_depth": max_depth
    },

    "shape": {
        "type": "obj",
        "filename": obj_abs_root,
        "bsdf": {
            "type": "roughplastic",
            "distribution": "beckmann",
            "int_ior": mat_ior,
            "alpha": mat_alpha,
            "diffuse_reflectance": mat_diff
        },
        "to_world": (mi.ScalarTransform4f().translate([0, -0, 0]) @
                     mi.ScalarTransform4f().rotate(axis=(0, -1, 0), angle=0) @
                     mi.ScalarTransform4f().rotate(axis=(1, 0, 0), angle=0) @
                     mi.ScalarTransform4f().scale(scale_to_meter))
    },

    "emitter": {
        "type": "projector",
        # "irradiance": projector_pattern,
        "irradiance": {
            "type": "bitmap",
            "filename": photo_abs_root,
            "raw": True
        },
        "scale": 1,
        "to_world": proj_transform,
        "fov": fov_proj
    }
}
```

**Comment by guge2** [comment]
I found that I can resolve this by setting projector's scale to be: `scale * 1000^2`, because projector irradiance's unit is W/m², and then  multiply 1000^2 to change to W/mm²
