### ISSUE TITLE
Curve and subdivision support enabling ?

### ISSUE THREAD

**Issue by nyue** [mitsuba-renderer/mitsuba3#143]
*Please add one of the following label to your issue's title, and delete this section:*

- [🐛 bug report]
- I tried enabling embree curve and subdivision support via CMake flags but even when I enabled them to ON, ccmake list them as OFF
- ``` EMBREE_GEOMETRY_CURVE            OFF
 EMBREE_GEOMETRY_GRID             OFF
 EMBREE_GEOMETRY_INSTANCE         ON
 EMBREE_GEOMETRY_POINT            OFF
 EMBREE_GEOMETRY_QUAD             OFF
 EMBREE_GEOMETRY_SUBDIVISION      OFF
```
- 
- [🔨 compilation issue]
- [✨ feature request]
- [❔ other question]

## Summary

*Please enter a brief description of your issue <- [remove this]*

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform: ...
- Compiler: ...
- Python version: ...
- Mitsuba 3 version: ...
- Compiled variants:
    * `scalar_rgb`
    * ...

## Description

*Please enter the full description of your issue <- [remove this]*

## Steps to reproduce

*For bug report, please enumerate the steps to follow in order to reproduce the issue <- [remove this]*

1. ...
2. ...

**Comment by dvicini** [comment]
Hi, 
Subdivision and curve primitives are currently not supported by Mitsuba. Feel free to post a feature request on the "Discussions" tab. I will close this here as we will try to keep the "issues" tab for bugs and issues running supported features.
Delio
