### ISSUE TITLE
Unsupported value type:   <class 'mitsuba.Transform4f'> with llvm based variants

### ISSUE THREAD

**Issue by flipphillips** [mitsuba-renderer/mitsuba3#1430]
## Summary

Attempting to do 'pretty normal' things with the `llvm` based variants causes a little bit of chaos in macOS, mainly that some types aren't supported. 

## System configuration

System information:
```
❯ python -m mitsuba.sys_info
System information:

  OS: 15.2
  CPU: b'Apple M3 Max'
  Python: 3.10.15 (main, Oct  3 2024, 02:24:49) [Clang 14.0.6 ]
  LLVM: 19.1.4

  Dr.Jit: 1.0.1
  Mitsuba: 3.6.0
     Is custom build? True
     Compiled with: AppleClang 16.0.0.16000026
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_mono
        llvm_rgb
        llvm_ad_rgb
        llvm_spectral
        llvm_ad_spectral
        llvm_ad_spectral_polarized
```
## Description

Scenes that render fine with `scalar` variants can't be parsed with `llvm` variants on macOS.

## Steps to reproduce

A simple test with a few variants.

```python
import mitsuba as mi

variants = ['scalar_rgb', 'llvm_spectral', 'llvm_ad_spectral']

for variant in variants:
    print(f"\nTesting variant: {variant}")
    mi.set_variant(variant)
    
    # Create transform
    transform = mi.Transform4f().look_at(
        origin=mi.Point3f(0, 0, 10),
        target=mi.Point3f(0, 0, 0),
        up=mi.Point3f(0, 1, 0)
    )
            
    test_dict = {
        'type': 'scene',
        'camera': {
            'type': 'perspective',
            'to_world': transform 
        }
    }
    
    try:
        scene = mi.load_dict(test_dict)
        print("Scene creation succeeded")
    except Exception as e:
        print(f"Scene creation failed: {str(e)}")
```

### Expected results 

Successful scene creation in all three variants.

### Actual results

```sh
❯ /Users/fxpppr/miniforge3/envs/mitsuba/bin/python /Users/fxpppr/GitHub/bobsight/variant2.py

Testing variant: scalar_rgb
Scene creation succeeded

Testing variant: llvm_spectral
Scene creation failed: ​[xml_v.cpp:423] Unsupported value type: <class 'mitsuba.Transform4f'>!

Testing variant: llvm_ad_spectral
Scene creation failed: ​[xml_v.cpp:423] Unsupported value type: <class 'mitsuba.Transform4f'>!
```

**Comment by lnuic** [comment]
Dear @flipphillips,

When defining the world transform of the perspective camera, you should use the `ScalarTransform4f`.
You can find examples of how to configure the sensors using a Python dictionary in the [documentation](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_sensors.html#perspective-pinhole-camera-perspective).

The following code should be a working version:

```python
import mitsuba as mi

variants = ['scalar_rgb', 'llvm_spectral', 'llvm_ad_spectral']

for variant in variants:
    print(f"\nTesting variant: {variant}")
    mi.set_variant(variant)
    
    # Create transform
    transform = mi.ScalarTransform4f().look_at(
        origin=mi.ScalarPoint3f(0, 0, 10),
        target=mi.ScalarPoint3f(0, 0, 0),
        up=mi.ScalarPoint3f(0, 1, 0)
    )
            
    test_dict = {
        'type': 'scene',
        'camera': {
            'type': 'perspective',
            'to_world': transform 
        }
    }
    
    try:
        scene = mi.load_dict(test_dict)
        print("Scene creation succeeded")
    except Exception as e:
        print(f"Scene creation failed: {str(e)}")```

**Comment by flipphillips** [comment]
@lnuic - thank you for the correction. I see the error of my ways. I've been making transition from `xml` to python and keep making these sorts of mistakes, and they're even more confusing when they work in some variants and not others... 

I'll close it but leave it here for someone equally confused in the future.

**Comment by flipphillips** [comment]
NB - feature request-ish, it is _very_ difficult to debug `dict` form loading when the only error message you get is `std::bad_cast`. 

I tried the 'intuitive' think like passing a named `debug` flag, and even RTFM and noticed `mi.DEBUG` but setting it to `True` still gives the same error.

**Comment by njroussel** [comment]
Hi @flipphillips 

I agree that this is annoying, but ultimately there isn't a ton we can do.

You're passing in some object and are expecting that it will fit some parameter that is of a certain type. There might be hundreds of reasons why that conversion could not happen. In fact, some parameters can be of various types so now we're not even sure to which one you were hoping to convert to.
Would an explicit list of handled types help?

**Comment by njroussel** [comment]
I've improved the error message in this commit: https://github.com/mitsuba-renderer/mitsuba3/commit/7db5401dcdbdcee70fd28b0736313f1365f279f8
