### ISSUE TITLE
Cannot load plugins in c++ only mitsuba3 script

### ISSUE THREAD

**Issue by baileyheading** [mitsuba-renderer/mitsuba3#1432]
## Summary

I'm trying to get Mitsuba3 running fully in c++. I currently cannot load the plugins for some reason. I think my issue is more about how to use the c++ api because it's not documented much. I've tried to use the repo itself to work out how to manually load the plugins in myself without success. Any tips would be of use. Lastly, it does otherwise work through the terminal and python.

## System configuration

Currently running on Mac os ARM. I don't think I have any issues with my systems build appears to compile without issue.

## Description

I'm able to compile and run things and I'm fairly satisfied that things are pathed / linked right, although hard to be certain. Have used otool a bit in this process and compiling with the paths etc. There may be some redundant steps below, but the main thing is that the loaded plugins printout is []. When I try and load various scenes I get message that a specific plugin (needed for that scene is missing such as srgb). 

```c++
        mitsuba::Thread::static_initialization();

        auto resolver = mitsuba::Thread::thread()->file_resolver();

        auto plugin_manager = mitsuba::PluginManager::instance();

        resolver->append("/path/to/mitsuba3/build/plugins");

        std::cout << "Plugin search paths:" << std::endl;
        for (const auto &path : *resolver) {
            std::cout << " - " << path << std::endl;
        }

        // List all loaded plugins
        auto loaded_plugins = plugin_manager->loaded_plugins();
        std::cout << "Loaded plugins:" << std::endl;
        for (const auto &plugin : loaded_plugins) {
            std::cout << " - " << plugin << std::endl;
        }
```

The dylibs did all build and the paths in the resolver are the ones I wanted, although I'm suspecting I'm not using it correctly perhaps

**Comment by rtabbara** [comment]
Hi @baileyheading ,

From what I can gather, you want to run an independent executable. If that's the case my suggestion would be to copy `src/mitsuba/mitsuba.cpp` and create a file in the same directory and use that as your base. i.e. Keep the `main` function prologue

```cpp
    Jit::static_initialization();
    Class::static_initialization();
    Thread::static_initialization();
    Logger::static_initialization();
    Bitmap::static_initialization();
```

and epilogues 

```cpp
    Profiler::static_shutdown();
    Bitmap::static_shutdown();
    StructConverter::static_shutdown();
    Logger::static_shutdown();
    Thread::static_shutdown();
    Class::static_shutdown();
    Jit::static_shutdown();
```

and gut everything else out you don't need. That eliminates any issues with relative pathing that may be a problem and if we can build a `mitsuba.exe` then your executable should also work in theory. With regards to your plugins not being listed in `loaded_plugins`, just looking at the code, at least with the C++ plugins, it seems like these are loaded lazily (see `PluginManager::PluginManagerPrivate::Plugin *plugin(const std::string &name)`), which may explain why they're not listed. Although I'm not sure why you're encountering an error of a missing `srgb` plugin.

The last thing to keep in mind, just be sure, is that Python plugins won't work through the C++ interface. So for example, attempting to use the Python integrator `prb` through the `mitsuba.exe` commandline tool won't work.

Aside from that, if that doesn't work, my only suggestion would be to try to step through the code to see if the plugins are at least attempted to be loaded when loading a scene and that might give you some clues as to why it's failing.

**Comment by baileyheading** [comment]
Thank you for your suggestions. I ended up modifying the cmakelists to do what I wanted. Specifically I was after a custom independent dylib for ffi usage.
