### ISSUE TITLE
Windows ARM64 pipy wheels?

### ISSUE THREAD

**Issue by oscarbg** [mitsuba-renderer/mitsuba3#1437]
Hi,

would be nice to have.. now we have some Win ARM Elite devices..
cpu backend (LLVM) of course..
ideally also Linux ARM64 (for Linux there could be GPU /CUDA support)..

thanks..

**Comment by merlinND** [comment]
Merging with https://github.com/mitsuba-renderer/mitsuba3/discussions/1433.
