### ISSUE TITLE
[🔨 compilation issue] DLL load failed while importing mitsuba_ext

### ISSUE THREAD

**Issue by juhyc** [mitsuba-renderer/mitsuba3#147]
## Summary

I follow 'https://mitsuba.readthedocs.io/en/latest/src/developer_guide/compiling.html#' step by step. Configuration by Cmake is fine but build have error.

## System configuration

- Platform: Window 10
- Compiler: Visual Studio 2019 x64
- Python version: Python 3.9.12 (Anaconda)
- Mitsuba 3 version: lateset 
- Compiled variants:
    * "scalar_rgb"
    * "scalar_spectral_polarized"
    * "cuda_ad_rgb"
    * "llvm_ad_rgb"

## Description
after command : cmake ..  -G "Visual Studio 16 2019" -A x64
![image](https://user-images.githubusercontent.com/42459518/181398769-d82effd1-97e2-4beb-aa2f-f45f76c361b8.png)
after command : cmake --build . --target ALL_BUILD --config Release
![image](https://user-images.githubusercontent.com/42459518/181398878-364d30e9-4c3a-4d0e-926a-ffd2ecc3645b.png)
When i did build (build -> solution build) via Visual Studio 2019. This method also encountered an errors like this.
![image](https://user-images.githubusercontent.com/42459518/181399020-bcbf00cd-4392-45e9-8010-f04f07013bc4.png)

## Steps to reproduce

1. git clone --recursive https://github.com/mitsuba-renderer/mitsuba3
2. cd mitsuba3
3. mkdir build
4. cd build
5. cmake ..  -G "Visual Studio 16 2019" -A x64
6. cmake --build . --target ALL_BUILD --config Release

**Comment by dvicini** [comment]
Hi,
I think other people have run into the same issue. We haven't had time to look into it yet. Sometimes it resolved on it's own when just running `cmake --build` again. My understanding (without looking into it) is that there is some ordering issue with the cmake target generating the Python "stubs". These stubs are only  necessary to facilitate autocomplete (e.g., in VS code).

Maybe you can try disabling the stub generation in Cmake and see if the build works then?

Delio

**Comment by Speierers** [comment]
Hi @juhyc,

Have you tried with a more recent version of MSVC?

**Comment by juhyc** [comment]
Sorry for the late reply.I haven’t tried recent version of MSVC.I just solved that problem by using Ubuntu operating system, not on Windows.It works on Ubuntu. Thanks.보낸 사람: Sebastien Speierer보낸 날짜: 2022년 8월 15일 월요일 오후 1:19받는 사람: mitsuba-renderer/mitsuba3참조: Juhyung Choi; Mention제목: Re: [mitsuba-renderer/mitsuba3] [🔨 compilation issue] DLL load failed while importing mitsuba_ext (Issue #147) Hi @juhyc,Have you tried with a more recent version of MSVC?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
