### ISSUE TITLE
[❔ other question] Per-instance colors possible?

### ISSUE THREAD

**Issue by cfreude** [mitsuba-renderer/mitsuba3#150]
The docs state that it is not possible to assign different materials to different instances:
https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_shapes.html#instance-instance

However, is it somehow possible to change the material parameters, e.g. color (albedo), per instance?

PS: congrats and thanks for your awesome work on mitsuba3!!!

**Comment by Speierers** [comment]
Hi @cfreude,

No this is not possible in the current version. Feel free to open a PR or a thread in Discussions if you think this is an important freature to have in the future.
