### ISSUE TITLE
[❔ other question] LLVM backend is inactive

### ISSUE THREAD

**Issue by holmes969** [mitsuba-renderer/mitsuba3#153]
## Summary
Error (see below) when run **tutorials/inverse_rendering/volume_optimization** in Jupyter notebook
<img width="842" alt="image" src="https://user-images.githubusercontent.com/15076831/181664025-9fa03615-65a5-4d1f-bc84-913d5f77c7ed.png">

## System configuration
- Platform: Windows11, Anaconda, Visual Studio 2019
- Python version: 3.9.12
- Mitsuba 3 version: latest
- Compiled variants: default ones

## Steps to reproduce
In Anaconda terminal
1. git clone --recursive https://github.com/mitsuba-renderer/mitsuba3
2. git submodule update --init --recursive
3. mkdir build
4. cd build
5. cmake .. -G "Visual Studio 16 2019" -A x64
6. cmake --build . --target ALL_BUILD --config Release
7. cd Release
8. setpath
9. cd ../../tutorials/inverse_rendering/
10. jupyter notebook
11. In jupyter notebook, run all

**Comment by merlinND** [comment]
Hi @holmes969,

Does you system have LLVM installed?
In case you use the Chocolatey package manager on Windows, this is the tip @dvicini had shared:

> `choco install llvm` and then set an environment variable (`DRJIT_LIBLLVM_PATH`) to point to `LLVM-C.dll`

**Comment by holmes969** [comment]
Hi Merlin,

I installed LLVM in my anaconda environment using "conda install -c anaconda llvm". Does that also suffice for the installation of LLVM? Maybe all I need to do is manually set the environment variable then.

**Comment by merlinND** [comment]
Yes, I think you'll need to set the environment variable then.
From the DrJit docs, the officially supported installation method also involves setting the `%PATH%` (or letting the LLVM installer set it for you in any case: 
https://drjit.readthedocs.io/en/latest/firststeps-py.html#llvm-backend

**Comment by holmes969** [comment]
Thanks. I followed the Dr.JIT instructions to install LLVM and it is working now. Anaconda LLVM installation seems not complete and llvm-c.dll cannot be found.

**Comment by Pikachuxxxx** [comment]
So I've tried everything manually installed LLVM and even tried checking the Env variables and set everything manually and I still run into this problem.

**Comment by Speierers** [comment]
@Pikachuxxxx could you provide information about your system and the version of LLVM you have installed?

**Comment by Pikachuxxxx** [comment]
I've tried using LLVM backend on Windows 10/11 with llvm 14.0

**Comment by Speierers** [comment]
Could you try to install another version of LLVM, e.g. 12 or 13? We have never tried Mitsuba 3 with LLVM 14 on Windows before.

**Comment by Pikachuxxxx** [comment]
LLVM 12 doesn't work either

**Comment by Speierers** [comment]
Hi @Pikachuxxxx, did you manage to solve this at the end? Otherwise please give us a full log of the compilation and runtime so we can help you with this.
