### ISSUE TITLE
How can I use the proper parameters to make the non-flat curve texture at the proper size of my bitmap figure

### ISSUE THREAD

**Issue by ljijjiang1234** [mitsuba-renderer/mitsuba3#158]
**Hello**
# How can I use the proper parameters to make the non-flat curve texture at the proper size of my bitmap figure
this is a bitmap picture I add the texture to the surface
![grid](https://user-images.githubusercontent.com/73884949/181904587-3d4b5112-85a6-4edd-a947-d25d96ded585.png)

and This is the curve I would like to add to, it's a ply file forma
![QQ图片20220730173412](https://user-images.githubusercontent.com/73884949/181904592-19520bf2-449b-46c0-9e8e-ff770b7b2fd3.png)

This is bitmap texture
![未命名图片](https://user-images.githubusercontent.com/73884949/181904601-26048611-cca9-429d-be07-2d5562132c6e.png)

**Comment by merlinND** [comment]
Hello @ljijjiang1234,

On the Mitsuba side, you can add a transformation to the `bitmap` texture object in your scene to scale & rotate it. For example, if you're using XML-based scenes:

```xml
        <texture type="bitmap" name="reflectance">
            <!-- .. Texture parameters go here .. -->

            <transform name="to_uv">
                <!-- Scale texture by factor of 2 -->
                <scale x="2" y="2"/>
                <!-- Offset texture by [0.5, 1.0] -->
                <translate x="0.5" y="1.0"/>
            </transform>
        </texture>
```
Source: https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_textures.html?highlight=to_uv#textures

Another option is to modify the UV mapping directly on your input mesh, for example if you want to account for the curvature of your shape.

**Comment by ljijjiang1234** [comment]
Thank for your advice ,I would like to try it soon.

**Comment by merlinND** [comment]
Hello @ljijjiang1234,

I'll close this issue for now but feel free to post again if you encounter other issues.

**Comment by ljijjiang1234** [comment]
![未命名图片](https://user-images.githubusercontent.com/73884949/182286986-367ed9d8-f0f4-45b1-85c4-91987c98c813.png)
All right , I just define UV mapping params when modeling, Seems very well ,Lets look what happened next with your excellent working. Thanks for your advice.

**Comment by merlinND** [comment]
Glad this worked, and thank you for the kind words!
