### ISSUE TITLE
[🔨 compilation issue] Complie issue for .xml

### ISSUE THREAD

**Issue by TLi347** [mitsuba-renderer/mitsuba3#159]
## Summary

I'm following the project [[code](https://github.com/rgl-epfl/differentiable-sdf-rendering)]. Installation by pip is fine but compile has an error.

## System configuration

- Platform: Ubuntu 18.04.5 LTS
- Complier: vscode 1.69.2
- Python version: Python 3.9.12
- Mitsuba 3 version: 3.0.1
- Compliled variants: scalar_spectral

## Description

RuntimeError: ​[xml.cpp:1113] Error while loading "/X/X/differentiable-sdf-rendering/scenes/dragon/dragon.xml" (near line 2, col 2): could not instantiate scene plugin of type "scene": Could not initialize OptiX!

![截屏2022-07-31 23 09 15](https://user-images.githubusercontent.com/53488014/182032843-98821a02-2324-424a-b70d-596930be20c5.png)

## Steps to reproduce

1. python python/optimize.py dragon --optconfig no-tex-12

**Comment by merlinND** [comment]
Hello @TLi347,

Does your machine have an NVIDIA GPU?
If not and you are trying to use the CPU only, you need to pass the `--llvm` flag as per these lines of the `optimize.py` script:

https://github.com/rgl-epfl/differentiable-sdf-rendering/blob/311d1d124a0cd27ae4a7f6e021751e043907c8af/python/optimize.py#L70-L71

In your issue above you indicated that you have only compiled the `scalar_spectral` variant. For this script to work, you will need `llvm_ad_rgb` to be compiled.

**Comment by merlinND** [comment]
Hi @TLi347,

In principle OptiX should be installed automatically as part of the NVIDIA driver, and loaded automatically by Mitsuba.
Perhaps you could try upgrading / re-installing the driver and make sure that all components are installed in the standard location.

The first thing to try would be to run through the basic gradient-based optimization tutorial, making sure to set the variant to `cuda_ad_rgb` (not LLVM). Do you encounter the same error then?
https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/gradient_based_opt.html

**Comment by TLi347** [comment]
Hi @merlinND ,

Yes, I got the same error.
I've followed your comment and tried to run gradient-based tutorials.

![image](https://user-images.githubusercontent.com/53488014/182180327-9d35c345-57b6-4bcd-a0c8-61a18c5fe6f5.png)

RuntimeError: ​[xml.cpp:1113] Error while loading "./scenes/cbox.xml" (near line 1, col 1): could not instantiate scene plugin of type "scene": Could not initialize OptiX!

**Comment by TLi347** [comment]
Ok, there is no 'libnvoptix.so.1' in my machine. I will try to re-install the NVIDIA driver. Thank you for your patience.
