### ISSUE TITLE
[🐛 bug report] Unexpected behaviour of a linear polarizer

### ISSUE THREAD

**Issue by fbergama** [mitsuba-renderer/mitsuba3#162]
## Summary

Rotating a linear polarizer object or modifying the parameter "theta" yields different results

## System configuration

- Platform: Ubuntu 
- Compiler: 20.04
- Python version: 3.9
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `scalar_rgb`
    * `scalar_mono_polarized`
    * `scalar_rgb_polarized`

## Description

We created a sample scene with a rectangle in front of the camera image plane. We associated the "linear polarizer" material to the rectangle. 
As stated in the [documentation](https://mitsuba.readthedocs.io/en/latest/src/generated/plugins_bsdfs.html#linear-polarizer-material-polarizer), modifying the rotation angle `theta` or rotating the rectangle around its z-axis (by the same amount) should yield to the same result but some differences are noticeable (see the attached images).

![Screen Shot 2022-08-01 at 17 13 15](https://user-images.githubusercontent.com/5987529/182181898-d75daa49-daaa-4b10-a392-6f93eb190a3d.png)

![Screen Shot 2022-08-01 at 17 14 01](https://user-images.githubusercontent.com/5987529/182181905-4564bb3b-a50e-4fb9-ba10-5f6860e4942c.png)

In particular, if we modify theta, the obtained Angle of Linear Polarization (AOLP) is constant throughout the whole rectangle up to several decimal digits. Instead, when rotating the whole rectangle, a radial pattern emerges with a difference in the AOLP of a few degrees.

## Steps to reproduce

Scene file:

```
<scene version='2.0.0'>
   
    <integrator type="stokes">
        <integrator type="aov" >
            <string name="aovs" value="nn:geo_normal,pos:position" />
            
            <integrator type="volpath">
                <!-- path tracer parameters -->
            </integrator>
            
        </integrator>
    </integrator>
    

    <!-- perspective camera -->
    <sensor type="perspective">
        <float name="near_clip" value="0.1"/>
        <float name="far_clip" value="100000"/>
        <float name="fov" value="$fov"/>

        <transform name="to_world">

        </transform>

        <film type="hdrfilm">
            <rfilter type="gaussian">
                <float name="stddev" value="0.8" />
            </rfilter>
            <integer name="width" value="$camw"/>
            <integer name="height" value="$camh"/>
            <string name="pixel_format" value="luminance" />
        </film>

        <sampler type="ldsampler">
            <integer name="sample_count" value="32"/>
        </sampler>
    </sensor>

    
    <!-- linear polarizer -->
    
    <shape type="rectangle" >
        
        <bsdf type="polarizer">
            <spectrum name="theta" value="$polar_ang"/>
        </bsdf>
        
        <transform name="to_world">
            <scale x="10.0" y="10.0" z="10.0" />
            <rotate x="1.0" y="0.0" z="0.0" angle="0.0"/>
            <rotate x="0.0" y="0.0" z="1.0" angle="$tilt"/>
            <translate x="0.0" y="0.0" z="30.0" />
        </transform>

    </shape>

    <emitter type="constant">
        <spectrum name="radiance" value="1" />
    </emitter> 
</scene>
```

Python notebook

```
import numpy as np
import matplotlib.pyplot as plt
import mitsuba

mitsuba.set_variant('scalar_mono_polarized')
from mitsuba import FileStream
from mitsuba import Bitmap, Struct
from mitsuba import Integrator
from mitsuba import load_file


def extract_layer_as_numpy( film, name, pxformat ):
    layers = film.bitmap(raw=False).split()
    for layer in layers:
        if layer[0]==name:
            return np.array( layer[1].convert(pxformat, Struct.Type.Float64, srgb_gamma=False)  )


# camera field of view
fov = 50

# rotation of the polarizer around z-axis (deg)
til = -45 # around z

# theta of the polarizer (deg)
pol_angle = 0


scene = load_file("tilted_polarizer_scene.xml", camw=200, camh=200, fov=fov, tilt=til, polar_ang=pol_angle)
sensor = scene.sensors()[0]
scene.integrator().render(scene, sensor)
film = sensor.film()
I = extract_layer_as_numpy( film, "<root>", Bitmap.PixelFormat.RGB )
S0 = np.squeeze(extract_layer_as_numpy( film, "S0", Bitmap.PixelFormat.Y ))
S1 = np.squeeze(extract_layer_as_numpy( film, "S1", Bitmap.PixelFormat.Y ))
S2 = np.squeeze(extract_layer_as_numpy( film, "S2", Bitmap.PixelFormat.Y ))
S3 = np.squeeze(extract_layer_as_numpy( film, "S3", Bitmap.PixelFormat.Y ))

normals = extract_layer_as_numpy( film, "nn", Bitmap.PixelFormat.XYZ )
p3d = extract_layer_as_numpy( film, "pos", Bitmap.PixelFormat.XYZ )

# compute aolp and dolp
aolp = 0.5 * np.arctan2(S2,S1)
dolp = np.sqrt( S1**2 + S2**2 ) / S0

# mask with nan values degree == 0
dolp[dolp<0.01] = np.nan
aolp[np.isnan(dolp)] = np.nan


plt.figure( figsize=(15,5))
plt.subplot(1,2,1)
plt.imshow(dolp, vmin=0.98, vmax=1)
plt.colorbar()
plt.title("dolp")

#plt.subplot(1,2,2)
plt.figure( figsize=(15,5))
plt.imshow(aolp*180/np.pi, cmap="hsv")
#plt.clim(44.9,45.1)
plt.colorbar()
plt.title("AOLP (deg), rot = %.2d, theta = %.2f"%(til,pol_angle))

```

**Comment by fbergama** [comment]
Any news on this issue? Can you confirm that is not the expected behavior?

I suppose that is due to a bug in the tilted-polarizer implementation.

**Comment by tizian** [comment]
Yes, something seems inconsistent here. I'm on vacation until next week and I'll try to have a look when I get back. In the meantime, any help with tracking this down is apreciated 🙂

**Comment by fbergama** [comment]
Nice to hear from you, don't worry, I'm not in a hurry. I'm a researcher working with PFA polarized cameras. We recently tried to compare some simple Mitsuba's rendered scenes against real data.

I think there are some inconsistencies on how Mitsuba implements [Korger et. al "The polarization properties of a tilted polarizer"](https://opg.optica.org/oe/fulltext.cfm?uri=oe-21-22-27032&id=274015). I'll try to hack the code a bit and keep you updated.

**Comment by ziyi-zhang** [comment]
Hi @tizian, I briefly tried the script during the siggraph week and can confirm the issue. 

I also observed that if we use an orthographic camera, the results will be matching. It seems to me that the main difference between orthographic and perspective cam is the incident angle of the camera ray? 
It happens that this script uses the stokes integrator. So I was suspecting the camera ray rotation in `stokes.cpp` at that time. But i didn't follow up later. Hope this helps.

**Comment by khalomer** [comment]
Hello everyone, I believe I have resolved this issue. As shown above, rotating the rectangular mesh vs specifying the rotation angle as a Mueller matrix produces different results as seen in the AoLP.  The inconsistency that @fbergama is describing is due to the rotation angle input as a Mueller matrix does not exhibit the changes in AoLP which should happen as detailed in the "The polarization properties of a tilted polarizer" paper. Off-axis rays will require a projection of the transverse plane onto the surface of the polarizer. Under Mitsuba's current implementation, only rotating the mesh produces the proper response. To correct this, the user-inputted rotation must correspond to the absorption-axis orientation (a = [sin(tht),cos(tht),0]) and not a rotation Mueller matrix. See the new snippet for the `sample()` function that applies this change:

        if constexpr (is_polarized_v<Spectrum>) {
            if (!m_polarizing) {
                return { bs, mueller::absorber(0.5f*transmittance) };
            }

            // Query rotation angle
            UnpolarizedSpectrum theta = dr::deg_to_rad(m_theta->eval(si, active));

            // Extract the user specified angle of the polarizer's transmission axis
            Float theta_float = theta[0,0];

            // Get standard Mueller matrix for a linear polarizer.
            Spectrum M = mueller::linear_polarizer(1.f);

            // Rotate optical element by specified angle
            //M = mueller::rotated_element(theta, M);

            /* The `forward` direction here is always along the direction that
               light travels. This is needed for the coordinate system rotation
               below. */
            Vector3f forward = ctx.mode == TransportMode::Radiance ? si.wi : -si.wi;

            // Define the new absorption axis based on the input polarizer angle
            Float cos_theta = dr::cos(theta_float);
            Float sin_theta = dr::sin(theta_float);

            /* To account for non-perpendicular incidence, we compute the
               effective transmitting axis based on "The polarization properties
               of a tilted polarizer" by Korger et al. 2013. */
            Vector3f a_axis(sin_theta, cos_theta, 0);

            Vector3f eff_a_axis = dr::normalize(a_axis - dr::dot(a_axis, forward)*forward);
            Vector3f eff_t_axis = dr::cross(forward, eff_a_axis);

            // Rotate in/out basis of M s.t. to standard basis
            M = mueller::rotate_mueller_basis_collinear(M, forward,
                                                        eff_t_axis,
                                                        mueller::stokes_basis(forward));

            // Handle potential absorption if transmittance < 1.0
            M *= mueller::absorber(transmittance);

            return { bs, M };
        } else {
            return { bs, 0.5f * transmittance };
        }


Note, I don't have a great way to convert the `UnpolarizedSpectrum theta` to a `Float`, so I do this by extracting the 0,0 element and define a new variable. I then define the new absorption axis w.r.t the input polarizer angle `theta`.  Probably a better way to do this, but I am not an expert in the data type conversion/format. 
With this correction, the AoLP when rotating the mesh and specifying a rotation angle are now the same:

![image](https://user-images.githubusercontent.com/84816226/187275147-13dd00c1-6ff6-4e5e-9ed8-9eaf164306cc.png)
![image](https://user-images.githubusercontent.com/84816226/187275174-1fddd3a5-fc14-4204-b501-7383a17cf364.png)

**Comment by fbergama** [comment]
My idea was to patch the code in the same way (ie. by creating a_axis as (sin_theta, cos_theta, 0) instead of (1,0,0)). What you did sounds reasonable to me.

Thanks!

**Comment by tizian** [comment]
Thanks for tracking this down, that all makes a lot of sense actually :)
I opened a corresponding PR: https://github.com/mitsuba-renderer/mitsuba3/pull/220

**Comment by wxw19990405** [comment]
Hi! @fbergama 
I am a postgraduate student studying 3D imaging. I want to simulate polarization cameras to obtain polarization images under different polarization angles (0°, 45°, 90°, 135°) by using mitsuba. However, I have encountered some problems in the simulation process https://github.com/mitsuba-renderer/mitsuba3/issues/832#issue-1826511853. Can you help me to find out the cause of this problem Or how should I properly simulate the behavior of a polarizing camera in a mitsuba?
