### ISSUE TITLE
[❔ other question] What and where is the "jit_init" function?

### ISSUE THREAD

**Issue by techtide** [mitsuba-renderer/mitsuba3#167]
## System configuration

- Platform: Debian, Windows Subsystem for Linux V2 with CUDA release 11.6, V11.6.55
- Python version: 3.10.4
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `cuda_ad_rgb`

## Description

My environment variable for `DRJIT_LIBCUDA_PATH` is set correctly to `/usr/lib/wsl/lib/libcuda.so`.

I encounter the following runtime error:
`jit_init_thread_state(): the CUDA backend is inactive because it has not been initialized via jit_init(), or because the CUDA driver library ("libcuda.so") could not be found! Set the DRJIT_LIBCUDA_PATH environment variable to specify its path.`

I have searched the documentation for both Mitsuba and Dr. Jit, but I am unable to find any documentation on the jit_init(). I have briefly looked into the codebase, but cannot seem to find a definition for jit_init even in the [`jit.h` header file ](https://github.com/mitsuba-renderer/mitsuba3/blob/master/include/mitsuba/core/jit.h). It is referenced [here](https://github.com/mitsuba-renderer/mitsuba3/blob/152352f87b5baea985511b2a80d9f91c3c945a90/src/mitsuba/mitsuba.cpp), but I cannot seem to figure out its usage and how I can call it from my code.

Would appreciate any guidance on how to resolve this issue. Is `jit_init` something I'm meant to call, or is something else amiss in my Mitsuba or CUDA setup?

**Comment by wjakob** [comment]
You will either have to run on a proper Windows or Linux session, but WSL is not supported, sorry. We won't be able to support WSL until NVIDIA makes OptiX work in this environment.

**Comment by maxfrei750** [comment]
Relevant thread from NVIDIA: https://forums.developer.nvidia.com/t/optix-on-wsl-windows-subsystem-for-linux/140297/15

**Comment by zhaoyangyang316** [comment]
Thanks for the note, lets wait nvidia to update OptiX.
