### ISSUE TITLE
[✨ feature request] Inverse-rendering using pytorch

### ISSUE THREAD

**Issue by owaranainatsu** [mitsuba-renderer/mitsuba3#168]
Can we use PyTorch in inverse rendering like the file [here](https://github.com/mitsuba-renderer/mitsuba2/blob/master/docs/examples/10_inverse_rendering/invert_cbox_torch.py) in mitsuba2?

**Comment by diiigle** [comment]
Related: https://github.com/mitsuba-renderer/mitsuba3/discussions/121#discussioncomment-3347271
Can we close it as an issue and keep it in the discussion?

**Comment by hiroaki-santo** [comment]
I also have the same issue in https://github.com/mitsuba-renderer/drjit/issues/54
Since it is categorized as a feature request and roadmap, is it impossible at the current Mitsuba3?

**Comment by Speierers** [comment]
This is on our roadmap. Let's discuss this further [here](https://github.com/mitsuba-renderer/mitsuba3/discussions/121#discussioncomment-3347271).

@hiroaki-santo you can take a look at [this experimental branch](https://github.com/mitsuba-renderer/drjit/tree/from_to_torch) for the time being. We hope to merge this in the next release.
