### ISSUE TITLE
[🐛 bug report] RuntimeError: ​[OBJMesh] Error while loading OBJ file "rectangle.obj": file not found

### ISSUE THREAD

**Issue by zhaoguangyuan123** [mitsuba-renderer/mitsuba3#172]
## Summary

Cannot find the 'rectangle.obj' when load the scene dict with mi.load_dict(...)

## System configuration

- Platform:  Mac OS, x64
- Python version: 3.8.5 (conda env)
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `llvm_ad_rgb`

## Description

cannot file the obj file even download the 'scene' folder and put it into the mitsuba directory. 
`RuntimeError: ​[OBJMesh] Error while loading OBJ file "rectangle.obj": file not found
`
### 1. pip install mitsuba==3.0.1
Requirement already satisfied: mitsuba==3.0.1 in /usr/local/anaconda3/lib/python3.8/site-packages (3.0.1)
Requirement already satisfied: drjit==0.2.1 in /usr/local/anaconda3/lib/python3.8/site-packages (from mitsuba==3.0.1) (0.2.1)

### 2. download the scene folder and put it into the folder of mitsuba
<img width="307" alt="image" src="https://user-images.githubusercontent.com/48136187/184502828-74ecb337-bd0d-4e7d-867f-e08a24338f20.png">

### 3. run part of script from tutorial https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/caustics_optimization.html

```

from os.path import realpath, join
import drjit as dr
import mitsuba as mi
mi.set_variant('llvm_ad_rgb')

SCENE_DIR = realpath('../scenes')

scene = {
    # Receiving plane
    'type': 'scene',
    'white-bsdf': {
        'type': 'diffuse',
        'id': 'white-bsdf',
        'reflectance': {'type': 'rgb', 'value': (1, 1, 1)},
    },
    'receiving-plane': {
        'type': 'obj',
        'id': 'receiving-plane',
        'filename': SCENE_DIR+'meshes/rectangle.obj',
        'to_world': \
            mi.ScalarTransform4f.look_at(
                target=[0, 1, 0],
                origin=[0, -7, 0],
                up=[0, 0, 1]
            ).scale((5, 5, 5)),
        'bsdf': {'type': 'ref', 'id': 'white-bsdf'},
    },
    
}

mi.load_dict(scene)
```

**Comment by zhaoguangyuan123** [comment]
> Hi @zhaoguangyuan123 ,
> 
> Where is the script file located on your system? Is it in the same folder as the `scenes` folder?

<img width="302" alt="image" src="https://user-images.githubusercontent.com/48136187/184578909-d087be7e-a66b-42bb-979f-e4f4c6f2887f.png">
The last file 'test_loadscene.py' is the script I was testing, in the same folder as the scenes folder.

**Comment by Speierers** [comment]
Then have you tried with `SCENE_DIR = realpath('scenes')` ?

**Comment by zhaoguangyuan123** [comment]
> 

Tried and not work either. 
Thank you.

**Comment by Speierers** [comment]
That is wierd. Could you try to print the following and post it here?
```python
print(mi.Thread.thread().file_resolver())
```

**Comment by zhaoguangyuan123** [comment]
> 
What I got is:
"zsh: parse error near `)'"


very wierd...

**Comment by zhaoguangyuan123** [comment]
> That is wierd. Could you try to print the following and post it here?
> 
> ```python
> print(mi.Thread.thread().file_resolver())
> ```

FileResolver[
  "/Users/guangyuan_zhao/mitsuba3",
  "/usr/local/anaconda3/lib/python3.8/site-packages/mitsuba"
]

**Comment by Speierers** [comment]
And I suppose your script file is located in `/Users/guangyuan_zhao/mitsuba3`?

**Comment by Speierers** [comment]
Also I think you need the following:
```
'filename': SCENE_DIR+'/meshes/rectangle.obj',
```
(note the `/` before `meshes`)

**Comment by zhaoguangyuan123** [comment]
> ```
> 
> ```

it works now with this suggestion. Thank you.

**Comment by merlinND** [comment]
That's why it's almost always better to use `join()` to build paths :)

**Comment by zhaoguangyuan123** [comment]
> Thanks for such lesson. :joy:
