### ISSUE TITLE
[🐛 bug report] Rendering failed because of texture conversion with backend `cuda_spectral`

### ISSUE THREAD

**Issue by lastmc** [mitsuba-renderer/mitsuba3#176]
## Summary

Hello, everyone!

We tried to render the [Staircase](https://benedikt-bitterli.me/resources/mitsuba/staircase.zip) scene using the command-line `mitsuba-bin` with the `cuda_spectral` backend but encountered the following error:

![image](https://user-images.githubusercontent.com/12976583/185075944-8b82efc8-c5f9-4b20-b8b4-1a3dcd15d757.png)

However, everything's fine with `cuda_rgb`.

## System configuration

- Platform: Windows 11
- Compiler: MSVC 19.31.31106.2
- Python version: N/A
- Mitsuba 3 version: 3.0.1 (commit )
- Compiled variants:
    * `scalar_rgb`
    * `scalar_spectral`
    * `llvm_rgb`
    * `llvm_spectral`
    * `cuda_rgb`
    * `cuda_spectral`

**Comment by Speierers** [comment]
Hi @lastmc,

I suspect one of the `bitmap` texture definition in the XML file is missing the following property:
```
<boolean name="raw" value="true"/>
```
This would ensure that the texture values are not converted into spectral values. For instance, in the case of the normal maps (stored as an RGB texture), it is important to let the renderer know that this texture shouldn't be converted.

Could you try to make this change on your end and let me know if this fixes things? In which case I will update the scene on my side and re-upload it on the different websites.

**Comment by lastmc** [comment]
Thanks! It works for me!
