### ISSUE TITLE
[❔ other question] How to render multiple irradiancemeters efficiently?

### ISSUE THREAD

**Issue by cfreude** [mitsuba-renderer/mitsuba3#179]
Is there a way to efficiently render multiple irradiancemeters?
Currently, I see two hacky solutions:
1. simply generate scenes (one irradiancemeter per scene) and render them seperatly.
2. change the transform of a single irradiancemeter and re-render

I was wondering if:
- it would be possible to have multiple irradiancemeters in the scene and simply "select" one for rendering without reloading the scene
or
- simply render them all at once into mulitple 1x1 images or a single larger image.
or
- have a irradiancemeter that doesn't only measure over the whole geometry and stores a 1x1 image
  but instead measures at multiple locations on the mesh and stores it into an image (texture) based on a UV parametrization.

**Comment by Speierers** [comment]
Hi @cfreude ,

It is possible to define multiple sensors in a scene and select the one to be used using the `sensor` argument of the `mirender` function (see [doc](https://mitsuba.readthedocs.io/en/latest/src/api_reference.html#mitsuba.render)).

In order to render all of them at once, you could create a new sensor plugin that stiches all those together. See the experimental [`batch` sensor](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/sensors/batch.cpp) as example. Note that this can also be done directlyi n python.

**Comment by Jerrypiglet** [comment]
Hi @Speierers thanks for mentioning the batch sensor! However I am caught up with an issue on how to implement the batch sensor in Python, given a list of sensors. Would it be possible that you can provide an example on this? Thanks!

**Comment by Jerrypiglet** [comment]
As a follow-up to my question, I have prepared [this script](https://gist.github.com/Jerrypiglet/663d9b153d070bf85a503bab44d885ce) for testing the batch sensor, which gives an error:

`
Traceback (most recent call last):
  File "tmp.py", line 56, in <module>
    img2 = mi.render(scene, sensor=mi.load_dict(batch_sensor_dict))
  File "/Users/jerrypiglet/miniconda3/envs/dvgo-py38/lib/python3.8/site-packages/mitsuba/python/util.py", line 518, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "/Users/jerrypiglet/miniconda3/envs/dvgo-py38/lib/python3.8/site-packages/drjit/router.py", line 5621, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "/Users/jerrypiglet/miniconda3/envs/dvgo-py38/lib/python3.8/site-packages/mitsuba/python/util.py", line 373, in eval
    return self.integrator.render(
RuntimeError: jit_var_new_op(select, r666, r0, r63): arithmetic involving an uninitialized variable!
`
Thanks again for the attention!

**Comment by Speierers** [comment]
Hi @Jerrypiglet ,

Please open a separate issue with information about your system for this.

Regarding the implementation of a `batch` sensor in Python, make sure to fully understand the implementation of `batch.cpp` and then take a look at the [following tutorial](https://mitsuba.readthedocs.io/en/stable/src/others/custom_plugin.html) on how to implement custom Mitsuba plugins in Python.
