### ISSUE TITLE
[🐛 bug report] Device ran out of memory, could not allocate 512 bytes

### ISSUE THREAD

**Issue by DiegoK98** [mitsuba-renderer/mitsuba3#182]
## Summary
The GPU immediately runs out of memory when using the cuda backend.

## System configuration
- Platform: Windows 10
- Compiler: MSVC 14.32
- Python version: 3.9.13
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `scalar_rgb`
    * `cuda_rgb`
- GPU: GTX 980 Ti (6GB of memory)

## Description
I have been using the llvm backend with no problem, but when I try to use the cuda backend, it says that the device has run out of memory. This is the command line full log for just setting the variant to 'cuda_rgb':

    https://pastebin.com/1Xwc9tBq

And when I just render a scene from the console, this is the log:

    https://pastebin.com/wQCjR9nw

The same error happens even if I just write cuda_ for the variant, instead of telling me that the variant does not exist:

    Microsoft Windows [Versión 10.0.19044.1889]
    (c) Microsoft Corporation. Todos los derechos reservados.
    
    C:\Users\Diego>mitsuba -m cuda_
    
    Caught a critical exception: jit_malloc(): out of memory! Could not allocate 512 bytes of device memory.
    
    C:\Users\Diego>

The steps to reproduce are in the logs

**Comment by Speierers** [comment]
Hi @DiegoK98 ,

This is strange indeed. Could you try to compile in Debug mode and run this into a debugger?

Also looking at the logs I see that Dr.Jit already complains about memory allocations at the top:
```
jit_flush_malloc_cache(): Dr.Jit exhausted the available memory and had to flush its allocation cache to free up additional memory. This is an expensive operation and will have a negative effect on performance. You may want to change your computation so that it uses less memory. This warning will only be displayed once.
```

Could it be that another process already consumes all the memory available on your GPU?

**Comment by wjakob** [comment]
@DiegoK98, could you try downloading and installing the latest NVIDIA driver (v515 +) to see if that fixes the issue?

**Comment by DiegoK98** [comment]
@wjakob My current driver was already 516.94

**Comment by DiegoK98** [comment]
@Speierers
> Could it be that another process already consumes all the memory available on your GPU?

I don't think that's the case, the task manager shows the GPU memory usage at 0,5/6GB

> Could you try to compile in Debug mode and run this into a debugger?

I have compiled in Debug mode, but I don't know how to run it into a debugger. Currently I am building with Visual Studio 2022 and executing from the default command line.

**Comment by Speierers** [comment]
In Visual Studio you can configure a command line to run in the debugger. Maybe you can take a look at [this tutorial](https://cs-people.bu.edu/deht/CS585/VSTutorial/#:~:text=To%20set%20command%2Dline%20arguments,program%20via%20the%20argv%20array.).

**Comment by HashaamSaeed** [comment]
I am facing the exact same issue with the following config :

- Platform: Windows 10
- Python version: 3.8.10
- Mitsuba 3 version: 3.0.1
- Nvdia driver version: 516.94
- GPU: GTX 980M (8GB of dedicated memory)
- GPU memory usage while execution: 0.8/8.0 GB

command line full log :
https://pastebin.com/9FNvBUQm

**Comment by DiegoK98** [comment]
It worked on my laptop with a GTX 1650, where I have the same driver version, same CUDA version, same python version, etc.
The biggest difference is the GPU model, so I am guessing there is something wrong with the GTX 980 models, or even with any GPU with compute capability 5.2 (https://developer.nvidia.com/cuda-gpus)

**Comment by HashaamSaeed** [comment]
@DiegoK98 
perhaps that might be the case considering the bigger L1,L2 caches of newer gen GPUs but if that was the case then i suppose the authors would have mentioned the limitations of compute capability in the docs or would have suggested the same in this thread.

Thanks for the follow up though :)

**Comment by njroussel** [comment]
Hi @HashaamSaeed @DiegoK98 

I actually managed to reproduce this recently on a GTX 970 but didn't have time to investigate yet.
I'll try do dig a bit deeper to understand what is going. It might indeed simply be related to the compute capability of the GPU.

**Comment by wjakob** [comment]
@njroussel : Nice! This is a really vexing problem that already appeared a long time ago while trying to track down an unrelated issue together with the OptiX Team (David Hart). For some reason, even the first call to malloc that allocates a tiny 512 bytes fails. This indicates that somehow CUDA isn't properly initialized, or we are missing another important bring-up step. This is puzzling because we check for various errors codes during the initialization, which presumably passed. If you have a piece of hardware that actually reproduces it then this will help a lot!

A GTX 970 should in principle be good enough (compute capability-wise) to run both OptiX and Mitsuba, though it will of course not be super-fast.

**Comment by HashaamSaeed** [comment]
Bonjour @njroussel @wjakob 

Thank you for the prompt responses.
Will try finding a solution as well as run on a different GPU with a similar config to recreate the error.
