### ISSUE TITLE
- [🐛 bug report] problem with branch ext/drjit in the git repository

### ISSUE THREAD

**Issue by tatue64** [mitsuba-renderer/mitsuba3#184]
## Summary

There seems to be a problem with the ext/drjit branch in the master branch of the git repository

git pullall leads to the following error 

fatal: Fehler am anderen Ende: upload-pack: not our ref 66553c40d737ce3c16e79f997fda127248fce17a
fatal: "fetch" in Submodul-Pfad 'ext/drjit' ausgeführt, aber enthielt nicht 66553c40d737ce3c16e79f997fda127248fce17a. Direktes Anfordern dieses Commits ist fehlgeschlagen.

## System configuration

- Platform:  Mitsuba Linux
- Compiler: clang
- Python version: 3.10.
- Mitsuba 3 version: 3.1
- Compiled variants:
    * `scalar_rgb`
    * ...

## Description

*Please enter the full description of your issue <- [remove this]*

## Steps to reproduce

*For bug report, please enumerate the steps to follow in order to reproduce the issue <- [remove this]*

1. ...
2. ...

**Comment by Speierers** [comment]
This should be fix now. We updated the submodules of Mitsuba and forgot to push some commits to the `drjit` repository.
