### ISSUE TITLE
[🐛 bug report] Incorrect behaviour of area light size

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/mitsuba3#185]
## Summary

The rectangle obtained by rendering a plane from an area light does not scale linearly with increasing the size of area light. 

## System configuration

- Platform: Ubuntu 20.04.4 LTS
- Python version: 3.8.10
- Mitsuba 3 version: 3.0.1
- Compiled variants: cuda_ad_rgb`

## Description

We construct a scene consisting of a large metallic cube with scale=1000 and centered at (0, 0, -1000). That is, its upper face is the part of the plane z = 0. We have a camera at the point (0, 0, 2) looking directly to this plane. A rectangle area light is placed in parallel to the camera plane and faces the same direction. Rendering such scene, we obtain a rectangle. It seems for me that if we scale the size of area light in two times, the size of the obtained rectangle should be scaled in two times also. It works for the small sizes of area light but then the size of rectangle stops to grow.  

Scale = 0.5: 
![download](https://user-images.githubusercontent.com/20816212/185464713-b3e13542-5153-4668-bef5-6c80a3e3573a.png)

Scale = 1:
![download (1)](https://user-images.githubusercontent.com/20816212/185464777-0ac15585-75c3-4dab-b507-2180c647de42.png)

Scale = 2 (in my opinion, it should be larger than scale=1!): 
![download (2)](https://user-images.githubusercontent.com/20816212/185464875-f872f8d1-dc72-4f1d-abee-e6d79a59a901.png)

## Steps to reproduce
Please look at the attached ipynb. 
[Mitsuba3_plane_area_size.ipynb.zip](https://github.com/mitsuba-renderer/mitsuba3/files/9376443/Mitsuba3_plane_area_size.ipynb.zip)

**Comment by Speierers** [comment]
Hi @TZZZZ ,

Running your script I get 3 times the same image. Could you try again on your end?

**Comment by TZZZZ** [comment]
Hi @Speierers , 

I updated the lib but I have the same results (small image and then two equal). I think that all three images should be different.

**Comment by merlinND** [comment]
Hi @TZZZZ,

One thing to keep in mind is that the area light emits in all directions of the upper hemisphere, not just perpendicularly to its surface.
Two more things to understand the situation a bit better:

1. Could you please post a simple 2D diagram illustrating the scene setup and showing what you expect in all three cases?
2. Try in `scalar_rgb` mode, since it's the simplest variant.

**Comment by TZZZZ** [comment]
Hi @merlinND, 

Thank you for the answer. 
In scalar_rgb I have equal images. 

This is a scene
<img width="1429" alt="blender_scene" src="https://user-images.githubusercontent.com/20816212/185672434-e9e755e0-b39c-4a4d-9279-8ac57e485403.png">

this is what blender is rendering with the light-size 50: 
<img width="268" alt="render50" src="https://user-images.githubusercontent.com/20816212/185672567-5ba9df48-408d-4c4c-888c-4a34787e8983.png">

the light-size 75: 
<img width="268" alt="render75" src="https://user-images.githubusercontent.com/20816212/185672666-f6221c17-0409-4a1f-8689-41ed30af4d03.png">

the light-size 100:
<img width="268" alt="render100" src="https://user-images.githubusercontent.com/20816212/185672722-41f437ee-7354-45f0-9a36-5828bf7cc2a8.png">


I expect similar behaviour that the image changes with the change of light-size linearly.

**Comment by merlinND** [comment]
Hello,

Thanks for the scene preview. By "metallic cube" I hadn't understood that we were supposed to see a perfect reflection of the light source.
You would have seen the same issue by pointing the camera at the light source directly btw.

The function `set_light()` you were using to change the world transform at runtime made some changes to individual entries of the transformation matrix, which I believe is not allowed.
By rewriting the function as follows, I get the expected results:

```python
def set_light(scale=10):
    trafo = mi.Transform4f(params['Camera.to_world'])
    trafo = mi.Transform4f.scale(scale) @ trafo
    params['Emitter.to_world'] = trafo
    params.update()
```

<img width="443" alt="image" src="https://user-images.githubusercontent.com/5563370/185675321-438e9e18-f937-431b-882c-88bd02007f17.png">

**Comment by merlinND** [comment]
To illustrate my point about directly editing transform matrices:

```python
params['Emitter.to_world'].matrix[0,0] = 1000
print(params['Emitter.to_world'].matrix[0,0])
print(params['Emitter.to_world'].inverse().matrix[0,0])

params['Emitter.to_world'].matrix[0,0] = 0.1
print(params['Emitter.to_world'].matrix[0,0])
print(params['Emitter.to_world'].inverse().matrix[0,0])
```

Prints:
```
1000.0
-0.0005000000237487257
0.10000000149011612
-0.0005000000237487257
```

If editing matrices directly is a requirement, you can always create a fresh transformation based on the matrix: 

```python3
mat = mi.Matrix4f(params['Emitter.to_world'].matrix)
mat[:3, :3] = 0
mat[0, 0] = 10
mat[1, 1] = 10
mat[2, 2] = 10
params['Emitter.to_world'] = mi.Transform4f(mat)
print(params['Emitter.to_world'])
print(params['Emitter.to_world'].inverse())
```

which prints:

```
[[10, 0, 0, 0],
 [0, 10, 0, 0],
 [0, 0, 10, 0],
 [0, 0, 0, 1]]
[[0.1, 0, 0, 0],
 [0, 0.1, 0, 0],
 [0, 0, 0.1, 0],
 [0, 0, 0, 1]]
```
