### ISSUE TITLE
[❔ other question] Sampling emitters in Python

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/mitsuba3#189]
Hi,

I'm trying to sample the emitters of a scene and want to get importance sampled rays.
In C++ there exists the function ```sample_emitter_ray``` in the scene class.
This function does however not exist in the Python class.
Is there a way to do this or should I just sample the sphere and use ```sample_emitter_direction```

Thanks for your help.

**Comment by Speierers** [comment]
Hi @DoeringChristian ,

Thanks for reporting this. It will be fixed in the next release, I added bindings for that method: [328ee79](https://github.com/mitsuba-renderer/mitsuba3/commit/328ee79f479658106c5f7b12dcf66dc33065fed4)
