### ISSUE TITLE
🐛 bug report] Tutorial object_pos_estimation does no longer work with Mitsuba 3.0.1

### ISSUE THREAD

**Issue by tatue64** [mitsuba-renderer/mitsuba3#192]
## Summary

The tutorial object_pose_estimation does not longer work.  

## System configuration

*For bug report, please enter information regarding your system configuration<- [remove this]*

- Platform:  manjaro linux
- Compiler: clang
- Python version: 3.10.5
- Mitsuba 3 version: 3.0.01
- Compiled variants:
    * `scalar_rgb`
    * ` llvm_ad_rgb` 

## Description

The cell computing loss_hist throws an error

> jit_var_new_op(add, r8943, r8968): arithmetic involving arrays of incompatible size!

This is maybe connected to the changes in the film plugin 

## Steps to reproduce

Run tutorial object_pose_estimation

1. ...
2. ...

**Comment by njroussel** [comment]
Hi @tatue64 

Indeed, our CI was down for a few days and unfortunately this bug made it's way through to `master`.
I'll be working on this to get it quickly resolved. In the meantime, you can revert to commit 570863df3f5a289ee33f251c239a8b000a85f10d to circumvent it.

**Comment by Speierers** [comment]
@tatue64 this should be fixed now. [647fb13](https://github.com/mitsuba-renderer/mitsuba3/commit/647fb135b825176dab199c0de188e419a61bf405)
