### ISSUE TITLE
[🔨 compilation issue] Error occurred when import mitsuba

### ISSUE THREAD

**Issue by Li-Jiren** [mitsuba-renderer/mitsuba3#194]
## Summary

Such an error occurred when importing mitsuba (in fact it occurred when importing drjit):
`ImportError: generic_type: type "VarType" is already registered!`

## System configuration

- Platform: Windows 10
- Python version: ...3.9.8
- Mitsuba 3 version: 3.0.1

## Description

Maybe it conflicted with other libs I've installed?
The full traceback:
```
ImportError                               Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_18864/844931039.py in <module>
      3 
      4 import enoki as ek
----> 5 import mitsuba
      6 mitsuba.set_variant('gpu_autodiff_rgb')
      7 get_ipython().run_line_magic('load_ext', 'autoreload')

c:\Users\19182\AppData\Local\Programs\Python\Python39\lib\site-packages\mitsuba\__init__.py in <module>
      6 import threading
      7 from importlib import import_module as _import, reload as _reload
----> 8 import drjit as dr
      9 import os
     10 import logging

c:\Users\19182\AppData\Local\Programs\Python\Python39\lib\site-packages\drjit\__init__.py in <module>
     22 
     23 # Native extension defining low-level arrays
---> 24 import drjit.drjit_ext as drjit_ext  # noqa
     25 
     26 # Routing functionality (type promotion, broadcasting, etc.)

ImportError: generic_type: type "VarType" is already registered!
```

**Comment by merlinND** [comment]
Hello @Li-Jiren,

From your backtrace, it looks like you imported Enoki first and then Mitsuba? I'm pretty sure that's where the problem comes from.
DrJit is the successor of Enoki, so if you replace all usage of Enoki with DrJit you'll no longer need `ek`.

**Comment by Li-Jiren** [comment]
I was using code from mitsuba 2 so I didn't notice that. Thank you!
