### ISSUE TITLE
[🐛 bug report] Error when rendering with orthographic sensor and ptracer

### ISSUE THREAD

**Issue by Virtual-Optix** [mitsuba-renderer/mitsuba3#198]
## Summary

When trying to render a scene using an orthographic sensor using the `ptracer` integrator and the variant `llvm_ad_rgb`, I get the following error:
`
RuntimeError: ​[Endpoint] OrthographicCamera::sample_direction(): not implemented!
`

## System configuration

- Platform: Windows
- Compiler: pip
- Python version: 3.9.9
- Mitsuba 3 version: 3.0.1
- Compiled variants:
    * `llvm_ad_rgb`
    * `cuda_ad_rgb`
    * `scalar_rgb`

**Comment by Speierers** [comment]
Hi @Virtual-Optix,

Indeed this is not supported. The orthographic sensor has a delta-dirac directional response, hence it is not possible to connect light path starting on emitters with locations on the camera plane.

Workarounds for this exist (e.g. bidirectional path tracing) but are not implemented in Mitsuba 3.

**Comment by Virtual-Optix** [comment]
Thank you for your quick reply and explanation.
