### ISSUE TITLE
[🐛 bug report] Quickstart Tutorial: Scene loading not working in pip-installed version

### ISSUE THREAD

**Issue by JaldertVicarious** [mitsuba-renderer/mitsuba3#199]
## Summary

In https://mitsuba.readthedocs.io/en/latest/src/quickstart/mitsuba_quickstart.html, the `load_file("../scene/cbox.xml")` command is not working in my `pip install`-ed version.

## System configuration

Installed with: 

`pip install mitsuba`

- Platform: Ubuntu 18.04
- Compiler: ...
- Python version: 3.8
- Mitsuba 3 version: 3.0.1
- Compiled variants: all

## Description

In https://mitsuba.readthedocs.io/en/latest/src/quickstart/mitsuba_quickstart.html, the `load_file("../scene/cbox.xml")` command is not working. 

As far as I can tell, there are no XML files bundled with the pip-installed package.

## Steps to reproduce

```python
import mitsuba as mi
mi.set_variant("scalar_rgb")
scene = mi.load_file("../scenes/cbox.xml")
```

Output:

```
RuntimeError: ​[xml.cpp:1390] "../scenes/cbox.xml": file does not exist!
```

On Github I see that there's a submodule referring to https://github.com/mitsuba-renderer/mitsuba-tutorials, which does have the `scenes` folder with the scenes the tutorials refer to.

Separately cloning the https://github.com/mitsuba-renderer/mitsuba-tutorials repository and referring to the `scenes` folder in that repo works.

**Comment by Speierers** [comment]
Indeed you will need to download the scene files from this tutorial (see download button at the top of the tutorial webpage).

**Comment by JaldertVicarious** [comment]
Perhaps we could update the text to better reflect this? Currently it says under[ "loading a scene"](https://mitsuba.readthedocs.io/en/latest/src/quickstart/mitsuba_quickstart.html#Loading-a-scene):

> Luckily for us, a few example scenes were already provided during the installation with pip install.

**Comment by Speierers** [comment]
I will fix that 👍
