### ISSUE TITLE
Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1

### ISSUE THREAD

**Issue by FROL256** [mitsuba-renderer/mitsuba3#201]
- [🐛 bug report]

## Summary

reproduce the AD tutorial code (https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/gradient_based_opt.html) and got this error at random loop iter

## System configuration

- Platform: Linux Mint 20.3 (Cinnamon), i9-10940X CPU @ 3.30GHz, 46.8 GiB Mem.
- Compiler: suppose none, but i have clang version 10.0.0-4ubuntu1 if this point is about llvm
- Python version: 3.8
- Mitsuba 3 version: Successfully installed drjit-0.2.1 mitsuba-3.0.1
- Compiled variants: 'llvm_ad_rgb'

## Description
```Python
import mitsuba as mi
import drjit as dr

def mse(image, image_ref):
  return dr.mean( dr.sqr(image - image_ref) )

#print(mi.variants())
#mi.set_variant('cuda_ad_rgb')
mi.set_variant('llvm_ad_rgb')

scene = mi.load_file("/home/frol/PROG/Mitsuba3Tests/matpreview_scene/scene_v3.xml", res=128, integrator='prb')
scene_params = mi.traverse(scene)
#print(str(scene_params))

param_key = "bsdf-matpreview.diffuse_reflectance.value"

print("rendering target image")
img_target = mi.render(scene, spp=64)
mi.Bitmap(img_target).write("/home/frol/PROG/Mitsuba3Tests/z_target.exr")

print("rendering origin image")
scene_params[param_key] = mi.Color3f(1,0,0)
scene_params.update()
img_origin = mi.render(scene, spp=64)
mi.Bitmap(img_origin).write("/home/frol/PROG/Mitsuba3Tests/z_origin.exr")

opt = mi.ad.Adam(lr=0.05)
opt[param_key] = scene_params[param_key]
scene_params.update(opt)

for i in range(50):
    print(f"render, step: {i:02d} ... ")
    img  = mi.render(scene, scene_params, spp=4)
    loss = mse(img, img_target)

    print(f"drender, step: {i:02d} ... ")
    dr.backward(loss)
    opt.step()

    opt[param_key] = dr.clamp(opt[param_key], 0.0, 1.0)
    scene_params.update(opt)

    mi.Bitmap(img).write(f"/home/frol/PROG/Mitsuba3Tests/z_render_{i:02d}.exr")
    print(f"opt_step: {i:02d}")

print("finished")
```
## Steps to reproduce

1) reproduce the AD tutorial code (https://mitsuba.readthedocs.io/en/latest/src/inverse_rendering/gradient_based_opt.html)
2) take material ball from here https://benedikt-bitterli.me/resources/
3) full code is located below
4) get "Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1" at random loop iteration

**Comment by FROL256** [comment]
It seems that this line cause a problem:
```
mi.Bitmap(img).write(f"/home/frol/PROG/Mitsuba3Tests/z_render_{i:02d}.exr")
```

**Comment by FROL256** [comment]
if i remove this line but then change resolution of image to 512x512 the bug gets back

**Comment by njroussel** [comment]
Hi @FROL256!

Let me confirm a couple things first: can you consistently reproduce this error?
I've managed to get it once, and since then have been incapable to reproduce it. 
This seems like a threading issue, which would indeed make this a sporadic error. However, we have "never" seen it before, and have been running similar scripts/workloads regularly. So there might be something specific in your setup.

Also, I see that you're passing ` res=128, integrator='prb'` to `load_file`. You have changed the scene description (XML file) to handle this, right?

**Comment by lynshwoo2022** [comment]
> > > You have changed the scene description (XML file) to handle this, right?
> 
> The problem is disappeared after i have changed these values inside XML file, thank you very much!

hello there, I encountered the same problem....so is this the problem of `res` in loading XML file?
