### ISSUE TITLE
Build Error：DLL load failed while importing drjit_ext

### ISSUE THREAD

**Issue by NorvinZhang2022** [mitsuba-renderer/mitsuba3#228]
use “cmake -B./build -H. -G "Visual Studio 16 2019" -A x64”  created projects
then use "cmake --build ./build --config Release"  to build mitsuba3
And got error:
[[=============================
 dlpack.cpp
  Generating Code...
     Creating library H:/DRTookit/mitsuba3/build4/ext/drjit/src/python/Debug/drjit_ext.lib and object H:/DRTookit/mitsuba3/build4/ext/drjit/src/python/Debug/dr
  jit_ext.exp
  drjit-python.vcxproj -> H:\DRTookit\mitsuba3\build4\Debug\python\drjit\drjit_ext.cp39-win_amd64.pyd
  Traceback (most recent call last):
    File "H:\DRTookit\mitsuba3\ext\drjit\resources\generate_stub_files.py", line 317, in <module>
      import drjit as dr
    File "H:\DRTookit/mitsuba3/build4/Debug/python\drjit\__init__.py", line 24, in <module>
      import drjit.drjit_ext as drjit_ext  # noqa
  ImportError: DLL load failed while importing drjit_ext: 鎵句笉鍒版寚瀹氱殑妯″潡銆?
C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targets(241,5): error MSB8066: Custom build for
'H:\DRTookit\mitsuba3\build4\CMakeFiles\01ef742381369a506b0f8633b071b686\drjit_stub_file_generation.rule;H:\DRTookit\mitsuba3\src\python\CMakeLists.txt' exited
 with code 1. [H:\DRTookit\mitsuba3\build4\src\python\drjit_stub_file_generation.vcxproj]
]]===================================

System information:
  OS: Windows 10 pro 21H1
  CPU: Intel(R) Core(TM) i9-10900K CPU
  GPU: Nvidia 3080
  Python version: 3.9.12

  CUDA version: 11.7
  NVidia driver: 516.94

  Mitsuba version: github master
  Compiled with: MSVC 19.29.30140.0

**Comment by NorvinZhang2022** [comment]
I can find "drjit_ext.cp39-win_amd64.pyd" in folder "build\Release\python\drjit"
but still have error"ImportError: DLL load failed while importing drjit_ext", even if I change file name from "drjit_ext.cp39-win_amd64.pyd" to "drjit_ext.pyd".

**Comment by njroussel** [comment]
@NorvinZhang2022 thank you for reporting this!

We've already had a few other reports concerning this. There is something fishy with the build system on Windows. Unfortunately, we haven't been able to replicate it on any of our machines, so we've made little progress to fix this issue so far.

In your build log, it seems like you're building a `Debug` build rather than a `Release` one as you specified in the command. Is this log from another build?
Apparently, re-running the build command (in the same folder) a second time will succeed. Can you confirm this?
Do you mind also providing the full logs of your build, rather than just where the error happens, please?

**Comment by khalomer** [comment]
I had success by including the Mitsuba build path/python path to my system environment prior to building (assuming you're building in Release). 
![image](https://user-images.githubusercontent.com/84816226/188002248-55f5199e-ca4f-4e3c-8686-9880ce029ea5.png)
![image](https://user-images.githubusercontent.com/84816226/188002482-1c4d358e-4053-43b6-8616-47b084a81a9e.png)

**Comment by njroussel** [comment]
@khalomer @NorvinZhang2022 
Were either of you using Conda's (miniconda, or anaconda) `python` executable ?

**Comment by khalomer** [comment]
> @khalomer @NorvinZhang2022
> Were either of you using Conda's (miniconda, or anaconda) `python` executable ?

Yes I was using the Anaconda python command prompt with an active environment while building. Seemed to be the only way for me to have Mitsuba identify my environment while building.

**Comment by NorvinZhang2022** [comment]
> Were either of you using Conda's (miniconda, or anaconda) python executable ?

Yes， I using  Conda's python executable.

**Comment by NorvinZhang2022** [comment]
> In your build log, it seems like you're building a Debug build rather than a Release one as you specified in the command. Is this log from another build?
Release Or Debug get same error,I will try khalomer's solution.

**Comment by njroussel** [comment]
Thanks.

Conda apparently has it's [own DLL search directives](https://docs.conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed), enabling `CONDA_DLL_SEARCH_MODIFICATION_ENABLE` worked for me.
The other solution, as you suggested, is adding the `mitsuba3\build\Release` folder to your `PATH` variables. In fact, that's what we're doing by using `os.add_dll_directory` in our [__init__.py ](https://github.com/mitsuba-renderer/drjit/blob/master/drjit/__init__.py#L7-L16). But apparently it doesn't seem to work with Conda.

If you want to dig deeper: https://github.com/conda/conda/issues/10897

**Comment by NorvinZhang2022** [comment]
@khalomer Thanks, your solution can solve this issue.

**Comment by NorvinZhang2022** [comment]
@njroussel Ihave tried "set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1" before build in conda Prompt terminal.

**Comment by njroussel** [comment]
Great thanks :+1: to both of you @NorvinZhang2022 @khalomer 
I'll close this issue for now. This should at least allow people to build `mitsuba` locally on Windows.

We might consider having something like `os.environ['CONDA_DLL_SEARCH_MODIFICATION_ENABLE']='1'` directly in our `__init__.py` if it makes sense. Right now, I'm not confident enough to say that this actually is the appropriate solution.
