### ISSUE TITLE
Builtin kd-tree sometimes fails due to bisection algorithm

### ISSUE THREAD

**Issue by schunkes** [mitsuba-renderer/mitsuba3#233]
## Summary

The bisection algorithm used in the internal kd-tree implementation fails in certain situations

## System configuration

System information:

  OS: Ubuntu 21.10
  CPU: AMD Ryzen 9 5900X 12-Core Processor
  Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
  CUDA: 11.3.109
  LLVM: 13.0.0

  Dr.Jit: 0.2.1
  Mitsuba: 3.0.1
     Is custom build? True
     Compiled with: Clang 11.0.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

The bisection algorithm used in the internal kd-tree has a hard failure criterion that raises a runtime error if the bisection is not finished after 100 iterations. The rationale behind this, as far as I've understood is that a bisection that halves the set of points with each step should take no more than 64 steps for 64-bit numbers. However due to the non-uniform distribution of floating point numbers on the number line this assumption can fail if the bisection target is close to zero.

Based on this blog entry, I have implemented a fix for this issue, with comparable performance. https://www.shapeoperator.com/2014/02/22/bisecting-floats/

If you wish, I can submit a PR with this fix immediately.

## Steps to reproduce

It is hard for me to provide a MWE, because I only encounter this problem in a procedurally generated scene with several million objects. 

If there are further questions, I can provide more information about this issue.

**Comment by wjakob** [comment]
Hi @schunkes ,

I understand the issue -- modifying the bisection routine sounds reasonable in principle (without having seen the code yet). Could you submit a PR with your changes?

Thanks,
Wenzel
Wenzel

**Comment by schunkes** [comment]
I added a PR with my code. I'm happy to get your feedback and update the code if necessary.

**Comment by Speierers** [comment]
Great thanks! I will take a look at the PR and close this issue for now.
