### ISSUE TITLE
Formatting changes after using clang-format

### ISSUE THREAD

**Issue by DoeringChristian** [mitsuba-renderer/mitsuba3#239]
Dear Mitsuba Team,

I am using clang-format automatically when writing files. In mitsuba when editing cpp files this changes the formatting even though I am using the ".clang-format" file. 
Before formatting in "src/render/mesh.cpp:34"
```cpp
MI_VARIANT
Mesh<Float, Spectrum>::Mesh(const std::string &name, ScalarSize vertex_count,
                            ScalarSize face_count, const Properties &props,
                            bool has_vertex_normals, bool has_vertex_texcoords) : Mesh(props) {
    m_name = name;
    m_vertex_count = vertex_count;
    m_face_count = face_count;

    m_faces = dr::zeros<DynamicBuffer<UInt32>>(m_face_count * 3);
    m_vertex_positions = dr::zeros<FloatStorage>(m_vertex_count * 3);

    if (has_vertex_normals)
        m_vertex_normals = dr::zeros<FloatStorage>(m_vertex_count * 3);
    if (has_vertex_texcoords)
        m_vertex_texcoords = dr::zeros<FloatStorage>(m_vertex_count * 2);

    initialize();
}
```
After formatting:
```cpp
MI_VARIANT
Mesh<Float, Spectrum>::Mesh(const std::string &name, ScalarSize vertex_count,
                            ScalarSize face_count, const Properties &props,
                            bool has_vertex_normals, bool has_vertex_texcoords)
    : Mesh(props) {
    m_name         = name;
    m_vertex_count = vertex_count;
    m_face_count   = face_count;

    m_faces            = dr::zeros<DynamicBuffer<UInt32>>(m_face_count * 3);
    m_vertex_positions = dr::zeros<FloatStorage>(m_vertex_count * 3);

    if (has_vertex_normals)
        m_vertex_normals = dr::zeros<FloatStorage>(m_vertex_count * 3);
    if (has_vertex_texcoords)
        m_vertex_texcoords = dr::zeros<FloatStorage>(m_vertex_count * 2);

    initialize();
}
```
In some files clang-format also changes the order of includes which seems to cause an error when compiling.
Do I need to set some options when using clang-format on mitsuba files?

Thanks for your help,
Christian Döring

**Comment by wjakob** [comment]
Hi Christian,

we don't recommend running clang-format on entire Mitsuba source code files. It does a good job in many cases but produces pretty ugly formatting in others. That's why we don't currently have a policy to auto-format everything. The clang-format file is merely provided as a reference so that you can run it on portions of newly contributed code to get something that overall looks pretty similar to most of the codebase.

Cheers,
Wenzel
