### ISSUE TITLE
loading scene with subsurface

### ISSUE THREAD

**Issue by Lezcool** [mitsuba-renderer/mitsuba3#244]
## Summary

Can not load scene with subsurface

## Description

I tried to load [cbox_sss.zip](https://www.mitsuba-renderer.org/scenes/cbox_sss.zip), but couldn't, error message `unexpected tag "subsurface".`
I checked the document saying that Diffusion-based subsurface scattering: currently missing, status undecided. But is it possible that load the scene and write my own BSSRDF function using Mitsuba3?
I try to do that because I am more familiar with python than C++, otherwise I think I have to try other renders.

**Comment by Speierers** [comment]
Indeed the `subsurface` plugins where not ported to Mitsuba 3. Instead you should the volumetric path tracer with a [homogeneous / heterogeneous participating medium](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_media.html#homogeneous-medium-homogeneous) to representt the subsurface scattering.
