### ISSUE TITLE
about the parameter to_world of camera or projector emmits

### ISSUE THREAD

**Issue by ljijjiang1234** [mitsuba-renderer/mitsuba3#248]
Hi, There is a confused question I would like to ask. I check the camera and projetor plugin, I fount the to_world params can not be differential , So would you like to give me some advice about how can I optimize the camera pose or projector pose in mitsuba
Here I find other people do projector pose estimation using params "Projector.position" and "Projector.rotation"  But I cant find these params in my program. Thanks.

the code some researcher does:
params = traverse(scene)
params.keep(["Projector.position", "Projector.rotation"])

**Comment by Speierers** [comment]
Hi @ljijjiang1234 

Currently the differentiable integrator do not properly handle discontinuities (e.g. using reparameterization) at the sensor level. For this reason we decided to keep the `to_world` parameter non-differentiable for now to avoid users working with incorrect gradients.

I should be able to take the time to look into this in the next couple weeks. I will keep you posted once this is fixed.

**Comment by ljijjiang1234** [comment]
Thank you very much about your work , And I  Will Try to use the your base work to compile and redefine the emitter source code in order to make it differentiate like someone else already done.

**Comment by njroussel** [comment]
The last few commits on `master` (ef9f559e0989fd01b43acce90892ba9e0dea255b .. ea513f73b65b8776afb75fdc8d40db4b1140345e) have made sensors parameters differentiable.

Note: Emitters still don't have a differentiable `to_world` parameter I believe.

**Comment by VijayVikasM** [comment]
Hi could someone guide me how exactly I can make my to_world params differentiable in case of an orthographic sensor?

**Comment by njroussel** [comment]
Mitsuba 3 cannot differentiate a orthographic sensor correctly.

Let me close this issue. The original question has been answered.
