### ISSUE TITLE
How to save the state of Adam optimizer from Mitsuba

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/mitsuba3#250]
## Summary

Hello, could you please help me to save the state of the Adam optimizer if that is possible? I need this to be able to continue optimization after restarting an optimization program. 

## Description

I tried to pickle it: `pickle.dumps(opt)` but I got 
`AttributeError: Can't pickle local object 'Adam.__init__.<locals>.<lambda>'`

I also have problems with manual saving attributes of Optimizer (opt) since I don't know how to manually update `opt.items()` (it has the type <class 'mitsuba.ad.optimizers.Optimizer.items.<locals>.OptimizerItemIterator'>)

## Steps to reproduce

import mitsuba as mi
import drjit as dr
import dill
import pickle

mi.set_variant('cuda_ad_rgb')

opt = mi.ad.Adam(lr=100.)
opt['x'] = mi.Float(2.)
opt['y'] = mi.Float(3.)
z = opt['y'] * 2 + opt['x']
dr.backward(z)
opt.step()
print(list(opt.items()), type(opt.items()))
pickle.dumps(opt)

**Comment by Speierers** [comment]
Hi @TZZZZ,

Mitsuba optimizers are similar to Python dictionaries. So you should be able to iterate over the optimizer variables like this
```python
for k, v in opt.items():
   save_variable_to_disk(k, v)
```

And later re-insert those variables in a new optimizer:
```python
opt = mi.ad.Adam()
vars = load_variables_from_disk()
for k, v in vars:
    opt[k] = v
```

I hope this is helpful.

**Comment by TZZZZ** [comment]
Thank you, this solves the problem of saving opt.items(). Am I right that the simplest solution is to save and upload in the same way other attributes of Adam optimizer (opt.state, opt.t) because they also influence optimization process?

**Comment by Speierers** [comment]
Yes, ideally you could save those too.

Glad this helped!
