### ISSUE TITLE
Some links from documentation are broken

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/mitsuba3#252]
## Summary

Hello, this is not a critical issue for sure, but maybe it would be helpful. Some links from docs have old names and don't work.
I attach the list obtained by a free utility that checks websites. 

[mitsuba_broken_links.pdf](https://github.com/mitsuba-renderer/mitsuba3/files/9568132/mitsuba_broken_links.pdf)

**Comment by njroussel** [comment]
Hi @TZZZZ 
Thanks for pointing these out, we will fix them.
Out of curiosity, what's the tool you used? We might want to run this every so often :)

**Comment by njroussel** [comment]
I've fixed the listed links and some more that I found in this commit: [cf69f4d](https://github.com/mitsuba-renderer/mitsuba3/commit/cf69f4d9959cbe6f7e6e960de603cdad17142b5e)

**Comment by TZZZZ** [comment]
Thank you, I used the website https://www.deadlinkchecker.com/website-dead-link-checker.asp. Maybe it is not the best one because it cannot check only subsections of sites. It also found some problems with links in Github repos and drjit, so it might be interesting for you as well.
