### ISSUE TITLE
[PluginManager] Plugin "ldrfilm" not found!

### ISSUE THREAD

**Issue by albertotono** [mitsuba-renderer/mitsuba3#253]
## Summary

While testing this repo https://github.com/zekunhao1995/PointFlowRenderer 
 
I got this error 

```
Caught a critical exception: [xml.cpp:1108] Error while loading "mitsuba_scene.xml" (near line 17, col 10): could not instantiate film plugin of type "ldrfilm": 
[xml.cpp:1108]   [PluginManager] Plugin "ldrfilm" not found!
```

## System configuration

Linux Ubuntu 20
Python 3.8 
Anaconda
RTX 2080, CUDA 11.1

In attachment my .xml [mitsuba_scene.zip](https://github.com/mitsuba-renderer/mitsuba3/files/9571923/mitsuba_scene.zip)

**Comment by Speierers** [comment]
This plugin wasn't ported to Mitsuba 3. You will need to use the `hdrfilm` plugin instead.

**Comment by njroussel** [comment]
Hi @albertotono 

I believe that in the project you mentioned they are using [Mitsuba 0.6](http://mitsuba-renderer.org/index_old.html).
Mitsuba 3 can maybe handle what they are doing, but it would require some changes in the scene description.
