### ISSUE TITLE
llvm_ad_rgb mode crashing with custom integrator plugin

### ISSUE THREAD

**Issue by arpit15** [mitsuba-renderer/mitsuba3#256]
## Summary
[Custom Path integrator python plugin](https://gist.github.com/arpit15/388da5ff3b38069641cdc21ce2cdf240) works fine with `cuda_ad_rgb` variant but crashes in `llvm_ad_rgb` variant. 

## System configuration
```System information:

  OS: Ubuntu 22.04.1 LTS
  CPU: Intel(R) Xeon(R) E-2124G CPU @ 3.40GHz
  GPU: NVIDIA GeForce RTX 2060
  Python: 3.10.7 (main, Sep  9 2022, 17:16:31) [GCC 11.2.0]
  NVidia driver: 515.65.01
  CUDA: 11.7.99
  LLVM: 16.0.0

  Dr.Jit: 0.2.1
  Mitsuba: 3.0.1
     Is custom build? True
     Compiled with: Clang 14.0.6
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
        cuda_ad_spectral
        llvm_ad_spectral
```
## Description
I tried to write Path integrator in python to learn about drjit and mitsuba3. I am able to obtain an image when I run the code with `cuda_ad_rgb` variant. 
![global_illum](https://user-images.githubusercontent.com/4703676/190664525-6ec4e02d-9e75-4671-b421-32fe4a74c1f3.png)
However, when I run the plugin with `llvm_ad_rgb`, it crashes with a [huge crash dump](https://gist.github.com/arpit15/117ba1b0a1ba350d9d417928c67095ab). 

## Steps to reproduce
1. Download the [plugin file](https://gist.github.com/arpit15/388da5ff3b38069641cdc21ce2cdf240)
2. Modify the `cbox.xml` file location
3. `python path_integrator_refined.py`
4. Change the variant to `llvm_ad_rgb`
5. Rerun the plugin  `python path_integrator_refined.py`

**Comment by wjakob** [comment]
Can you try updating to Mitsuba 3.0.2?

**Comment by wjakob** [comment]
(this is likely a bug that we fixed in an updated Dr.Jit release referenced by this Mitsuba version).

**Comment by arpit15** [comment]
Thanks! works in Mitsuba 3.0.2 version
