### ISSUE TITLE
Weird patterns in brushed roughconductor

### ISSUE THREAD

**Issue by mich-sanna** [mitsuba-renderer/mitsuba3#261]
## Summary

Some weird patterns (perlin noise-like) appear on the surface of a model with lots of co-planar triangles. The material is rough conductor, and the patterns appear when alpha_u and alpha_v are different (e.g. brushed aluminium), whereas they don't appear when the alphas are the same.

![image](https://user-images.githubusercontent.com/54891577/191001116-4d509363-7967-4e86-924c-8a49b7544ddb.png)

## System configuration

System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
  GPU: Quadro P2000 with Max-Q Design
  Python: 3.8.13 | packaged by conda-forge | (default, Mar 25 2022, 05:59:00) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 516.94
  LLVM: 0.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: MSVC 19.33.31629.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Summary above tells most of the story. Scene xml + asset are attached.

Admittedly the mesh is one that has been poorly reconstructed from a cad file (lots of triangles for a flat surface). However the triangles are perfectly coplanar so I wouldn't expect this patter to appear?

<img src=https://user-images.githubusercontent.com/54891577/191001306-119b6fa2-c821-4857-92a0-af0aedd08203.png width="640"/>

Also, it doesn't seem to depend from the sampler, the number of samples, choice of filter, resolution, or backend.

## Steps to reproduce
[noisy_pattern.zip](https://github.com/mitsuba-renderer/mitsuba3/files/9598192/noisy_pattern.zip)

**Comment by Speierers** [comment]
Could it be that the UVs are not provided with the mesh? In which case Mitsuba will you the barycentric coordinate within the triangles as UV coordinate which is probably not what you want here, and could lead to such artifacts.

**Comment by mich-sanna** [comment]
oh wow, bull's eye 😮 
I replaced the file with one that has UVs and it shows no artifacts!

Why is that happening even though i don't use any textures/images? 
does it have to do with the orientation of alpha_u and alpha_v? (in which case I guess it *needs* to calculate some directions for u and v) 

Thanks for the hint and explanation!

**Comment by Speierers** [comment]
Yes indeed, `alpha_u` and `alpha_v` are interpreted along the UV axis of the mesh. In your case it was completely messed up hence the weird pattern artifact. Glad this worked for you :)
