### ISSUE TITLE
How to change the gradients during optimization

### ISSUE THREAD

**Issue by TZZZZ** [mitsuba-renderer/mitsuba3#275]
## Summary

Hello, could you please help me to find the easiest way to manually change the gradients during optimization? 

## Description

I have some gradients from pytorch losses and want to add them to the gradients in mitsuba. As I get it, dr.grad(opt[key]) uses info from opt[key].grad_(), and I am not sure how to change it.

**Comment by Speierers** [comment]
You should be able to use `dr.set_grad(..)` for this. For instance, to add the gradient from PyTorch you could do the following:
```python
dr.set_grad(opt[key], dr.grad(opt[key]) + pytorch_grad)
```

**Comment by TZZZZ** [comment]
Thank you!
