### ISSUE TITLE
[🐛 bug report] Irregular distribution returns a wrong max()

### ISSUE THREAD

**Issue by tomasiser** [mitsuba-renderer/mitsuba3#278]
Hi there, the irregular continuous distribution seems to have a wrong concept of maximum.

Configuration:
```python
import mitsuba as mi
mi.set_variant('llvm_ad_spectral')
```
using the latest commit 1eaa8be.

Here is how a texture with a regular distribution behaves:
```python
mi.load_dict({
    "type": "spectrum",
    "value": [(400, 1), (500, 2), (600, 1)]
}).max()
```
returns `2.0`, which is correct.

A slight change of `500` to `501` makes it an irregular distribution:
```python
mi.load_dict({
    "type": "spectrum",
    "value": [(400, 1), (501, 2), (600, 1)]
}).max()
```
which returns `400.0`, which is obviously incorrect.

**Comment by tomasiser** [comment]
https://github.com/mitsuba-renderer/mitsuba3/blob/master/include/mitsuba/core/distr_1d.h#L807
Confirmed that changing `nodes[0]` to `pdf[0]` fixes the problem :)

**Comment by Speierers** [comment]
That's fixed now, thanks!
