### ISSUE TITLE
Empty/black pixels when rendering a simple shape with spp=1

### ISSUE THREAD

**Issue by trancelestial** [mitsuba-renderer/mitsuba3#287]
Hi, thank you for the amazing work you have done with the mitsuba renderer. I have a question regarding a simplified case where I observed an unexpected result: 

When rendering (aov + direct integrator) a simple rectangle shape (both 'type': 'rectangle', and a ply rectangle composed of only two triangles) with diffuse bsdf, using a single sample per pixel (spp=1), box filter, and a single point light I observe black/empty pixels both on the boundary and inside of the rendered shape (and its depth...). You can see the zoomed-in image below:

![image](https://user-images.githubusercontent.com/22893239/192789390-76cfe31c-4de9-4ce4-8063-6985ec958c9b.png)

Is this behavior expected? From my understanding for each pixel, a ray should be cast and intersected with the object. This intersection should be valid for the (black) pixels inside of the object. Since there is only a single sample per pixel, the box filter should basically output a single sample of the incoming radience for each pixel's ray, which for the rays that intersect with the shape's surface should be non-zero. I just started working with mitsuba, and might be getting the inner machinery of it wrong, so I would be grateful for any clarification/help you can provide to resolve this issue. Let me know if I can provide more information on my setting.

## System configuration

System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: Intel(R) Core(TM) i9-10850K CPU @ 3.60GHz
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
  NVidia driver: 510.47.03
  CUDA: 11.5.119
  LLVM: 12.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

**Comment by Speierers** [comment]
Hi @trancelestial ,

Could you share the scene file so we can give this a try on our side?

**Comment by trancelestial** [comment]
Hi @Speierers, I couldnt find an easy way to export the scene object to XML format, but here is a python dictionary of the scene https://pastebin.com/y1cwfnXH, I hope this works.

**Comment by Speierers** [comment]
Thanks, I am looking into that issue.

**Comment by trancelestial** [comment]
Hi @Speierers,

I saw your pull request is merged so I just compiled it and I'm happy to say that there are no black pixels inside the object anymore. Thank you for solving this! 

The ragged boundary of the object is still visible, and I assume that this is not caused by the mentioned instability but due to the rays having a random offset/perturbation from the center of the pixel. If this is the case, could you tell me if it is possible to disable this feature e.g. to cast the ray always through the pixel's center?

**Comment by Speierers** [comment]
For this you will need to write a custom rendering pipeline that generates the rays and call the sample method of the integrator in python. This way you'll have full control over the ray generation and can decide to not apply a random offset.
