### ISSUE TITLE
Unable to include a scene file from a python dictionary

### ISSUE THREAD

**Issue by vinhig** [mitsuba-renderer/mitsuba3#296]
Hi, is there a way to include a .xml file into a python dictionary scene? This may be useful when including scenes/parts of a scene that have been generated from a third party software (blender eg). As far as I know, the current state of the documentation and the source code doesn't provide such a feature, I may be wrong (and I hope to be wrong).

The need resides in something like:

```python
# ...
"my_file": {
    "type": "include",
    "filename": "./some_scene.xml"
}
# ...
```

If the desired feature is already present, please update the documentation to reflect it.

Have a nice day!

**Comment by njroussel** [comment]
Hi @vinhig 

The function `load_dict` can take a dictionnary where the values are already instantiated mitsuba objects. So you can load any partial scene description using `load_file`, and then use that value in your `dict` object. Like so:

```
partial_scene = mi.load_file('partial_scene.xml')

mi.load_dict({
    'type': 'scene',
    'some_shape': {
        'type': 'disk'
    },
    'rest_of_scene': partial_scene
})
```

**Comment by vinhig** [comment]
That's some good news! Thx for answering.
