### ISSUE TITLE
[🐛 bug report] Unable to import mitsuba in Blender

### ISSUE THREAD

**Issue by UNakade** [mitsuba-renderer/mitsuba3#298]
## Summary

Unable to import mitsuba in Blender 3.3.0 (errors like `double free or corruption (out)`, `free(): invalid pointer`)

## System configuration

System information:

  OS: Ubuntu 22.04.1 LTS
  CPU: 11th Gen Intel(R) Core(TM) i9-11900K @ 3.50GHz
  GPU: NVIDIA RTX A4000
  Python: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  NVidia driver: 515.43.04
  CUDA: 11.7.64
  LLVM: 14.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? True
     Compiled with: Clang 14.0.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_spectral
        llvm_ad_spectral

## Description

After sourcing `setpath.sh`, I could `import mitsuba` in a Blender script (run using `blender -b -P script.py`). Today I updated Mitsuba (old commit hash: 5da5f76719c573562f9911f8963c3d8d18e8c176, new commit hash: 39ff40498eeb73ab9466822db103bffc52a1f8f0) and I can't import it anymore. I'm getting errors like `double free or corruption (out)`, `free(): invalid pointer`. Blender version is 3.3.0

## Steps to reproduce

1. Compile Mitsuba
2. `source setpath.sh`
3. create file `script.py` with `import mitsuba`
4. run `blender -b -P script.py`

I'm not sure where Blender/Mitsuba store their error logs. I did not find `/tmp/blender.crash.log`. If there is any other information you need, please let me know.

**Comment by njroussel** [comment]
Hi @UNakade 

Unfortunate timing, we have [pushed a fix](https://github.com/mitsuba-renderer/mitsuba3/commit/d456826ef9a3a2309dabd6d821b94e8daa620ba2) for this and it should be direclty available in the next releases of mitsuba and the blender plugin. In the meantime, you should be able to just set the environment variable `DRJIT_NO_RTLD_DEEPBIND` manually to fix this issue.
I'll keep this issue open until you confirm that this works.

**Comment by UNakade** [comment]
I'll not be able to test this before Wednesday, will inform you here. Just to clarify, I should set the environment variable `DRJIT_NO_RTLD_DEEPBIND` to `true` for it to work?

If I cloned the repository today and the fix is from 3 days ago, shouldn't it already be working on my machine? I'll try your suggested solution regardless. 

Thank you for your response

**Comment by njroussel** [comment]
You can set it to whatever, the code just checks that it exists.

Not exactly, your cloned repository will know to check for that envvar, but it still needs to be set. Eventually, the blender plugin will take care of setting the envvar for you but that hasn't been done yet I believe.

**Comment by UNakade** [comment]
I tried it again after setting that environment variable, but it did not work. Here's the error message:

```
Blender 3.3.0 (hash 0759f671ce1f built 2022-09-07 00:16:43)
Error: Python: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/snap/blender/2790/3.3/scripts/modules/addon_utils.py", line 478, in disable_all
    addon_modules = [
  File "/snap/blender/2790/3.3/scripts/modules/addon_utils.py", line 478, in <listcomp>
    addon_modules = [
RuntimeError: dictionary changed size during iteration
```

**Comment by UNakade** [comment]
Ok, now that you are pointing me towards the `mitsuba-blender` repository, I realize the confusion. I was not talking about the `mitsuba-blender` add-on for Blender. I was talking about the `mitsuba` module being imported in a python script that happens to be running via Blender. This used to be possible before, but not anymore. 

I used to run a script in Blender that used to export the scene according to my requirements (unlike the `mitsuba-blender` add-on which has never worked properly for me) and also render it using `mitsuba`. I guess I can just export it first and render it separately with `mitsuba` now.

**Comment by njroussel** [comment]
Ohhhhh I see, I misunderstood. 

Then your previous error message doesn't make much sense to me. This clearly seems like a Blender addon issue to me.

> I tried it again after setting that environment variable, but it did not work. Here's the error message:
> 
> ```
> Blender 3.3.0 (hash 0759f671ce1f built 2022-09-07 00:16:43)
> Error: Python: Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/snap/blender/2790/3.3/scripts/modules/addon_utils.py", line 478, in disable_all
>     addon_modules = [
>   File "/snap/blender/2790/3.3/scripts/modules/addon_utils.py", line 478, in <listcomp>
>     addon_modules = [
> RuntimeError: dictionary changed size during iteration
> ```

Either way this envvar is the key to the puzzle. If you're using a custom build of Mitsuba on Linux with Clang, this `DRJIT_NO_RTLD_DEEPBIND` has to be set for Mitsuba to play nicely within Blender.
