### ISSUE TITLE
Texture of Area Light

### ISSUE THREAD

**Issue by njroussel** [mitsuba-renderer/mitsuba3#322]
### Discussed in https://github.com/mitsuba-renderer/mitsuba3/discussions/321

<div type='discussions-op-text'>

<sup>Originally posted by **stefanjp** October 11, 2022</sup>
According to the documentation, the area light of mitsuba 3 the radiance parameter supports spectrum and no texture. In mitsuba 2 I could optimize the texture of the area light. Looking in the source code of the mitsuba 3 area light I could not comprehend why it is not possible to pass a texture as parameter. Internally the [reflectance parameter](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/emitters/area.cpp#L248) has texture type and the `EmitterFlag::SpatiallyVarying` is considered in the [source code](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/emitters/area.cpp#L168) of the area light.

When trying to use the bitmap plugin together with the radiance parameter, the rendering call crashes on my system with "**Critical Dr.Jit compiler failure: jit_var(r0): unknown variable!**". As I would like to use mitsuba 3 to optimize the texture of an area light (together with the position of a spherical mirror), I was wondering why this happens and if there is a simple solution to this problem. If the issue is not known, I am happy to provide a complete example (containing the meshes) and create an issue.

My code looks as follows:
```python
import drjit as dr
import mitsuba as mi
mi.set_variant('cuda_ad_rgb') #mi.set_variant('llvm_ad_rgb')

from mitsuba.scalar_rgb import Transform4f as T

emitter_size = .6
emitter_z_transform = 1
emitter_to_world = T.scale([emitter_size,emitter_size,1]) @ T.look_at(origin=[0, 0, emitter_z_transform],
                                target=[0, 0, 0],
                                up=[0, 1, 0])

sensor_z_transform = .2
optimization_iterations = 10
# spatially varying illumination texture
emitterarray = dr.ones(mi.TensorXf, (256, 128, 3)) * 10
scene = mi.load_dict({
    'type': 'scene',
    'integrator': {
        'type': 'direct_reparam',
    },
    'sensor':  {
        'type': 'perspective',
        'to_world': T.look_at(origin=[0, 0, sensor_z_transform],
                                target=[0, 0, 0],
                                up=[0, 1, 0]),
        'fov': 60,
        'film': {
            'type': 'hdrfilm',
            'width': 64,
            'height': 64,
            'rfilter': { 'type': 'gaussian' },
            'sample_border': True
        },
    },
    'wall': {
        'type': 'rectangle',
        'to_world': T.translate([0, 0, -1]).scale(.6),
        'bsdf': {
            'type': 'diffuse',
            'reflectance': { 'type': 'rgb', 'value': (1, 0.1, 0.1) },
        }
    },
    'calibration_sphere': {
        'type': 'ply',
        'filename': 'sphere.ply',
        'to_world': T.scale(1),
        'bsdf': {
            'type': 'conductor',
            'material': 'Cr'
        },
    },
    'light': {
        'type' : 'ply',
        'to_world': T.scale([emitter_size,emitter_size,1]) @ T.look_at(origin=[0, 0, emitter_z_transform],
                                target=[0, 0, 0],
                                up=[0, 1, 0]),
        'filename': 'emitter.ply',
        'emitter': {
            'type': 'area',
            'radiance': {
                'type': 'bitmap',
                'raw': True,
                'bitmap': mi.Bitmap(emitterarray),
                'filter_type': 'bilinear'
            }
        }
    }
})
img_ref = mi.render(scene, seed=0, spp=20)
```</div>

**Comment by njroussel** [comment]
Hi @stefanjp

Here's a tiny example where we render a scene with the an area light that uses a Texture:
```
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')

# Texture for area light
bmp = mi.Bitmap(mi.render(mi.load_dict(mi.cornell_box())))

scene_description = mi.cornell_box()
scene_description['light']['emitter']['radiance'] = {
    'type': 'bitmap',
    'bitmap': mi.Bitmap(mi.TensorXf(bmp) * 10)
}

scene = mi.load_dict(scene_description)
out = mi.Bitmap(mi.render(scene))
```

There are two points regarding your initial discussion:
1. Unfortunately, the documentation is currently wrong. I will fix that asap.
2. I don't see anything _obviously_ wrong in your snippet. Do you mind making a smaller reproducer ? Ideally using the assets of `mi.cornell_box` or provide them as you suggested.

**Comment by stefanjp** [comment]
Hi @njroussel and thank you so much to help me track down the issue by providing a working example!

My System:

>   OS: Windows 11 Pro
>   CPU: Intel(R) Core(TM) i5-8600K CPU @ 3.60GHz   3.60 GHz
>   GPU: RTX 2080
>   Python version: 3.9.7
>   LLVM version: 14.0.6
>   CUDA version: 11.7
>   NVidia driver:  516.94
> 
>   Dr.Jit version: e73234e773e1fd3f9103c261f5132eda217cee55
>   Mitsuba version: latest (47980c855d508febb4b02271d560e56b8f36ee77)
>      Compiled with: Microsoft (R) C/C++ Optimizing Compiler Version 19.29.30140 for x64
>      Variants compiled: "scalar_rgb", "scalar_spectral", "cuda_ad_rgb", "llvm_ad_rgb"

It seems using a _ply_ mesh and using a _texture_ together causes the crash. I have tried it with both a cube and a rectangle as a mesh for the emitter and it crashes either way. Also with both _cuda_ad_rgb_ and _llvm_ad_rgb_ variants. Using _rgb_ radiance with with a _ply_ mesh as shape works fine, also using _texture_ radiance with a _rectangle_ as shape works.

In my example the first two render calls work fine and the last one crashes. The used mesh is attached [emitter_rectangle.zip](https://github.com/mitsuba-renderer/mitsuba3/files/9772474/emitter_rectangle.zip).


```python
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')
import drjit as dr
from mitsuba.scalar_rgb import Transform4f as T
# Texture for area light
bmp = dr.ones(mi.TensorXf, (256, 128, 3)) * 10

scene_description = mi.cornell_box()
cornell_light_to_world = scene_description['light']['to_world']

scene_description['light'] = {
        'type' : 'ply',
        'to_world': cornell_light_to_world,
        'filename': 'emitter_rectangle.ply',
        'emitter': {
            'type': 'area',
            'radiance': {
                'type': 'rgb',
                'value': [10,10,10]
            }
        }
    }
scene = mi.load_dict(scene_description)
# renders fine
out1 = mi.Bitmap(mi.render(scene))

scene_description['light'] = {
        'type' : 'rectangle',
        'to_world': cornell_light_to_world,
        'emitter': {
            'type': 'area',
            'radiance': {
                'type': 'bitmap',
                'bitmap': mi.Bitmap(bmp)
            }
        }
    }
scene = mi.load_dict(scene_description)
# renders fine
out2 = mi.Bitmap(mi.render(scene))

scene_description['light'] = {
        'type' : 'ply',
        'to_world': cornell_light_to_world,
        'filename': 'emitter_rectangle.ply',
        'emitter': {
            'type': 'area',
            'radiance': {
                'type': 'bitmap',
                'bitmap': mi.Bitmap(bmp)
            }
        }
    }
scene = mi.load_dict(scene_description)
# crashes here
out3 = mi.Bitmap(mi.render(scene))
```

**Comment by njroussel** [comment]
Sorry for the long delay, this was a pain to track down.
It was finally fixed here:
https://github.com/mitsuba-renderer/drjit-core/pull/21

It's made it's way to `master` on Mitsuba and will be available in the next PyPI release (next few days).

**Comment by stefanjp** [comment]
Thank you for looking into this and providing a fix! Hope it was worth the effort! And congrats for the amazing work.
