### ISSUE TITLE
Rendering produces black/empty images

### ISSUE THREAD

**Issue by jonny-sexton** [mitsuba-renderer/mitsuba3#327]
## Summary

Rendering produces black/empty images. Rendering seems to be working, as per the terminal output, however the saved image (cbox.exr) is around 3kb and completely black.

## System configuration

Macbook Pro M1 14
Mac OS Monterey 12.6
Python 3.10

Output of `python -m mitsuba.sys_info`:
```
System information:

  OS: 12.6
  CPU: b'Apple M1 Pro'
  Python: 3.10.8 (main, Oct 13 2022, 10:17:43) [Clang 14.0.0 (clang-1400.0.29.102)]
  LLVM: 15.0.2

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? True
     Compiled with: AppleClang 14.0.0.14000029
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_rgb
```

I built mitsuba from source (as the pip installation did not work), and then linked to the repo in my python script with:

```
import sys
sys.path.insert(0, '/Users/Jonny/Desktop/Programming/master-thesis/repos/mitsuba3/build/python/')
import mitsuba as mi
```

## Description

I followed the steps laid out in the quickstart guide to render an image from one of the example scenes, however a black image is rendered. No error messages are printed to the terminal. This is my script:
```
# Import the library using the alias "mi"
import sys
sys.path.insert(0, '/Users/Jonny/Desktop/Programming/master-thesis/repos/mitsuba3/build/python/')
import mitsuba as mi
import matplotlib.pyplot as plt

# Set the variant of the renderer --> ['scalar_rgb', 'scalar_spectral', 'llvm_ad_rgb']
mi.set_variant('scalar_rgb')
# Load a scene
scene = mi.load_file("/Users/Jonny/Desktop/Programming/master-thesis/datasets/google-gazebosim/scenes/cbox.xml")
# Render the scene
image = mi.render(scene)
# Write the rendered image to an EXR file
mi.Bitmap(image).write('cbox.exr')
```

And this is the image it produces (converted to png):

![cbox (1)](https://user-images.githubusercontent.com/28055759/195894176-ab6bfe9a-004b-4c3a-aeb2-d62cd5ea12d3.png)

## Steps to reproduce

1. Build mitsuba from source --> https://mitsuba.readthedocs.io/en/latest/src/developer_guide/compiling.html#macos
2. Run the script mentioned in the Description section.

**Comment by jonny-sexton** [comment]
One side note that might be relevant, I am using Mac OS Monterey (12.6), which is not listed in the requirements. When I tried to install mitsuba via pip, whenever I imported the library Python would just crash which is why I had to build it from source.

**Comment by wjakob** [comment]
Could you send us send us a backtrace of the crash you get via the regular PyPI binaries? (e.g. via LLDB)

**Comment by jonny-sexton** [comment]
Here is the output to the terminal when I try to import mitsuba:
```
python test.py       
[1]    26978 illegal hardware instruction  python test.py
```

**Comment by jonny-sexton** [comment]
`test.py` is just a file containing an import statement like so:
```
import mitsuba as mi
```

**Comment by jonny-sexton** [comment]
It looks like there was a similar issue for TensorFlow, and relates to the [M1 chip specifically](https://stackoverflow.com/questions/65383338/zsh-illegal-hardware-instruction-python-when-installing-tensorflow-on-macbook). As a temporary workaround I will just use my Linux notebook instead, but if you would like my help in debugging further then just let me know 👍

**Comment by wjakob** [comment]
Aha! I think I know what is happening. You are running an x86 shell, with x86 python, and installed the x86 PyPI packages of Mitsuba. They use AVX2 instructions, and those aren't supported by Apple's x86 emulation layer ("Rosetta 2").

Instead, what you should do is to run an arm64 shell, install arm64 python (e.g. via Homebrew), and then install the arm64 Mitsuba packages. I'll close this issue.

**Comment by wjakob** [comment]
This may also help: https://superuser.com/questions/1668554/arm64-mac-how-to-keep-two-shell-environments-with-and-without-rosetta-organiz

**Comment by jonny-sexton** [comment]
Brilliant, that's fixed the problem! Thank you so much for your help :-)

My issue was Homebrew. I originally installed it on my old intel Mac, so when I migrated the data to my new M1 Mac it transferred the intel version of Homebrew too.

To fix this, I [uninstalled Homebrew](https://stackoverflow.com/questions/66242037/how-to-uninstall-homebrew-of-rosetta-and-install-homebrew-native-on-mac-bigsu-m), and re installed it again using this guide: https://earthly.dev/blog/homebrew-on-m1/

Et voilà:

![cbox (2)](https://user-images.githubusercontent.com/28055759/197010005-7e1415e3-e4fa-44eb-becb-e9d107c2b4c3.png)
