### ISSUE TITLE
prb_reparam does not change maxdepth via XML 

### ISSUE THREAD

**Issue by mfischer-ucl** [mitsuba-renderer/mitsuba3#334]
I think I encountered a bug in load_file: when specifying different `reparam_max_depth` values for the `prb_reparam` integrator, they are not loaded correctly into the resulting scene. 

See the MWE to reproduce: 

```python
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')

scene_prb4 = mi.load_file('test4.xml')
scene_prb23 = mi.load_file('test23.xml')

print(scene_prb4)
print(scene_prb23)

```

In the output of the `print` statement, both scenes have a `PRBReparamIntegrator[max_depth = 6, rr_depth = 5]`, i.e., the `reparam_max_depth` attribute in the xml is ignored. This is the definition of `test4.xml`: 

```xml
<scene version="3.0.0">

	<default name="spp" value="4096"/>
	<default name="resx" value="512"/>
	<default name="resy" value="512"/>

	<integrator type="prb_reparam">
		<integer name="reparam_max_depth" value="4"/>
	</integrator>
	<sensor type="perspective">
    <float name="fov" value="45"/>
    <transform name="to_world">
        <lookat origin="1, 1, 1" target="1, 2, 1" up="0, 0, 1"/>
    </transform>
    </sensor>

    <shape type="sphere">
    <transform name="to_world">
        <scale value="2"/>
        <translate x="1" y="0" z="0"/>
    </transform>
    <bsdf type="diffuse"/>
    </shape>

</scene>
```

The file `test23.xml` is exactly the same, but the `reparam_max_depth` value is set to 23. 

My output of mitsuba.sys_info: 

System information:
```

  OS: Ubuntu 20.04.4 LTS
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.7 (default, Sep 16 2021, 13:09:58) [GCC 7.5.0]
  NVidia driver: 510.85.02
  CUDA: 10.1.243
  LLVM: 12.0.0

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? True
     Compiled with: Clang 9.0.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

```

**Comment by Speierers** [comment]
Hi @mfischer-ucl ,

I just noticed that in the documentation of the `prb_reparam` integrator, two properties are missing: `max_depth` and `rr_depth`. Those are different than the `reparam_max_depth` property which only affects the auxiliary rays traced to compute the reparameterizations. I will fix the documentation.
