### ISSUE TITLE
difference between python and c++ implementation of bsdf

### ISSUE THREAD

**Issue by rajeshsharma-ai** [mitsuba-renderer/mitsuba3#351]
## Summary

difference between python and c++ implementation of bsdf
## System configuration

System information:
  OS: Ubuntu 22.04 LTS
  CPU: AMD Ryzen 7 5800X 8-Core Processor
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
  NVidia driver: 515.48.07
  LLVM: 15.0.3

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

  
## Description

Run the attached python file. It has a python implementation of diffuse bsdf. When compared to the output of the built-in diffuse, the output image is different.

Run the attached python file. It has a python implementation of diffuse bsdf. When compared to the output of the built-in diffuse, the output image is different.
------------------------------------------------------------------------
[tstdiffuse.txt](https://github.com/mitsuba-renderer/mitsuba3/files/9859106/tstdiffuse.txt)

**Comment by Speierers** [comment]
The default reflectance value of the `diffuse` BSDF defined in `diffuse.cpp` is `0.5`, hence the difference in the image here I suppose.
