### ISSUE TITLE
cuda environment

### ISSUE THREAD

**Issue by JLfot** [mitsuba-renderer/mitsuba3#362]
## System configuration

System information:

  OS: Windows10
  CPU: AMD R7 4800H
  GPU: NIVDIA Geforce RTX 2060
  Python version: 3.10
  LLVM version: ...
  CUDA version: 10.2
  NVidia driver: ...

  Dr.Jit version: ...
  Mitsuba version: 3.0
     Compiled with: ...
     Variants compiled: ...

## Description

I have downloaded CUDA and set the environment as the paper said. But when I try to use the cuda_ad_rgb variant to run the code in tutorials, the python program will unexpectedly exit with no error information. It seems that my cuda is not detected.

**Comment by njroussel** [comment]
Hi @JLfot 

As requested in the template, could you please run `python -m mitsuba.sys_info` and post it here? Having all your environment information greatly helps us when trying to understand the issues you encounter.

You do not need to download, nor install CUDA. Mitsuba interfaces directly with your GPU driver, entirely bypassing the need for CUDA.

Depending on your setup, it is quite possible that Jupyter is suppressing the crash/exit logs of mitsuba. Can you please try running your code in a simple Python script. There you should have more information about what is happening. You can also increase the logging level with `mitsuba.set_log_level` and `drjit.set_log_level` if the original error message is not enough.

**Comment by JLfot** [comment]
Hi @njroussel 
![KK@B~J}K8RW %%O6KND447S](https://user-images.githubusercontent.com/109345928/199669342-e0e27017-e49a-4089-91f7-7923b0aa76bd.png)
this is my system information, will it help?

**Comment by njroussel** [comment]
I can't spot anything wrong :slightly_frowning_face: 

Can you try what I suggested in the last part of my message: running your code in a Python script ?
Hopefully that will at least give us an error message.

**Comment by JLfot** [comment]
OK, I'm trying . Thank you for your advice!

**Comment by JLfot** [comment]
I write a simple python script to render a cornel box scene. I run the code line by line in the console which I don't know if this is what you mean and here are the results: 
llvm_ad_rgb:

![1](https://user-images.githubusercontent.com/109345928/199676984-89299602-ab73-4ea5-908e-cd6953db5c8c.png)

![2](https://user-images.githubusercontent.com/109345928/199677001-04f24b20-da15-4cfb-975c-eda6622333cb.png)

cuda_ad_rgb:
![3](https://user-images.githubusercontent.com/109345928/199677935-14afdcf1-b91a-4815-a954-fda0495e541b.png)
![4](https://user-images.githubusercontent.com/109345928/199677946-a61c0a8d-6a4b-4227-9750-c4c7d0ff5f62.png)

**Comment by njroussel** [comment]
I'm a bit confused.

> Backend MacOSX is interactive backend. Turning interactive mode on.
Are you on MacOS ?

**Comment by JLfot** [comment]
No, I'm on Windows10.
I don't know why there is this MacOSX sentence, thisi is the first time it appear. If I run the `plt.axis()` and `plt.imshow()`together, it won't appear. I think this maybe not ralated to my cuda issue.

**Comment by njroussel** [comment]
Ok ok.

This crash is really surprising. Can you try enabling more logs, as follows:
```python
import mitsuba as mi
import drjit as dr

mi.set_variant('cuda_ad_rgb')

mi.set_log_level(mi.LogLevel.Trace)
dr.set_log_level(dr.LogLevel.Trace)
```

If this still doesn't give us any additional information, you might have to compile the project yourself.

**Comment by JLfot** [comment]
Sorry for replying so late! 
I tried run the commands as you give, but it doesn't give me any information.

**Comment by njroussel** [comment]
I'm stumped.
The last thing I can suggest is to compile the project yourself, in `Debug` mode can use a debugger to track down where it is crashing.

**Comment by JLfot** [comment]
Ok, thank you for your suggestion! I will tried to compile the project myself.

**Comment by JLfot** [comment]
I have rebuild my computer and then succeeded.
