### ISSUE TITLE
How can I render an image with a non-random initial ray in Python?

### ISSUE THREAD

**Issue by keepitwiel** [mitsuba-renderer/mitsuba3#368]
## Summary

I want to simulate a perspective camera where the initial ray directions are determined by a regular grid, i.e. without randomization.

## System configuration

OS X 12.6.1

System information:

  OS: 12.6.1
  CPU: b'Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz'
  Python: 3.10.6 (main, Aug 11 2022, 13:49:25) [Clang 13.1.6 (clang-1316.0.21.2.5)]
  LLVM: 14.0.6

  Dr.Jit: 0.2.2
  Mitsuba: 3.0.2
     Is custom build? False
     Compiled with: AppleClang 13.0.0.13000029
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_rgb

## Description

As I understand it, when rendering a scene: 
* the Sensor is responsible for creating an initial set of rays that emanate from the camera.
* the Sampler is responsible for adding randomness to the initial rays.

How can I tell the Sensor to ignore the Sampler when constructing the initial rays? I would like the Sampler to be involved in the Integrator.

As you can see from the code below, I tried to create my own Integrator, and send rays to it that were generated without randomness, but I feel there must be a simpler way by e.g. registering a custom Sampler or Sensor.

## Steps to reproduce

1. Create custom Integrator in Python and call it with "non-random" rays:

```python

import mitsuba as mi
import drjit as dr
import numpy as np
from matplotlib import pyplot as plt

mi.set_variant('llvm_ad_rgb')
from mitsuba.python.ad.integrators.common import mis_weight


BSDF_SAMPLES = 0
EMITTER_SAMPLES = 1

SUM = BSDF_SAMPLES + EMITTER_SAMPLES
WEIGHT_BSDF = 0 if BSDF_SAMPLES == 0 else 1.0 / BSDF_SAMPLES
WEIGHT_LUM = 0 if EMITTER_SAMPLES == 0 else 1.0 / EMITTER_SAMPLES
FRAC_BSDF = BSDF_SAMPLES / SUM
FRAC_LUM = EMITTER_SAMPLES / SUM


class DirectIntegrator:
    """
    Poorly transcribed from C++ version of DirectIntegrator in Mitsuba.
    """
    def sample(self, scene, sampler, ray, active):
        # see if there is a surface interaction for a given ray
        surface_interaction = scene.ray_intersect(ray)

        # we only keep valid rays, that is rays
        # where we find a valid surface interaction
        valid_ray = active & surface_interaction.is_valid()

        n = len(active)

        result = mi.Color3f([0] * n)

        # ----------------------- Visible emitters -----------------------

        """omitted code"""

        # ----------------------- Emitter sampling -----------------------

        """omitted code"""

        # ----------------------- BSDF sampling --------------------------

        """omitted code"""

        return result, valid_ray


if __name__ == "__main__":
    cbox = mi.cornell_box()
    scene = mi.load_dict(cbox)

    o = mi.Point3f(0, 0, 4)
    d = dr.normalize(mi.Vector3f(0, 0, -1))
    l = 1
    w = 1.5
    h = 1.5
    n_x = 256
    n_y = 256

    x, y = dr.meshgrid(
        dr.linspace(mi.Float, -w / 2, h / 2, n_x),
        dr.linspace(mi.Float, -h / 2, h / 2, n_y),
    )
    z = dr.linspace(mi.Float, 2, 2, n_x * n_y)

    # calculate origin + direction of rays emenating from raster
    o_ray_local = mi.Vector3f(x, y, z)
    o_ray = mi.Frame3f(d).to_world(o_ray_local) + o
    d_ray = dr.normalize(o_ray - o)

    # sampler
    sampler = mi.PCG32(size=dr.prod([n_x, n_y]))
    # create rays
    ray = mi.Ray3f(o=o_ray, d=d_ray)

    # active mask
    active = mi.Mask([True] * (n_x * n_y))

    integrator = DirectIntegrator()
    result = integrator.sample(scene, sampler, ray, active)

    fig, axes = plt.subplots(1, 1)
    img = np.array(result[0]).reshape((n_x, n_y, 3))
    img *= 255
    img = np.clip(img, 0, 255)
    img = img.astype(np.uint8)
    axes.imshow(img)
    plt.show()
```

**Comment by njroussel** [comment]
Hi @keepitwiel 

Personally, were I to implement this too, I would have written a custom pipeline like you did.

It is possible to do it with a custom `Sensor` plugin. But the solution would be somewhat hacky. The `sample_position` argument in `Sensor.sample_ray()` and `Sensor.sample_ray_differntial()`  is just the pixel position plus some random offset. So, you could quantize that value so that it would always give you back the pixel position which would be like sampling your regular grid.
This only works if you `Film` resolution matches whatever grid resolution you want to for your ray generation.

**Comment by keepitwiel** [comment]
Thanks @njroussel for your response!

I've tried the custom pipeline just now, that seems to work.
