### ISSUE TITLE
Updating to_world transformation for instances

### ISSUE THREAD

**Issue by diolatzis** [mitsuba-renderer/mitsuba3#377]
## Summary

Updating the to_world transformation for isntances of shapegroups doesn't update the shapes' positions in a new render. I am doing the same update to the to_world transformation of sensors and it seems to work fine.

## Description

I want to edit the position of a shapegroup instance through Python. I have tried the following:

```
translate = np.array([0.2, 1.0, 0.0])

to_world = np.eye(4)
to_world[:3, 3] = translate

params['my_instance.to_world'] = to_world
#params.set_dirty('my_instance.to_world')
params.update()
```
The transfromation seems to get updates when I check params but in the rendering the shapes are not moving. I have tried setting the parameter as dirty but no luck. If this is just not supported yet do you have a suggestion on what the cleanest way to do this would be?

Thanks for all the great work guys!

**Comment by Speierers** [comment]
We are aware of this issue, it will be fixed in the next release.

**Comment by Speierers** [comment]
Ok, I will fix this on `master`
