### ISSUE TITLE
Why is rendered tensor shape is "transposed" relative to sensor resolution?

### ISSUE THREAD

**Issue by v-san** [mitsuba-renderer/mitsuba3#383]
Greetings!

I'm working on an inverse rendering project and everything is fine when the rendering resolution is squared (i.e. width == height).
But if the resolution is non-squared, the rendered tensor has width and height swapped and I get shape mismatch when trying to compute loss function between a rendered image and a pre-existing image.
I've created a [gist which outputs rendered tensor shape](https://gist.github.com/v-san/a60b5fed9ecf01023db0426ce260df54) and shapes/resolutions after various conversions to illustrate my question.
I expected that if sensor resolution is set, for example, to 1024x512 with rgb format, tensor with 1024x512x3 shape will be returned by the *render* function. But as gist shows, 512x1024x3 tensor is returned instead. And if this tensor is converted to bitmap, it will have correct resolution of 1024x512.
What am I doing wrong ? And how can I solve this problem of rendering and computing loss in non-square resolution?

Thanks!

**Comment by njroussel** [comment]
Hi @v-san 

This is just a matter of conventions.

You expected the returned value to be `width x height x channels`, which is the usual convention for textures. And if you use `mi.Bitmap` or a `bitmap` `Texture` object this is indeed what you'll see in Mitsuba.
However, we're dealing with Tensors and this convention is actually quite bizarre if you think about the fact that the texture is stored as a row-major array. The order of the dimensions does not reflect the order of dimensions traversed in the flattened array: you first traverse the channels of a pixel, the the width of the image, then the height (more of  `height x width x channels`).

Tensors are just an abstract container - they do not know that they actually are a texture in some cases - this is why they have a `height x width x channels` shape. The "texture convention" of ordering dimensions also breaks down if we now to deal with N-dimensional tensors. This also matches what is usually done in Python/tensor-frameworks.

You shouldn't have any issues when computing your loss, underneath the hood the tensor data is style stored in C-style/row-major like for a texture. I do not know how you're loading your reference image, but you should most likely change how that is done to match the Mitsuba/Python convention.

Take a look at [this issue ](https://github.com/mitsuba-renderer/mitsuba3/issues/82), there's a bit more detail on the usual pitfalls of Python indexing.

**Comment by v-san** [comment]
Thank you very much for detailed response! Indeed, I had an incorrect texture transformation in my texture loading function.
