### ISSUE TITLE
Face indices are different for the "same" object

### ISSUE THREAD

**Issue by Kerstin08** [mitsuba-renderer/mitsuba3#391]
## Summary

I'm not sure if that is intended behavior or a bug:
The face indices returned (e.g. via traversing the scene and getting the face indices from the returned values) are different based on which kind of indices are used to describe the face. If e.g. the "same" sphere is used in a scene and one of the spheres is exported with only the vertices indices describing the face, those are returned. However, if the second sphere also e.g. normals indices describing the faces, those are returned. It seems that always the last index, which makes up a description point of the face is returned:
v -> v
v//n -> n
v/u -> u
Therefore, for the "same" objects different face indices are returned, which seems odd. I would expect all indices making up the face description to be returned. Is this intended or a bug?
I've added test results where the face indices from a sphere with just vertices, vertices+normals, vertices+texcoords, and vertices+normals+texcoords are stored as well as the corresponding sphere objects.
[tests.zip](https://github.com/mitsuba-renderer/mitsuba3/files/10027070/tests.zip)

## System configuration

OS: Windows-10
CPU: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
GPU: NVIDIA GeForce RTX 2060
Python: 3.10.4
NVidia driver: 517.00
CUDA: 11.4.120
LLVM: 0.0.0
Dr.Jit: 0.2.2
Mitsuba: 3.0.2
Is custom build? False
Compiled with: MSVC 19.33.31629.0
Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

**Comment by njroussel** [comment]
Hi @Kerstin08 

This is indeed intended. It's just a by-product of how we store objects in memory. You can `mi.traverse()` your meshes and check the `vertex_count` parameter they will have different values. 

We duplicate some of the information to make indexing/lookups easier. Imagine that for every face we just store 3 indices. We can use the same index value to lookup the appropriate value in a vertex arrrary, normal array, and uv array if we duplicate some of the data. The key is just to allocate enough for every unique (vertex, normal, uv) triplet that is used in the original file.
