### ISSUE TITLE
Batch sensor: unknown error

### ISSUE THREAD

**Issue by Jerrypiglet** [mitsuba-renderer/mitsuba3#422]
## Summary

Hi there, I am caught up with an issue on how to implement the batch sensor in Python, given a list of sensors. Please see the detailed description below. Thanks!

## System configuration

System information:

  OS: OS X
  CPU: M1 Mac (arm64-apple-darwin22.2.0)
  GPU: N/A
  Python version: 3.8
  LLVM version: Unknown
  CUDA version: N/A
  NVidia driver: N/A

  Dr.Jit version: 0.3.2
  Mitsuba version: 3.1.1
     Compiled with: llvm
     Variants compiled: llvm_ad_rgb

## Description

I have prepared [this script](https://gist.github.com/Jerrypiglet/663d9b153d070bf85a503bab44d885ce) for testing the batch sensor, which gives an error:

``` bash
  File "tmp.py", line 56, in <module>
    img2 = mi.render(scene, sensor=mi.load_dict(batch_sensor_dict))
  File ".../site-packages/mitsuba/python/util.py", line 518, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File ".../site-packages/drjit/router.py", line 5621, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File ".../site-packages/mitsuba/python/util.py", line 373, in eval
    return self.integrator.render(
RuntimeError: jit_var_new_op(select, r357, r0, r63): arithmetic involving an uninitialized variable!
```

I have tried to look into ``batch.cpp`` to make sure whether I am calling the API correctly but not entirely sure whether I am formulating the list of ``radiancemeter`` sensors as member of the ``batch`` sensor correctly.

Meanwhile what I am trying to do with the ``batch`` sensor is to implement rendering of the environment map panorama at one point of the scene, via querying the radiance in all directions along the sphere. I wonder if there is a direct API available in Mitsuba to allow faster rendering of environment maps at scene locations?

## Steps to reproduce

[Test script](https://gist.github.com/Jerrypiglet/663d9b153d070bf85a503bab44d885ce)

**Comment by wjakob** [comment]
Hi @Jerrypiglet  -- the error aside, this does not seem like a good use of the `batch` sensor that is made for rendering a few full 2D images at the same time. What you likely want is some variant of the `spherical` plugin from Mitsuba 1 (http://mitsuba-renderer.org/releases/current/documentation.pdf). This should not be difficult to port, PRs are welcome :-)

**Comment by Jerrypiglet** [comment]
Hey @wjakob thank you so much for the update! I will look into porting the plugin. Meanwhile I wonder if you any idea on what the error is about and whether there is something wrong with the way I formulate the batch sensor?

**Comment by wjakob** [comment]
It seems reasonable to me. Likely you are running into an edge case of the implementation that was never tested with such 1-pixel sensors.

**Comment by Jerrypiglet** [comment]
hey @wjakob upon checking the code, I found it might be beyond my expertise to port the sensor. It would be great if the spherical sensor can one day be officially implemented. I will stay tuned, and again thanks for the great work!

**Comment by Speierers** [comment]
As this isn't an issue, let me close this.
