### ISSUE TITLE
Build issue - drjit submodule

### ISSUE THREAD

**Issue by alhirzel** [mitsuba-renderer/mitsuba3#423]
The `mitsuba3` project refers to a specific commit of the `drjit` submodule. The commit `165a9a` of `drjit` currently shows a weird error on GitHub:

https://github.com/mitsuba-renderer/drjit/tree/165a9a24db367029f687e9c52c61fb4b1d73b8be

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Is there an issue with the submodule reference? Or perhaps there was a force push on `drjit` and `mitsuba3` needs to be updated?

Note that this still seems to somehow work when using `git clone --recursive`, but is breaking when I am [jumping through some hoops to build efficiently using AUR](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=mitsuba3-git). Perhaps this hoop-jumping is part of the root cause, but something has changed in the last 7 days to break it.

**Comment by njroussel** [comment]
Hi @alhirzel 

Indeed there's been a few force pushes recently on both repositories.
I'm sorry this is causing issues in your `PKGBUILD`. I don't see what could be the issue here.
We'll be pushing updates to Mitsuba `master` soon, which should reference different Dr.Jit commits, so hopefully that will fix this problem

**Comment by njroussel** [comment]
The most recent commit on `master` (cf456d7f6d4bd565a4b201475bd28c814f16c891) should have set Dr.Jit to commit that is tracked on the main branch again. 

I'll close this issue for now. If it still doesn't fix your issue, please tell me we can re-open this :)

**Comment by alhirzel** [comment]
@njroussel - issue resolved, thanks much :)
