### ISSUE TITLE
Principal BSDF renders (metallic: 1.0, specular: 0.0) as black

### ISSUE THREAD

**Issue by chrisoffner** [mitsuba-renderer/mitsuba3#424]
## Summary

The Principled BSDF renders a surface as fully black if `metallic` is fully cranked up to 1.0 but `specular` is at 0.0.

Setting `specular` even just to 0.000001 changes the render entirely, showing a fully reflective surface (which is what I would expect for `metallic` at 1.0).

<img width="1454" alt="specular_zero" src="https://user-images.githubusercontent.com/18167754/205493137-6ffcb1ff-9d25-49c6-9091-2cc0bb118d6f.png">

<img width="1449" alt="specular_nonzero" src="https://user-images.githubusercontent.com/18167754/205493132-84696302-47b2-45d5-a6ef-995a2b555178.png">

## System configuration

System information:

  OS: macOS Ventura 13.0.1 (22A400)
  CPU: 2,4 GHz 8-Core Intel Core i9
  GPU: AMD Radeon Pro 5500M 8 GB, Intel UHD Graphics 630 1536 MB

  Mitsuba version: Mitsuba version 3.0.2 (master[47a3958e], Mac OS, 64bit, 16 threads, 8-wide SIMD)

## Steps to reproduce

1. Render an object with the following BSDF and observe that the surface appears as a highly reflective metal.
```xml
<bsdf type="principled">
	<rgb value="0.141238 0.176228 0.800000" name="base_color"/>
	<float name="specular" value="0.000001"/>
	<float name="metallic" value="0.5"/>

	<float name="spec_trans" value="0.0"/>
	<float name="roughness" value="0.0"/>
	<float name="spec_tint" value="0.0"/>
	<float name="anisotropic" value="0.0"/>
	<float name="sheen" value="0.0"/>
	<float name="sheen_tint" value="0.0"/>
	<float name="clearcoat" value="0.0"/>
	<float name="clearcoat_gloss" value="0.0"/>
</bsdf>
```
2. Render the same scene with merely the `specular` line replaced as follows to observe that the surface appears fully black.
```xml
<float name="specular" value="0.0"/>
```

**Comment by Speierers** [comment]
Hi @chrisoffner,

I think this is the expected result. Setting a value of `0.0` to `specular` will completely disable the specular component of the BSDF. IIRC, `metallic=1.0` indicates that the BSDF should be perfectly specular, hence this contradiction will result in a null response from the BSDF.

**Comment by efylmzr** [comment]
Hi @chrisoffner  and @Speierers,
I think this is actually a bug. When specular is 0, (it means eta=1), one of the operations was becoming undefined (c/0) . I remember that I forced eta to be at least 1.0001. If you can render with value 0.0, there should be a mistake in one of the control statements. I can look into that. Thanks for pointing out.
