### ISSUE TITLE
Tutorial  “Gradient-based optimization” does not work in spectral mode

### ISSUE THREAD

**Issue by gnauk** [mitsuba-renderer/mitsuba3#428]
## Summary

when use the cuda_ad_spectral variant, the inverse  tutorial produces an error  

## System configuration

 OS: Windows-10
  CPU: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
  GPU: NVIDIA GeForce RTX 3060 Laptop GPU
  Python: 3.9.7 (default, Sep 16 2021, 16:59:28) [MSC v.1916 64 bit (AMD64)]
  NVidia driver: 517.00
  CUDA: 11.6.55
  LLVM: 0.0.0

  Dr.Jit: 0.3.2 (DEBUG)
  Mitsuba: 3.1.1 (DEBUG)
     Is custom build? False
     Compiled with: MSVC 19.33.31630.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        cuda_ad_spectral
        cuda_ad_mono

## Description

The error happens in 
    # Backpropagate through the rendering process
    dr.backward(loss)

TypeError: backward_from(): the argument does not depend on the input variable(s) being differentiated. Raising an exception since this is usually indicative of a bug (for example, you may have forgotten to call dr.enable_grad(..)). If this is expected behavior, skip the call to backward_from(..) if ek.grad_enabled(..) returns False.

Thanks for your Help.

**Comment by njroussel** [comment]
I have no idea what was originally causing the issue, but it has been fixed since. No recent change comes to mind, please keep this issue updated if you are still encountering this problem.
