### ISSUE TITLE
Avoid "out of memory" error on CUDA variant for high-res renderings

### ISSUE THREAD

**Issue by dekuenstle** [mitsuba-renderer/mitsuba3#432]
## Summary

Rendering high-resolution images (e.g., FullHD+4000spp) with the cuda_ad_rgb variant fails, because the required memory easily exceeds feasible VRAM sizes. I search for possible workarounds without reducing the resolution or SPP. 

## System configuration
'''
System information:

  CPU: Intel(R) Xeon(R) Gold 5218 CPU @ 2.30GHz
  GPU: Tesla V100-SXM2-32GB
  Python: 3.9.0 (default, Nov 15 2020, 14:28:56) [GCC 7.3.0]
  NVidia driver: 515.65.01
  LLVM: 0.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
'''
## Description

See the summary above. 

As a possible workaround, I already tried the `prb` integrator (as recommended in the docs of the .render function) but failed:
When I changed the integrator in the XML and invoked the mitsuba-CLI, I got a "plugin prb not found" error; when I run mitsuba via python, I got an error requesting "multi-pass". However, it is unclear to me how to invoke multi-pass rendering via the python API. 

PS: I much appreciate your work and the improvements of mitsuba3; especially how easily the GPU-variant can be installed and used in contrast to compiling mitsuba2. 

## Steps to reproduce

Use a moderately complex scene with the path integrator, then run:
```
mitsuba -m cuda_ad_rgb -Dresx=1920 -Dresy=1200  -Dspp=2048 -o Scene.png Scene.xml
...
2022-12-06 19:57:44 WARN  main  [SamplingIntegrator] The requested rendering task involves 2359296000 Monte Carlo samples, which exceeds the upper limit of 2^32 = 4294967296 for this variant. Mitsuba will instead split the rendering task into 2 smaller passes to avoid exceeding the limits.
2022-12-06 19:57:44 INFO  main  [SamplingIntegrator] Starting render job (1920x1200, 2048 samples, 2 passes)
Caught a critical exception: jit_malloc(): out of memory! Could not allocate 34359738368 bytes of device memory.
```

**Comment by wjakob** [comment]
Hi @dekuenstle,

this is a stupid technical issue related to 32 bit indexing within the generated kernels. We will have a better solution in the future. For now, what I suggest is that you call the renderer twice with 2048 spp (and with different `seed` values in the sampler) and then average the resulting images.

**Comment by dekuenstle** [comment]
Thanks a lot for the prompt response and your work!
