### ISSUE TITLE
Specifying separate fovs for x and y

### ISSUE THREAD

**Issue by errissa** [mitsuba-renderer/mitsuba3#438]
## Summary

Is it possible to specify separate FOVs for x and y directions? I am trying replicate a sensor with non-square pixels.

## System configuration
System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: 12th Gen Intel(R) Core(TM) i9-12900H
  GPU: NVIDIA GeForce RTX 3080 Ti Laptop GPU
  Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  NVidia driver: 515.65.01
  CUDA: 11.7.64
  LLVM: 12.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

**Comment by Speierers** [comment]
Hi @errissa ,
This isn't supported in Mitsuba 3. You will need to implement your own sensor plugin to support non-square pixels. See [this tutorial](https://mitsuba.readthedocs.io/en/stable/src/others/custom_plugin.html) on how to implement new plugins in Python directly.
