### ISSUE TITLE
Add meaningful error message when Python requirement is not sufficient

### ISSUE THREAD

**Issue by G-nn-r** [mitsuba-renderer/mitsuba3#442]
## Summary

Mitsuba requires Python 3.8. When trying to install Mitsuba without this requirement, there is no meaningful error message:
```
pip install mitsuba
ERROR: Could not find a version that satisfies the requirement mitsuba (from versions: none)
ERROR: No matching distribution found for mitsuba
```

## System configuration

System information:

  OS: Windows 10
  Python version: 3.7.1

**Comment by njroussel** [comment]
Hi @G-nn-r 
I'm not quite sure I understand.
We have no control over this, it would be up to `pip` to print a relevant error message.

Or are you suggesting we upload an "empty" package to PyPI which would just raise an error message as soon as it's imported?

**Comment by wjakob** [comment]
I agree with @njroussel  -- this is an issue that you should escalate to `pip` and not this project. I will point out that Python 3.7 is also quite old at this point. It is beyond its maintenance cycle and only receives critical security-related fixes at this point.
