### ISSUE TITLE
Bug Report of Disney Principled BSDF

### ISSUE THREAD

**Issue by JamesZFS** [mitsuba-renderer/mitsuba3#443]
## Summary

I found a seeming failure case of principled BSDF when setting the `metallic` to a non-zero value and `specular` to zero.

## System configuration

System information:

  OS: macOS Monterey
  CPU: M1

  Dr.Jit version: 0.3.2
  Mitsuba version: 3.1.1
     Compiled with: clang
     Variants compiled: scalar_rgb, scalar_spectral, llvm_ad_rgb

## Description

While working on my graphics course project at ETH, I am trying to compare my Disney principled BSDF against Mitsuba. I ended up running into a corner case which Mitsuba doesn't seem to handle well when setting the `metallic` parameter to some non-zero value and `specular` to zero, with the [test scene provided by Tungsten Renderer](https://benedikt-bitterli.me/resources/mitsuba/material-testball.zip)

When setting the tested material to `metallic` 1 (i.e., to disable diffuse lobe) and `specular` 0:
```xml
<bsdf type="twosided" id="Material" >
	<bsdf type="principled">
		<rgb name="base_color" value="0.9,0.9,0.9"/>
		<float name="metallic" value="1.0" />
		<float name="specular" value="0.0" />
	</bsdf>
</bsdf>
```

The rendered result looks completely dark:
![bug_mi_m1s0](https://user-images.githubusercontent.com/31480030/207417819-a80438b5-252d-4895-89b7-d6e3083d18b3.png)

However, changing `specular` to any non-zero value, e.g. 0.01:
```xml
<bsdf type="twosided" id="Material" >
	<bsdf type="principled">
		<rgb name="base_color" value="0.9,0.9,0.9"/>
		<float name="metallic" value="1.0" />
		<float name="specular" value="0.01" />
	</bsdf>
</bsdf>
```

The result suddenly changes to bright:
![bug_mi_m1s0 01](https://user-images.githubusercontent.com/31480030/207418210-d86948ad-4871-4c8c-ba40-aca267a1cba0.png)

Which is counterintuitive. The experiment was done on different variants, and the problem always exists.

After diving into the code, it seems to me the issue is related to the specular lobe mask:

https://github.com/mitsuba-renderer/mitsuba3/blob/f3ac81bc5c6ce65d5843dde3a1d5f230353453e3/src/bsdfs/principled.cpp#L552-L556

which is used as a precondition for computing the specular reflection BSDF value.

https://github.com/mitsuba-renderer/mitsuba3/blob/f3ac81bc5c6ce65d5843dde3a1d5f230353453e3/src/bsdfs/principled.cpp#L584-L585

So when `specular` is set to 0, the dielectric fresnel term will always equal zero, which leads to the mask being false.

However, in the case of a non-zero `metallic`, the principled fresnel computed in the specular branch will not be zero anymore.

Disabling this `(F_spec_dielectric > 0.0f)` part in the mask assignment will fix this issue and the result of `metallic 1, specular 0` will not be dark anymore.

Similar issues might also happen for other lobes like the specular transmission. I didn't have time to check that :)

**Comment by chrisoffner** [comment]
I pointed this out the other day but was told it's supposed to work like this.

https://github.com/mitsuba-renderer/mitsuba3/issues/424

**Comment by JamesZFS** [comment]
> I pointed this out the other day but was told it's supposed to work like this: #424

Oops
