### ISSUE TITLE
[🐛 bug report] Wrong HG Phase function sampling when g is negative

### ISSUE THREAD

**Issue by yuhan-zh** [mitsuba-renderer/mitsuba3#455]
## Summary

The HG Phase function sampling is doing something wrong when g is negative.
It's easy to tell that there is a bug once it's pointed out. So instead of providing any code to reproduce the problem, I will just show where the bug is and the reason.

## Description
 Line 79 of src/phase/hg.cpp:  dr::masked(cos_theta, m_g < dr::Epsilon<ScalarFloat>) = 1 - 2 * sample2.x();
( https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/phase/hg.cpp#L79 )

The mask "m_g < dr::Epsilon<ScalarFloat>" is true for any negative m_g.
This will result in Uniform Sphere Sampling for any negative m_g

The correct code should be: dr::masked(cos_theta, dr::abs(m_g) < dr::Epsilon<ScalarFloat>) = 1 - 2 * sample2.x();

**Comment by wjakob** [comment]
oops, that's not good. Fixed now, thanks for the report!
