### ISSUE TITLE
Dr.Jit compiler failure with textured emitters

### ISSUE THREAD

**Issue by steinraf** [mitsuba-renderer/mitsuba3#460]
## System configuration

System information:

  OS: EndeavourOS Linux
  CPU: AMD Ryzen 7 5800H with Radeon Graphics
  GPU: NVIDIA GeForce RTX 3060 Laptop GPU
  Python: 3.10.8 (main, Nov  1 2022, 14:18:21) [GCC 12.2.0]
  NVidia driver: 525.60.11
  CUDA: 11.8.89
  LLVM: 14.0.6

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

When trying to use a textured area emitter, the autodiff variants both raise an error `Critical Dr.Jit compiler failure: jit_var(r0): unknown variable!`, the non-ad variants both just dont terminate, even for 1 spp 800x600 scenes.

## Steps to reproduce

1. main.py
```
import mitsuba as mi
import matplotlib.pyplot as plt

print(mi.variants())

mi.set_variant('cuda_ad_rgb')

scene = mi.load_file("scenes/finalScenes/texturedEmitterTest.xml")


image = mi.render(scene)

plt.axis("off")
plt.imshow(image ** (1.0 / 2.2))

plt.show()

mi.util.write_bitmap("out.hdr", image)
```

2. textureEmitterTest.xml
```
<scene version='3.0.0'>
    <integrator type="path">
        <integer name="max_depth" value="200"/>
    </integrator>

    <sensor type="perspective">
        <float name="fov" value="27.7856"/>

        <transform name="to_world">
            <lookat target="0, 0.893051, 4.41198"
                    origin="0, 0.919769, 5.41159"
                    up="0, 1, 0"/>
        </transform>



        <sampler type="independent">
            <integer name="sample_count" value="1"/>
        </sampler>

        <film type="hdrfilm">
            <integer name="height" value="600"/>
            <integer name="width" value="800"/>
        </film>

    </sensor>

    <shape type="obj">
        <string name="filename" value="scenes/obj/sphere2.obj"/>

        <transform name="to_world">
            <scale value="0.0333, 0.0333, 0.0333"/>
            <scale value="0.3263, 0.3263, 0.3263"/>
            <translate value="0, 1, 0"/>
        </transform>

        <emitter type="area">
            <texture type="bitmap" name="radiance">
                <string name="filename" value="scenes/textures/UVChecker.jpg"/>
            </texture>
        </emitter>
    </shape>
</scene>
```

**Comment by njroussel** [comment]
Hi @steinraf 

I have not been able to reproduce this. We've had issues in the past with textured-area-mesh-emitters, and are still abusing some non-documented features in `cuda` variants.  But the `scalar_` and `llvm_` variants should have no issues regarding this.

Could you try building `mitsuba` locally and see if the error persists ?

**Comment by steinraf** [comment]
Hey @njroussel 

I built mitsuba from scratch with the newly released version and now it seems to be working successfully without any errors with the cpu scalar and the cuda autodiff variant.
