### ISSUE TITLE
[BUG]: Error drjit.ones() with dtype = mi.UInt32

### ISSUE THREAD

**Issue by takkasila** [mitsuba-renderer/mitsuba3#464]
## Summary

Calling function drjit.ones() with dtype as mi.UInt32 causes an error.

## System configuration

System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
  GPU: NVIDIA GeForce RTX 3060 Laptop GPU
  Python: 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 516.59
  CUDA: 11.6.124
  LLVM: 0.0.0

  Dr.Jit: 0.3.0 (DEBUG)
  Mitsuba: 3.1.0 (DEBUG)
     Is custom build? False
     Compiled with: MSVC 19.33.31630.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
## Description

Calling function drjit.ones() with dtype as mi.UInt32 prompt the following error
```python 
dr.ones(dtype= mi.UInt32, shape= 5)
```
```
Exception has occurred: TypeError
(): incompatible function arguments. The following arguments types are supported:
    1. (arg0: int, arg1: int) -> drjit.cuda.ad.UInt
Invoked with: 1.0, 5
    File "path_to_local_mitsuba3\build\Debug\python\drjit\router.py", line 4722, in ones
```

## Steps to reproduce

```python 
import drjit as dr
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')
dr.ones(dtype= mi.UInt32, shape= 5)
```

**Comment by njroussel** [comment]
Hi @takkasila 

Thanks for reporting this issue. I pushed a fix to `drjit`: https://github.com/mitsuba-renderer/drjit/commit/79be010fd663ad200441180c5bf58c9358879fee

You can apply the same patch locally on your files until this fix makes its way into a public release. Or, alternatively, you can just use `dr.full(type, 1, shape)` that should work too :)
