### ISSUE TITLE
Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1

### ISSUE THREAD

**Issue by lynshwoo2022** [mitsuba-renderer/mitsuba3#467]
## Summary

in `llvm_ad_rgb` mode, rendering an img in pytorch optimization loop, after a few iteration, error occured  when running `loss.backward()`:  `Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1` 
https://github.com/mitsuba-renderer/mitsuba3/issues/201 this issue dosen't help. 
## System configuration

System information:

  OS: Ubuntu 20.04.4 LTS
  CPU: Intel(R) Xeon(R) Platinum 8276L CPU @ 2.20GHz
  GPU: Tesla V100-PCIE-32GB
Tesla V100-PCIE-32GB
  Python: 3.8.15 | packaged by conda-forge | (default, Nov 22 2022, 08:49:35) [GCC 10.4.0]
  NVidia driver: 470.129.06
  LLVM: 12.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
## Description
except for the error:
```
Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1
```
it can also be :
```
    loss.backward()
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/autograd/function.py", line 199, in apply
    return user_fn(self, *args)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/autograd/function.py", line 340, in wrapper
    outputs = fn(ctx, *args)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/router.py", line 5854, in backward
    args_grad = drjit_to_torch(_dr.grad(ctx.args_drjit))
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/router.py", line 5788, in drjit_to_torch
    return tuple(drjit_to_torch(b, enable_grad) for b in a)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/router.py", line 5788, in <genexpr>
    return tuple(drjit_to_torch(b, enable_grad) for b in a)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/router.py", line 5792, in drjit_to_torch
    b = a.torch()
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/generic.py", line 1653, in torch
    return from_dlpack(a.__dlpack__())
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/generic.py", line 1638, in op_dlpack
    struct = a.export_(migrate_to_host=False, version=2)
  File "/home/ubuntu482/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/drjit/generic.py", line 1581, in export_
    _dr.sync_thread()
RuntimeError: jit_free(): unknown address <0x561dc300d8c0>!
drjit-autodiff: variable leak detected (14 variables remain in use)!
 - variable a3684273 (2 references)
 - variable a3684269 (1 references)
 - variable a3684270 (1 references)
 - variable a3684272 (2 references)
 - variable a3684274 (1 references)
 - variable a3684450 (1 references)
 - variable a3684271 (2 references)
 - variable a3684426 (1 references)
 - variable a3684283 (1 references)
 - variable a3684267 (2 references)
 - (skipping the rest)
```

## Steps to reproduce

1.` import mitsuba as mi; mi.set_variant("llvm_ad_rgb")`
2. setup scene with `prb_reparam`
3.
```python
@dr.wrap_ad(source='torch', target='drjit')
def render_texture(texture:torch.Tensor, vertex_pos:torch.Tensor, spp=8, seed=1):
    params = mi.traverse(scene)
    params['face.bsdf.brdf_0.reflectance.data'] = texture
    params['face.vertex_position'] = dr.ravel(vertex_pos)
    params.update()
    return mi.render(scene, params, spp=spp, seed=seed, seed_grad=seed+1)
...
opt =  torch.optim.Adam({texture, lr:0.005, vertex_pos,  lr:0.005})
loss = (img-render_texture(texture, vertex_pos)).abs().mean()
opt.zero_grad()
loss.backward()  # error occured here
opt.step()
```

also got a warning:` WARN  main  [BitmapTexture] BitmapTexture contains pixels that exceed the [0, 1] range!`

**Comment by njroussel** [comment]
Hi @lynshwoo2022 

Thanks for reporting this issue. To be clear do you get both the assertion error and the runtime error?

We've fixed some long-standing backend issues that could potentially be the cause here. Unfortunately, a new version containing these fixes hasn't been released yet (it should happen soon). You could try building mitsuba locally and see if that helps.

Additionally, there are quite a few open issues right now with `dr.wrap_ad`, we haven't had the time to look into those yet. That might also be the cause.

**Comment by lynshwoo2022** [comment]
> Hi @lynshwoo2022
> 
> Thanks for reporting this issue. To be clear do you get both the assertion error and the runtime error?
> 
> We've fixed some long-standing backend issues that could potentially be the cause here. Unfortunately, a new version containing these fixes hasn't been released yet (it should happen soon). You could try building mitsuba locally and see if that helps.
> 
> Additionally, there are quite a few open issues right now with `dr.wrap_ad`, we haven't had the time to look into those yet. That might also be the cause.

thanks for your reply!
i got either assertion error  or runtime error. not both at the same time. also it happens after a few iteration. I'll try build locally.

**Comment by lynshwoo2022** [comment]
i'll update in [here](https://github.com/mitsuba-renderer/mitsuba3/issues/468)
