### ISSUE TITLE
vertex_pos and envmap became NAN when integrating Mitsuba3 `prb_reparam`  into PyTorch

### ISSUE THREAD

**Issue by lynshwoo2022** [mitsuba-renderer/mitsuba3#468]
## Summary
I tried to use `prb_reparam` integrator to optimize `vertex_pos` and `envmap` in pytorch, but found vertex_pos became `nan` during iteration.

## Description

I choose to use `prb_param` to optimzie, after reading this [tutorial]( https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_integrators.html). starting fine, but after a few iterations, both `vertex_pos` and `envmap` became nan, `diffuse_tex` remained fine.

## Steps to reproduce
here's my code
1. scene:
```python
import drjit as dr
import mitsuba as mi
mi.set_variant("llvm_ad_rgb")
from mitsuba import ScalarTransform4f as T

origin = T.rotate([0, 0, 1], 90).rotate([0, 1, 0], 90) @ mi.ScalarPoint3f([0, 0, 100])  
scene =  mi.load_dict({
      "type": "scene",
      "integrator": {
                "type": "prb_reparam",
                'max_depth': 8,
                'reparam_rays': 8,
                'hide_emitters':True
       },
      "light": {
                'type': 'envmap',
                'bitmap':  mi.Bitmap(mi.TensorXf(mi.PCG32(size=64**2 * 3).next_float32(), shape=(64, 64, 3))),
              },
      "mesh": {
                'filename':'face.ply',
                'type': 'ply',
                'bsdf':{
                    'type': 'principled',
                    'base_color': {
                        'type': 'bitmap',
                        'filename': 'albedo_diff_uv.png',
                    },
                    'specular': 0.5,
                    'roughness': 0.5,
                },
            },
      "sensor": {
                'type': 'perspective',
                'to_world': T.look_at(
                    origin=origin,
                    target=[0, 0, 0],
                    up=[0, 0, 1]),
                'fov': 15.,
                'sampler': {
                    'type': 'independent',
                    'sample_count': 16
                },
                'film': {
                    'type': 'hdrfilm',
                    'width':  512,
                    'height': 512,
                    'sample_border': True,
                    'rfilter': {
                             'type': 'gaussian',
                         },
                    'pixel_format': 'rgba',
                 },
            }
        })
...
params = mi.traverse(scene)
params['sensor.x_fov'] = fov.view(1)
vertex_texcoords = mi.Point2f(mi.Float(uvmap[:,0].numpy()), 
                            mi.Float(uvmap[:,1].numpy()))
params['mesh.vertex_texcoords'] = dr.ravel(vertex_texcoords)
```
2. render:
```python

@dr.wrap_ad(source='torch', target='drjit')
def render(vertex_pos, normals, fov,
              diff_tex, specular, roughness, 
              envmap, samples, seed):
        # except for samples and seed, other params are of type torch.Tensor
        params = mi.traverse(scene)
        params_scene['sensor.x_fov'] = dr.ravel(fov)
        # mesh
        params['mesh.vertex_positions'] = dr.ravel(vertex_pos)
        # bsdf
        params['mesh.bsdf.base_color.data'] = diff_tex
        params['mesh.bsdf.roughness.value'] = dr.ravel(roughness)
        params['mesh.bsdf.specular'] = dr.ravel(specular)
        #envmap
        params['light.data'] = envmap
        params_scene.update()
        return mi.render(scene, params, spp=samples, seed=seed, seed_grad=seed+1)
```
3. in main.py:
```python
loss_fn = nn.L1Loss()
optimizer = torch.optim.Adam([
            {'params': self.vShCoeffs, 'lr': 0.001},
            {'params': self.vShapeCoeff, 'lr': 0.01},
            {'params': self.vAlbedoCoeff, 'lr': 0.001},
            {'params': self.vSpecular, 'lr': 0.001}
        ])
for it in range(400):
       vertex_pos = transform(computeVertex(self.vShapeCoeff), trans, rots)
       diff_tex = computeTex(computeVertexAlbedo(self.vAlbedoCoeff), uvmap)
       envmap = computeEnvmap(SH(self.vShCoeffs))

       img_r = render(vertex_pos, diff_tex, specular, roughness, envmap, samples=8, seed=it)
       loss = loss_fn(img_gt, img_r)
       optimizer.zero_grad()
       loss.backward()
       optimizer.step()
```
4: around iter=20, vertex_pos and envmap became nan.

looking forward to your help (T T).

**Comment by lynshwoo2022** [comment]
also tried to change `prb` to `prb_param`, envmap became `nan` earlier than `vertex_pos`

**Comment by njroussel** [comment]
Hi @lynshwoo2022 

You could try clamping your parameters to guarantee that they stay in some resonable range. If you're getting similar warnings to what you reported in #467, I'd recommend taking a look at [this tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/gradient_based_opt.html#Optimization). We explicitly clamp some parameters during the optimization.

**Comment by lynshwoo2022** [comment]
Grateful for your help!

yes i got similar warnings. however, #467 and `NaN` sometimes happens before diff_tex exceeds the [0, 1] range.
one more question is, is it ok to write `render()` function like i repo in step 2? will it work to optimize envmap and vertex_pos? can it be something wrong with `prb_reparam` integrator during backpropagation, looks like getting bad gradients?

**Comment by njroussel** [comment]
The `render` function looks good. I'm not update to date with the `dr.wrap_ad` semantics, I might be missing something.

I don't know much about your current setup, but instead of trying everything at the same time, maybe it's worth running synthetic experiments in which you only optimize one of the parameters. For example, try to only optimize an envmap with your current code (`render` included). Debugging these optimizations is a pain, usually a step-by-step approach like this would at least allow you to isolate what is failing and when is it failing.

**Comment by lynshwoo2022** [comment]
thanks a lot! i'll try. and i'll repo if i make any progress.
:)

**Comment by lynshwoo2022** [comment]
hi @njroussel ,   i did some experience:
1. ```python
    # params['mesh.vertex_positions'] = dr.ravel(vertex_pos) 
    params['mesh.bsdf.base_color.data'] = dr.clamp(diff_tex, 0, 1)
    ...
   ```
   in this way, optimization went fine. no error.
2. ```python
    params['mesh.vertex_positions'] = dr.ravel(vertex_pos)
    params['mesh.bsdf.base_color.data'] = dr.clamp(diff_tex, 0, 1)
    ....
    #params['light.data'] = envmap
   ```
   in this way, i got error: 
   ```bash
   Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1
   Assertion failed in /project/ext/drjit-core/ext/nanothread/src/queue.cpp:354: remain == 1
   Aborted (core dumped)
   ```
3. ```python
    params['mesh.vertex_positions'] = dr.ravel(vertex_pos)
    params['mesh.bsdf.base_color.data'] = dr.clamp(diff_tex, 0, 1)
    ....
    params['light.data'] = envmap
   ```
   in this way i got `nan`, and when `nan` occured, a few iterations later i got error: like `2.`

i guess is something wrong with `prb_reparam`, did i miss anythin on how to set it? my setting is: 
```\
```

**Comment by lynshwoo2022** [comment]
i tried complie mitsuba3 from git. problem still remains.

**Comment by njroussel** [comment]
That's good news!

So you're still getting `NaN`s in the `envmap` and the `vertex_pos` ?
I'd rerun experiment number 2) now that you've solved the assertion error is solved.

A good step would be to see how specific pixels in the `envmap` change during the optimization. It would be nice to understand if the values are just exploding, or if they suddenly jump to `NaN`.

Also, if you're only optimizing the `envmap` you can use `prb` rather than `prb_reparam`: maybe there is a specific bug in `prb_reparam`.

**Comment by lynshwoo2022** [comment]
> That's good news!
> 
> So you're still getting `NaN`s in the `envmap` and the `vertex_pos` ? I'd rerun experiment number 2) now that you've solved the assertion error is solved.
> 
> A good step would be to see how specific pixels in the `envmap` change during the optimization. It would be nice to understand if the values are just exploding, or if they suddenly jump to `NaN`.
> 
> Also, if you're only optimizing the `envmap` you can use `prb` rather than `prb_reparam`: maybe there is a specific bug in `prb_reparam`.

thanks for your reply, i'll try printing envmap. 
also, i want to optimzie vertex_pos and envmap both.

**Comment by lynshwoo2022** [comment]
seems like it suddenly dumps nan. 
I added `with torch.autograd.detect_anomaly():` in my code, and it throwed error:
```
site-packages/torch/autograd/__init__.py:154: UserWarning: Error detected in ToDrJitBackward. Traceback of forward call that caused the error:
  File "optimizer.py", line 583, in <module>
    optimizer.run(inputDir,
  File "optimizer.py", line 531, in run
    self.runStep2()
  File "optimizer.py", line 260, in runStep2
    images = self.pipeline.render(cameraVerts, diffuseTextures, specularTextures, seed=2)
  File "/projects/raytracing/pipeline.py", line 149, in render
    img = self.renderer.renderimg(cameraVerts[i], normals[i], fovs[i],
  File "/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/mitsuba-3.1.1-py3.8-linux-x86_64.egg/drjit/router.py", line 5821, in f
    return ToDrJit.apply(*args)
 (Triggered internally at  /opt/conda/conda-bld/pytorch_1639180588308/work/torch/csrc/autograd/python_anomaly_mode.cpp:104.)

Traceback (most recent call last):
  File "optimizer.py", line 583, in <module>
    optimizer.run(inputDir,
  File "optimizer.py", line 531, in run
    self.runStep2()
  File "optimizer.py", line 300, in runStep2
    loss.backward()
  File "/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/_tensor.py", line 307, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "/anaconda3/envs/pytorch110py38/lib/python3.8/site-packages/torch/autograd/__init__.py", line 154, in backward
    Variable._execution_engine.run_backward(
RuntimeError: Function 'ToDrJitBackward' returned nan values in its 6th output.
```
how can i locate which one is the 6th output?

**Comment by njroussel** [comment]
Could you try removing `samples` and `seed` from your wrapped `render` function?
The error you reported in 1. seems to point out that the 6th output of the wrapped function is causing issues, here this would be the `seed` parameter. You can take a look at the code in `ext/drjit/drjit/router.py`. The output/input naming is ambiguous here, but the order refers to the parameters of the function that is warpped with `dr.wrap_ad`.
There might be a bug when dealing with non-`torch.Tensor` types.

For 2., this makes sense, doesn't it? Your optimizer takes some step which makes value of the parameter jump to `NaN`, then its gradient will only become `NaN`once a call to `dr.backward` is made. You can take a look at what exactly the optimizer step is before the first `NaN` parameter value in the `envmap`.

Unfortunately, I don't believe there are any other examples than the [tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html) you linked.

I will hopefully be able to take a deeper look into the `wrap_ad` issues this week.

**Comment by lynshwoo2022** [comment]
thanks for your patience and reply :)
for 1, i changed a little bit of my code on render function, so the 6th param should be `envmap`.(updated in the first floor)
for 2, i might not clearly explain it (editted a little above). i think gradients changed to nan first and then after optim.step() envmap changed to nan. And I'll take a look following your advice, thanks.

**Comment by lynshwoo2022** [comment]
hi @njroussel， I tried this [obj pose estimation tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/object_pose_estimation.html) in mitsuba(no pytorch), just changing integrator to `prb_reparam`. i got nan too. `direct_reparam` worked fine.
```
Iteration 49: error=0.001977, angle=nan, trans=[nan, nan]58, -0.0079]
```

**Comment by njroussel** [comment]
Some good news: I'm able to reproduce the behavior in 2. This is is really surprising.
It might be an issue in `prb_reparam` after all. This code is really complex, it will be hard to track down what's exploding/breaking. 

Now for 1, the difference between both `Integrators`s is that the `_reparam` version can handle discontinuities.
When using `print(mi.traverse(scene))` you should see a list of all parameters that are exposed and each one has a different set of flags which you can learn more about here: https://mitsuba.readthedocs.io/en/stable/src/plugin_reference.html#flags.
You'll see that both the `roughness` and the `envmap.data` introduce discontinuities. You can also verify this by looking at the individual plugins' documentation, there's always a table of the parameters which also has a column for these flags: 
* [envmap](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_emitters.html#environment-emitter-envmap)
* [principled](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_bsdfs.html#the-principled-bsdf-principled)

So, the fact that `prb` fails here is expected.

**Comment by lynshwoo2022** [comment]
thanks a lot for your reply! 
i can imagine it will be truely a hard work to fix `prb_reparam`... please let me know if you make any progress :)

**Comment by lynshwoo2022** [comment]
hi there, is there any progress?

**Comment by njroussel** [comment]
Sorry, this has fallen behind.

I don't know when, what, or how, but I can no longer reproduce this. The object pose estimation tutorial with `prb_reparam` runs just fine now. 

I'll close this. Please keep this updated if you're still seeing issues on your end, I'll re-open the issue.
