### ISSUE TITLE
[🐛 bug report] Envmap seems to be queried incorrectly

### ISSUE THREAD

**Issue by dorverbin** [mitsuba-renderer/mitsuba3#469]
## Summary

Rendering a mirror sphere with an envmap with a single element on and the rest set to zero creates images that look wrong.

## System configuration

System information:

  OS: CentOS Linux release 7.9.2009 (Core)
  CPU: Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
  GPU: NVIDIA TITAN V
  Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
  NVidia driver: 515.65.01
  CUDA: 9.0.176
  LLVM: 0.0.0

  Dr.Jit: 0.3.2
  Mitsuba: 3.1.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Rendering a sphere with material `conductor` under envmap illumination results in mismatches between my own simple ray tracer and Mitsuba's result. Upon further investigation it seems like there might be an off-by-one indexing error somewhere. When setting only one of the elements of the envmap to 1 and the rest to 0, there seem to be a few issues:
1. The rendered images are identical when setting the top leftmost or the top rightmost element of the envmap to 1. See leftmost and rightmost images on the top row below. (There are also other repeating images later on.)
2. Some rendered images look like multiple elements are turned on. See, for example, the third column from the left on the first row.
3. The angle between consecutive azimuthal values looks more like $2\pi/(W-1)$ than $2\pi/W$, where $W$ is the envmap width.

Both of these seem like they could be related to the additional column from [line 145 of `envmap.cpp`](https://github.com/mitsuba-renderer/mitsuba3/blob/820c38e575b5e9e45fa89e046871c88a20181ef1/src/emitters/envmap.cpp#L145), but I couldn't exactly trace the cause. I don't think this is related, but line 504 of the same file subtracts 2 from both dimensions, but I think only the horizontal dimension is padded.
 
--- 

Here's a 3x6 grid of rendered images illuminated by a 3x6 envmap. Each image was rendered using an envmap where only the corresponding element of the envmap is set to 1 and the rest to 0.

![mitsuba_delta_envmap](https://user-images.githubusercontent.com/15837806/209752131-973a1e03-0e2e-4929-bdb0-9fa6a71af3d3.png)

And here's the corresponding grid but rendered using my simple ray tracer, which looks more like what I was expecting:

![my_delta_envmap](https://user-images.githubusercontent.com/15837806/209752957-4349eb6a-12a3-44d6-8600-8e6f70bdcc76.png)

## Steps to reproduce

Here's some code to render the 18 images above corresponding to a 3x6 envmap with a single value set to 1:
```
import mitsuba as mi
import numpy as np
import matplotlib.pyplot as plt

mi.set_variant('cuda_ad_rgb')

rows = 3
cols = 6

scene_dict = {
    'type': 'scene',
    'integrator': {
        'type': 'path',
        'max_depth': 2,
        'hide_emitters': True
    },
    'sensor': {
        'type': 'perspective',
        'fov': 40.0,
        'near_clip': 0.001,
        'far_clip': 10.0,
        'to_world': mi.ScalarTransform4f.look_at(origin=(0.0, 3.0, 0.0), target=(0.0,)*3, up=(1.0, 0.0, 0.0)),
        'sampler': {
            'type': 'stratified',
            'sample_count': 2048
        },
        'film': {
            'type': 'hdrfilm',
            'width': 256,
            'height': 256,
            'pixel_format': 'rgba',
        }
    },
    'sphere': {
        'type': 'sphere',
        'radius': 0.9,
        'bsdf': {
            'type': 'conductor',
        }
    }
}

scene_dict['envmap'] = {
    'type': 'envmap',
    'bitmap': mi.Bitmap(np.ones((rows, cols, 4)).astype(np.float64))
}


scene = mi.load_dict(scene_dict)
params = mi.traverse(scene)

imgs = []
for i in range(rows):
    for j in range(cols):
        envmap = np.concatenate([np.zeros((rows, cols, 3)),
                                 np.ones((rows, cols, 1))], axis=2).astype(np.float64)
        envmap[i, j, :] = 1.0

        params['envmap.data'] = envmap
        params.update()

        img = mi.render(scene, spp=128).numpy()
        imgs.append(img[:, :, :3])
```

This can be plotted as a grid using:
```
plt.figure(figsize=[12, 6])
for i in range(cols):
    for j in range(rows):
        ind = i * rows + j
        plt.subplot(rows, cols, ind + 1)
        plt.imshow(imgs[ind])
        plt.axis('off')
```

**Comment by njroussel** [comment]
Hi @dorverbin 

Quite recently, we found an indexing issue which was fixed here:https://github.com/mitsuba-renderer/mitsuba3/commit/7bf132f6ae3ec46085a7b24bdb1fcce84983425e
This hasn't made it's way into a new release yet, but you can build mitsuba locally to use it.

![image](https://user-images.githubusercontent.com/7280710/209780938-08682c2c-d162-4be0-9c26-b528138d40d0.png)

These are thenew rendered results. As you can see, some of the weird "croppings" were fixed (examples: (row 1, col 1) or (row 2, col 1).

There is still a difference when compared to your implementation. As you mentionned, we are adding an extra column in `envmap.cpp`. The purpose for this is to guarantee that there will be no visible vertical seam in the envamp - there will always be a smooth wrapping. Specifically, for inverse rendering, if your are trying to optimize an `envmap` this is most likely a property you would want. Unfortunately this also means that during `params.update()` we need to slightly change the data of the `envmap`. You can check this by printing `params['envmap.data']` after the update, the data will have changed.For more details take a look at these lines: https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/emitters/envmap.cpp#L251-L257

**Comment by njroussel** [comment]
I'll close this issue for now. If there is something else I missed, please tell me. We can always re-open this issue :smile:

**Comment by dorverbin** [comment]
This is really helpful -- I just tried it and got a perfect match with my code. Thanks a lot, @njroussel!
