### ISSUE TITLE
`VolumeGrid` scene parameter update fails with scalar variant

### ISSUE THREAD

**Issue by leroyvn** [mitsuba-renderer/mitsuba3#480]
## Summary

Updating a `VolumeGrid` scene parameter sets it to incorrect values when using a scalar variant.

## System configuration

Running on an Intel Mac, on the latest `master`.

```
System information:

  OS: 13.1
  CPU: b'Intel(R) Core(TM) i7-8700B CPU @ 3.20GHz'
  Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 17:00:52) [Clang 13.0.1 ]
  LLVM: 15.0.6

  Dr.Jit: 0.4.0
  Mitsuba: 3.1.1
     Is custom build? True
     Compiled with: AppleClang 14.0.0.14000029
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_rgb
```

## Description

I construct a simple scene consisting of a participating medium and update its extinction coefficient. When I use the `scalar_rgb` variant and update the value, it is set to zero. The problem disappears when I use the `llvm_ad_rgb` variant.

The following gist contains a minimal reproducer: https://gist.github.com/leroyvn/19e1e86fa7fa21c52df148db5deab0ea

Oddly, the issue is different on my other machine (an Ubuntu workstation with a Ryzen 9 CPU): some elements of the array are set to zero or close-to-zero values, not all of them.

## Update [2023-01-09] − Output on AMD Ryzen 9 5900X

<details>
<summary>System configuration</summary>

```
System information:

  OS: Ubuntu 22.04.1 LTS
  CPU: AMD Ryzen 9 5900X 12-Core Processor
  GPU: NVIDIA GeForce GT 730
  Python: 3.10.8 | packaged by conda-forge | (main, Nov 22 2022, 08:26:04) [GCC 10.4.0]
  NVidia driver: 470.161.03
  LLVM: 14.0.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
```

</details>

<details><summary>Terminal output</summary>

```
Constructed:

[[[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]


 [[[1. 1. 1.]
   [1. 1. 1.]]

  [[1. 1. 1.]
   [1. 1. 1.]]]]

Updated (TensorXf):

[[[[3.0252138e-13 3.0901434e-41 0.0000000e+00]
   [0.0000000e+00 5.0000000e-01 5.0000000e-01]]

  [[5.0000000e-01 5.0000000e-01 5.0000000e-01]
   [5.0000000e-01 5.0000000e-01 5.0000000e-01]]]


 [[[5.0000000e-01 5.0000000e-01 5.0000000e-01]
   [5.0000000e-01 5.0000000e-01 5.0000000e-01]]

  [[5.0000000e-01 5.0000000e-01 5.0000000e-01]
   [5.0000000e-01 5.0000000e-01 5.0000000e-01]]]]
```

</details>

![volumegrid_issue](https://user-images.githubusercontent.com/34740232/211287300-89637adf-8944-4475-bbe9-c4753bcfb911.png)

**Comment by njroussel** [comment]
Hi @leroyvn 

I took a quick look and was able to identify what was causing this bug. We're not handling self-assignments with the copy assignment operator correctly in `dr::DynamicArray` types: [copy assignment operator](https://github.com/mitsuba-renderer/drjit/blob/master/include/drjit/dynamic.h#L104-L113)


Here's a quick and dirty patch, which hopefully should be enough:
```
diff --git a/include/drjit/dynamic.h b/include/drjit/dynamic.h
index 23f774b..08486c9 100644
--- a/include/drjit/dynamic.h
+++ b/include/drjit/dynamic.h
@@ -102,6 +102,8 @@ struct DynamicArray
     }

     DynamicArray &operator=(const DynamicArray &a) {
+        if (this == &a)
+            return *this;
         if (m_free)
             delete[] m_data;
         m_data = new Value[a.m_size];
```

(We're quite busy with other tasks at the moment and I don't feel comfortable pushing this fix without adding a few more tests and checking if there aren't any other blatant bugs in this class.
I should have more time in a couple of weeks to "properly" fix this.)

**Comment by njroussel** [comment]
I'll keep this issue open, to not lose track of it until the a commit/fix is pushed.

**Comment by leroyvn** [comment]
Hi @njroussel, any news on that front? I've been the patch you suggested since a bit more than a month, it seems to do the job.

**Comment by njroussel** [comment]
I've pushed a fix in this commit: https://github.com/mitsuba-renderer/mitsuba3/commit/b253ddee05ca6dd09cc72eeb0713693e9dbb8d61 (it's slightly different). 
Thanks for the reminder :)

**Comment by leroyvn** [comment]
Thank you very much!
