### ISSUE TITLE
Cannot import fastsweep in 3.2.0

### ISSUE THREAD

**Issue by Dustinpro** [mitsuba-renderer/mitsuba3#493]
## Summary

In the latest version 3.2.0, import fastsweep will report ImportError: undefined symbol: jit_var_new_scatter
It does not happen to mitsuba 3.1.1

## System configuration

System information:

  OS: Ubuntu 20.04
  Python version: 3.8, 3.10
  LLVM version: 12.0.0
  CUDA version: 11.7.99
  NVidia driver: 520.61.05

  Dr.Jit version: 0.4.0
  Mitsuba version: 3.2.0

## Steps to reproduce

1. import fastsweep

**Comment by njroussel** [comment]
Hi @Dustinpro 

`fastsweep` wasn't released with strict enough dependency requirements: it is no longer compatible with the newer Dr.Jit version (0.4.0).

You can either downgrade your Mitsuba/Dr.Jit verisons, or build Mitsuba/fastsweep locally ([fastsweep build instructions](https://github.com/rgl-epfl/fastsweep#installation)).
