### ISSUE TITLE
rgb2spec.h error: unknown type name '__m512' when building on Xeon Phi Knights Landing

### ISSUE THREAD

**Issue by rrubberr** [mitsuba-renderer/mitsuba3#496]
## Summary

When attempting to build mitsuba3, the build fails with the following error:

```
FAILED: src/render/CMakeFiles/mitsuba-render.dir/srgb.cpp.o 
/usr/bin/c++ -DLITTLE_ENDIAN -DMI_BUILD_MODULE=MI_MODULE_LIB -DMI_ENABLE_EMBREE=1 -DMI_ENABLE_LLVM=1 -I../include -I../ext/tinyformat -Iinclude -I../ext/embree/include -I../ext/rgb2spec -I../ext/drjit/ext/drjit-core/ext/nanothread/include -I../ext/embree/kernels/../include -I../ext/drjit/include -I../ext/drjit/ext/drjit-core/include -fdiagnostics-color=always -O3 -DNDEBUG -flto -fno-fat-lto-objects -fPIC -fvisibility=default   -fno-math-errno -ffp-contract=fast -fno-trapping-math -march=native -Wall -Wextra -Wno-unused-local-typedefs -Wdouble-promotion -fno-strict-aliasing -std=gnu++17 -MD -MT src/render/CMakeFiles/mitsuba-render.dir/srgb.cpp.o -MF src/render/CMakeFiles/mitsuba-render.dir/srgb.cpp.o.d -o src/render/CMakeFiles/mitsuba-render.dir/srgb.cpp.o -c ../src/render/srgb.cpp
In file included from ../src/render/srgb.cpp:6:
../ext/rgb2spec/rgb2spec.h:51:4: error: ‘__m512’ does not name a type; did you mean ‘__m128’?
   51 |    __m512 rgb2spec_eval_avx512(float coeff[RGB2SPEC_N_COEFFS], __m512 lambda);
      |    ^~~~~~
      |    __m128
```

System information:

  OS: Debian 11
  CPU: Xeon Phi 7210
  GPU: NVIDIA TITAN RTX
  Python version: 3.9.2
  LLVM version: 11.0
  CUDA version: 11.2
  NVidia driver: 470.161.03

  Dr.Jit version: Latest
  Mitsuba version: Latest
     Compiled with: CLANG 13.0.1
     Variants compiled: `"scalar_rgb", "scalar_spectral", "llvm_rgb", "llvm_spectral"` -however, the build will fail with any variants selected.

## Description

The issue is related to the Dr. Jit requirement expressed in `fwd.h` here:

```
#  if defined(__AVX512F__) && defined(__AVX512CD__) && defined(__AVX512VL__) && defined(__AVX512DQ__) && defined(__AVX512BW__)
```
Which in turn enables a selection of CLANG header files in `packet_intrin.h`:

```
#  if defined(DRJIT_X86_AVX512)
#    include <avx512fintrin.h>
#    include <avx512vlintrin.h>
#    include <avx512bwintrin.h>
#    include <avx512cdintrin.h>
#    include <avx512dqintrin.h>
#    include <avx512vldqintrin.h>
#    include <avx512vlbwintrin.h>
```

Knights Landing supports only AVX 512 F, CD, ER, and PF; not VL, DQ, and BW which were introduced with Skylake X and Cannon Lake series processors. Mitsuba2 compiles on this system with functional AVX 512 support:

`INFO  main  [mitsuba.cpp:194] Mitsuba version 2.0.0 (master[563f923c], Linux, 64bit, 256 threads, 16-wide SIMD)`

...as it seems to have required only AVX512 F. 

Since the VL, DQ, and BW extensions were included with Skylake X and above, I believe only Knights Landing series processors are impacted.

## Steps to reproduce

1. Attempt to compile mitsuba3 on a system with AVX512F and CD, but without VL, DQ, and BW support.

**Comment by wjakob** [comment]
With the cancellation of KNL, it made no sense to further invest into this platform and we dropped support a while ago. You might be able to get it to work by forcing it to a lower architecture, e.g. by running cmake with `"-DMI_NATIVE_FLAGS=-march=haswell"`.

Note that the LLVM backend might still use the AVX512F parts, it is quite good at taking the IR that Mitsuba emits and compiling it to various architectures.
