### ISSUE TITLE
Animation from the SIGGRAPH 2012 presentation 

### ISSUE THREAD

**Issue by ibaris** [mitsuba-renderer/mitsuba3#500]
Hello,

do you offer the code to the animation from the [SIGGRAPH 2012](https://www.cs.cornell.edu/projects/manifolds-sg12/) presentation somewhere? The visualization is brilliant.  

<img src="https://user-images.githubusercontent.com/15630368/212889416-5e17a136-250a-4242-9e0b-1269cd623e8b.png" width="200">

**Comment by wjakob** [comment]
Please keep SIGGRAPH issues for actual Mitsuba problems, we have a discussion tab for such questions.

Regarding your question, let me point you to a much fancier version of this visualization courtesy of @tizian : https://github.com/tizian/manifold-visualizer
