### ISSUE TITLE
Unreferenced property "["eta"]" in bsdf plugin of type "roughplastic"

### ISSUE THREAD

**Issue by EsteBran** [mitsuba-renderer/mitsuba3#517]
## Summary

Trying to render an xml file from commandline results in error when handling the `eta` property in the roughplastic bsdf

## System configuration

System information: Thinkpad p51

  OS: Windows-10
  CPU: Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
  Python: 3.10.2 (tags/v3.10.2:a58ebcc, Jan 17 2022, 14:12:15) [MSC v.1929 64 bit (AMD64)]
  CUDA: 11.3.58
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: MSVC 19.34.31937.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
  

## Description

I have an xml scene file with all the models and envmap paths in there. When I try to render it by running `mitsuba  <xml filename>` from a terminal spawned within the same directory I get this error:

```
PS C:\_________\Desktop\________\output\material\roughplastic> mitsuba .\1620498_C_20221130_145924_850_fixed_es_0.xml
2023-02-01 15:11:33 INFO  main  [mitsuba.cpp:332] Mitsuba version 3.2.0 (master[8ee2606], Windows, 64bit, 8 threads, 8-wide SIMD)
2023-02-01 15:11:33 INFO  main  [mitsuba.cpp:333] Copyright 2022, Realistic Graphics Lab, EPFL
2023-02-01 15:11:33 INFO  main  [mitsuba.cpp:334] Enabled processor features: cuda llvm avx sse4.2 x86_64
2023-02-01 15:11:33 INFO  main  [xml.cpp:1433] Loading XML file ".\1620498_C_20221130_145924_850_fixed_es_0.xml" with variant "scalar_rgb"..

Caught a critical exception: [xml.cpp:1161] Error while loading ".\1620498_C_20221130_145924_850_fixed_es_0.xml" 
(near line 37, col 5): unreferenced property "["eta"]" in bsdf plugin of type "roughplastic"
```

## Steps to reproduce

This is what the bsdf field looks like in the xml file:

```
 <bsdf type="roughplastic" id="bsdf">
      <rgb name="specular_reflectance" value="0.240841, 0.240841, 0.240841"/>
      <rgb name="diffuse_reflectance" value="0.070723, 0.070723, 0.070723"/>
      <float name="alpha" value="0.774925"/>
      <float name="eta" value="0.815872"/>
   </bsdf>
```

**Comment by hesom** [comment]
I believe eta is only an internal property of roughplastic and gets computed as eta = int_ior / ext_ior. This is why it's separately listed as a "state parameter" in the docs.

**Comment by EsteBran** [comment]
I changed "eta" to "int_ior" and that fixed the error and gave me the correct render. Thanks!

**Comment by njroussel** [comment]
That is indeed correct @hesom :+1:
