### ISSUE TITLE
No constructor of mi.MonteCarloIntegrator in python

### ISSUE THREAD

**Issue by class255** [mitsuba-renderer/mitsuba3#519]
## Summary

I cannot inherit mi.MonteCarloIntegrator class in python. I got a TypeError with message "No constructor defined!".

## System configuration

System information:

  OS: Windows 11 (I'm actually using Windows 11, but `python -m mitsuba.sys_info` prints "Windoes-10")
  CPU: 12th Gen Intel(R) Core(TM) i9-12800K, 3.18GHz with 24 cores
  GPU: NVIDIA GeForce GTX 1080Ti
  Python version: 3.10.8
  LLVM version: N/A (-1.-1.-1)
  CUDA version: 11.7.99
  NVidia driver: 516.94

  Dr.Jit version: 0.4.0
  Mitsuba version: 3.2.0
     Compiled with: MSVC 19.34.31937.0 (I installed by `pip install`)
     Variants compiled: default four variants

## Description

Dear community,

I am trying to reproduce `mitsuba3/blob/master/src/integrators/path.cpp` in python to understand how to implement mitsuba integrator plugin in python.
However, I failed to inherit `mi.MonteCarloIntegrator` class in python, while the original C++ implementation of `PathIntegrator` inherits `MonteCarloIntegrator`.
For details, when I run the following code:
```python
import mitsuba as mi

mi.set_variant('scalar_rgb') # It fails.
class PracticeIntegrator(mi.MonteCarloIntegrator): # It fails.
# mi.set_variant('cuda_ad_rgb') # It works.
# class PracticeIntegrator(mi.ad.integrators.common.RBIntegrator): # It works.
    def __init__(self, props=mi.Properties()):
        print("Constructor start")
        super().__init__(props=props)
        print("Constructor end")
        
mi.register_integrator("practice", lambda props: PracticeIntegrator(props))

if __name__ == "__main__":
    pint = PracticeIntegrator()
```
then I get the following restuls.
```
Constructor start
Exception has occurred: TypeError
PracticeIntegrator: No constructor defined!
  File "C:\{my local path}\quastion_integrator_constructor.py", line 9, in __init__
    super().__init__(props=props)
  File "C:\{my local path}\quastion_integrator_constructor.py", line 15, in <module>
    pint = PracticeIntegrator()
TypeError: PracticeIntegrator: No constructor defined!
```

However, I succeeded to inherit the constructor of `mi.ad.integrators.common.RBIntegrator` in AD variants. In the above code, commenting out Lines 3 and 4 uncommenting Lines 5 and 6 works well without any error.

I finally succeeded to porting `path.cpp` into a python code by inheritting `mi.ad.integrators.common.RBIntegrator` instead of `mi.MonteCarloIntegrator`, but it only works with AD variants.
Thus, I still do not know how I can implement integrator plugin in python for scalar non-AD variant.
Is there any other way to inherit an appropriate integrator class? or does not the current version of mitsuba support custom integrator plugins for scalar variants in python?

Thanks.

**Comment by ziyi-zhang** [comment]
Hi @class255 
RBIntegrator inherits from ADIntegrator. They are both defined in python, and their base class in cpp is `mi.SamplingIntegrator` (integrator_v.cpp). `MonteCarloIntegrator` is not properly exposed in the binding (it's almost identical with samplingintegrator).

Scalar mode does not have AD support. It should work if we inherit from `mi.SamplingIntegrator`, but i am not certain. Hope this helps.

**Comment by class255** [comment]
Thanks to reply!

Now I solved the problem by inheriting `mi.SamplingIntegrator` instead and modifying Line 9 `super().__init__(props=props)` to use positional argument, as `super().__init__(props)`.
