### ISSUE TITLE
Conversion of `Spectrum` by `@wrap_ad()` in the use of BSDFs alone

### ISSUE THREAD

**Issue by hiroaki-santo** [mitsuba-renderer/mitsuba3#520]
## Summary

I wish to use a (polarized) BRDF function implemented in Mitsuba alone without `render()` function in conjunction with PyTorch.  I wrote the following code, but there is a problem with casting `spectrum` returned from `bsdf.eval()` to DrJit's tensor.

When I just return the `spectrum` to the `warp_ad()`, I get a type error.
When I cast `spectrum` to `mi.TensorXf`, the output is correct but is not differentiable.

Do we have a way of casting `spectrum` to PyTorch tensor in a differentiable manner?
Thank you in advance.

## System configuration

  CPU: Intel(R) Core(TM) i9-10980XE CPU @ 3.00GHz
  GPU: Quadro RTX 8000
  Python: 3.8.13 (default, Mar 28 2022, 11:38:47) [GCC 7.5.0]
  NVidia driver: 520.61.05
  CUDA: 11.0.221
  LLVM: 12.0.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? True
     Compiled with: Clang 9.0.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
        scalar_rgb_polarized
        scalar_spectral_polarized
        cuda_ad_rgb_polarized
        cuda_ad_spectral_polarized

## Code

```
import drjit as dr
import mitsuba as mi
import torch

mi.set_variant('cuda_ad_rgb_polarized')
device = "cuda"

bsdf = mi.load_dict(
    {"type": "pplastic",
     "diffuse_reflectance": {
         'type': 'rgb',
         'value': [0.5, 0.5, 0.5]
     },
     }
)

params = mi.traverse(bsdf)


@dr.wrap_ad(source="torch", target="drjit")
def bsdf_eval(wi, wo, diffuse_color):
    params["diffuse_reflectance.value"] = dr.unravel(mi.Color3f, dr.ravel(diffuse_color))
    params.update()

    ctx = mi.BSDFContext()
    si = dr.zeros(mi.SurfaceInteraction3f)
    si.wi = dr.unravel(mi.Vector3f, dr.ravel(wi))
    spectrum = bsdf.eval(ctx, si, dr.unravel(mi.Vector3f, dr.ravel(wo)))

    # return spectrum # TypeError: wrap_ad(): differential input arguments should be Dr.Jit tensor!
    return mi.TensorXf(spectrum)  # no gradient?


wi = torch.rand(size=(5, 3)).to(torch.float32).to(device)
wo = torch.rand(size=(5, 3)).to(torch.float32).to(device)

diffuse_color_torch = torch.ones((3,), dtype=torch.float32, device=device, requires_grad=True)

spectrum = bsdf_eval(wi, wo, diffuse_color_torch)

loss = torch.sum(spectrum)
loss.backward()
print(diffuse_color_torch.grad) # all zero

```

**Comment by njroussel** [comment]
Hi @hiroaki-santo 

This is actually not related to the `@dr.wrap_ad` decorator, but just how the casting/construction of `mi.TensorXf` objects. What is happening here is that `mi.TensorXf(spectrum)` is using the `__array_interface__` property of the `Color3f` object to built the tensor. Unfortunately, there is no gradient tracking trough that interface.

Here's an example of how to keep gradient tracking across the `Color3f` -> `TensorXf` conversion:
```python
import mitsuba as mi
import drjit as dr

mi.set_variant('cuda_ad_rgb')

r = mi.Float(0)
g = mi.Float(1)
b = mi.Float(2)
dr.enable_grad(b)
dr.set_grad(b, 1)
color = mi.Color3f(r, g, b)

tensor = dr.zeros(mi.TensorXf, shape=(3, 1))
tensor[0] = color.x
tensor[1] = color.y
tensor[2] = color.z

dr.forward(b, dr.ADFlag.ClearNone)

print(f"{color=}")                 # color=[[0.0, 1.0, 2.0]]
print(f"{dr.grad(color)=}")        # dr.grad(color)=[[0.0, 0.0, 1.0]]
print(f"{tensor.array=}")          # tensor.array=[0.0, 1.0, 2.0]
print(f"{dr.grad(tensor.array)=}") # dr.grad(tensor.array)=[0.0, 0.0, 1.0]
```
