### ISSUE TITLE
'sensor.to_world' Optimization - Not Differentiable

### ISSUE THREAD

**Issue by szanykmclean** [mitsuba-renderer/mitsuba3#521]
System information:

  OS: Ubuntu 20.04.5 LTS
  CPU: Intel(R) Xeon(R) CPU @ 2.20GHz
  GPU: NVIDIA A100-SXM4-40GB
  Python: 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
  NVidia driver: 510.47.03
  CUDA: 11.2.152
  LLVM: 12.0.0

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

Hello, I am running into an issue with trying to run an optimization very similar to the tutorial here: https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/gradient_based_opt.html

(running on Google Colab)

However, I am trying to optimize the camera `sensor.to_world` parameter. Basically, I am trying to figure out the location settings of the camera for some image based on a reference image.
1. My basic code is here below. I am using teapot, and have two different rendered images, one is my `image_ref` and the other is `image_init`. I am trying to optimize image init so that at the end of optimization loop, the camera will move to the same location as it is in image ref.
<img width="869" alt="Screenshot 2023-02-02 at 7 20 35 PM" src="https://user-images.githubusercontent.com/17147267/216488277-d5d1926f-6c59-4101-b365-db744755c10f.png">

2. The issue I am having is this: basically I am not able to use this key = 'sensor.to_world' in params[key] as the optimization param. The params['sensor.to_world'] is a <class 'mitsuba.cuda_ad_rgb.Transform4f'> object which is not differentiable and not a float. I know you have recently updated the codebase to allow for differentiation w.r.t. sensor.to_world parameters here: https://github.com/mitsuba-renderer/mitsuba3/issues/248 however, I am wondering if there is either a bug or I did something incorrect in my setup?
<img width="1014" alt="Screenshot 2023-02-02 at 7 21 50 PM" src="https://user-images.githubusercontent.com/17147267/216488425-8f8b85f5-1440-46cc-8ce5-c871ece8a89a.png">

From what I understand, drjit data types are differentiable, but the mitsuba.cuda_ad_rgb.Transform4f object doesn't seem to be, so I have been trying to convert it to somethat that can be optimized over, however with no luck.
Thanks for your help!

Please see full src code attached.
[mitsuba_camera_optim.ipynb.zip](https://github.com/mitsuba-renderer/mitsuba3/files/10574749/mitsuba_camera_optim.ipynb.zip)
[scenes-20230202T225837Z-001.zip](https://github.com/mitsuba-renderer/mitsuba3/files/10574750/scenes-20230202T225837Z-001.zip)

**Comment by szanykmclean** [comment]
I have since figured out to take the `params[key].matrix` attribute and pass the Matrix4f object into the optimizer, however, I am also trying to flatten the matrix using ravel so that the optimization will run correctly, however, ravel does not seem to be working. Any ideas on this?

**Comment by szanykmclean** [comment]
figured it out. closing issue.

**Comment by VijayVikasM** [comment]
Hi,I am working on something similar and I would like to know how you have solved this issue.
