### ISSUE TITLE
Albedo aov rendering crash

### ISSUE THREAD

**Issue by NicNel** [mitsuba-renderer/mitsuba3#537]
## Summary
Hi! It seems that 'aov' integrator, with enabled albedo, leads to rendering crashes in cases when the scene environment is visible through the camera. 

## System configuration
System information:

  OS: Windows 10
  CPU: intel core i5
  GPU: GTX 1070

  Mitsuba version: current master branch
     Compiled with: Visual Studio 2022
     Variants compiled: scalar_rgb, scalar_spectral, cuda_spectral

## Description
Access to SurfaceInteraction3f properties in the albedo sampling method fails in cases when ray has no valid interaction with the surface.
Possible code to fix this issue:

```
case Type::Albedo: {
                    Color3f rgb(0);
                    if (dr::any_or<true>(si.is_valid())) 
                    {
                        BSDFPtr m_bsdf = si.bsdf(ray);
                        Spectrum spec = m_bsdf->eval_diffuse_reflectance(si, active);
                        rgb = spectrum_to_color3f(spec, ray, active);
                    }
                        
                    *aovs++ = rgb.r();
                    *aovs++ = rgb.g();
                    *aovs++ = rgb.b();
                    }
                    break;
```

## Steps to reproduce
1. Choose aov integrator with enabled albedo 
2. Set the direction of the camera so that the environment map could be visible directly
3. Run mitsuba in scalar_rgb or scalar_spectral mode

**Comment by njroussel** [comment]
Hi @NicNel 

Thank you very much for the detailed bug report!
This was fixed this in the following commit: https://github.com/mitsuba-renderer/mitsuba3/commit/b876a4f5fa40985078ac87daacd502bbcefa9faf
