### ISSUE TITLE
Cannot access element of TensorXf and convert tensor slice to Point3f

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#541]
System information:
OS: Windows-10
CPU: Intel64 Family 6 Model 16 Stepping 5, GenuineIntel
GPU: NVIDIA RTX A4000
Python: 3.9.7
NVidia driver: 517.40
CUDA: 10.0.130
LLVM: -1-1-1
DrJit: 0.4.0
Mitsuba: 3.2.0, no custom build, MSVC 19.34.31937.0, variants: scalar_rgb, scalar_spectral, cuda_ad_rgb, llvm_ad_rgb

Hi, 

I am using variant cuda_ad_rgb. I created a mi.TensorXf from a numpy tensor of shape (90,90,180,3). I can convert back the TensorXf to numpy with .numpy() and check that it is correctly created. However, I am stuck accessing values from TensorXf and transforming [0,0,0,:] entry to mi.Point3f. I looked at the drjit documentation, mitsuba documention, and methods of TensorXf using pprint, but could not find how. Could you please show me what is the correct way of accessing elements from TensorXf and where I can find the information?

Checking that elements from A are similar (up to float precision) as T is ok:
```python
A = np.random.rand(90,90,180,3)
T = mi.TensorXf(A.ravel().astype('float32'), shape=(90,90,180,3))
```
None of the access below give me the value. Some give `TensorXf(shape=(...))` and other calls just don't work.

```python
print('value:', T[0,0,0,:]) # TensorXf(shape=(3,))
print('value:', T[0,0,0,0]) # TensorXf(shape=(0))
print('value:', T.__getitem(0)__.__getitem(0)__.__getitem(0)__.__getitem(0)__) # same as above
print('value:', T[0][0][0][0]) # same as above
print('value:', T[0][0][0][0].data_()) # large value unrelated to true entries
print('value:', T[0][0][0][0].Value()) # 0.0 for any entry
print('value:', T[0,0,0,0][0]) # too many indices
print('value:', dr.slice(T,[0,0,0,0])) # has not attributes entry
print('value:', mi.Point3f(T[0,0,0,:]) # Point3f constructor expects: 1 or 3 values of type "Float"...
```

Thank you

**Comment by njroussel** [comment]
Hi @osylum 

This is a bit unfortunate, it's missing in the Dr.Jit reference/documentation. The `TensorXf.array` property is the underlying flat `Float` object used as storage for the tensor. So this is the way to do get a `Point3f` for example:
```python
A = np.random.rand(90,90,180,3)
T = mi.TensorXf(A.ravel().astype('float32'), shape=(90,90,180,3))
point = mi.Point3f(T[0, 0, 0, :].array)
```

**Comment by osylum** [comment]
Thank you very much
