### ISSUE TITLE
Code not transparent from change in variant from cuda_ad_rgb to scalar_rgb variant

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#542]
## Summary

Results change strongly when changing variant.

## System configuration

System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
  GPU: NVIDIA RTX A4000
  Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 517.40
  CUDA: 10.0.130
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.0
  Mitsuba: 3.2.0
     Is custom build? False
     Compiled with: MSVC 19.34.31937.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Hi,

When I switch to scalar_rgb from cuda_ad_rgb, I get very different behaviors, which make the code not transparent to change in those variants. More generally, it seems that when I use scalar_rgb, I can't use array operations. Below is an example with dr.linspace that does not behave as I would expect from a numpy analog function. I might not understand the usage of the scalar_rgb version. In case this is the expected result, could you please explain when to use scalar_rgb?

## Steps to reproduce

import mitsuba as mi
mi.set_variant("cuda_ad_rgb")
a = dr.linspace(mi.Float, 0., 1., 10)
print(a) # result is the expected numpy equivalent array

import mitsuba as mi
mi.set_variant("scalar_rgb")
a = dr.linspace(mi.Float, 0., 1., 10)
print(a) # result is 0.0

**Comment by njroussel** [comment]
Hi @osylum 

I'd recommend you take a look at [this documentation page on variants](https://mitsuba.readthedocs.io/en/stable/src/key_topics/variants.html#part-1-computational-backend) and also the [introductory page for Dr.Jit](https://drjit.readthedocs.io/en/latest/intro.html).

A fundamental difference between `numpy` and `drjit` is that that `numpy` is operating on arrays: multiple objects. On the hand, `drjit` is operating on vectorized objects: single objects that happen to have many (#vectorization-width) values underneath it.
The scalar mode reduces the vectorization width to 1, so now you are operating on single object/values. A `mi.Float` in this mode is effectively just one single `float`.

**Comment by osylum** [comment]
I get it, thank you. It was a bit confusing on functions like linspace though.

**Comment by njroussel** [comment]
Yes, I've also hit that wall a few times :sweat:
