### ISSUE TITLE
Struct converter fails in non-vectorized mode

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#544]
Hi, 

This is somewhat of a niche issue I ran into today: if Mitsuba is run without vectorization flags, the struct converter fails to properly convert the rendered image and the output image when rendering the Cornell box is black. This can be reproduced by running

```
cmake .. -GNinja -DMI_NATIVE_FLAGS=""
ninja
mitsuba  ../resources/data/scenes/cbox/cbox.xml

```

So there is some kind of inconsistency between AVX and non-AVX mode in struct.cpp. A few tests in test_struct.py fail as well, which could help localize the issue. 

I don't really have a need to fix this on our end for now, but it would probably be good to either fix this code path or just disable the struct JIT for non-avx machines (i.e., CPUs that are >10 years old at this point).

Best,
Delio

**Comment by njroussel** [comment]
Hi @dvicini 

I've pushed a fix https://github.com/mitsuba-renderer/mitsuba3/commit/8e441f0361d6def2c6f101fd8243d8646d57b9be.

The issue was even "worse": we were using `asmjit` to generate `SSE` instructions which are also obviously not available. I'm actually a bit surprised that this runs just fine :exploding_head:.

**Comment by dvicini** [comment]
Hi @njroussel 

Thanks for taking a look. Indeed, at least SSE instructions need to be available. However, I don't think that fixes the issue. I think the reason it worked anyway is that all that matters at runtime is the actual hardware, not the flags specified to the compiler. 

By running the following cmake command, the JIT compiler remains enabled (since SSE instructions are available), but doesn't use the AVX code path:
`cmake .. -GNinja -DMI_NATIVE_FLAGS="-march=westmere" `

So clearly something is broken in the SSE code path. I spend some time today trying to isolate it. The tests that fail are test14_weight, test16_alpha_1 and test19_alpha_4. I think it might be somehow related to some of the logic around L1344. If I comment out this part, the test14_weight at least passes. I couldn't quite isolate why this code would fail though.

**Comment by njroussel** [comment]
I see, I wrongly assumed that `asmjit` would disable instructions depending on the flags used to compile.

I took a quick stab as this. Indeed, it seems related to the `blendvps` instruction (L1347 and L1391). Not immediately obvious what's wrong here. I'll take another look tomorrow.

**Comment by njroussel** [comment]
@dvicini PR #546 should fix this issue. It passes our CI, but before I merge it, could I ask you to see if that branch is causing any other issues on your end? Your build system seems to be testing a larger set of architectures than ours.

**Comment by dvicini** [comment]
Thanks a lot for looking into this. I also saw that the asmjit dependency was pretty stale, so either way I very much appreciate the upgrade :). It seems to work on my end as far as I can tell. I definitely would appreciate this PR being merged even for the upgrade of asmjit itself
