### ISSUE TITLE
direct_reparam integrator missing

### ISSUE THREAD

**Issue by ShnitzelKiller** [mitsuba-renderer/mitsuba3#555]
I am trying to follow the tutorial on [object pose estimation](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/object_pose_estimation.html), have found that the required integrator that uses reparameterization to handle silhouette discontinuities does not exist. The link in the page does not work, as there is no entry in the API reference. It is listed in the plugin reference, but when I attempt to load a scene with a direct_reparam integrator in it, I get the error message
```
RuntimeError: ​[PluginManager] Plugin "direct_reparam" not found!
```
I cannot find any reference in the docs to additional downloads for plugins that are not included by default. I cannot find the name of this integrator in the mitsuba3 source code. I do not know where to find these integrators. Has its functionality been relegated to a setting of one of the existing integrators?

**Comment by njroussel** [comment]
Hi @ShnitzelKiller 

In the future, could you please fill out the issue template when opening new issues? It helps us avoid some back-and-forth about some very basic questions on your environment/setup.

The link is unfortunately wrong :slightly_frowning_face:, it should link to the plugin reference: https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_integrators.html#reparameterized-direct-integrator-direct-reparam.

The `direct_reparam` integrator should be available in any `*_ad_*` variant. Does this command report the same error message?
```
python -c "import mitsuba as mi; mi.set_variant('llvm_ad_rgb');mi.load_dict({'type': 'direct_reparam'})"
```

**Comment by ShnitzelKiller** [comment]
I see. Using the cuda_ad_rgb variant works. I had altered the tutorial code to use the scalar_rgb variant since I couldn't get llvm to be detected.
