### ISSUE TITLE
Optimization crashes

### ISSUE THREAD

**Issue by h-OUS-e** [mitsuba-renderer/mitsuba3#557]
## Summary

Hello, I am trying to run caustic optimization, but it crashes at certain settings and after a handful of iterations. I temporarily solved the issue by using a lower 'render_resolution' of my reference image, but the issue happens when I have a render_resolution of 256x256, at iteration 900. At iteration 512x512, it just crashed quickly before rendering, and that might mean that my system doesn't have enough memory, but I was wondering why would the optimization for 256 at least crash after running the through 900 iterations. 

The above was on my own code, but I also tried to replicate it on the caustic optimization tutorial. I didn't change anything in the tutorial except that I bumped up the render_resolution to 256x256. It also somehow crashed at iteration 900. My code setup is almost identical to the tutorial though.

## System configuration

System information:

OS: Windows-10
CPU: Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
GPU: NVIDIA GeForce RTX 3060 Laptop GPU
Python: 3.10.9 | packaged by conda-forge | (main, Jan 11 2023, 15:15:40) [MSC v.1916 64 bit (AMD64)]
NVidia driver: 512.78
LLVM: -1.-1.-1

Dr.Jit: 0.4.1
Mitsuba: 3.2.1
   Is custom build? False
   Compiled with: MSVC 19.34.31942.0
   Variants:
      scalar_rgb
      scalar_spectral
      cuda_ad_rgb
      llvm_ad_rgb

The message I get following the error is: "jit_flush_malloc_cache(): Dr.Jit exhausted the available memory and had to flush its allocation cache to free up additional memory. This is an expensive operation and will have a negative effect on performance. You may want to change your computation so that it uses less memory. This warning will only be displayed once."

Although earlier before upgrading mitsuba and drjit, I was getting the error: "Critical Dr.Jit compiler failure: jit_var(########): unknown variable! "

**Comment by njroussel** [comment]
Hi @h-OUS-e 

You indeed do not have enough memory :frowning_face:  

The reason why this is happening exactly at iteration 900, is because at iterations 700 and 900 we double  the `spp` count. Take a close look at [this section ](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/caustics_optimization.html#6.-Running-the-optimization) of the tutorial.
