### ISSUE TITLE
set_size removed from Film's python interface?

### ISSUE THREAD

**Issue by a3ahmad** [mitsuba-renderer/mitsuba3#574]
## Summary

The set_size method has been removed from the python version of the Film interface, was it intended?

The differentiable SDF codebase relies on this method.

**Comment by Speierers** [comment]
Hi @a3ahmad ,

Yes indeed the `set_size` method was removed from the `Film` python API in an effort to make Mitsuba objects immutable except when using the traverse mechanism. The size of the film should be changed as follow in Python:

```python
    params = mi.traverse(scene)
    params['camera.film.size'] = new_size
    params.update()
```
