### ISSUE TITLE
Choice of Reconstruction filter and film pixel format affect Depth Integrator

### ISSUE THREAD

**Issue by kyrollosyanny** [mitsuba-renderer/mitsuba3#575]
## Summary
Im using the Depth integrator to get the depth buffer of a scene (i.e. distance along optical axis from camera to the objects in the scene).  I noticed that the ```rfilter``` property affects the values stored in the depth buffer. It seems to be doing the filter after accumulating the depth.  **What is the best rfitler to get pure depth values?** In addition,  **what the best ```pixel_format``` is for saving the depth buffer?**. Currently, Im currently using ```rgb```. **Changing pixel format affects the results. Would luminance be better? or```xyz``` format?** I attached a small example below to show the issue. Changing ```rfilter``` between box, tent and others would produce different depth map results

Thanks a lot for the help and the great tool!

## System configuration
Mitsuba version: .3

## Steps to reproduce

```
<scene version="3.0.0">
    <integrator type="depth">
        <!-- <integer name="max_depth" value="10" /> -->
    </integrator>
    <sensor type="perspective">
    <float name="fov" value="95" />
    <float name="near_clip" value="0.1" />
    <float name="far_clip" value="6.4" />
<!--     <transform name="to_world">
        <lookat origin="0 , 0, 0" target="0, 0, 1" up="0, 1, 0" />
        <scale x="-1" />
        <translate x="-0.032" />
    </transform> -->
    <sampler type="multijitter">
        <integer name="sample_count" value="64" />
    </sampler>
    <film type="hdrfilm">
        <integer name="width" value="100" />
        <integer name="height" value="100" />
        <string name="file_format" value="openexr" />
        <string name="pixel_format" value="rgb" />
        <rfilter type="box" />
    </film>
</sensor>
<bsdf type="roughdielectric"/>
<shape type="cube" id="cube">
    <transform name="to_world">
        <scale value="0.025" />
        <!-- <rotate x="1" angle="45" /> -->
        <!-- <rotate y="1" angle="45" /> -->
        <translate z="0.6" x="0" />
    </transform>
</shape>
</scene>
```

**Comment by njroussel** [comment]
The `box` reconstruction filter is what you're looking for. It will only average all samples in a pixel.

As for the pixel format, you'll want to leave `rgb`, that's the "raw" format -- sample values will not be transformed.

The easiest way to debug these kind of things is to use an `orthographic` sensor, you'll have an exact expectation of what depths you're supposed to see in your scene. For what it's worth, the `aov` integrator can also emit `depth` maps and you won't have to worry about the pixel format.

**Comment by kyrollosyanny** [comment]
Hi @njroussel, I have a couple quick follow up questions:

1.  Using ```orthographic``` sensor and a ```box``` reconstruction filter.  I didnt get the correct answer for my simple example of a cube0.47m away. I got something like the image attached below. The bright yellow is 0.475 but you can see the rest of the pixels of the cube have different depth values. This suggest that the filter is still sampling nearby pixels. Would you have a suggestion on how to fix that?
<img width="198" alt="image" src="https://user-images.githubusercontent.com/14105969/223223253-52b219f2-ce69-434b-9bee-2b2181e585f5.png">


2. In ```orthographic``` sensor, the depth value did not change as I moved the object in X and Y but same depth. Which is the behavior I expect. However, trying this with ```perspective``` sensor, the value for the depth changed as the cube moved in X and Y. For example, in the test above, is the cube translation is ```<translate z="0.6" x="0.05" y="-0.01" />```, I get very different numbers for the depth. in ```perspective``` but the correct value in ```orthographic```. Would you know how to fix that?

Thanks a lot for your answers and help :)

**Comment by njroussel** [comment]
1. Are you doing 1 spp renders? The XML you posted will render 64 samples per pixel, so unless your cube perfectly aligns with your pixel grid, the edges of the cube will be "blurry" as some samples (for a single pixel) will hit the shape and others will hit the background.
The value difference (0.47 -> 0.475)  however is surprising, could you please provide the exact scene description?

2. I'm not quite sure I understand. This isn't really surprising is it? The distance from the the pinhole (origin) of the perspective camera to any point on the cube depends on the X and Y coordinates too.

**Comment by kyrollosyanny** [comment]
Hi @njroussel,   

1.  Thanks for explaining the effect of samples per pixels. It makes sense why more samples can result in blurry edges. Is the best practice here to use ```spp=1``` and ```box filter``` to get the depth buffer? In addition, does the choice of the sampler matter at all? Im currently using ```multijitter``` ? Please find the scene description attached below, it looks much better now with your suggestion 
```
<scene version="3.0.0">
    <integrator type="aov">
        <string name="aovs" value="dd.y:depth,nn:position"/>
    </integrator>
    <sensor type="perspective">
    <float name="fov" value="95" />
    <float name="near_clip" value="0.1" />
    <float name="far_clip" value="6.4" />
<!--     <transform name="to_world">
        <lookat origin="0 , 0, 0" target="0, 0, 1" up="0, 1, 0" />
        <scale x="-1" />
        <translate x="-0.032" />
    </transform> -->
    <sampler type="multijitter">
        <integer name="sample_count" value="1" />
    </sampler>
    <film type="hdrfilm">
        <integer name="width" value="2000" />
        <integer name="height" value="2000" />
        <string name="file_format" value="openexr" />
        <string name="pixel_format" value="rgb" />
        <!-- <rfilter type="tent" /> -->
        <rfilter type="box"/>
<!--         <rfilter type="gaussian">
             <float name="stddev" value="0.01"/>
        </rfilter> -->
    </film>
</sensor>
<bsdf type="diffuse" id="checkerboard_png">
    <texture type="bitmap" name="reflectance">
        <string name="filename" value="C:\Users\ppo\Documents\Code\tholos-tholos-experimental\mitsuba\textures\checkerboard.png" />
    </texture>
</bsdf>
<shape type="cube" id="cube">
    <transform name="to_world">
        <scale value="0.15" />

        <translate z="0.6" x="0.1" y="-0.1" />
    </transform>
    <ref id="checkerboard_png" />
</shape>
<emitter type="point">
    <point name="position" x="-0.11304648220539093" y="0.892427921295166" z="-0.2924525737762451"/>
    <rgb value="159.15494 111.27203 67.07243" name="intensity"/>
</emitter>
<emitter type="directional">
    <rgb value="2.000000 1.121867 0.600000" name="irradiance"/>
    <transform name="to_world">
        <matrix value="0.535593 0.047724 0.058656 0.000000 0.000000 0.419573 -0.341375 2.979093 -0.075618 0.338023 0.415453 -7.262619 0.000000 0.000000 0.000000 1.000000"/>
    </transform>
</emitter>

</scene>
```
2. I see. so the depth integrator returns the Euclidian distance. Im interested in the Z component of the distance, and not the full Euclidian distance. I tried using the position argument in the avo integrator and then using the values from the to_world transform to convert the Z world coordinates values to Z camera coordinate values as follows: ```Znew= mat[2,0]*X+mat[2,1]*Y+mat[2,2]*Z+mat[2,3]```  Where X,Y,Z are the images returned by the ```Position aov integrator``` and mat is the ```to_world``` trasform



Is that the best practice here?

Thanks a lot for your help and fast responses

**Comment by njroussel** [comment]
1. I guess it all depends on your application. In general, I would indeed say that `spp=1` and using a `box` filter is a common necessity.
As for the sampler, again, it really depends on what you want. I would assume that most people actually want to sample the exact middle of the pixel. We don't have a sampler/sensor for that. However, this most likely isn't more than 20 lines of python: you spawn some rays (with their origin exactly where you want them), you intersect the scene with the ray, you measure the depth. See [this tutorial](https://mitsuba.readthedocs.io/en/stable/src/rendering/scripting_renderer.html#Spawning-rays) up until the "Ambient occlusion" section.

2. Oh yes, indeed, it is not the Z-component! What you suggest is reasonable and correct I believe. I'm now wondering if you might not just want to use the `orthographic` sensor.

I think for what you seem to be doing, you should really take a look at the tutorial I linked above. I find it really easy to spawn rays and compute some measure "by hand" rather than committing to the huge framework of plugins and their parameters.

Can I close this issue now?

**Comment by njroussel** [comment]
Oh wow, thanks @chaosink! I never knew of this.

This just goes to prove my point in the last paragraph, sometimes it's just easier to write simple stuff like this yourself rather than finiding the correct plugin/parameter.

**Comment by kyrollosyanny** [comment]
Thank you so much @njroussel  and @chaosink  for the help and the great suggestions. Mitsuba3 is so awesome!
