### ISSUE TITLE
Rendered uv values not in range [0,1]

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#576]
## Summary
Rendered uv values not in range [0,1]

## System configuration

OS: Windows-10
CPU: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
GPU: NVIDIA RTX A4000
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
NVidia driver: 517.40
CUDA: 10.0.130
LLVM: -1.-1.-1

Dr.Jit: 0.4.0
Mitsuba: 3.2.0
Is custom build? False
Compiled with: MSVC 19.34.31937.0
Variants:
scalar_rgb
scalar_spectral
cuda_ad_rgb
llvm_ad_rgb

## Description

I have uv values lower and greater than 1 in the renders (at least in [-1.4,1.4]), but expected values in range [0,1]. Can I avoid this? If not, how should I treat values not in range [0,1], clipping, treating it periodically?

Thank you

**Comment by njroussel** [comment]
Hi @osylum

I'm going to need more information.  What shape are you using? How are you extracting these UV values ? What does "treating it periodically" mean?

**Comment by njroussel** [comment]
Sorry, I'm still confused. Why is there a third channel in your image?

This is how you are expected to save the AOV output:
```python
senor.film().bitmap().write("output.exr")
```
It will keep all channel names in the EXR.

There might be a bug in how we report these UV values, but I'll need a reproducer from you to fix it.

**Comment by osylum** [comment]
It was stored like this and the third channel was added to visualize data with tev directly. I will prepare a minimal reproducible example.

<pre><code>
  imageio.imwrite(mask_path, img[..., 3:4])
  imageio.imwrite(point_path, img[..., 4:7])
  imageio.imwrite(normal_path, img[..., 7:10])
  imageio.imwrite(
      uv_path,
      np.concatenate(
          (img[..., 10:12], np.zeros(img.shape[:-1] + (1,), dtype=np.float32)),
          axis=-1
      )
  )
</code></pre>

**Comment by osylum** [comment]
Here is a minimal example, but I used a mitsuba sphere instead for simplicity.

<pre><code>
import os,sys
import gc
import shutil

from timeit import default_timer as timer

import mitsuba as mi
print('available mitsuba variants:', mi.variants())
#mi.set_variant("scalar_rgb")
mi.set_variant('llvm_ad_rgb') # could not find LLVM-C.dll
#mi.set_variant('cuda_ad_rgb')
import drjit as dr

os.environ["OPENCV_IO_ENABLE_OPENEXR"] = "True"
import cv2 as cv

import imathnumpy
import numpy as np
from scipy import stats
from scipy.spatial.transform import Rotation as Rot

import imageio


# Debug rendered uv values outside the range [0,1]
# Conclusion: TODO




def render_sphere(savedir):

    mask_path = os.path.join(savedir, 'mask.exr')
    point_path = os.path.join(savedir, 'point.exr')
    normal_path = os.path.join(savedir, 'normal.exr')
    uv_path = os.path.join(savedir, 'uv.exr')


    # define sensor
    # --------------------------------------------------------------------------
    camera_origin = [0., -3., 0.]
    camera_target = [0., 0., 0.]

    camera_to_world = mi.ScalarTransform4f.look_at(
        origin=camera_origin,
        target=camera_target,
        up=[0, 0, 1]
    )
    camera_fov = 38.8839

    render_resolution = [864, 486]

    sensor = mi.load_dict({
        "type": "perspective",
        "fov_axis": "x",
        "fov": camera_fov,
        "to_world": camera_to_world,
        "film": {
            "type": "hdrfilm",
            "width": render_resolution[0],
            "height": render_resolution[1],
            "pixel_format": "rgba",
            "rfilter": {"type": "lanczos"},
        }
    })

    # define geo
    # --------------------------------------------------------------------------
    sphere_center = camera_target
    sphere_radius = 0.5
    sphere = {  # mi.load_dict({
        'type': 'sphere',
        'center': sphere_center,
        'radius': sphere_radius,
        'bsdf': {
            'type': 'plastic',
        }
    }  # )

    # define emitter
    # --------------------------------------------------------------------------
    emitter = mi.load_dict({
        "type": "point",
        "position": camera_origin,
        "intensity": 1000.,
    })

    scene = mi.load_dict({
        "type": "scene",
        "emitter": emitter,
        "geometry": sphere,
    })


    # render
    # --------------------------------------------------------------------------
    img = mi.render(
        scene,
        sensor=sensor,
        integrator=mi.load_dict({
            "type": "aov",
            "aovs": "pp:position,nn:sh_normal,uv:uv",
            "shadow_integrator": {
                "type": "direct",
                "hide_emitters": True,
            },
        }),
    ).numpy()
    imageio.imwrite(mask_path, img[..., 3:4])
    imageio.imwrite(point_path, img[..., 4:7])
    imageio.imwrite(normal_path, img[..., 7:10])
    imageio.imwrite(
        uv_path,
        np.concatenate(
            (img[..., 10:12], np.zeros(img.shape[:-1] + (1,), dtype=np.float32)),
            axis=-1
        )
    )

    sensor.film().bitmap().write(os.path.join(savedir,"output.exr"))
            
            
def main():

    savedir = r'S:\mitsuba_outputs\tmp'
    render_sphere(savedir)
    
    
if __name__ == "__main__":
    main()
</code></pre>

You should find some parts like the images below in uv.exr or output.exr (which is indeed a nicer way to export).

![image](https://user-images.githubusercontent.com/125469281/223150823-c7caf304-3734-4f17-8bcf-d4e106a18123.png)
![image](https://user-images.githubusercontent.com/125469281/223152293-ac926fa6-c2f5-467e-a2c7-4883ab06b703.png)

**Comment by njroussel** [comment]
The AOVs also pass through the `rfilter`. Your choice of filter is what is causing negative values here.

What you most likely want to be doing is producing a 1spp render with the `box` filter, otherwise your UV values will be some sort of accumulation/weighted result which is rarely what you'd want.

**Comment by osylum** [comment]
Thank you very much, seems good now.
