### ISSUE TITLE
ScalarTransform2f does not exist

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#588]
Hi,

Just to mention a probable mistake in the documentation. I could not find ScalarTransform2f; I think it does not exist (anymore):

https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_textures.html
 'to_uv': mi.ScalarTransform2f.scale([2, 2]) * mi.ScalarTransform2f.translate([0.5, 1.0])

versus

https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_shapes.html
'to_uv': mi.ScalarTransform4f([2, 10, 0])

**Comment by njroussel** [comment]
Fixed in https://github.com/mitsuba-renderer/mitsuba3/commit/f582af686ccdf7e58a2466c5664910ed6a3114c2

Thank you!
