### ISSUE TITLE
How to use a sunsky emitter?

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#591]
Hi,

I saw that a previous version of Mitsuba had a sunsky (Hosek2012 ) emitter (https://github.com/mitsuba-renderer/mitsuba/blob/master/src/emitters/sunsky.cpp), but could not use it in Mitsuba3 or find it in code or documentation (https://github.com/mitsuba-renderer/mitsuba3/tree/master/src/emitters or https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_emitters.html).

Is there a way to use this sunsky emitter in Mitsuba3?

Thank you

**Comment by njroussel** [comment]
Hi @osylum 

It has not been implemented in Mitsuba 3.

 It is definitely a feature we would like to have. However, we have no plan of implementing it ourselves in the foreseeable future. We'd happily welcome a PR for this :smile: .
