### ISSUE TITLE
Remaining strong white points when rendering using volpath tracer and envmap

### ISSUE THREAD

**Issue by osylum** [mitsuba-renderer/mitsuba3#593]
## Summary

Remaining strong white points when rendering using volpath tracer and envmap. 

## System configuration

OS: Windows-10
CPU: Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
GPU: NVIDIA RTX A4000
Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
NVidia driver: 517.40
CUDA: 10.0.130
LLVM: 15.-1.-1

Dr.Jit: 0.4.0
Mitsuba: 3.2.0
Is custom build? False
Compiled with: MSVC 19.34.31937.0
Variants:
scalar_rgb
scalar_spectral
cuda_ad_rgb
llvm_ad_rgb

## Description

I am trying to reproduce results from the publication of Che2020 to learn subsurface scattering material properties.

I am rendering an armadillo mesh with homogenous interior medium (bsdf=null), using an "envmap", and the "volpath" tracer. The image has remaining white spots despite increasing sample count, trying different samplers, reducing envmap scale, or reducing the size of the envmap. The different variants (scalar, llvm, cuda) give the same result. I don't get this with all envmaps, but it seems to happen mostly with those having a high range of radiance (sunny sky, studio light). 

It works with the campus.exr and grove.exr envmaps:
![image](https://user-images.githubusercontent.com/125469281/225384607-a38a9d10-f2de-4804-be11-4e700510d652.png)
![image](https://user-images.githubusercontent.com/125469281/225383572-d33f4cd6-6b9f-4b2c-aad6-5905dab0d2ed.png)

but I have white spots with the dreifaltigkeitsberg_512.exr, schoenbrunn-front_hd.hdr, and studio_small_01_512.exr maps:
![image](https://user-images.githubusercontent.com/125469281/225384793-bcae9f06-a991-4f6b-a285-3da14afbe25e.png)

![image](https://user-images.githubusercontent.com/125469281/225383777-9325e4e7-5efe-4d89-b582-19a00660c2f0.png)
![image](https://user-images.githubusercontent.com/125469281/225383915-c0696bd1-3afc-4ac0-8c8a-784f47cea1d6.png)

Could you please point me to what I am doing wrong?
Thank you

## Steps to reproduce

Below is the scene definition with:
- meshmodel: armadillo model
- xValue, yValue, zValue: all zero for now
- simgaT: 30.
- albedo: 0.8
- g: 0.2
- nsamples: between 128 and 4096
- render_resolution: (128,128) or (512,512)
 

**side note about sample_count or spp**: mitsuba finds it is not a power of two and rounds to the next upper power of two. Probably because of value precision/conversion, e.g. if spp is truned into float . I tried to cast to int64, but it did not help.

<pre><code>
def create_scene(meshmodel,
			    sigmaT=30., albedo=0.8, g=0.2,
			    nsamples=256, render_resolution=[512,512]):

	meshmodel_dir = '../ITNSceneFiles/models'
	meshmodel_path = os.path.join(meshmodel_dir, meshmodel + ".obj")

	# main object
	phase = {
		'type': 'hg',
		'g': g
	}
	mesh_medium = {
		'type': 'homogeneous',
		'sigma_t': sigmaT,
		'albedo': albedo,
		'sample_emitters': False, # do not compute shadows inside the material
		'phase': phase
	}
	mesh_to_world = mi.ScalarTransform4f.translate([0., 0.5, -1.9]).rotate([0.,1.,0.], 180.) # note: reverse from xml
	mesh = {
		'type': 'obj',
		'filename': meshmodel_path,
		'bsdf': {'type': 'null'},
		'interior': mesh_medium,
		'face_normals': True, # buddha has wrong face normals
		'flip_normals': False,
		'to_world': mesh_to_world
	}

	# floor
	if False:
		rectangle_reflectance_texture = {
			"type": "bitmap",
			"filename": "../ITNSceneFiles/textures/concrete_darker.png",
			'to_uv': mi.ScalarTransform4f.scale([20., 20., 0.])
		}
		rectangle_bsdf = {
			'type': 'diffuse',
			'reflectance': rectangle_reflectance_texture
		}
		rectangle_to_world = mi.ScalarTransform4f.scale([20.,20.,20.]).rotate([1.,0.,0.], -90.) # note: reverse from xml
		rectangle = {
			'type': 'rectangle',
			'to_world': rectangle_to_world,
			'bsdf': rectangle_bsdf
		}

	# light
	# sunsky emitter does not exist in mitsuba3
	if True:
		envmaps_dir = "../ITNSceneFiles/envmaps"
		#envmap_filepath =os.path.join(envmaps_dir, 'campus.exr')
		#envmap_filepath =os.path.join(envmaps_dir, 'dreifaltigkeitsberg_512.exr')
		envmap_filepath =os.path.join(envmaps_dir, 'schoenbrunn-front_hd.hdr')
		emitter = {
			'type': 'envmap',
			'filename': envmap_filepath,
			#'to_world': envmap_to_world,
			'scale': 0.5
		}
	else:
		#emitter_to_world =
		trafo = mi.Transform4f.rotate(axis=[1., 0., 0.], angle=-30.)
		position = trafo @ mi.Point3f(0., 24., -24.)
		pos = [position[0][0], position[1][0], position[2][0]]
		emitter = {
			'type': 'point',
			#'position': [position[0][1], position[0][1], position[0][2]],
			'position': pos,
			'intensity': 300.
		}

	camera_to_world = mi.ScalarTransform4f.rotate([1., 0., 0.], -30.).look_at(
		origin=[0, 24, -24],
		target=[0, 23, -23],
		up=[0, 1, 1]
	) # note: reverse from xml
	#origin, target, up = inverse_look_at(camera_to_world)
	#print(f'origin: {origin}')
	#print(f'target: {target}')
	#print(f'up: {up}')
	sensor = {
		"type": "perspective",
		#"fov_axis": "x",
		"fov": 2.5,
		"film": {
			"type": "hdrfilm",
			"width": render_resolution[0],
			"height": render_resolution[1],
			"pixel_format": "luminance", # "rgb", "rgba"
			"rfilter": {"type": "gaussian"}, #, "stddev": 0.25},
			# "rfilter": {"type": "lanczos"},
			"banner": False
		},
		'near_clip': 1.0,
		'far_clip': 100.,
		"to_world": camera_to_world,
		'sampler': {
			'type': 'ldsampler', # ldsampler, independent, stratified, multijitter, orthogonal
			'sample_count': nsamples # seems to read value slightly above nsamples and then upsample to next power of 2
		}
	}

	# integrator
	integrator = {
		'type': 'volpath',
		'max_depth': -1,
		'rr_depth': 5  # 5: 24s, 20: 31s
	}

	# scene
	scene = mi.load_dict(
		{
			"type": "scene",
			"emitter": emitter,
			"object": mesh,
			#"floor": rectangle,
			"sensor": sensor,
			"integrator": integrator
		}
	)

	return scene
<code/> <pre/>

**Comment by njroussel** [comment]
Hi @osylum 

Are these high radiance values or NaNs?
I have not rendered your scenes, but typically 4k samples is not "a lot", to get rid of all variance. Also, you should enable `sample_emitters` when working with a `null` BSDF. Finally, it might be worth giving `volpathmis` a go too.

**Comment by osylum** [comment]
They are not Nans, just higher values. Setting sample_emitters=True solved my problem. Thank you very much.
