### ISSUE TITLE
'Interior' name not exported when using dict_to_xml

### ISSUE THREAD

**Issue by dargouder** [mitsuba-renderer/mitsuba3#598]
## Summary

Interior for volumes doesn't get added as a name when exporting dict to xml.

## System configuration

System information:

  OS: Windows-10
  CPU: AMD64 Family 25 Model 33 Stepping 2, AuthenticAMD
  GPU: NVIDIA GeForce RTX 3090 Ti
  Python: 3.10.9 | packaged by conda-forge | (main, Feb  2 2023, 20:14:58) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 531.29
  CUDA: 11.8.89
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: MSVC 19.33.31630.0
     Variants:
        scalar_rgb
        cuda_ad_rgb

## Description

I created a dictionary that consists of a shape with a volume interior. Rendering this resulted in no issues.

When exporting this to an xml, using mi.xml.dict_to_scene, the interior name is omitted thus resulting in no volume inside the shape.

## Steps to reproduce

I've included a Jupyter notebook exhibiting the issue.

**Comment by dargouder** [comment]
[dict_to_xml_test.zip](https://github.com/mitsuba-renderer/mitsuba3/files/11000514/dict_to_xml_test.zip)

**Comment by njroussel** [comment]
Hi @dargouder 

Thank you for reporting this. We never added support for volumes to this function. I pushed a fix in https://github.com/mitsuba-renderer/mitsuba3/commit/15d63df4d3eab283de0c7ed511c312bba504ec46.

Please keep this issue updated if you encounter other issues with volumes specifically.
