### ISSUE TITLE
"TypeError: gather_(): incompatible function arguments." with cuda_rgb variant

### ISSUE THREAD

**Issue by gerwang** [mitsuba-renderer/mitsuba3#602]
## Summary

Hi, 
When I call `dr.unravel` on a returned TensorXf from a dr.wrap_ad function, the below error occurs. This error only appears with `cuda_rgb` variant, when switching to `cuda_ad_rgb` variant, it disappeared.

## System configuration

System information:

  OS: Ubuntu 18.04.6 LTS
  CPU: ...
  GPU: RTX 3090
  Python version: 3.8.5
  LLVM version: ...
  CUDA version: 11.3
  NVidia driver: 510.108.03

  Dr.Jit version: 0.4.1
  Mitsuba version: 3.2.1
     Compiled with: clang
     Variants compiled: cuda_rgb

## Description

The errors are below:

```
Traceback (most recent call last):
  File "/data/lingjingwang/git-task/nerfstudio/render/emitters/pytorch_emitter.py", line 76, in <module>
    img = mi.render(scene)
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/mitsuba/python/util.py", line 518, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/drjit/router.py", line 5585, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/mitsuba/python/util.py", line 373, in eval
    return self.integrator.render(
  File "/data/lingjingwang/git-task/nerfstudio/render/emitters/pytorch_emitter.py", line 56, in eval
    return dr.unravel(mi.Color3f, res_tensor)
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/drjit/router.py", line 1124, in unravel
    return gather(dtype, array, indices)
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/drjit/router.py", line 732, in gather
    return dtype.gather_(source, index, active)
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/drjit/generic.py", line 1498, in gather_
    result[i] = _dr.gather(cls.Value, source, index[i], mask[i])
  File "/data/lingjingwang/git-task/mitsuba3/cmake-build-release/python/drjit/router.py", line 732, in gather
    return dtype.gather_(source, index, active)
TypeError: gather_(): incompatible function arguments. The following argument types are supported:
    1. (source: drjit.cuda.Float, index: drjit.cuda.UInt, mask: drjit.cuda.Bool, permute: bool = False) -> drjit.cuda.Float

Invoked with: [15.935516357421875, 15.935661315917969, 15.935976028442383, 15.9389066696167, 15.937461853027344, .. 72791 skipped .., 20.090112686157227, 20.023500442504883, 20.023571014404297, 20.096235275268555, 20.095600128173828], [0, 3, 6, 9, 12, .. 24257 skipped .., 72786, 72789, 72792, 72795, 72798], [True]
```

## Steps to reproduce

Here is a runnable script that reproduces the issue. The code is almost the same as this discussion https://github.com/mitsuba-renderer/mitsuba3/discussions/586. I use a somewhat complex program to reproduce because I cannot reproduce the error using `dr.unravel` outside a plugin method. Also, when switching from `cuda_rgb` to `cuda_ad_rgb` variant, the error disappears. However, I still want to use cuda_rgb because it occupies less memory.

```python

import mitsuba as mi

mi.set_variant('cuda_rgb')
import drjit as dr
import torch


class TinyTorchNN(torch.nn.Module):
    def __init__(self):
        super().__init__()
        self.lin1 = torch.nn.Linear(in_features=3, out_features=64)
        self.lin2 = torch.nn.Linear(in_features=64, out_features=3)
        self.act = torch.nn.ReLU(inplace=True)
        self.act_out = torch.nn.Softplus()

    def forward(self, x: torch.Tensor):
        x = self.lin1(x)
        x = self.act(x)
        x = self.lin2(x)
        x = self.act_out(x)
        return x


class PyTorchEmitter(mi.Emitter):

    def __init__(self, props: mi.Properties):
        super().__init__(props)
        self.tiny_nn = TinyTorchNN().cuda()

    @dr.wrap_ad(source='drjit', target='torch')
    def torch_func(self, v):
        print(v.shape)
        v = v.t()
        res = self.tiny_nn(v)
        res = res.t().contiguous()
        return res * 20  # brighter

    def eval(self, si: mi.SurfaceInteraction3f, active: bool = True) -> mi.Color3f:
        v = si.wi
        v_tensor = dr.empty(mi.TensorXf, shape=dr.shape(v))
        v_tensor[0] = v.x
        v_tensor[1] = v.y
        v_tensor[2] = v.z
        res_tensor = self.torch_func(v_tensor)
        return dr.unravel(mi.Color3f, res_tensor) # ERROR HERE

    def pdf_direction(self, it, ds, active: bool = True) -> float:
        return 0.  # mock function


if __name__ == '__main__':
    mi.register_emitter('mytorch', lambda props: PyTorchEmitter(props))
    scene_dict = mi.cornell_box()
    scene_dict['light']['emitter'] = {
        'type': 'mytorch'  # replace area emitter with my emitter
    }
    scene_dict['integrator'] = {
        'type': 'direct',
        'emitter_samples': 0,  # so that we only need to implement `eval()` in emitter
        'bsdf_samples': 1,
    }
    scene = mi.load_dict(scene_dict)
    dr.set_flag(dr.JitFlag.LoopRecord, False)
    dr.set_flag(dr.JitFlag.VCallRecord, False)
    img = mi.render(scene)
    mi.util.write_bitmap('./out.png', img)

```

**Comment by gerwang** [comment]
Some code like this
```python
        res_buffer = dr.empty(mi.TensorXf, shape=dr.shape(res_tensor))
        res_buffer.array[:] = res_tensor.array
        return dr.unravel(mi.Vector3f, res_buffer, order='F')
```
suppresses the error. Hope it can help the investigation.

**Comment by njroussel** [comment]
I'm not able to reproduce this, what version of Pytorch are you using?

**Comment by gerwang** [comment]
1.12.1+cu113

> I'm not able to reproduce this, what version of Pytorch are you using?

**Comment by njroussel** [comment]
Great thank you.

Ok, so as the name suggests, `wrap_ad` was originally intended to handle AD types and mixing gradient-tracking frameworks. By using `cuda_rgb` you're sort of breaking the convention.

The solution is to explicitly remove any AD tracking/types from the return values of the wrapped function. Like this:
```python
res_tensor = dr.detach(self.torch_func(v_tensor), preserve_type=False)
```
Previously `res_tensor` was a `drjit.cuda.ad.TensorXf`, with this line it is a `dr.cuda.TensorXf`.

I don't think we want to change this behaviour.

**Comment by gerwang** [comment]
I see. Seems like a conversion between TensorXf and torch.Tensor is more straightforward and automatic than I expected.

**Comment by njroussel** [comment]
Yes, we implement both the `__array_interface__` and the `dlpack` protocol for all DrJit types. Type conversions should almost always be `var = drjit_type(object_from_framework)`  :smile:

**Comment by gerwang** [comment]
When talking about "straightforward and automatic conversion between TensorXf and torch.Tensor", I mean should I remove the `dr.wrap_ad` decorator when using `cuda_rgb`?

**Comment by njroussel** [comment]
Both options:
* Keeping `wrap_ad` but explicitly casting outputs to a non-AD type 
* Removing `wrap_ad` but explicitly casting input and outputs to the correct framework

are functionally the same.

It's a matter of what you think is clearer in your code. In fact, you could quite easily write your own function wrapper that explicitly doesn't deal with AD types.
