### ISSUE TITLE
Rays diffuse off a white BSDF in an unexpected way

### ISSUE THREAD

**Issue by h-OUS-e** [mitsuba-renderer/mitsuba3#604]
## Summary

Rays are being reflected off a white bsdf in a weird way.

System information:

  OS: Windows
  CPU: 5800X
  GPU: 3080 Ti
  Python version: 3.8.10

  Dr.Jit version: 0.4.1
  Mitsuba version: 3.2.1

## Description

I am shooting some rays in the same direction, straight through a refractive medium. The light rays correctly go through the refractive medium, but reflect off of a white diffuse BSDF material in a way that is different from what I would've expected.

Firstly, when the screen is close, the rays reflect, but when the screen is a bit farther away, they are completely absorbed? 

Second, when the screen is close and the ray are reflected, the rays tend to all reflect at the same angle instead of at random angle. Why is that?

Attaching code and a few snippets.

```ruby
# Attempting to record paths in a mitsuba loop
#### v. Construct Ray Vectors 
rays = mi.Ray3f(o=ray_origins, d=ray_dir)


# Getting Sampler from Camera
loaded_sensor = mi.load_dict(sensor)
sampler = loaded_sensor.sampler().clone()

# Primary Surface Intersection
si = scene.ray_intersect(rays)

# BSDF context
bsdf_ctx = mi.BSDFContext()

n_rays = dr.shape(ray_origins)[1]
idx = dr.arange(mi.UInt32, n_rays)  # index of rays
depth_count = mi.UInt32(0)
max_depth = config['max_depth']
active = mi.Bool(True)
active_bsdf = mi.Bool(True)
# Path
paths = Path(max_depth, n_rays)


loop = mi.Loop(name='Path Tracing', state=lambda: (sampler, rays, depth_count, active, si))
loop.set_max_iterations(max_depth)
print("Starting loop")


while loop(si.is_valid() & (depth_count < max_depth) & active):
    # 1. Get BSDF from Surface Interaction and context
    bsdf = si.bsdf(rays)
    
    # 2. Sample new ray directions
    bsdf_sample, bsdf_weight = bsdf.sample(bsdf_ctx, si, sampler.next_1d(),
                                            sampler.next_2d() )
    # active_bsdf = active & dr.any(dr.neq(bsdf_weight, 0.0))

    # 3. Spawn a new ray starting at the surface interactions
    rays2 = si.spawn_ray(si.to_world(bsdf_sample.wo))

    # # 4. Record points
    # # ray_points.append(np.array(rays2.o).copy().tolist())
    paths[depth_count] = PathType(rays2.o, rays2.d)

    # # 5. Calculate new surface interactions
    si = scene.ray_intersect(rays2)

    # # 6. Increase loop Iteration Count
    depth_count+=1

    active = (depth_count < max_depth) & si.is_valid()
```

![image](https://user-images.githubusercontent.com/66432003/226251974-f782db7f-47ac-46a1-aa03-99fb17f9435d.png)
![image](https://user-images.githubusercontent.com/66432003/226252075-d41e5fc7-9da4-429f-8c44-60d0300d432d.png)

**Comment by njroussel** [comment]
Hi @h-OUS-e 

What do you mean by "absorbed" ? As far as I can tell, you're not tracking any radiance.

As for why they all have the same direction, you might want to check this line:
```python
bsdf_sample, bsdf_weight = bsdf.sample(bsdf_ctx, si, sampler.next_1d(), sampler.next_2d()
```

Your sampler might simply not be wide enough. So every ray is getting the same exact random number. You should print `sampler.next_*d()` to check this. It should be as wide as your number of rays.

**Comment by h-OUS-e** [comment]
By absorbance, I mean, when the rectangle screen is very far, and the ray hits the screen, and I spawn a new ray and intersect it with the scene, the new `si.p` is is invalid. I assumed that meant that the ray has been absorbed. Why else would it not reflect back?

For the sampler, I tried with just 9 rays to debug, and sample.next_1d() is giving me 9 values, but they a lot of them are the same exact value and I am not quite sure why is that. 
`[0.40107786655426025, 0.40107786655426025, 0.40107786655426025, 0.36056363582611084, 0.36056363582611084, 0.36056363582611084, 0.36056363582611084, 0.6160186529159546, 0.6160186529159546]`

I dont know if this is related, but I am defining the sampler by cloning it from the camera sensor.
```ruby
# Getting Sampler from Camera
loaded_sensor = mi.load_dict(sensor)
sampler = loaded_sensor.sampler().clone()
```

Not sure if there is the root of the problem and if there is a better way to approach it.

**Comment by h-OUS-e** [comment]
yes it is an `independent` sampler with `'sample_count': 512`

**Comment by njroussel** [comment]
I don't kno whow your sensor is entirely set up but you can just create and setup a sampler like this:
```python
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')

sampler = mi.load_dict({
    'type': 'independent',
})
sampler.seed(0xBADCAFE, 10)
print(sampler.next_1d()) # 10 random floats in [0, 1]
```

**Comment by h-OUS-e** [comment]
okay, so that seemed to work, I am getting different random values from `sample.next_1d()`. But for some reason, a lot of the rays still don't scatter as you can see in the images below. And they scatter less the farther they are from the lens. Is there a reason for that? The BSDF of the screen is a white 'diffuse' with rgb values of 0.9,0.9,0.9. 


Closer Screen:
![image](https://user-images.githubusercontent.com/66432003/226655608-55972bd0-f97f-4a67-8bac-5542b71c627e.png)

Farther Screen:
![image](https://user-images.githubusercontent.com/66432003/226656077-734be2c0-3916-4f47-85f1-81f69ecc958b.png)

**Comment by njroussel** [comment]
Great :tada: !

Yes, indeed. Having a multiple new rays spawned at each interaction would break the parallelism model: the number of rays would grow exponentially.
