### ISSUE TITLE
[🐛 bug report] Null BRDF has Delta flag?

### ISSUE THREAD

**Issue by saeedhd96** [mitsuba-renderer/mitsuba3#605]
## Summary

`mi.has_flag(brdf, flags.Delta) `shows unexpected behavior on Null BRDF?

## Description

A `Null` brdf is not expcted to have `Delta` flag I guess. However, when asking `mi.has_flag()` it reports `True`.  Is this expected behavior?

## Steps to reproduce

```
shape = mi.load_string("""	<shape version="3.1.0" type="rectangle">
		                    <bsdf type="null"/>
	                        </shape>
""")
brdf = shape.bsdf()
print(mi.has_flag(brdf.flags(), mi.BSDFFlags.Delta))

```
The response is:

`True`

**Comment by njroussel** [comment]
Hi @saeedhd96 

Why wouldn't it? A `Null` BSDF indicates that there are no scattering events: the ray just continues straight. So, for a given incident direction there is a single outgoing direction, hence the delta flag.

**Comment by saeedhd96** [comment]
Oh ok that makes sense.
Then what is your recommended way to check for perfect specular and
dielectric brdfs?

Just check if it has flags DeltaReflection | DeltaTransmission ?

**Comment by njroussel** [comment]
Yes.

FWIW, the `Delta` flag is defined like this:
```
Delta = Null | DeltaReflection | DeltaTransmission,
```
