### ISSUE TITLE
Low Volatile GPU-Util with Inverse Volumetric Rendering

### ISSUE THREAD

**Issue by roflmaostc** [mitsuba-renderer/mitsuba3#607]
Hi,

while running the [inverse volumetric rendering tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/volume_optimization.html) I observed a low volatile GPU-util of ~10%.
I set `mi.set_variant('cuda_ad_rgb')`.

The second part, with the upsamled volume of `(64,64,64)` runs with higher volatile, but far from being 100%.

Is that due to the small volumes and small number of cameras that CUDA is not fully utilized? With more cameras (~20) I observe higher volatiles.

I would be happy about your comment on that :)! And thanks for the great work on this!

Best,

Felix

Setup:
```
mitsuba                  3.2.1
NVIDIA-SMI 525.85.05    Driver Version: 525.85.05    CUDA Version: 12.0 
Linux saturn 5.19.0-35-generic #36~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

└─(17:17:36)──> python -m mitsuba.sys_info                 ──(Mo,Mär20)─┘
System information:

  OS: Ubuntu 22.04.2 LTS
  CPU: AMD Ryzen 9 5900X 12-Core Processor
  GPU: NVIDIA GeForce RTX 3060
  Python: 3.10.9 (main, Mar  8 2023, 10:47:38) [GCC 11.2.0]
  NVidia driver: 525.85.05
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

```

**Comment by njroussel** [comment]
The `batch` sensor is a "aggregate" of sensors in some sense. It can output renders for multiple sensors at the same time. You might want to take a look at that.

I would say that this is the recommended sensor for multi-view optimizations.

**Comment by roflmaostc** [comment]
No need at the moment, I think. Thanks a lot! I'll let you know if I don't have success with it :smile: 

By the way, I was wondering if we can turn off the scattering of the gas cloud? So let's say I only want to include absorption but no scattering. 
I tried to set `albedo=0`. Is that correct?

**Comment by njroussel** [comment]
Yes, that's correct. (Here's a handy [reference](https://pbr-book.org/3ed-2018/Volume_Scattering/Volume_Scattering_Processes#Out-ScatteringandAttenuation) - I always get confused :sweat_smile:)
