### ISSUE TITLE
ScalarTransform2f referenced in the docs for textures does not exist

### ISSUE THREAD

**Issue by ShnitzelKiller** [mitsuba-renderer/mitsuba3#621]
The docs reference methods of creating 2D transformations to apply to texture UV coordinates here:
[https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_textures.html](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_textures.html
)

However, no such class exists. It seems like that should say ScalarTransform3f.

**Comment by njroussel** [comment]
Hi 

This was already reported here https://github.com/mitsuba-renderer/mitsuba3/issues/588 and fixed.
It will be visible in the next release.

**Comment by njroussel** [comment]
Actually, the fix is still wrong... let me fix that again.
