### ISSUE TITLE
Bitmap does not support numpy arrays with negative strides

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#639]
Hi,

The Bitmap class produces undefined behavior when being initialized from a numpy array with negative strides. The negative strides can for example arise when using `np.flip`. Minimal reproducer:

```
import matplotlib.pyplot as plt

import mitsuba as mi
mi.set_variant("scalar_rgb")

x = np.random.random(size=(32,32,3))
x = np.flip(x, axis=0)

fig, ax = plt.subplots(1, 3, figsize=(10,3))
ax[0].imshow(x)
ax[0].set_title('x')
ax[1].imshow(np.array(mi.Bitmap(x)))
ax[1].set_title('mi.Bitmap(x)')
# By first invoking `.copy()`, numpy creates an array with only positive strides
ax[2].imshow(np.array(mi.Bitmap(x.copy())))
ax[2].set_title('mi.Bitmap(x.copy())')
```

This produces the following image (output changes on every run):
<img width="696" alt="image" src="https://user-images.githubusercontent.com/5487532/229731900-a508e817-0aaf-4f60-af28-731f9f750e6f.png">

I think either throwing an error when the strides are negative or automatically copying the memory to the correct layout for the bitmap class would be fine here. Maybe there is some suitable pybind11 function to handle this conversion automatically?

(It also seems that mi.TensorXf does not suffer from this, as it invokes `.ravel()` to convert to a numpy array to a TensorXf)

**Comment by njroussel** [comment]
Hi,

This is tightly related to https://github.com/mitsuba-renderer/mitsuba3/issues/611.
We basically don't support any striding, the array must be tightly packed.

I planned on having a go at this later this week.

**Comment by njroussel** [comment]
Fixed in https://github.com/mitsuba-renderer/mitsuba3/commit/5b784dbd251d04cd77d3fb8f0d7eed85620c5b32.
