### ISSUE TITLE
Unable to load a scene: "could not instantiate film plugin of type "ldrfilm":"

### ISSUE THREAD

**Issue by charlo1998** [mitsuba-renderer/mitsuba3#653]
## Summary

i get an error while loading a custom scene.

## System configuration

OS: Windows-10
  CPU: Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
  GPU: NVIDIA GeForce RTX 2060
  Python: 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:19:38) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 517.00
  CUDA: 9.0.176
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: MSVC 19.34.31942.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
## Description

when loading my scene using mi.load_file(file.xml), i get this error:

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-7-d0877494fe4a>](https://localhost:8080/#) in <cell line: 3>()
      1 import mitsuba as mi
      2 mi.set_variant("scalar_rgb")
----> 3 scene = mi.load_file("shapenetcorev2_278test0_chair.xml")
      4 image = mi.render(scene, spp=256)

RuntimeError: ​[xml.cpp:1136] Error while loading "shapenetcorev2_278test0_chair.xml" (near line 17, col 10): could not instantiate film plugin of type "ldrfilm": 
[xml.cpp:1136]   [PluginManager] Plugin "ldrfilm" not found!

## Steps to reproduce
run this with my XML scene:

import mitsuba as mi
mi.set_variant("scalar_rgb")
scene = mi.load_file("shapenetcorev2_278test0_chair.xml")
image = mi.render(scene, spp=256)

[shapenetcorev2_278test0_chair.zip](https://github.com/mitsuba-renderer/mitsuba3/files/11206015/shapenetcorev2_278test0_chair.zip)

**Comment by njroussel** [comment]
Hi @charlo1998 

Your scene description was most likely written for Mitsuba 0.6 Some plugins were re-named or haven't been ported at all yet.
Specifically for the `ldrfilm`, we only have a `hdrfilm` ([link](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_films.html#high-dynamic-range-film-hdrfilm)) now. You'll find all plugin references here: https://mitsuba.readthedocs.io/en/stable/src/plugin_reference.html
