### ISSUE TITLE
Noisy Texture on Object

### ISSUE THREAD

**Issue by alakhag** [mitsuba-renderer/mitsuba3#665]
## Summary

I am trying to load a mesh along with an environment map emitter. I see noisy output on 'shape', with both diffuse and principled bsdf.

## System configuration

System information:

  OS: Ubuntu 20.04.4 LTS
  CPU: Intel(R) Core(TM) i7-9700K CPU @ 3.60GHz
  GPU: NVIDIA GeForce RTX 2080 Ti
NVIDIA GeForce RTX 2080 Ti
  Python: 3.8.3 (default, Jul  2 2020, 16:21:59) [GCC 7.3.0]
  NVidia driver: 470.141.03
  CUDA: 11.0.221
  LLVM: 12.0.0

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

I am trying to compare the variation of specularity and roughness values, but the rendered output of object is blurry. This does not seem correct.

![0 0_1 0](https://user-images.githubusercontent.com/24429931/232160920-3f876074-8dd9-41e4-bb44-c42beb86db7a.png)
0 roughness, 1 specularity

![0 0_0 0](https://user-images.githubusercontent.com/24429931/232161092-d63a94fb-e622-447f-b1a2-4fc7b9a1ba7c.png)
0 roughness, 0 specularity

![1 0_1 0](https://user-images.githubusercontent.com/24429931/232161133-8b82fd0d-e3e0-4083-a63d-6f9037a57972.png)
1 roughness, 1 specularity

## Steps to reproduce

```
import mitsuba as mi
import trimesh
import numpy as np

mi.set_variant('llvm_ad_rgb')

texture = mi.Bitmap('obj/texture_map.png')
environment = mi.Bitmap('envmap/envmap1.png')

texture_map = {
    'type' : 'bitmap',
    'bitmap' : texture,
}

roughnesses = np.linspace(0.0, 1.0, 11)
specularities = np.linspace(0.0, 1.0, 11)

for roughness in roughnesses:
    for specularity in specularities:
        mesh = {
            'type' : 'obj',
            'filename' : 'obj/textured_simple.obj',
            'material' : {
                'type' : 'principled',
                # 'base_color': texture_map,
                'roughness' : roughness,
                'specular' : specularity,
            }
        }

        trimesh_mesh = trimesh.load('obj/textured_simple.obj')
        center = trimesh_mesh.centroid

        scene = mi.load_dict(
            {
                'type' : 'scene',
                'integrator' : {
                    'type' : 'path',
                    'max_depth' : 2,
                },
                'sensor' : {
                    'type' : 'perspective',
                    'to_world' : mi.ScalarTransform4f.look_at(
                        origin = (-0.3, 0, 0.75),
                        target = center,
                        up = (0, 1, 0)
                    ),
                    'fov' : 45,
                    'film' : {
                        'type' : 'hdrfilm',
                        'width' : 512,
                        'height' : 512,
                        'pixel_format' : 'rgb',
                        'component_format' : 'float32',
                        'rfilter' : {
                            'type' : 'gaussian'
                        }
                    }
                },
                'shape': mesh,
                'emitter' : {
                    'type' : 'envmap',
                    'bitmap' : environment,
                }
            }
        )

        img = mi.Bitmap(mi.render(scene))
        R = str(roughness)
        R = R[:3]
        S = str(specularity)
        S = S[:3]
        mi.util.write_bitmap('outputs_env1/'+R+'_'+S+'.png', img)
```

**Comment by njroussel** [comment]
Hi @alakhag 

You have not defined a `Sampler` in your scene. By default, it will create a [`independent`](https://mitsuba.readthedocs.io/en/stable/src/generated/plugins_samplers.html#independent-sampler-independent) sampler with 4 samples per pixel.

Four samples per pixel is not enough to produce a converged image, hence the noisy outputs. Increase the `spp` either in the sampler or you can also pass it directly to `mi.render` as a `kwarg`.
