### ISSUE TITLE
Strange Issue when modify mitsuba3 grid volume

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/mitsuba3#671]
modified file: /mitsuba3/src/volumes/grid.cpp

add these to line 510:
```
        if constexpr(dr::is_cuda_v<Float>) {
            using FloatC = dr::CUDAArray<float>;
            using FloatD   = dr::DiffArray<FloatC>;

            using IntC = dr::CUDAArray<int>;
            using IntD   = dr::DiffArray<IntC>;

            using MaskC = dr::CUDAArray<bool>;
            using MaskD   = dr::DiffArray<IntC>;


            FloatD all_pos = dr::zeros<FloatD>(128*128*32*3);

            FloatD fdd = dr::arange<IntD>(128*128*32);

            IntD ix = dr::arange<IntD>(128*128*32) * 3;
            IntD iy = dr::arange<IntD>(128*128*32) * 3 + 1;
            IntD iz = dr::arange<IntD>(128*128*32) * 3 + 2;
            dr::scatter_reduce(ReduceOp::Add, all_pos, fdd, ix);
            dr::scatter_reduce(ReduceOp::Add, all_pos, fdd, iy);
            dr::scatter_reduce(ReduceOp::Add, all_pos, fdd, iz);
            std::cout << all_pos << std::endl;
        }
```
at std::cout all_pos, I see the error: RuntimeError: jit_var_eval(): variable r1320 remains dirty after evaluation!
any idea why this happens and how to fix it? I am doing this for a different evaluation of the interpolate_1 method. Let me know if there is any proper way to do that

I attach the original file and the Python script to reproduce this issue here. Thanks!
[error.zip](https://github.com/mitsuba-renderer/mitsuba3/files/11249522/error.zip)

Additional question: can I run mitsuba3 in wavefront mode? if so, how?
simply doing this: dr.set_flag(dr.JitFlag.LoopRecord, False)
is python will crash, let me know if you need more details to reproduce this.

**Comment by njroussel** [comment]
Hi @andyyankai 

In order to print variables you most often need to be running in wavefront mode.
To enable wavefront mode you need to enable these two flags:
```python
dr.set_flag(dr.JitFlag.LoopRecord, False)
dr.set_flag(dr.JitFlag.VCallRecord, False)
```

**Comment by andyyankai** [comment]
Seems switching to Wavefront fix everything... I will close this issue for now
Thanks Nicolas!
