### ISSUE TITLE
Reinterpreting a bool array into a float one in a custom integrator

### ISSUE THREAD

**Issue by joeylitalien** [mitsuba-renderer/mitsuba3#675]
I'm tyring to write a custom integrator in Python that outputs several non-standard auxiliary buffers. So far, I've managed to do most of what I want but I am having trouble casting bool arrays to floats to later save them to a multichannel EXR. For context, I am essentially trying to save the scattering type at a vertex as follows:

```python
# ------ Evaluate BSDF * cos(theta) and sample direction -------
bsdf_val, bsdf_pdf, bsdf_sample, bsdf_weight = bsdf.eval_pdf_sample(
bsdf_ctx, si, wo, sampler.next_1d(), sampler.next_2d()) 
diffuse = mi.Float(mi.has_flag(bsdf_sample.sampled_type, mi.BSDFFlags.Diffuse)) # This throws an error
````

The traceback looks like this:
```
Traceback (most recent call last):
  File "/Users/jlitalien/miniconda3/envs/mts/lib/python3.11/site-packages/drjit/detail.py", line 191, in array_init
    raise _dr.Exception(
drjit.Exception: Refusing to do an extremely inefficient element-by-element array conversion from type <class 'drjit.llvm.ad.Bool'> to <class 'drjit.llvm.ad.Float'>. Did you forget a cast or detach operation?
```

This looks like a simple fix but after looking for casting operators in both docs, I haven't really been able to figure it out. I have tried using `dr.reinterpret_cast_v()` as follows, but it is throwing another error:

```
diffuse = dr.reinterpret_array_v(mi.Float, mi.has_flag(bsdf_sample.sampled_type, mi.BSDFFlags.Diffuse))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlitalien/miniconda3/envs/mts/lib/python3.11/site-packages/drjit/router.py", line 579, in reinterpret_array_v
    return reinterpret_array(dtype, value, _dr.VarType.Void,  _dr.VarType.Void)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jlitalien/miniconda3/envs/mts/lib/python3.11/site-packages/drjit/router.py", line 565, in reinterpret_array
    return dtype.reinterpret_array_(value)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: reinterpret_array_(): incompatible function arguments. The following argument types are supported:
    1. (arg0: drjit.llvm.ad.Int) -> drjit.llvm.ad.Float
    2. (arg0: drjit.llvm.ad.UInt) -> drjit.llvm.ad.Float
    3. (arg0: drjit.llvm.ad.Float) -> drjit.llvm.ad.Float

Invoked with: [True, True, True, True, True, .. 262134 skipped .., True, True, True, True, True]
```

What is meant here by "try to cast or detach" exactly? I need this casting because `dr.scatter()` is incompatible with boolean values.

## System configuration

  OS: macOS Ventura 13.0
  CPU: Apple M2 Max
  Python version: 3.11.2

**Comment by njroussel** [comment]
Hi @joeylitalien :smile: 

I don't believe we have an explicit **casting** operation for `Bool`. Something like this is typically achieved by using `out = dr.select(mask, true_value, false_value)` - this allows you to go from a `Bool` to any type.

**Comment by joeylitalien** [comment]
Hi @njroussel.

Worked like a charm, thanks! :)
