### ISSUE TITLE
Something wrong when setting variant as "cuda_ad_rgb"

### ISSUE THREAD

**Issue by Goo-JZhang** [mitsuba-renderer/mitsuba3#683]
## Summary

I would like to use gpu to do the rendering, but when I tried mi.set_variant('cuda_ad.rgb'), I get the runtime error.

I install mitsuba and drjit via pip install.

## System configuration

System information:

  OS: Linux version 5.15.90.1-microsoft-standard-WSL2 (oe-user@oe-host) (x86_64-msft-linux-gcc (GCC) 9.3.0, GNU ld (GNU Binutils) 2.34.0.20200220)
  CPU: Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz with x86_64 architecture
  GPU: GTX 1650
  Python version: python3.9
  LLVM version: Not install
  CUDA version: 12.0
  NVidia driver: 528.02

There is my output of nvidia-smi:

nvidia-smi
Mon Apr 24 13:08:40 2023
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 527.92.01    Driver Version: 528.02       CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8     1W /  50W |      9MiB /  4096MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                                                   Usage      |
|=============================================================================|
|    0   N/A  N/A        56      G   /Xwayland                       N/A      |
+-----------------------------------------------------------------------------+

  Dr.Jit version: 0.4.1
  Mitsuba version: 3.2.1
     Compiled with: Don't know
     Variants compiled: Don't know
There is my `mitsuba -v` command output:
Mitsuba version 3.2.1 (master[2c03478], Linux, 64bit, 12 threads, 8-wide SIMD)
Copyright 2022, Realistic Graphics Lab, EPFL
Enabled processor features: cuda llvm avx f16c sse4.2 x86_64

## Description

Python 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import drjit as dr
>>> import mitsuba as mi
>>> mi.variants()
['scalar_rgb', 'scalar_spectral', 'cuda_ad_rgb', 'llvm_ad_rgb']
>>> mi.set_variant('cuda_ad_rgb')
Traceback (most recent call last):
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/__init__.py", line 107, in __getattribute__
    _import('mitsuba.mitsuba_' + variant + '_ext'),
  File "/home/zjlwsl/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 565, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1173, in create_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
ImportError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/__init__.py", line 317, in set_variant
    _import('mitsuba.ad.integrators')
  File "/home/zjlwsl/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/python/ad/__init__.py", line 1, in <module>
    from .integrators import *
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/python/ad/integrators/__init__.py", line 25, in <module>
    importlib.import_module('mitsuba.ad.integrators.' + name)
  File "/home/zjlwsl/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/python/ad/integrators/prbvolpath.py", line 6, in <module>
    from .common import RBIntegrator, mis_weight
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/python/ad/integrators/common.py", line 8, in <module>
    class ADIntegrator(mi.CppADIntegrator):
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/__init__.py", line 253, in __getattribute__
    result = module.__getattribute__(key)
  File "/home/zjlwsl/anaconda3/lib/python3.9/site-packages/mitsuba/__init__.py", line 115, in __getattribute__
    raise AttributeError(e)
AttributeError: jit_init_thread_state(): the CUDA backend hasn't been initialized. Make sure to call jit_init(JitBackend::CUDA) to properly initialize this backend.

**Comment by Goo-JZhang** [comment]
Same problem occurred when I install mitsuba via cmake.

**Comment by njroussel** [comment]
Hi @Goo-JZhang 

Can you use `drjit` without Mitsuba? You can follow the example [here](https://drjit.readthedocs.io/en/latest/firststeps-py.html). How about the Mitsuba command line? Can you render a scene?

I don't think we've seen something like this in a while.

**Comment by Goo-JZhang** [comment]
Also I can produce the result with 'scalar_rgb', 'scalar_spectral', 'llvm_ad_rgb', using 
```
import mitsuba as mi
mi.set_variant('scalar_rgb')
img = mi.render(mi.load_dict(mi.cornell_box()))
import matplotlib.pyplot as plt
plt.axis("off")
plt.imshow(img ** (1.0 / 2.2))
```
where 'scalar_rgb' can be replaced by any of 'scalar_spectral' and 'llvm_ad_rgb'

**Comment by njroussel** [comment]
Can you use other CUDA based tools in your environment? Something like Pytorch? Or is this exclusive to Mitsuba?

**Comment by Goo-JZhang** [comment]
@njroussel 
I can use tensorflow with cuda and I've used tensorflow to train a neuronetwork model in other course.
Here's my command line output:

~/$ python
Python 3.9.16 (main, Mar  8 2023, 14:00:05)
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
\>\>\> import tensorflow as tf
2023-04-24 23:30:44.075361: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-04-24 23:30:46.061103: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
\>\>\> tf.test.is_built_with_cuda()
True

**Comment by Goo-JZhang** [comment]
Updated.
I've found that I made a mistake when I added cuda path to environment variable. I could set_variant successfully but met another error when I run the code in [here](https://github.com/mitsuba-renderer/mitsuba3/issues/683#issuecomment-1520383046)

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In[2], line 4
      2 import drjit as dr
      3 mi.set_variant('cuda_ad_rgb')
----> 4 img = mi.render(mi.load_dict(mi.cornell_box()))
      5 import matplotlib.pyplot as plt
      6 plt.axis("off")

RuntimeError: Could not initialize OptiX!
----------------------------------------------------------------------------
It tells me that 
`jit_optix_api_init(): Failed to load OptiX library! Very likely, your NVIDIA graphics driver is too old and not compatible with the version of OptiX that is being used. In particular, OptiX 7.4 requires driver revision R495.89 or newer.`
However my NVIDIA driver version is 527.92.01

**Comment by zhaoguangyuan123** [comment]
> 

It might be because of your NVCC version.

Type : nvcc -V to see the version.

Mine was 9.1 and it will result in bug. The bug vanish when I upgrade it to 12.0.

Best,

**Comment by Goo-JZhang** [comment]
@zhaoguangyuan123 
I've update my nvidia driver in order to match my cuda version.

```
~$ nvidia-smi
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 530.47                 Driver Version: 531.68       CUDA Version: 12.1     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650         On | 00000000:01:00.0 Off |                  N/A |
| N/A   50C    P8                1W /  N/A|     96MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+----------------------+

+---------------------------------------------------------------------------------------+
| Processes:                                                                            |
|  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
|        ID   ID                                                             Usage      |
|=======================================================================================|
|    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
|    0   N/A  N/A      3719      C   /python3.9                                N/A      |
+---------------------------------------------------------------------------------------+
~$ nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2023 NVIDIA Corporation
Built on Mon_Apr__3_17:16:06_PDT_2023
Cuda compilation tools, release 12.1, V12.1.105
Build cuda_12.1.r12.1/compiler.32688072_0

```

**Comment by zhaoguangyuan123** [comment]
> @zhaoguangyuan123 I've update my nvidia driver in order to match my cuda version.
> 
> ```
> ~$ nvidia-smi
> +---------------------------------------------------------------------------------------+
> | NVIDIA-SMI 530.47                 Driver Version: 531.68       CUDA Version: 12.1     |
> |-----------------------------------------+----------------------+----------------------+
> | GPU  Name                  Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf            Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |                                         |                      |               MIG M. |
> |=========================================+======================+======================|
> |   0  NVIDIA GeForce GTX 1650         On | 00000000:01:00.0 Off |                  N/A |
> | N/A   50C    P8                1W /  N/A|     96MiB /  4096MiB |      0%      Default |
> |                                         |                      |                  N/A |
> +-----------------------------------------+----------------------+----------------------+
> 
> +---------------------------------------------------------------------------------------+
> | Processes:                                                                            |
> |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
> |        ID   ID                                                             Usage      |
> |=======================================================================================|
> |    0   N/A  N/A        20      G   /Xwayland                                 N/A      |
> |    0   N/A  N/A      3719      C   /python3.9                                N/A      |
> +---------------------------------------------------------------------------------------+
> ~$ nvcc -V
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2023 NVIDIA Corporation
> Built on Mon_Apr__3_17:16:06_PDT_2023
> Cuda compilation tools, release 12.1, V12.1.105
> Build cuda_12.1.r12.1/compiler.32688072_0
> ```

I see.

**Comment by njroussel** [comment]
Ohhhhh, I completely missed the fact that you were using WSL. 

As far as I know, OptiX is not supported in WSL: https://forums.developer.nvidia.com/t/problem-running-optix-7-6-in-wsl/239355/2?u=njroussel

**Comment by wjakob** [comment]
Can we somehow detect WSL and emit a more useful error message? 🤔

**Comment by njroussel** [comment]
I looked into this a while ago, my understanding was that it's actually quite hard to determine if some process is running inside WSL. Some methods exists but they aren't fool proof. I didn't look any further, but if there's something that can work in _most_ cases, that would be nice indeed.

**Comment by Goo-JZhang** [comment]
@njroussel 
I've done my last try by installing OptiX and mitsuba mannually,
```
from drjit.cuda import Float, UInt32, Array3f, Array2f, TensorXf, Texture3f, PCG32, Loop  
import drjit as dr  
def sdf(p: Array3f) -> Float:  
    return dr.norm(p) - 1  
sdf(Array3f(1, 2, 3))
```
could produce the correct. But the OptiX error is still there, hope that OptiX will give support to WSL in the near future.
I would give up but do my project on my Windows environment.
Thanks for your paying attention on this issue.
