### ISSUE TITLE
Measured polarized BSDF doesn't work in JIT variants

### ISSUE THREAD

**Issue by helloKOGOU** [mitsuba-renderer/mitsuba3#694]
## Summary

Error reported using the plugin BSDFs "Measured polarization material"

## System configuration
System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
  GPU: NVIDIA GeForce RTX 4060 Laptop GPU
  Python: 3.10.10 (tags/v3.10.10:aad5f6a, Feb  7 2023, 17:20:36) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 531.68
  CUDA: 12.0.76
  LLVM: 16.0.2

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: MSVC 19.35.32217.1
     Variants:
        scalar_rgb
        cuda_ad_rgb
        cuda_spectral_polarized
        cuda_rgb_polarized
        llvm_ad_rgb

## Description
Add to the XML file:
<bsdf type="measured_polarized" id="brass">
    <string name="filename" value="D:/pBRDF/5_brass/5_brass_inpainted.pbsdf"/>
    <float name="alpha_sample" value="0.02"/>
</bsdf>
Then set the variant:
mi.set_variant('cuda_spectral_polarized')

scene = mi.load_file('D:/scenes/teapot/scene_v2.xml')
image = mi.render(scene, spp=1024)

<img width="689" alt="b47bf5db15f36b9f39bdc959bf5e103" src="https://user-images.githubusercontent.com/118666111/234454858-64ab7015-570c-4083-8991-d38b4dca9bd3.png">

But I don't get this error when I use the variable "scalar_spectral_polarized"

**Comment by njroussel** [comment]
HI @helloKOGOU 

I think you forgot to past the XML file.

**Comment by helloKOGOU** [comment]
Hello@njroussel 
<scene version="3.0.0">
	<default name="integrator" value="path" />
	<default name="spp" value="512" />
	<default name="resy" value="720" />
	<default name="resx" value="1280" />
	<default name="max_depth" value="65" />
	<integrator type="stokes">
        <integrator type='path'/>
    </integrator>
	<sensor type="perspective">
		<float name="fov" value="35" />
		<transform name="to_world">
			<matrix value="-0.00550949 -0.342144 -0.939631 23.895 1.07844e-005 0.939646 -0.342149 11.2207 0.999985 -0.00189103 -0.00519335 0.0400773 0 0 0 1" />
		</transform>
		<sampler type="independent">
			<integer name="sample_count" value="$spp" />
		</sampler>
		<film type="hdrfilm">
			<integer name="width" value="$resx" />
			<integer name="height" value="$resy" />
			<string name="file_format" value="openexr" />
			<string name="pixel_format" value="rgb" />
			<rfilter type="tent" />
		</film>
	</sensor>
<bsdf type="measured_polarized" id="brass">
    <string name="filename" value="D:/pBRDF/5_brass/5_brass_inpainted.pbsdf"/>
    <float name="alpha_sample" value="0.02"/>
</bsdf>

	<bsdf type="twosided" id="FloorBSDF"> 
		<bsdf type="diffuse" >
			<texture name="reflectance" type="checkerboard">
			<rgb name="color0" value="0.325, 0.31, 0.25" />
				<rgb name="color1" value="0.725, 0.71, 0.68" />
				<transform name="to_uv">
					<scale x="20.000000" y="20.000000" />
				</transform>
			</texture>
		</bsdf>
      </bsdf>
	<shape type="rectangle" id="Floor">
		<transform name="to_world">
			<matrix value="-39.9766 39.9766 -1.74743e-006 0 4.94249e-006 2.47125e-006 -56.5355 0 -39.9766 -39.9766 -5.2423e-006 0 0 0 0 1" />
		</transform>
		<ref id="FloorBSDF" />
	</shape>
	<shape type="obj" id="Material_0001">
		<string name="filename" value="models/Mesh001.obj" />
		<transform name="to_world">
			<matrix value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1" />
		</transform>
		<ref id="brass" />
	</shape>
	<shape type="obj" id="Material_0002">
		<string name="filename" value="models/Mesh000.obj" />
		<transform name="to_world">
			<matrix value="1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1" />
		</transform>
		<ref id="brass" />
	</shape>
	<emitter type="envmap">
		<transform name="to_world">
			<matrix value="-0.922278 0 0.386527 0 0 1 0 0 -0.386527 0 -0.922278 1.17369 0 0 0 1" />
		</transform>
		<string name="filename" value="textures/envmap.hdr" />
           <float name="scale" value="5" />
	</emitter>
</scene>

**Comment by njroussel** [comment]
Ok, I've found what was producing the error, but the rendered output does not match the `scalar` output at all. This might take some time to fix.

**Comment by helloKOGOU** [comment]
> Ok, I've found what was producing the error, but the rendered output does not match the `scalar` output at all. This might take some time to fix.

Thank you very much, if this error is fixed, I sincerely look forward to your reply

**Comment by njroussel** [comment]
I have looked at this. It would require quite a bit more investigation/work to get the `measuredpolarized` BSDF to work in JIT variants.

A PR to solve this would be welcome - I won't have time to work on this myself.

**Comment by opueyociutad** [comment]
Hello @njroussel, do you have any indications of where the bug may be?
I am trying to fix it and I would appreciate any guidance.

**Comment by njroussel** [comment]
Hi @opueyociutad 

I honestly do not remember much. I fixed some obvious JIT-compilation issues, that's why it runs happily, despite returning wrong results. 

Fundamentally this shouldn't be too hard to debug:
* Find some reference scene where a `scalar` variant and JIT-based variant differ. Or even simpler/better just a `bsdf.eval()` query that differs.
* Isolate a single ray (1 spp rendering of a 1x1 film) and still see the discrepancy
* Disable symbolic executrion (run in wavefront mode) with `dr.set_flag(dr.JitFlag.LoopRecord, False);dr.set_flag(dr.JitFlag.VCallRecord, False)`.
* Sprinkle print statements at every line of the BSDF evaluation.
* Run the code with both variants
* Use the print statements to determine where the execution starts to differ between both variants. 

This should hopefully allow you to isolate some lines of code in `measuredpolarized.cpp` that are wrong. From there, the issue is hopefully obvious. Just by taking a quick look again now, I didn't notice anything that was blatantly illegal/wrong in JIT variants.

**Comment by opueyociutad** [comment]
Hi @njroussel, I have created a pull request (#1114) fixing the problem. Your indications were very useful to fix the bug, thanks.
