### ISSUE TITLE
'PyTorch and Mitsuba interoperability' needs data

### ISSUE THREAD

**Issue by tasty0tomato** [mitsuba-renderer/mitsuba3#706]
## Summary

This is a issue about document https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html.
There are files like `../scenes/textures/image_001.png` which is not in the data from the Tutorials.

**Comment by njroussel** [comment]
Thanks for reporting this, I'll fix this.

In the meantime, you can manually download the data from here: https://github.com/mitsuba-renderer/mitsuba-tutorials/tree/master/scenes

**Comment by njroussel** [comment]
This should be updated soon. Thank you.
