### ISSUE TITLE
eval_cubic

### ISSUE THREAD

**Issue by Ginko2501** [mitsuba-renderer/mitsuba3#714]
## Summary

I am comparing the `eval()` and `eval_cubic()` functions in `mi.Texture3f`, and the difference seems rather large.

## Description

Here is a simple illustration

grid = [1,2,3,4,5,6,7,8,]

grid = mi.TensorXf(grid, shape=(2,2,2,1))

grid = mi.Texture3f(grid)

dist = grid.eval([1, 1, 1])
print(dist) # prints 8

dist = grid.eval_cubic([1, 1, 1])
print(dist) # prints 7.8541669845581055

Perhaps I misunderstood something, but it would be nice if I can have a clarification.

**Comment by njroussel** [comment]
Hi @Ginko2501 

These two methods do not evaluate the same thing.

The [`eval`](https://github.com/mitsuba-renderer/drjit/blob/master/include/drjit/texture.h#L414-L422) method computes the linear interpolation of the 4 adjacent pixels (for a 2D texture).
The [`eval_cubic`](https://github.com/mitsuba-renderer/drjit/blob/master/include/drjit/texture.h#L679-L698) method computes the (clamped) cubic B-spline interpolation of the 8 adjacent pixels (for a 2D texture).

The online documentation is lacking for these texture object... I'd refer directly to the documentation in the source code for now (links above).
