### ISSUE TITLE
How can I scatter an Interaction class?

### ISSUE THREAD

**Issue by Goo-JZhang** [mitsuba-renderer/mitsuba3#742]
mitsuba version: 3.3.0
drjit version: 0.4.2

When I run
```python
import mitsuba as mi
import drjit as dr
mi.set_variant('cuda_ad_rgb')

si = dr.zeros(mi.SurfaceInteraction3f, 10)
tsi = dr.zeros(mi.SurfaceInteraction3f, 20)

dr.scatter(tsi, si, index = 2)
```
My jupyter notebook kernel will crash due to maximum recursion depth is reached.

It's the only way that I scatter every members of a SurfaceInteraction3f members?

**Comment by njroussel** [comment]
Hi @Goo-JZhang 

Thanks for the reproducer. 
Surprisingly, this was something that was never implemented. I pushed a fix (https://github.com/mitsuba-renderer/mitsuba3/commit/0b2a03245d90e2c7aba40baa4ec441786ddcd260) to `master` just now.
