### ISSUE TITLE
TensorXf to Bitmap to tensorXf ... unexpected results

### ISSUE THREAD

**Issue by devmdxac** [mitsuba-renderer/mitsuba3#755]
Hello everyone,

I have a really simple question and feel almost stupid for asking it, but I explored the documentation many times, and could not find any solution so far.

Starting from the "Gradient-based optimization" tutorial, I wanted to evaluate Mitsuba inverse rendering capabilities using real images. The code below illustrate my issue / misunderstanding:
```python
import drjit as dr
import mitsuba as mi
from matplotlib import pyplot as plt

mi.set_variant('cuda_ad_rgb')

scene = mi.load_file('../scenes/cbox.xml', res=128, integrator='prb')

image_ref = mi.render(scene, spp=512)
plt.imshow(image_ref)
plt.show()
```
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/13435060/b674264c-b6d2-4c39-b05c-84326f99008f)

```python
bmp = mi.util.convert_to_bitmap(image_ref)
plt.imshow(bmp)
plt.show()
```
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/13435060/3ecd940c-0bde-46ec-bf41-c4c95b400bf3)

```python
img = mi.TensorXf(bmp)
plt.imshow(img)
plt.show()
```
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/13435060/20322dfb-fd0e-4793-8066-7dbd99e6ae8e)

There is obviously a format issue but I cannot figure it out (notably using the information provided in the image I/O section). That is a real problem because, if I want to work with real images, I would assume that I have to read and then convert these images into tensorXf in order to proceed to any inverse rendering tasks efficiently. 

Finally, if I can ask a last question, I would like to know how I can access (display) values stored in a tensorXf array (without having to convert it into a numpy array).

I thank you for your help,
Bet Wishes

**Comment by ziyi-zhang** [comment]
Hi, 

You can read the source code of `convert_to_bitmap` which converts the storage to be UInt8 (srgb). Matplotlib imshow takes this format as input.

A tensor can be accessed using square brackets like `tensor[0, 1, :]` in python. See the tests for more examples: https://github.com/mitsuba-renderer/drjit/blob/31a83a999a765eda671107761290eda615f8cb81/tests/python/test_tensor.py.
In cpp, it can be accessed using `dr::gather`.

**Comment by njroussel** [comment]
Hi @devmdxac 

Ziyi is correct. The `plt.imshow` method only takes in integers with values in [0, 255] or floats in [0, 1]. The line `img = mi.TensorXf(bmp)` created a `TensorXf`  (floating point tensor) with values in [0, 255] which is simply not supported. You need to re-map to the [0, 1] range as such: `plt.imshow(img / 255)`.

In addition you can access the underlying flat array (`mi.Float`) of a `mi.TensorXf` by using `tensor_object.array`.
