### ISSUE TITLE
Rendering problem with pplastic BSDF and Orthogonal camera

### ISSUE THREAD

**Issue by marcoromelli** [mitsuba-renderer/mitsuba3#757]
## Summary

I'm trying to render a simple scene with a `pplastic` material associated to a rectangle, an orthogonal camera and a constant environment emitter but the rectangle is rendered all black.

## System configuration

```
python -m mitsuba.sys_info
jit_kernel_load(): cache file "C:\Users\roman\AppData\Local\Temp\drjit\d30246d2dab00df925524d056480522e.cuda.bin" is from an incompatible version of Dr.Jit. You may want to wipe your ~/.drjit directory.
jit_kernel_write(): could not write compiled kernel to cache file "C:\Users\roman\AppData\Local\Temp\drjit\d30246d2dab00df925524d056480522e.cuda.bin.tmp": 80
System information:

  OS: Windows-10
  CPU: Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
  GPU: NVIDIA GeForce RTX 2080
  Python: 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
  NVidia driver: 516.94
  CUDA: 11.4.152
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? False
     Compiled with: MSVC 19.33.31629.0
     Variants:
        scalar_rgb
        cuda_spectral
        cuda_spectral_polarized
```

## Description
When rendering the following scene I get a totally black rendering output.
```xml
<scene version="3.0.0">
    <integrator type="stokes">
        <integrator type="aov">
            <string name="aovs" value="nn:geo_normal,dd:position"/>
                <integrator type="volpath" name="my_image">
                    <integer name="max_depth" value="20"/>
                </integrator>
        </integrator>
    </integrator>

    <sensor type="orthographic">
        <transform name="to_world" >
            <scale x="4" y="4"/>
            <lookat origin="0, 0, 300" target="0, 0, 0" up="0, 1, 0"/>
        </transform>
<!--        <float name="fov" value="3"/>-->
        <sampler type="multijitter">
            <integer name="sample_count" value="36"/>
        </sampler>

        <film type="hdrfilm">
            <integer name="width" value="600"/>
            <integer name="height" value="600"/>
            <rfilter type="gaussian">
                <float name="stddev" value="1.0"/>
            </rfilter>
        </film>
    </sensor>

    <shape type="rectangle">
        <transform name="to_world">
            <scale x="20" y="20"/>
            <translate z="-0.01"/>
        </transform>
        <bsdf type="pplastic">
            <float name="alpha" value="0.1"/>
            <float name="int_ior" value="0.5"/>
            <rgb name="diffuse_reflectance" value="0.1,0.6,0.1"/>
        </bsdf>
    </shape>

    <emitter type="constant">
        <rgb name="radiance" value="0.1"/>
    </emitter>

</scene>
```
If I change the material to `roughplastic` or I place a perspective camera instead of the orthogonal one, the rendering turns out correct (more or less green).

## Steps to reproduce

Tell me how to upload the scene files if needed. 

Rendering was performed with the command `mitsuba -m cuda_spectral_polarized scene.xml`.

**Comment by marcoromelli** [comment]
Any feedback on this? I reproduced the same problem on an Ubuntu machine so it doesn't seem to be something specific to my hardware.

**Comment by marcoromelli** [comment]
Thanks @tizian . Tilting the plane (or the camera) did the job.

Still I think it makes sense to keep this issue open until someone can contribute a "real" solution.

Maybe a simple logic like 
```C++
if (n == wi_hat)
{
    s_axis_out = -s_axis_in;
}
else
{
    s_axis_out = dr::normalize(dr::cross(n,  wi_hat));
}
```

**Comment by tizian** [comment]
Yes I agree, let's keep it open.
The challenge is not getting rid of the NaNs, but to do something that makes sense from the physical point of view.

**Comment by marcoromelli** [comment]
I see. Let me try to write out the problem so that maybe it's helpful. 

When `n != wi_hat` s_axis_out is the unit-norm vector orthogonal to the plane spanned by `n` and `wi_hat`.

If `n == wi_hat` the cross product is the `(0, 0, 0)` vector and the orthogonal vector can be any vector lying on the plane perpendicular to `n`.

If what I wrote is correct the first question that comes to me is: does it hurt to chose one arbitrarily? 
The resulting `s_axis_out` is used in `rotate_mueller_basis` but maybe since this is a special case it makes sense to handle it with one of the other functions to rotate Mueller matrices?

I hope I didn't write bullshit and let me know if I can help in some way! I have a telecentric lens with a polar camera attached to it at my disposal so I can make real-world experiments if needed.
