### ISSUE TITLE
Eikonal loss

### ISSUE THREAD

**Issue by zichenwang01** [mitsuba-renderer/mitsuba3#765]
Hi,

I am writing an Eikonal loss function---
``` 
def eikonal_loss(sdf:SDF):   
    """Eikonal loss"""  
    grid = Point3f(sdf.grid.tensor().array)
    grad = sdf.gradient(grid)
    norm = dr.norm(grad)
    return dr.sum(dr.abs(norm - 1))
```

The problem is that (1) norm often returns values within 1 +- 1e-3, which accumulates error; and (2) if my SDF is a sphere, then near the center of the sphere, the autodiff gradients become `Point3f(0,0,0)`, which does not have the desired nice unit-length property. This results in my Eikonal loss often being as high as 5e4. 

I suppose both these two problems originate from not enough precision in the autodiff. As I am still learning Mitsuba while I am developing my codes, I would like to ask if this is expected and if there is any way I could improve precision? Thank you!

**Comment by ziyi-zhang** [comment]
Hi, 
Did you store the SDF with an explicit function (eg: drjit documentation) or a 3D grid with some interpolation? Could you attach a minimal reproducer?

The AD system analytically computes the gradient formula of the SDF function (from your sdf definition), and evaluates the formula with your variant, likely to have single float precision. I don't think it is responsible for such a huge error.
More likely the underlying SDF function is not properly [re-distanced](https://github.com/rgl-epfl/fastsweep), or has reached its max expressive power (eg: a coarse grid with linear interpolation cannot fit the SDF function of a sphere very well). 
You can try to test with explicit functions to see if the issue persists.
