### ISSUE TITLE
test_renders - test_projector_constant_direct fails for cuda_* modes at random

### ISSUE THREAD

**Issue by Microno95** [mitsuba-renderer/mitsuba3#766]
## Summary

Running the test suite with the following system configuration leads to a failing test case during `test_renders.py` when rendering `test_projector_constant_direct.xml` with the `direct` integrator and `jit_flag_option_0` jit flags.

## System configuration

System information:
```bash
  OS: Windows-10
  CPU: AMD64 Family 25 Model 33 Stepping 0, AuthenticAMDd
  GPU: NVIDIA GeForce RTX 3090
  Python: 3.9.13 | packaged by conda-forge | (main, May 27 2022, 16:51:29) [MSC v.1929 64 bit (AMD64)]
  NVidia driver: 535.98
  CUDA: 11.7.99
  LLVM: 15.-1.-1

  Dr.Jit: 0.4.2 (DEBUG)
  Mitsuba: 3.3.0 (DEBUG)
     Is custom build? False
     Compiled with: MSVC 19.35.32217.1
     Variants:
        scalar_rgb
        scalar_mono
        scalar_spectral
        llvm_mono
        llvm_ad_mono
        cuda_mono
        cuda_ad_mono
        cuda_rgb
        cuda_ad_rgb
        cuda_spectral
        cuda_ad_spectral
```
## Description

The mentioned test fails due to an OptiX pipeline compilation failure. It occurs at random but usually with this specific test case under `cuda_*` modes. It's unclear to me what is specifically causing the failure in that the logged output for the `cuda_mono` case simply says:
```bash
0x000000b3a65e1e00 "COMPILE ERROR: failed to create pipeline
Info: Pipeline statistics
	module(s)                            :     2
	entry function(s)                    :    13
	trace call(s)                        :     1
	continuation callable call(s)        :     0
	direct callable call(s)              :     0
	basic block(s) in entry functions    :   397
	instruction(s) in entry functions    :  9186
	non-entry function(s)                :     1
	basic block(s) in non-entry functions:    10
	instruction(s) in non-entry functions:    77
	debug information                    :    no
"
```
with the following PTX code emitted by the JIT compiler: [emitted_ptx.txt](https://github.com/mitsuba-renderer/mitsuba3/files/11664951/emitted_ptx.txt)

## Steps to reproduce

1. Compile master branch of mitsuba3 with `cuda_mono` enabled
2. Run test suite, specifically run `test_renders.py` suite
3. Error!

**Comment by njroussel** [comment]
It took us a while to figure this out. It was related to some driver change in v535.
It has been identified and fixed in https://github.com/mitsuba-renderer/drjit-core/commit/883e26eb9134d7b8bf4953514c8284365800af3c and been propagated to Mitsuba 3's master branch.

Thank you for the detailed bug report. It helped us narrow it down to a specific driver version :smile:
