### ISSUE TITLE
Nested area emitter segfaults

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#771]
Hi,

I ran into an edge case using a nested area emitter defined in Python. I can render a single scene using this emitter just as expected. However, if I subsequently instantiate and render another scene in the same process, the VCall tracing fails. I get a segmentation fault when the nested area emitter wants to call into the associated shape (inside the `sample_direction` function). 

Looking into this some more, it seems that the VCall tracing both times uses the same `m_shape` pointer. The first time we render a scene this is the correct pointer to the associated shape. But the second time the `m_shape` pointer points to a now invalid address. 

So somehow the VCall tracing seems to use an outdated version of the function, which bakes in the old pointer.

Any idea why this would happen?

Update: On second thought - could it be that the recording with the outdated shape pointer is happening due to some dangling reference to the original area emitter? I.e., the original area emitter still is somewhere in the system, while the shape was already cleaned up? (the area emitter holds a pointer and not a ref<Shape>). In that case we should figure out where that reference comes from...

Here a minimal reproducer. The first call to `f` succeeds and the second one produces a segfault.
```python
import mitsuba as mi
import drjit as dr

mi.set_variant('llvm_ad_rgb')

class MyEmitter(mi.Emitter):

  def __init__(self, props):
    mi.Emitter.__init__(self, props)
    self.nested_emitter = props['nested_emitter']
    self.m_flags = self.nested_emitter.flags()

  def prepare(self):
    self.nested_emitter.set_shape(self.shape())

  def eval(self, si, active):
    return self.nested_emitter.eval(si, active)

  def sample_direction(self, it, sample, active):
    return self.nested_emitter.sample_direction(it, sample, active)
    
  def eval_direction(self, it, ds, active):
    return self.nested_emitter.eval_direction(it, ds, active)

  def pdf_direction(self, it, ds, active):
    return self.nested_emitter.pdf_direction(it, ds, active)

  def bbox(self):
    return self.nested_emitter.bbox()

  def to_string(self):
    return f"""MyEmitter[
   nested_emitter = {self.nested_emitter}
                         ]"""


mi.register_emitter('my_emitter', lambda props: MyEmitter(props))

def f():
    scene = mi.load_dict(
        {
            'type': 'scene',
            'integrator': {'type': 'direct'},
            'light': {
                'type': 'sphere',
                'emitter': {
                    # 'type': 'area',
                    'type': 'my_emitter',
                    'nested_emitter': { 'type': 'area',},
                },
            },
            'sensor': {
                'type': 'perspective',
                'film': {'type': 'hdrfilm', 'height': 512, 'width': 512},
            },
        },
    )
    # Ensure the shape is passed down to the nested area light
    if hasattr(scene.emitters()[0], 'prepare'):
        print("Setting emitter shape")
        scene.emitters()[0].prepare()

    print(scene.shapes()[0])
    # Virtual function call to sample_direction
    emitter = mi.EmitterPtr(scene.emitters()[0])
    it = dr.zeros(mi.Interaction3f, 1)
    emitter.sample_direction(it, [0.3, 0.5], True)

f()
f()
```

**Comment by njroussel** [comment]
HI @dvicini 

This has been a longstanding problem, and as far as I can remember its a limitation with pybind11.

Any instance of a custom plugin will leak and never be cleaned up: https://github.com/mitsuba-renderer/mitsuba3/blob/master/include/mitsuba/python/python.h#L55-L87. I would need to look at it again to exactly recall the fine details of why we **need** to leak  trampolined objects.

The few times I had to circumvent this limitation, I was lucky enough to be in a situation where I could simply instantiate each scene in a different process.

**Comment by njroussel** [comment]
FWIW, we have tracked this in the stack of stuff to re-consider/fix when we move to [`nanobind`](https://github.com/wjakob/nanobind), which should happen _soon_. If you can configure this out before then, I'd gladly welcome a PR. But until this migration, I don't plan to work on any of these binding-specific issues.

**Comment by dvicini** [comment]
Thanks for the quick reply!

Yes I see, I also just realized that this is what causes this problem. I think it would be good if we could fix this for good. This kind of spillover between separate scenes is tricky to debug and could be very confusing for people not familiar with those details.

I also don't recall why this leaking of the reference would be needed. At least in the first version of this code that we wrote, it was just a hack to prevent the object from being cleaned up prematurely. Maybe it's possible to have a cleanup callback for the `ref` type to retain ensure proper destruction. I will for now just use a workaround of keeping an explicit shape reference, but revisit this if necessary.

**Comment by dvicini** [comment]
If anyone else runs into this issue: there is actually a super simple workaround. The above code works when adding
```
self._shape = self.shape()
```
in the `prepare()` method. The reason this works is that this will internally increase the reference counter of the shape and prevent its deallocation. The variable `_shape` now holds a reference to the shape, unlike the variable on the C++ side which only keeps a raw pointer. It doesn't solve the problem of the missing cleanup, but at least prevents segfaults.

**Comment by dvicini** [comment]
Closing this issue for now, but can be discussed further in PR #776
