### ISSUE TITLE
`dr.linspace` does not work with the variant `scalar_rgb`

### ISSUE THREAD

**Issue by chenzhekl** [mitsuba-renderer/mitsuba3#775]
## Summary

i recently encountered a bug where the following code snippet produced different outputs under `scalar_rgb` and `cuda_ad_rgb`:

```python
import mitsuba as mi
import drjit as dr


mi.set_variant("cuda_ad_rgb")
dr.linspace(mi.Float, 0, 100, 3)
# [0.0, 50.0, 100.0] in `cuda_ad_rgb`
```

```python
import mitsuba as mi
import drjit as dr


mi.set_variant("scalar_rgb")
dr.linspace(mi.Float, 0, 100, 3)
# 0.0 in `scalar_rgb`
```

I am not sure if this is expected.

## System configuration

System information:

  OS: Ubuntu 22.04
  CPU: Intel(R) Xeon(R) Gold 6338 CPU @ 2.00GHz
  GPU: NVIDIA RTX A6000
  Python version: 3.10
  LLVM version: N/A
  CUDA version: 11.7
  NVidia driver: 515.86.01

  Dr.Jit version: 0.4.2
  Mitsuba version: 3.3.0
     Compiled with: precompiled wheel from PyPI
     Variants compiled: precompiled wheel from PyPI

## Description

Please refer to the Summary section.

## Steps to reproduce

Please refer to the Summary section.

**Comment by njroussel** [comment]
Hello @chenzhekl 

This is expected. In `scalar` variants, as the name suggests, types are scalar  - they can only represent a single value/object. On the other hand, JIT variants will practically always use vectorized types where a single object can represent multiple values.

Maybe more specifically:
```python
import mitsuba as mi

mi.set_variant('cuda_ad_rgb)'
print(mi.Float) # Prints: <class 'drjit.cuda.ad.Float'>

mi.set_variant('scalar_rgb)'
print(mi.Float) # Prints: <class 'float'>
```
A common Python `float` (the equivalent of `mi.Float` in `scalar` variants) cannot be used as an array.

**Comment by chenzhekl** [comment]
Thank you! @njroussel
