### ISSUE TITLE
edit parameters

### ISSUE THREAD

**Issue by zichenwang01** [mitsuba-renderer/mitsuba3#780]
Hi,

I noticed that if I transformed my ply in the scene.xml file, then edits of PLYMesh positions in python are no longer effective. I am not sure if this is intended, but I am writing this just in case.

    <shape type="ply">
        <string name="filename" value=".\bunny.ply"/>
        
    </shape>

**Comment by njroussel** [comment]
Hi @zichenwang01 

This should not be the case.
Could you post a small reproducer of what you're exactly doing?

A general comment: please use the full issue template when opening a new issue, knowing your mitsuba/drjit versions and system specs can often help us figure out what you're running into.

**Comment by zichenwang01** [comment]
I think I have figured out the problem: basically after `params = mi.traverse(scene)`, I need to explicitly pass in the parameters `mi.render(scene, params, spp=32)`

Thank you for your reminder. I will pay attention to the format next time.
