### ISSUE TITLE
Use of a compiled version from Python (ModuleNotFoundError: No module named 'drjit.drjit_ext')

### ISSUE THREAD

**Issue by chris1231231231233** [mitsuba-renderer/mitsuba3#781]
Good evening,
I installed Mitsuba 3 via pip and could go through several of the tutorials using Jupyer lab.
I then uninstalled it via pip and followed the instructions (https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html) to compile a version including 
"scalar_rgb", "scalar_spectral", "cuda_ad_spectral", "llvm_ad_spectral".

Even after sourcing the setpath.sh file, I am not able to use Mitsuba from Python (directly running it from  the console works, but I very much prefer the Python interface!). The following error message is given:
ModuleNotFoundError: No module named 'drjit.drjit_ext'. I also tried to compile & install Dr.Jit separately, but that did not help.

Could you please advise me how to access the compiled Mitsuba version from Python?

Thanks a lot for the efforts!
Christian

```
----> 1 import mitsuba

File ~/mitsuba3/build/python/mitsuba/__init__.py:6
      4 import os as _os
      5 from importlib import import_module as _import, reload as _reload
----> 6 import drjit as _dr
      8 import typing, types
      9 import threading

File ~/mitsuba3/build/python/drjit/__init__.py:37
     35 # Native extension defining low-level arrays
     36 with scoped_rtld_deepbind():
---> 37     import drjit.drjit_ext as drjit_ext  # noqa
     39 # Routing functionality (type promotion, broadcasting, etc.)
     40 import drjit.router as router  # noqa

ModuleNotFoundError: No module named 'drjit.drjit_ext'
```

**Comment by merlinND** [comment]
Hello @chris1231231231233,

Before troubleshooting further, I would recommend uninstalling the DrJit that you compiled and installed separately, to make sure that it doesn't conflict with the one that gets built with Mitsuba.

Could you please fill the issue template to let us know what OS, compiler, etc you are using?

If you check your Mitsuba build directory, `build/python/drjit` should contain a shared library with a name like `drjit_ext.cpython-310-x86_64-linux-gnu.so` (depending on your Python version and OS). Make sure that you are trying to import `mitsuba` with the same Python version that was used during the build (in this example, version `3.10`).

**Comment by chris1231231231233** [comment]
Good evening,

@merlinND:
Thank you for the promt help - the situation was exactly as described by you.
Different Python versions were used for compilation and by Jupyter Lab. Installing Miniconda, setting up a new environment (never did that before) and installing everything (Mitsuba compilation + Python + Jupyter + ... sourcing the setpath.sh) from that made things work.

I already have a couple of questions regarding the proper use of spectrally resolved rendering (using "volpathmis") and the application of OptiX denoising - where could I post these (I guess not here)?

**Comment by njroussel** [comment]
Hi @chris1231231231233 

Feel free to open a new "Q&A" topic under the GitHub discussions tab. We'll gladly help you out over there.

I'll close this issue, thanks @merlinND :smile:
