### ISSUE TITLE
mi.util.write_bitmap() Doesn't Keep Alpha for PNGs

### ISSUE THREAD

**Issue by zxcv020509** [mitsuba-renderer/mitsuba3#787]
write_bitmap() and convert_to_bitmap() assume uint8 and RGB for both JPEG and PNG.
https://github.com/mitsuba-renderer/mitsuba3/blob/65e37497001f757ca67cd33e71d0f8315e7b5cb0/src/python/python/util.py#L541

A quick fix could let PNGs have uint16 and RGBA.

**Comment by njroussel** [comment]
Hi @zxcv020509 

This has already been addressed [here](https://github.com/mitsuba-renderer/mitsuba3/discussions/767). The [Bitmap](https://mitsuba.readthedocs.io/en/stable/src/api_reference.html#mitsuba.Bitmap) class has a lot of flexibility.
