### ISSUE TITLE
PyTorch tutorial: out of memory

### ISSUE THREAD

**Issue by CodeAssemblingChicken** [mitsuba-renderer/mitsuba3#789]
## Summary
In the [PyTorch example](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html), my system runs out of memory.

## System configuration

System information:

  OS: Linux Mint 21.1
  CPU: AMD Ryzen 5 2600 Six-Core Processor
  Python: 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0]
  LLVM: 15.0.7

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description
I don't have a CUDA capable GPU, so I ran the example with the `llvm_ad_rgb` variant.
But in the [optimization loop](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/pytorch_mitsuba_interoperability.html#Optimization-loop), I run out of memory after one training iteration. My system has 32 GB of RAM available.
Is this to be expected when running on the CPU?

## Steps to reproduce

1. Run Optimization Loop with `llvm_ad_rgb` backend

**Comment by njroussel** [comment]
Hi @CodeAssemblingChicken 

I just tried this myself, I'm quite far from using 32GB of RAM -- please check your other running processes. If you still believe this is an issue within Mitsuba, could you try tracking down what exactly is using that much memory? At least identify which lines in the notebook are the main culprits.

**Comment by CodeAssemblingChicken** [comment]
Hi @njroussel, thanks for the quick reply.
The line that causes the massive memory usage is `loss.backward()`:
```python
for i in range(iteration_count):
    loss_accum = 0
    optimizer.zero_grad()
    for j, texture in enumerate(textures):
        rendered_img = render_texture(model(texture), spp=spp, seed=i*len(textures)+j)
        loss = loss_fn(rendered_img, texture.torch())
        print(type(loss))
        loss.backward()
        loss_accum += loss.item()
    optimizer.step()
    train_losses.append(loss_accum)
    print("end")
    print(
        f"Training iteration {i+1}/{iteration_count}, loss: {train_losses[-1]}",
        end="\r",
    )
```
Without it, the process uses under 5 GB of RAM.
With the line, the process immediately jumps to ~20 GB of RAM used and peaks at around 28 GB, where it then crashes.

I'm just starting to get into Mitsuba and PyTorch. I can't tell if the issue is with PyTorch, Mitsuba, my system or a combination of those.
Outside a Jupyter Notebook in a normal python script, I get the same result.

**Comment by CodeAssemblingChicken** [comment]
I think I found my mistake.
So I had the same problem in Google Colab, both with CPU and GPU.
Then I remembered I couldn't find the four images used in the tutorial, so I used my own. Turns out, those were just too big. Resizing from 180x180 to 90x90 now seems to work.
Sorry for the misunderstanding
