### ISSUE TITLE
Improving OptiX Cache Reuse

### ISSUE THREAD

**Issue by errissa** [mitsuba-renderer/mitsuba3#802]
I have a script that renders over number of camera poses and in investigating how to improve its performance I discovered that Mitsuba/DrJIT generate a separate OptiX kernel for each one of the camera poses. If I have 50 poses, I get 50 OptiX kernel cache misses and take the performance hit of generating and compiling those kernels. Those 50 kernels differ _only_ in the embedded camera extrinsics. That's it - there are _no_ other differences. It seems like it would be more efficient to generate a single kernel and feed the extrinsics to the kernel with each invocation. Then you only need 1 kernel and the cache can be reused both within a single invocation of the script and subsequently when I run the script on a different set of images.

Is that possible? If it requires a code change to Mitsuba or DrJIT I would gladly implementing the change, just point me in the right direction.

**Comment by njroussel** [comment]
Hi @errissa 

Yoiu'll want to take a look at [this reply](https://github.com/mitsuba-renderer/mitsuba3/discussions/565#discussioncomment-5164097) in a  previous discussion. 

To recap, this is possible by specifying the sensor's extrinsic parameters as `opaque` to Dr.Jit. However, this should already have been done for most parameters in a [previous PR](https://github.com/mitsuba-renderer/mitsuba3/pull/571). Which sensor plugin are you using? Are you only modifying their position?

**Comment by errissa** [comment]
Thanks for the information @njroussel. I'll take a look!

I am using the perspective sensor and only changing the `to_world` and `fov` parameters of the perspective sensor.

**Comment by njroussel** [comment]
That is already supported:

```python
import mitsuba as mi
import drjit as dr

# Let's ignore the initial render because it might contain some extra scene loading computation
mi.set_variant('cuda_ad_rgb')
scene = mi.load_dict(mi.cornell_box())
img = mi.render(scene) # Launches 2 kernels
dr.eval()



dr.set_log_level(dr.LogLevel.Warn) # Suppress kernel launches
params = mi.traverse(scene)
params['sensor.x_fov'] = params['sensor.x_fov'] + 0.5
params['sensor.to_world'] = params['sensor.to_world'] @ mi.Transform4f.translate([0.1, 0, 0])
params.update()
dr.eval() # In case there are scheduled variables

dr.set_log_level(dr.LogLevel.Info) # Log kernel launches
img = mi.render(scene)
mi.Bitmap(img).write("tmp1.exr")



dr.set_log_level(dr.LogLevel.Warn) # Suppress kernel launches
params = mi.traverse(scene)
params['sensor.x_fov'] = params['sensor.x_fov'] + 0.5
params['sensor.to_world'] = params['sensor.to_world'] @ mi.Transform4f.translate([0.1, 0, 0])
params.update()
dr.eval() # In case there are scheduled variables

dr.set_log_level(dr.LogLevel.Info)  # Log kernel launches
img = mi.render(scene)  # Launches 2 kernels
mi.Bitmap(img).write("tmp2.exr")
```

This currently prints/logs 2 pairs of two kernels which are identical. This leads be to believe that you are merging some extra computation into each `render()` call if you are getting different kernels for each viewpoint/fov.

I will close this issue for now, we can re-open it if you provide me with a reproducer of this flawed caching :smile:

**Comment by yuanxion** [comment]
> Hi @errissa
> 
> Yoiu'll want to take a look at [this reply](https://github.com/mitsuba-renderer/mitsuba3/discussions/565#discussioncomment-5164097) in a previous discussion.
> 
> To recap, this is possible by specifying the sensor's extrinsic parameters as `opaque` to Dr.Jit. However, this should already have been done for most parameters in a [previous PR](https://github.com/mitsuba-renderer/mitsuba3/pull/571). Which sensor plugin are you using? Are you only modifying their position?

Managed to add the `dr.make_opaque` to reduce the cache misses, according to the hint above:
```
// changes
    params["sensor.to_world"] = to_world
    params["sensor.x_fov"] = x_fov
+   dr.make_opaque(params['sensor.to_world'])
+   dr.make_opaque(params['sensor.x_fov'])
    params.update()
```
