### ISSUE TITLE
Add `flip_tex_coords` to .ply plugin

### ISSUE THREAD

**Issue by skiler07** [mitsuba-renderer/mitsuba3#814]
## Summary

It seems that texcoords mappings are flipped in the Y-axis after reading the mesh texcoords. Hence, it produced un-intuitive renders. It seems that `vertex_texcoords` are flipped in the Y-axis after loading the mesh. 

I can apply a `to_uv` transform to do the flip, but it would be good to have a similar functionality between .obj and .ply files, especially that .ply seems to be the recommended option. `flip_tex_coords` is defined once, while the alternative of `to_uv` transform requires me to instantiate the transform for every texture.

## Description

At the moment, my textures produce artefacts - black patches and incorrect coloration of the 3D object, due to incorrect Y-axis mapping.

![Result vs Expected](https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/0b7ea74a-88eb-407d-be49-675b61f13dd3)

Ply file header:

```
ply
format binary_little_endian 1.0
element vertex 159
property float x
property float y
property float z
property float nx
property float ny
property float nz
property float u
property float v
element face 240
property list uchar int vertex_indices
end_header
```

**Comment by njroussel** [comment]
Hi @skiler07 

Thanks for pointing this out. This feature was now added.

I've tried to track down the history and reasoning behind this convention in Mitsuba and haven't found anything. To ensure backwards compatibility, the default behavior is therefore unchanged and texture flipping must be enabled manually by users.
