### ISSUE TITLE
Cannot use drjit.any() within texture eval() method

### ISSUE THREAD

**Issue by donovan-kreul** [mitsuba-renderer/mitsuba3#820]
## Summary

Hi, I am writing a custom texture plugin to generate a texture procedurally. My code will run correctly when using the `scalar_rgb` variant, but the render times are extremely slow. However, when switching to `llvm_ad_rgb`, I get an error when the `drjit.any()` function is called from within my texture's `eval()` method. 

## System configuration

System information:

  OS: 12.6.7
  CPU: b'Intel(R) Core(TM) i5-1038NG7 CPU @ 2.00GHz'
  Python: 3.11.4 (main, Jun 20 2023, 16:51:49) [Clang 14.0.0 (clang-1400.0.29.202)]
  LLVM: 16.0.6

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? False
     Compiled with: AppleClang 14.0.0.14000029
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_rgb

## Description

I am trying to create a procedural texture which colors a surface with an array of red rings on a blue background. In order to model the rings, I wrote a function`rectGrid` which returns a list of 3d grid points. These points are used by the texture as the centers of the rings. This makes use of the `drjit.any()` method. See below the code for the texture:

~~~
import mitsuba as mi 
import drjit as dr 
import math
from drjit.llvm import Float, Array3f
    
def rectGrid(xWidth, xStart, xStop):
    (xStart, xStop) = (math.floor(xStart / xWidth) * xWidth, math.ceil(xStop / xWidth) * xWidth)
    xVals = dr.linspace(Float, xStart, xStop, int((xStop - xStart) / xWidth) + 1)
    xv, yv = dr.meshgrid(xVals, xVals)
    zv = dr.zeros(Float, len(xv))
    return Array3f(xv, yv, zv)
    
class myTexture(mi.Texture):
    def __init__(self, props):
        mi.Texture.__init__(self, props)
        self.radius = 0.2
        self.ringWidth = 0.01
        self.pointsList = rectGrid(0.12, -1, 1)
            
    def eval(self, si, active=True):
        dists = dr.norm(self.pointsList - si.p) - self.radius     # SDF
        # dists = dr.arange(Float, 5) + 1
        bools = dr.abs(dists) < self.ringWidth
        inRing = dr.any(bools)
        return mi.Color3f(1, 0, 0) * inRing + mi.Color3f(0, 0, 1) * (not inRing)
~~~

As mentioned above, this code runs without issue in the scalar variant, but in the llvm variant, it acts as if the call to `drjit.any()` is a part of a loop and throws an error:

~~~
Traceback (most recent call last):
  File "/.../planeTest.py", line 95, in <module>
    image = mi.render(scene, spp=spp)
            ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitsuba/python/util.py", line 518, in render
    return dr.custom(_RenderOp, scene, sensor, params, integrator,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drjit/router.py", line 5585, in custom
    output = inst.eval(**{ k: _dr.detach(v) for k, v in kwargs.items() })
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/mitsuba/python/util.py", line 373, in eval
    return self.integrator.render(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../proceduralTexture.py", line 53, in eval
    inRing = dr.any(bools)
             ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/drjit/router.py", line 3344, in any
    return arg.any_()
           ^^^^^^^^^^
RuntimeError: jitc_var_eval(r1540): placeholder variables are used to record computation symbolically
and cannot be scheduled for evaluation! This error message could appear for
the following reasons:

1. You are using DrJit's loop or virtual function call recording feature
   and tried to perform an operation that is not permitted in this restricted
   execution mode. Please see the documentation of recorded loops/virtual
   function calls to learn about these restrictions.

2. You are accessing a variable that was modified as part of a recorded
   loop and forgot to specify it as a loop variable. Please see the
   drjit::Loop documentation for details.
~~~

I have taken a look into the mentioned documentation, and I have not found anything described there which should apply to my code, as I do not run any loops. Furthermore, I was confused to find that by defining `dists = dr.arange(Float, 5)`, the code ran without an issue. Thus, as the error mentioned, the issue is with one or more of the `self.pointsList`, `si.p`, and `self.radius` variables being considered placeholders and not available at the time of calling `dr.any()`.  I am not sure why this is the case, especially when comparing my texture to the [checkerboard.cpp](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/textures/checkerboard.cpp) built-in texture, which appears to call the similar function `dr::any_or` within its `eval()` method without issue.

## Steps to reproduce

The scene I have used for testing, as well as the code above, is found here: 
[procedural-test.zip](https://github.com/mitsuba-renderer/mitsuba3/files/12152769/procedural-test.zip)

In addition, here is a tiny render created by the same code when we use variant 'scalar_rgb':
![test](https://github.com/mitsuba-renderer/mitsuba3/assets/37644774/1c5e1b49-ec2c-4bdb-886a-6f2e134b236f)

1. Run `python3 simplePlaneTest.py`
2. Note the error given.

**Comment by njroussel** [comment]
Hi @donovan-kreul

As specified in that error message, it also applies to virtual function calls which is what we're dealing with in your reproducer.

More importantly, the actual problem in your code is a confusion of vectorization width and array lengths.
In the call to `mi.render` practically every variable is vectorized over the rays. For example, the `si` argument you get in `eval()` is vectorized, hence `dr.with(si.p)` is equal to `resolution.width x resolution.height x spp`. The issue is that `self.pointsList` is vectorized over the number of points. This mismatch in size is most likely not what you want. Intuitively, you can imagine that every ray/lane is running in it's own thread and then suddenly half-way through your computation this number of threads changes.

You should be storing `self.pointsList` as a simple `list[mi.ScalarPoint3f]` and iterate through that list to run your condition. Keeping our previous analogy of each ray having it's own thread, in a single thread you'd want to compare a single intersection point with against each point in your list sequentially.

**Comment by njroussel** [comment]
Disabling all recording features with:
```
dr.set_flag(dr.JitFlag.VCallRecord, False)
dr.set_flag(dr.JitFlag.LoopRecord, False)
```
will allow you to print variables anywhere in your code. You can use this to print the variables in your `eval()` function to better undestand this (problematic) changing vectorization width.

**Comment by donovan-kreul** [comment]
Hi @njroussel,

Thank you for your clear and thorough explanation. Your suggestions worked perfectly, and the `dr.set_flag()` commands you gave are very useful for debugging. I really appreciate your help! I'll go ahead and close this issue.
