### ISSUE TITLE
Transform between XML file format and python dict format 

### ISSUE THREAD

**Issue by wxw19990405** [mitsuba-renderer/mitsuba3#822]
## Summary
why rotation matrix turn out differently in this two format？
**XML**
<sensor type="perspective">
        <string name="fov_axis" value="larger"/>
        <float name="fov" value="41"/>

        <transform name="to_world">
            <rotate x="0.0" y="1.0" z="0.0" angle="180.00"/>
            <rotate x="1.0" y="0.0" z="0.0" angle="-32.13"/>
            <rotate x="0.0" y="1.0" z="0.0" angle="-114.95"/>
            <rotate x="0.0" y="0.0" z="1.0" angle="-0.77"/>
            <translate x="-1.027193" y="1.043566" z="-0.508638"/>
        </transform>

        <ref id="sampler"/>
        <ref id="film"/>
    </sensor>

**result rotation matrix:**
      to_world = [[0.421789, 0.00566882, 0.906676, -0.888513],
                  [0.470785, 0.853247, -0.224345, 0.520944],
                  [-0.774891, 0.521476, 0.357221, 1.15846],
                  [0, 0, 0, 1]]

**PYTHON DIC**

```
'sensor':{
        'type':'perspective',
        'fov_axis':'larger',
        'fov':41,
        "to_world": T.rotate([0, 1, 0], 180.00).rotate([1, 0, 0], -32.13).rotate([0, 1, 0], -114.95)
        .rotate([0, 0, 1], -0.77).translate([-1.027193, 1.043566, -0.508638]),
        'sampler':{
            'type':'ref',
            'id':"sampler"
        },
        'film':{
            'type':'ref',
            'id':'film'
        }
    },
```

**result rotation matrix:**
      to_world = [[0.421789, 0.493545, 0.760596, -1.02719],
                  [-0.00566878, 0.840287, -0.542112, 1.04357],
                  [-0.906676, 0.224345, 0.357222, -0.508638],
                  [0, 0, 0, 1]]

## System configuration
  Python version: 3.9
  Mitsuba version: 3.0

**Comment by njroussel** [comment]
Hi @wxw19990405 

The order of operations is different. In the XML version, the new matrices are on the left-hand side of the operation ([source](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/core/xml.cpp#L893)). Whereas in the `load_dict` version, the new matrices are on the right-hand side of the operation ([source](https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/core/python/transform_v.cpp#L219C35-L219C35)).

**Comment by wxw19990405** [comment]
thank you very much！
