### ISSUE TITLE
Does not compile (cstdint)

### ISSUE THREAD

**Issue by manuel5975p** [mitsuba-renderer/mitsuba3#838]
cstdint is not included in several places where it should be. How do you want to update this?
For example
```
ext/drjit/ext/drjit-core/src/common.h
ext/openexr/OpenEXR/IlmImf/ImfHuf.cpp
ext/openexr/OpenEXR/IlmImf/ImfMisc.cpp
ext/rgb2spec/rgb2spec_opt.cpp
```

**Comment by merlinND** [comment]
Hello @manuel5975p,

Could you please fill-in the issue template, including your OS and compiler version?

**Comment by manuel5975p** [comment]
First of all, this is because GCC 13 doesn't use cstdint as widely in other headers anymore, see here: https://gcc.gnu.org/gcc-13/porting_to.html
OS: Linux 5.15.122-1-MANJARO
  CPU: AMD Ryzen 9 3900X 12-Core Processor
  GPU: NVIDIA GeForce RTX 3070
  Python version: Python 3.10.10
  LLVM version: 15
  CUDA version: 12.2
  NVidia driver: 535.86.05
I hope this helps🙃🙃🙃🙃🙃🙃🙃!

**Comment by njroussel** [comment]
Hi @manuel5975p 

Per our [recommendations](https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html#linux), clang is still strongly recommended. GCC is also technically supported, for various reasons, but we haven't been keeping up with the bleeding edge.

We can look into this in a couple of weeks. Until then, the workaround is pretty easy: just use another compiler or compiler version :smile:

**Comment by manuel5975p** [comment]
Okay, I will switch to clang then. However it would be advisable to include the required headers explicitly anyway.

**Comment by Peter0x44** [comment]
This is related to libstdc++, not clang
Should be reproducible with `clang++ -stdlib=libstdc++`
Assuming it hasn't been resolved already

**Comment by njroussel** [comment]
Fixed in `master`.
