### ISSUE TITLE
Getting metallic/roughness value of a principled BSDF

### ISSUE THREAD

**Issue by Frollo24** [mitsuba-renderer/mitsuba3#848]
Hello community:

I was trying to get the metallic value of a scene which only has principled BSDFs in it and my first approach was to create a custom integrator which read the properties of the BSDF and returned its metallic or roughness value in order to create a G-buffer of the scene (position, normal, albedo, metallic, roughness, etcetera), but I want to know if there is a better way to achieve this generation of a custom G-buffer.

## System configuration

System information:

  Dr.Jit version: 0.4.1
  Mitsuba version: 3.2.1

## Code example
This is a code example of which I'm trying to accomplish with a custom Metallic integrator:

```
from typing import List, Tuple

import mitsuba as mi
import drjit as dr


class Metallic(mi.SamplingIntegrator):
    def __init__(self, props):
        mi.SamplingIntegrator.__init__(self, props)
        pass

    def sample(self, scene: mi.Scene, sampler, ray: mi.RayDifferential3f, medium: mi.Medium = None, active: bool = True) -> Tuple[mi.Color3f, bool, List[float]]:
        si = scene.ray_intersect(ray=ray, active=active)
        bsdf = si.bsdf(ray)  # The metallic BSDF that I want to get the value from

        ctx = mi.BSDFContext()
        eval = bsdf.eval(ctx, si, mi.Vector3f(0, 0, 1), active)

        valid = si.is_valid()
        color = dr.select(valid, eval, mi.Color3f(0.0, 0.0, 0.0))

        return color, valid, [dr.select(valid, 1.0, 0.0)]

    def aov_names(self) -> List[str]:
        return ['metallic.M']

    def to_string(self) -> str:
        return 'MetallicIntegrator[]'
```

**Comment by njroussel** [comment]
Hi @Frollo24 

**When creating an issue please fill out the entire issue template. It save us a lot of time - we can skip the basic back & forth to understand what environment you're running code in, the script you're trying, etc.**

Are you building Mitsuba from source? I don't believe we have support for AOVs in custom Python integrators in the last PyPI release. This is however supported on `master`.

We've recently added the possibility to evaluate [arbitrary BSDF attributes](https://github.com/mitsuba-renderer/mitsuba3/blob/master/include/mitsuba/render/bsdf.h#L499). We'll soon have this automatically supported in the `aov` integrator too.

**Comment by Frollo24** [comment]
Thanks for your response,

No, I've installed Mitsuba from PyPI because I'm using it in a Python environment and I don't think I'll have access to a custom build of Mitsuba. I guess I'll have to wait until it has support for evaluate arbitrary BSDF attributes.

**Comment by njroussel** [comment]
Hi again @Frollo24 

That's unfortunate.

We should be pushing out a new release either this or next week. Feel free to open a discussion thread once it is released if you need any further guidance. In the meantime, I'll close this issue.
