### ISSUE TITLE
Dictionary scene format

### ISSUE THREAD

**Issue by sagesimhon** [mitsuba-renderer/mitsuba3#852]
Hi, 

Is there a dictionary version of the sample XML files (namely, `cbox.xml`) found in the tutorials?
I'm having a hard time converting my XML file to a dictionary for a full scene and I can't find a thorough format definition beyond the few liners in the docs which do not include the full details to support a cornell box. 

Thanks!

**Comment by rtabbara** [comment]
Hi @sagesimhon,

You can call `mi.cornell_box()` to output a dictionary version counterpart.

More generally, the [Plugin reference](https://mitsuba.readthedocs.io/en/stable/src/plugin_reference.html) includes both sample XML and Python snippets for the majority of plugins available.

**Comment by hgchen** [comment]
Besides the Cornell box scene, for more generic cases, is there a way to load the scene XML file to a Python dict that can be input `mi.load_dict()`? `mi.load_file()` will load the XML directly as Mitsuba Scene class, but not the Python dict. Thanks.

**Comment by merlinND** [comment]
Hello @hgchen,

I don't believe there is a utility for XML to dict conversion. We do have [XML to Properties](https://mitsuba.readthedocs.io/en/stable/src/api_reference.html#mitsuba.xml_to_props), though.
