### ISSUE TITLE
scence differences in XML vs. dict

### ISSUE THREAD

**Issue by sagesimhon** [mitsuba-renderer/mitsuba3#853]
## Summary

I am testing a conversion tool of scenes from xml format to dict format (I wish such a tool already existed) . I noticed that the order of any defined transformations in the xml file must be reversed when defined in the dict version. For example: 

```
<shape type="rectangle">
        <transform name="to_world">
            <scale value = "0.5"/>
            <translate x="0" y="0.5" z="0.0"/>
            <rotate z="1" angle="180"/>
        </transform>
    .....
```

where scaling, followed by translating, followed by rotating, will need to be specified as in reveres order as such:

```
{
        'type': 'rectangle',
        'to_world': mi.ScalarTransform4f.rotate([0, 0, 1], 180).translate([0, 0.5, 0]).scale([0.5, 0.5, .5]),

       ...
}
```

NOT as this:

```
{
        'type': 'rectangle',
        'to_world': mi.ScalarTransform4f.scale([0.5, 0.5, .5]).translate([0, 0.5, 0]),.rotate([0, 0, 1], 180),

       ...
}
```

Which is contrary to the documents. 

## System configuration
System information:

  OS: 12.6.2
  CPU: b'Apple M1 Pro'
  Python: 3.9.16 (main, Mar  8 2023, 04:29:24) [Clang 14.0.6 ]
  LLVM: 16.0.1

  Dr.Jit: 0.4.1
  Mitsuba: 3.2.1
     Is custom build? False
     Compiled with: AppleClang 14.0.0.14000029
     Variants:
        scalar_rgb
        scalar_spectral
        llvm_ad_rgb

## Steps to reproduce

1.  render the scene from an xml with transformations
2. render the scene from a dict with the same transformations in reversed order

**Comment by ziyi-zhang** [comment]
Hi,

- With dict, we are describing a matrix `T=T1 @ T2 @ T3` where the right most operation goes first. `to_world: T1.T2.T3` is the chained syntax and is equivalent with the above `@` syntax.
- With xml, we are describing the transformation in the "natural" human language order: we define a shape, apply a trafo to the shape, first scale, then translate....

> a conversion tool of scenes from xml format to dict format (I wish such a tool already existed)

I personally would be happy to have this tool in Mitsuba if you are willing to open a PR. @njroussel 
One use case is to dynamically assemble scenes with Python (in batch), convert to xml for static usage later. It decouples the scene generation stage and the rendering/experiment stage. IMO this is easier to maintain a large research project.

**Comment by njroussel** [comment]
Hi @sagesimhon 

Indeed, these examples weren't consistent in the documentation. I've fixed them in: https://github.com/mitsuba-renderer/mitsuba3/commit/9bff606922441c922b99110c9be9855d347d48a4

The explanation given by @ziyi-zhang is still correct.
