### ISSUE TITLE
Compilation issue in C++

### ISSUE THREAD

**Issue by g1r4ff3** [mitsuba-renderer/mitsuba3#879]
## Summary

mitsuba 3 can't be compiled in C++.

## System configuration

System information:

  OS: Windows 11
  CPU: AMD Ryzen 9 7950x 16-Core Processor
  GPU: GeForce RTX 4090
  Python version: 3.11.4
  CUDA version: 12.2
  NVidia driver:  536.67

  Dr.Jit version: 0.4.2
  Mitsuba version: 3.3.0
     Compiled with: Microsoft Visual Studio Community 2022 17.7.2
     Variants compiled: scalar_rgb, scalar_spectral, cuda_ad_rgb, llvm_ad_rgb

## Description

Hi, i just want to implement a custom shape plugin by C++, so as a first step of implementing it i've tried to compile the system according to this(https://mitsuba.readthedocs.io/en/stable/src/developer_guide/compiling.html#), but i can't.
Although I've repeat the procedure described in that document over and over after the first try, i'm still in trouble.
I have no idea what to do from here, please help me. thank you in advance.

## Steps to reproduce

1. clone the repository by  `git clone --recursive https://github.com/mitsuba-renderer/mitsuba3`
2. configure it by `cmake -G "Visual Studio 17 2022" -A x64 -B build`
3. build the system by opening `mitsuba.sln` and performing 'build solution' in Debug/x64 on Visual Studio Community 2022.
4. type `setpath` on the cmd from the built path(~/build/Debug/)
5. try an example scene such as scene.xml in tutorials directory, but the console says that 'mitsuba' is not recognized as an internal or external commandm, operable program or batch file.

below is a log of the output window:
[Output-Build.txt](https://github.com/mitsuba-renderer/mitsuba3/files/12444897/Output-Build.txt)

**Comment by g1r4ff3** [comment]
I've resolved the problem by re-installing all relevant programs that are needed to compile the system (visual studio 2022, cmake, git, python, cuda toolkit), so close this issue.

**Comment by HuixianZhong** [comment]
Hello, I'm having the same issue, can you share the details you dealt with

**Comment by njroussel** [comment]
Hi @HuixianZhong 

It's recently been brought to our attention that Windows builds fail with more recent versions of pybind. Could you try using `pybind11==2.11` ?
