### ISSUE TITLE
SceneParameters turns to dict when under wrapping function

### ISSUE THREAD

**Issue by olkovi** [mitsuba-renderer/mitsuba3#897]
## System configuration

System information:

  CPU: Intel(R) Xeon(R) CPU E5-2680 v4 @ 2.40GHz
  GPU: Tesla P100-PCIE-16GB
  Python: 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0]
  NVidia driver: 525.125.06
  CUDA: 11.8.89
  LLVM: 15.0.7

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

I am trying to perform geometry optimisation by passing gradients from Mitsuba renders to Pytorch and then updating the SceneParameters object with the new parameter values, which necessitates the use of the @dr.wrap_ad wrapper. However, when under the wrapper, instead of updating, the update method turns SceneParameters into a dictionary. Can anything be done to circumvent this?

The render function is as follows:

```python
#@dr.wrap_ad(source='torch', target='drjit')
def renderimg(scene, params_scene, vertices:torch.Tensor, faces:torch.Tensor, normals:torch.Tensor, samples):  
    
    params_scene['object.vertex_positions'] = dr.ravel(vertices)
    params_scene['object.vertex_normals'] = dr.ravel(normals)
    params_scene['object.faces'] = dr.ravel(faces)
    params_scene.update()

    return mi.render(scene, params_scene, spp=samples)
```

If uncommented, the render won't be performed, giving "Exception: params should be an instance of mi.SceneParameter!"

**Comment by olkovi** [comment]
Actually the params_scene appears to become a dict as soon as it enters the wrapped function, even before any update to its values.

**Comment by olkovi** [comment]
So, it appears that the global SceneParameters can be updated with the resulting dict by doing 

```python
params.update(params_scene)
        return mi.render(scene, params, spp=samples)
```
However, this results in "Critical Dr.Jit compiler failure: jit_var(r1635): unknown variable!", when attempting to render.

**Comment by njroussel** [comment]
Hi @olkovi 

Maybe a bit of an explanation:

As per the `wrap_ad` documentation, every argument and is casted from `torch` to `drjit`:
> The wrapped function’s arguments will be casted to the tensor types corresponding to the target framework.

For arguments that cannot be converted they are simply passed as is. Unfortunately, the `SceneParameters` can be partially interpreted as a `torch` type and will see some undesired conversions happen. It is typically safer to have an extra wrapper to pass the non-`torch` arguments to your function.
