### ISSUE TITLE
moment integrator support for prb volume rendering

### ISSUE THREAD

**Issue by andyyankai** [mitsuba-renderer/mitsuba3#910]
I try to run an optimization using moment integrator (I also write an moment for rgb mode) for volume rendering.
It seems it can optimize the scene(such as albedo) for a path integrator(for surface).
However, when I run the moment integrator for volume rendering, the backward step told me there is no gradient enabled in the scene...
Is that something expected?
Thanks

**Comment by njroussel** [comment]
Hi @andyyankai 

Integrators that make use of nested integrators have some issues when trying to differentiate them. For example they would not use any adjoint definitions but rather just use plain AD.
However, they should still work, and that error message is unexpected.
Are you using `prbvolpath` or `volpath` ? A small reproducer would help.

**Comment by andyyankai** [comment]
Thanks, I will put a script here tomorrow

**Comment by andyyankai** [comment]
[moment_issue.zip](https://github.com/mitsuba-renderer/mitsuba3/files/12667108/moment_issue.zip)
Here is the script, I also attach the momentrgb integrator as mitsuba3 integrator plugin. (I guess moment integrator should be same in this case)
when I am using prbvolpath the error occur.
when I use volpath it seems fine.
you can edit data/inital.xml and target.xml for different integrator

**Comment by andyyankai** [comment]
Just a noice that volpath tracing is also very low using moment..
