### ISSUE TITLE
Integrator.cpp uses drjit-core flags, but the library might not be linked

### ISSUE THREAD

**Issue by DawyD** [mitsuba-renderer/mitsuba3#912]
## Summary

Integrator.cpp uses JIT flags, but drjit-core is not compiled and linked if neither cuda nor llvm variants are included

System information:

  OS: Mac OS
  Mitsuba version: 3.4.0 (7d91235d5c5d5273de8011746fb480d9662181d0)
     Compiled with: clang-15
     Variants compiled: scalar_rgb, scalar_mono

## Description

Methods `render_forward` and `render_backward` in file `src/render/integrator.cpp` use DrJit flags which are defined in drjit-core library. However, if we compile Mitsuba without LLVM or CUDA variant, the MI_ENABLE_JIT flag in Cmake is OFF and hence drjit-core library is not compiled and not linked.

One then finds the following error: `ld: Undefined symbols: _jit_flag, referenced from: mitsuba::Integrator ...`

## Steps to reproduce

Compile Mitsuba without the any llvm and cuda variants.

```
git clone --recursive https://github.com/mitsuba-renderer/mitsuba3
cd mitsuba3
git checkout 7d91235d5c5d5273de8011746fb480d9662181d0
git submodule update --init --recursive
mkdir build
cd build
cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
sed -i '' '87s/.*/        "scalar_rgb", "scalar_mono"/' mitsuba.conf
cmake -GNinja .. -DCMAKE_BUILD_TYPE=Release
ninja
```

**Comment by njroussel** [comment]
Hi @DawyD 

Thanks for the bug report, I fixed it in https://github.com/mitsuba-renderer/mitsuba3/commit/a911982d899c5b7d129f00eb46861c0818b60d12.
