### ISSUE TITLE
directionalarea and glass not working

### ISSUE THREAD

**Issue by Skyflote** [mitsuba-renderer/mitsuba3#916]
I tried rendering a simple prism scene with a rectangle as directionalarea but when doing so using ptracer glass appears black. (rays go through the glass and refraction seems to work but glass is black)

  OS: windows 11
  CPU: i5-12600k
  GPU: rtx 3070 ti
  Python version: last
  CUDA version: last
  NVidia driver: last

**Comment by Skyflote** [comment]
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/77280542/a822fca1-8dfc-4bf6-ba3e-9b4207240cad)
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/77280542/4ed66f1d-c71b-4513-934a-7e65a44be368)

**Comment by Skyflote** [comment]
Or Is there any other good way to render a glass prism with dispersion?

**Comment by njroussel** [comment]
Hi @Skyflote 

This is expected. With a perfectly smooth `dielectric` it is impossible to connect your light path from the prism to the sensor as the angle will never match the refracted angle produced by the glass prism.

[Dispersion is not supported](https://github.com/mitsuba-renderer/mitsuba3/discussions/829) in Mitsuba 3.

**Comment by Skyflote** [comment]
@njroussel thank you for the answer and explanation!
