### ISSUE TITLE
Black pixels at glaring angles.

### ISSUE THREAD

**Issue by georgy95** [mitsuba-renderer/mitsuba3#919]
## Summary

Render has black artefacts after rendering.

## System configuration

System information:

  OS: 13.2.1
  CPU: b'Apple M1'
  Python: 3.10.1 (main, Mar 24 2023, 21:25:11) [Clang 14.0.0 (clang-1400.0.29.202)]
  LLVM: 16.0.6

  Dr.Jit: 0.4.2
  Mitsuba: 3.3.0
     Is custom build? True
     Compiled with: AppleClang 14.0.0.14000029
     Variants:
        scalar_rgb
        llvm_ad_rgb

## Steps to reproduce

[coffeecup.zip](https://github.com/mitsuba-renderer/mitsuba3/files/12728865/coffeecup.zip)

Download and unzip. Add the directory path as `ROOT_DIR` variable. Run the script below.

Reproduction code:

```
import os
import mitsuba as mi
mi.set_variant("scalar_rgb")

ROOT_DIR = "dir-path-to-unziped-folder"

def create_path(f, base=ROOT_DIR):
    return os.path.join(base, f)
    

top_material = {
    "type": "principled",
    "base_color": {
        "type": "rgb",
        "value": 0.1
    },
    "specular": 0.5,
    "roughness": 0.4
}

cup_material_two_sided = {
    "type": "twosided",
    "bsdf": {
        "type": "normalmap",
        "normalmap": {
            "type": "bitmap",
            "filename": create_path("9c9a4480139145d7b823e8ab4f3776db.png"),
            "raw": True,
        },
        "bsdf": {
            "type": "principled",
            "base_color": {
                "type": "bitmap",
                "filename": create_path("74d4ab8d192d4be8a4c830172201406e.png")
            },
            "roughness": {
                "type": "bitmap",
                "filename": create_path("6b2335c066bc47eb9c2364e5b0d6ce56.png")
            }
        }
    }
}

cup_material = {
    "type": "normalmap",
    "normalmap": {
        "type": "bitmap",
        "filename": create_path("9c9a4480139145d7b823e8ab4f3776db.png"),
        "raw": True,
    },
    "bsdf": {
        "type": "principled",
        "base_color": {
            "type": "bitmap",
            "filename": create_path("74d4ab8d192d4be8a4c830172201406e.png")
        },
        "roughness": {
            "type": "bitmap",
            "filename": create_path("6b2335c066bc47eb9c2364e5b0d6ce56.png")
        }
    }
}


mesh1 = {
    "type": "ply",
    "filename": create_path("09ffdc83295c48c3bdb345dff8ced4cd.ply"),
    "bsdf": cup_material
}

mesh2 = {
    "type": "ply",
    "filename": create_path("164818af986a446686287699af403749.ply"),
    "bsdf": cup_material
}

mesh3 = {
    "type": "ply",
    "filename": create_path("bd0dd345d46a40c599617f2f6c307211.ply"),
    "bsdf": top_material
}

mesh4 = {
    "type": "ply",
    "filename": create_path("fbcdba7210774547bb74114d5f73aa73.ply"),
    "bsdf": cup_material
}

integrator = {
    "type": "path",
    "max_depth": 10,
    "rr_depth": 5,
    "hide_emitters": False,
}

envlight = {
    "type": "envmap",
    "filename": create_path("8318368896314118b5bfc983fdc00ff3.hdr"),
    "scale": 1
}

xz_flip = mi.ScalarTransform4f(
    [[-1, 0, 0, 0], [0, 1, 0, 0], [0, 0, -1, 0], [0, 0, 0, 1]],
)

sensor = {
    "type": "perspective",
    "fov": 50,
    "near_clip": 0.1,
    "far_clip": 10000,
    "to_world": mi.ScalarTransform4f(
        [[0.999525, -0.0133847, 0.0277509, 0.113515],
         [0, 0.900708, 0.434425, 2.94756],
         [-0.0308101, -0.434219, 0.90028, 3.15189],
         [0, 0, 0, 1]]
    ) @ xz_flip,
    "film": {
        "type": "hdrfilm",
        "width": 1024,
        "height": 1024,
        "pixel_format": "rgba",
        "rfilter": {"type": "box"},
    },
    "sampler": {"type": "independent", "sample_count": 16},
}


scene = {
    "type": "scene",
    "integrator": integrator,
    "envlight": envlight,
    "mesh1": mesh1,
    "mesh2": mesh2,
    "mesh3": mesh3,
    "mesh4": mesh4
}

mi_scene = mi.load_dict(scene)
mi_sensor = mi.load_dict(sensor)
params = mi.traverse(mi_scene)

# render
mi.render(scene=mi_scene, sensor=mi_sensor, spp=50)
bm = mi_sensor.film().bitmap()

# preview image
from PIL import Image
import numpy as np
bmp = bm.convert(
    pixel_format=mi.Bitmap.PixelFormat.RGBA,
    component_format=mi.Struct.Type.UInt8,
    srgb_gamma=True
)
img = Image.fromarray(np.array(bmp))
```

The above code renders:

![result](https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/61713789-a5fd-4d37-a349-5c5b13295839)

Note the black border around the cup. 

<img width="649" alt="Screenshot 2023-09-26 at 15 34 42" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/cdf65b6f-668d-4419-b9ac-eae6db8d8830">

With a constant env emitter:

<img width="448" alt="Screenshot 2023-09-26 at 16 17 01" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/af6f7270-53ae-4319-b7a2-fabd35bab7b6">

### Extra bug

If a `twosided` material is used for the cup material i.e. `cup_material_two_sided`, there is an additional artefact at the bottom:

<img width="508" alt="Screenshot 2023-09-26 at 15 37 31" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/e9336b28-7df2-42fd-8da7-0bafa97ef685">

## Expected behaviour

A render that doesn't have the black artefacts.

**Comment by njroussel** [comment]
Hi @georgy95 

This is most likely because of your normal map data.

If you render these scenes with the `aov` integrator, namely the shading normals (`sh_normal`). You should see that in those black regions the normal is facing backward. This means that you're effectively hitting the inside of the material, hence the black output. 

This problem persists even with the `twosided` integrator because of the order in which they were declared. You should have:
`'type': 'normalmap', 'normalmap': { ... }, 'bsdf': { 'type': 'twosided', 'bsdf': { ... } }`
instead of:
`'type': 'twosided',  'bsdf': { 'type': 'normalmap', 'normalmap': { ... }, 'bsdf': { ... } }`
The backface/frontface normal test is taking place before the normal map evaluation in the latter where as it's taken place after the normal map evaluation in the former.

Fundamentally, this is still an issue with the actual data in the normal map files you're providing.

**Comment by njroussel** [comment]
Hmm that would suggest that mesh itself is defining normals that could be backfacing dependent on the viewing angle. The good news is that you should also be able to see this in an AOV render.

**Comment by dvicini** [comment]
I am not 100% sure I remember this correctly. But I think I've seen cases where Blender Cycles handles bad shading normals more robustly than Mitsuba. I think it's a bit more forgiving about backfacing shading normals and produces fewer of those black outlines.

**Comment by njroussel** [comment]
Yes, I believe Blender will "trace through" the shape when hitting the front face of a triangle with a back-facing normal.
