### ISSUE TITLE
Sensor's film is a black image when using AOV integrator & built from source.

### ISSUE THREAD

**Issue by georgy95** [mitsuba-renderer/mitsuba3#921]
## Summary

When using AOV integrator, it seems that the rendered noisy image is not accessible from the sensor's film. The issue only arrises on builds from source. Everything works as expected for pypi build.

Previously, I could obtain the noisy color image from the sensor using `sensor.film().bitmap().split()[0][1]`. Now this returns a black image (a 0 tensor).

## System configuration

System information:

OS: 13.2.1
CPU: b'Apple M1'
Python: 3.10.1 (main, Mar 24 2023, 21:25:11) [Clang 14.0.0 (clang-1400.0.29.202)]
LLVM: 16.0.6

Dr.Jit: 0.4.2
Mitsuba: 3.3.0
Is custom build? True
Compiled with: AppleClang 14.0.0.14000029
Variants:
scalar_rgb
llvm_ad_rgb

## Steps to reproduce

Run the following code:

```
import os
import mitsuba as mi
mi.set_variant("scalar_rgb")

integrator = {
    "type": "aov",
    "aovs": "albedo:albedo,normals:sh_normal",
    "image": {
        "type": "path",
        "max_depth": 10,
        "rr_depth": 5,
        "hide_emitters": False,
    }
}

envlight = {
    "type": "constant",
    "radiance": {
        "type": "rgb",
        "value": [0.8, 0.1, 0.1]
    }
}

sensor = {
    "type": "perspective",
    "fov": 50,
    "near_clip": 0.1,
    "far_clip": 10000,
    "to_world": mi.ScalarTransform4f.look_at(
        origin=[0,0,1],
        target=[0,0,0],
        up=[0,1,0]
    ),
    "film": {
        "type": "hdrfilm",
        "width": 1024,
        "height": 1024,
        "pixel_format": "rgba",
        "rfilter": {"type": "box"},
    },
    "sampler": {"type": "independent", "sample_count": 16},
}

scene = {
    "type": "scene",
    "integrator": integrator,
    "envlight": envlight,
}

mi_scene = mi.load_dict(scene)
mi_sensor = mi.load_dict(sensor)
params = mi.traverse(mi_scene)
result = mi.render(scene=mi_scene, sensor=mi_sensor, spp=10)
```

`sensor` object could previously be used to get the noisy image, but now is all 0s:
<img width="396" alt="Screenshot 2023-09-27 at 00 18 41" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/fafe1b7f-3a5b-444b-aa40-98b2da8d6b9a">

The solution is to use the `result` object (obtained after `mi.render()`), which contains the expected noisy environment image:

<img width="374" alt="Screenshot 2023-09-27 at 00 20 01" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/81c0918c-2e9a-4f76-8e44-7d3aee2299dc">

**Comment by rtabbara** [comment]
Hi @georgy95 , this is a related to a previous reported issue and a fix for both is coming soon
