### ISSUE TITLE
Albedo color not matching surface diffuse color

### ISSUE THREAD

**Issue by georgy95** [mitsuba-renderer/mitsuba3#922]
## Summary

I'm not sure if Albedo is computed correctly. I'd expect the albedo map from the AOV integrator to match the input base color of the surface material. But that is not the case. In the example below, a rectangle of color [0.1, 0.1, 0.1] has a much whiter diffuse color. Albedo color != Material diffuse color

## System configuration

System information:

OS: 13.2.1
CPU: b'Apple M1'
Python: 3.10.1 (main, Mar 24 2023, 21:25:11) [Clang 14.0.0 (clang-1400.0.29.202)]
LLVM: 16.0.6

Dr.Jit: 0.4.2
Mitsuba: 3.3.0
Is custom build? True
Compiled with: AppleClang 14.0.0.14000029
Variants:
scalar_rgb
llvm_ad_rgb

## Steps to reproduce

code
```
import os
import mitsuba as mi
mi.set_variant("scalar_rgb")

integrator = {
    "type": "aov",
    "aovs": "albedo:albedo,normals:sh_normal",
    "image": {
        "type": "path",
        "max_depth": 10,
        "rr_depth": 5,
        "hide_emitters": True,
    }
}

principled_diffuse = {
    "type": "principled",
    "base_color": {
        "type": "rgb",
        "value": [0.1, 0.1, 0.1]
    }
}

rectangle = {
    "type": "rectangle",
    "material": principled_diffuse
}

envlight = {
    "type": "constant",
    "radiance": {
        "type": "rgb",
        "value": [1, 1, 1]
    }
}

sensor = {
    "type": "perspective",
    "fov": 90,
    "near_clip": 0.1,
    "far_clip": 10000,
    "to_world": mi.ScalarTransform4f.look_at(
        origin=[0,0,3],
        target=[0,0,0],
        up=[0,1,0]
    ),
    "film": {
        "type": "hdrfilm",
        "width": 1024,
        "height": 1024,
        "pixel_format": "rgba",
        "rfilter": {"type": "box"},
    },
    "sampler": {"type": "independent", "sample_count": 16},
}

scene = {
    "type": "scene",
    "integrator": integrator,
    "envlight": envlight,
    "rectangle": rectangle
}

mi_scene = mi.load_dict(scene)
mi_sensor = mi.load_dict(sensor)
params = mi.traverse(mi_scene)
result = mi.render(scene=mi_scene, sensor=mi_sensor, spp=10)
```

The albedo map is:

<img width="303" alt="Screenshot 2023-09-27 at 10 48 12" src="https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/fed54382-d1c7-4d10-8782-db3ebe838f04">

Expected albedo map:

![Group 35](https://github.com/mitsuba-renderer/mitsuba3/assets/6961787/f774e908-30d4-4302-ad40-80d985121345)

**Comment by rtabbara** [comment]
Hi @georgy95,

I would try to write out the albedo map

```mi.util.write_bitmap("albedo.exr", mi_sensor.film().bitmap().split()[1][1])```

and then inspect the pixels in `tev`. For me, I get the expected linearspace RGB results
![albedo](https://github.com/mitsuba-renderer/mitsuba3/assets/3273442/b207678c-28ce-4c1b-95b6-ac59d3121da9)

**Comment by ljijjiang1234** [comment]
Hi , Did you check RGB value to garantee if they are sRGB gamma correction? I think maybe there are linear-RGB to sRGB conversion in your code
