### ISSUE TITLE
RuntimeError: ​[Endpoint] Projector::eval_direction(): not implemented!

### ISSUE THREAD

**Issue by ljijjiang1234** [mitsuba-renderer/mitsuba3#923]
## Summary

Hi, when I estimate the camera pose of the scene , more specificly , I use directional emitter (Projector ) as emitter , I can not do auto diff on scene parameters all about the geometry. So I cannot estimate the sensor pose or other parameter like mesh position , So would you kindly like to share me about some solution to sovle this Issue about pose estimation in directional emitter ?

## System configuration

System information:

  OS: Windows11
  CPU: i913900k
  GPU: RTX4090
  Python version: 3.11
  LLVM version: ...
  CUDA version: 11.8
  NVidia driver: ...

  Dr.Jit version: 0.4.3
  Mitsuba version: 3.4.0
     Compiled with: pytorch
     Variants compiled: ...

## Steps to reproduce

1. I create a scene to estimate the camera pose of the scene 
2. emitter I choose projector , seems like when projector in the scene, the following error happen:
3. **RuntimeError: ​[Endpoint] Projector::eval_direction(): not implemented!**
## Question
How can I estimate the camera pose when some directional emitter like projector is in the scene.
## Main code
~~~python
#%% 
key="sensor.to_world"
opt = mi.ad.Adam(lr=0.000025)
opt['angle'] = mi.Float(0)
opt['trans'] = mi.Point2f(0, 0)
initial_to_world=params_uncom[key]

def apply_transformation(params, opt):
    opt['trans'] = dr.clamp(opt['trans'], -0.5, 0.5)
    opt['angle'] = dr.clamp(opt['angle'], -0.5, 0.5)
    trafo = mi.Transform4f.translate([opt['trans'].x, opt['trans'].y, 0.0]).rotate([0, 1, 0], opt['angle'] * 100.0)
    params[key] = trafo @ initial_to_world
    params.update()

apply_transformation(params_uncom, opt)
img_init = mi.render(scene_uncom, seed=0, spp=2)
plt.imshow(img_init)
plt.axis("off")
plt.show()




#%%
loss_hist = []
for it in range(50):
    apply_transformation(params_uncom, opt)
    img = mi.render(scene_uncom, params_uncom, seed=it, spp=1)
    #image=torch_func(ccm,img)
    dr.enable_grad(img)
    mi.util.write_bitmap('out/geometry/out_%03i.png' % it,img)
    loss = dr.sum(dr.sqr(img - img_ref)) / len(img_ref)
    dr.backward(loss)
    opt.step()
    loss_hist.append(loss)
    params_uncom.update(opt)
    print(f"Iteration {it:02d}: error={loss[0]:6f}")







~~~ xml emitter
<!--        <emitter type="projector">-->

<!--            <float name="scale" value="10"/>-->
<!--            <float name="fov"  value="65.53183214616236"/>-->
<!--            <texture type="bitmap" name="irradiance">-->
<!--                <string name="filename" value="texture/s.jpg"/>-->
<!--            </texture>-->
<!--            <transform name="to_world">-->
<!--                <lookat origin="-.3618560173,  .07395002211,   .15192131887"-->
<!--                        target="0.53448138,   0.07076841,  0.84221226"-->
<!--                        up    ="0.09169954,-0.99546141, 0.02545145"/>-->
<!--            </transform>-->
<!--        </emitter>-->

**Comment by njroussel** [comment]
Hi @ljijjiang1234 

I've added the missing implementation for `eval_direction` to `master`: https://github.com/mitsuba-renderer/mitsuba3/commit/0c23b01d43e92feab0051a93fc1a9ed5235debe8

**Comment by ljijjiang1234** [comment]
Hi , thanks for your work , a fantastic reasearch renderer help us do some intereting research project!

**Comment by ljijjiang1234** [comment]
<img width="703" alt="image" src="https://github.com/mitsuba-renderer/mitsuba3/assets/73884949/b3066e83-4c83-4e8e-b75a-f760af1f25d1">
Hi ,  after recompile mitsuba3 , maybe other function was not implemented. I guess not reverse function not reload by none parameters , but actually in differentiating camera pose of the scene , it may call the traverse() function ,without any parameters, would you kindly like to tell me how to fix this bug?
