### ISSUE TITLE
eval_cubic_gradient()

### ISSUE THREAD

**Issue by zichenwang01** [mitsuba-renderer/mitsuba3#939]
Hi,

In short, my SDF class uses eval_cubic_gradient() but returns wrong results under CUDA. eval_cubic_gradient() would return the correct result under LLVM, and eval_cubic() would return the correct result under both CUDA and LLVM. I have tested LLVM on win11 and ubuntu and CUDA on ubuntu using 2080ti.

Here is a small reproducer of the problem (apologies for the indentation)

```python
import drjit as dr
import mitsuba as mi

\# mi.set_variant("cuda_ad_rgb")
mi.set_variant("llvm_ad_rgb")

from mitsuba import Float, Point3f, Vector3f

def dist_to_sphere(p : Point3f) -> Float:
    """Signed distance function for a sphere."""
    center = Point3f(0.5, 0.5, 0.5)
    return dr.norm(p - center) - 0.1

class SphereSDF():
    def \_\_init__(self, res=256):
        self.res = res
        grid = dist_to_sphere(dr.meshgrid(
            dr.linspace(Float, 0, 1, res),
            dr.linspace(Float, 0, 1, res),
            dr.linspace(Float, 0, 1, res)
        ))
        grid = mi.TensorXf(grid, shape=(res,res,res,1))
        self.grid = mi.Texture3f(grid)
    def at(self, p:Point3f) -> Float:
        """Return the signed distance at a point."""
        # return self.grid.eval(p)[0]
        return self.grid.eval_cubic(p)[0]
    def gradient(self, p:Point3f) -> Vector3f:
        """Return the gradient of the signed distance at a point."""
        return self.grid.eval_cubic_grad(p)[1][0]
        # return self.grid.eval(p)[1][0]
    
sdf = SphereSDF()

\# print [0.00043045441270805895] under both cuda or llvm
print("sdf at (0.5,0.6,0.5): ", sdf.at(Point3f(0.5,0.6,0.5)))

\# print [[0.0, 0.0, 0.0]] under cuda and [[8.416453312065642e-08, 1.003411054611206, 1.0652104975861221e-07]] under llvm
print("sdf grad at (0.5,0.6,0.5): ", sdf.gradient(Point3f(0.5,0.6,0.5)))
```

**Comment by ziyi-zhang** [comment]
Hi, 

When setting up the 3D grid texture, you can use
```
self.grid = mi.Texture3f(grid, False, False)
```
- The first "False" disables the use CUDA texture query hardware acceleration, which is ~40% (vaguely remember the number) faster than disabled but leads to slightly poor numerical results.
- The second "False" disables migration of the data to GPU. This avoids storing two copies of data, but would lead to zero evaluation of certain functions. Please see source code in `ext/drjit/include/drjit/texture.h` (it's in drjit not mitsuba).

Best

**Comment by zichenwang01** [comment]
I see! Got it working again. So many thanks!
