### ISSUE TITLE
Logger is uninitialized for Python threads

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#950]
Hi,

I ran into an edge case when running Mitsuba functions within Python threads that I don't control directly. In that case, the `Logger` of the current thread won't be initialized and a call to `mi.Log` will try to access a `nullptr` inside `PyLog` (in `core/python/logger.cpp`. A minimal reproducer:

```
import threading
import mitsuba as mi 

def threaded_function():
  mi.set_variant("llvm_ad_rgb")
  mi.Log(mi.LogLevel.Warn, "This will fail")

thread = threading.Thread(target=threaded_function)
thread.start()
thread.join()
```

This segfaults because `Thread.thread().logger()` will be a `nullptr`. I am not sure what's the best fix for this properly. It's easy to check if the logger is a `nullptr` in `PyLog`, but it's unclear to me what's the best way to correctly access the main Logger within a Python thread.

**Comment by rtabbara** [comment]
Hi Delio,

I think the solution in this case is to store the main thread `ThreadEnvironment` (which includes the logger) and then set that in the launched thread using `ScopedSetThreadEnvironment`:
```
import threading
import mitsuba as mi

def threaded_function():
  mi.set_variant("llvm_ad_rgb")
  with mi.ScopedSetThreadEnvironment(env):
      mi.set_log_level(mi.LogLevel.Warn)
      mi.Log(mi.LogLevel.Warn, "This will fail")

mi.set_variant("llvm_ad_rgb")
env = mi.ThreadEnvironment()
thread = threading.Thread(target=threaded_function)
thread.start()
thread.join()
```
I believe the `Logger` itself is thread-safe so I don't think there's any issue with multiple threads sharing the same logger.

**Comment by dvicini** [comment]
Hi Rami,

Thanks, that works! 

Should we maybe throw an exception (with an explanation of the solution) in case the logging function is called and the logger is found to be null? E.g. something like "Cannot use `mi.Log` if no `Logger` instance is set on the current thread. This is likely due to the logging function being called from a non-Mitsuba thread. The solution to this is to use a `ScopedThreadEnvironment` to locally set the logger in the thread"

**Comment by rtabbara** [comment]
Hi Delio,

Sorry for the delay in getting back to this &ndash; I had put up something a while ago but wanted Nicolas to take a look before I merged it and I forgot about that. Based on your suggestion, I've put in [65503b1](https://github.com/mitsuba-renderer/mitsuba3/commit/65503b1dfb4c8779c5631d2118dfe407638ff0b6) which will throw an exception and give users a bit more information when attempting to use the logger outside of a Mitsuba thread.

**Comment by dvicini** [comment]
Perfect, thanks for fixing it!
