### ISSUE TITLE
Retrieving roughness attributes from microfacet-based materials

### ISSUE THREAD

**Issue by joeylitalien** [mitsuba-renderer/mitsuba3#952]
## Summary
It is currently not possible to retrieve roughness values from microfacet-based materials using the newly-introduced `bsdf.eval_attribute()` function. The default value always returns zero and ignores the `alpha` value. I feel like this isn't supposed to happen?

## System configuration

System information:

  OS: Ubuntu 20.04.6 LTS
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  GPU: NVIDIA TITAN V
  Python: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
  NVidia driver: 535.113.01
  CUDA: 11.6.55
  LLVM: 12.0.0

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Steps to reproduce

```python
import mitsuba as mi
mi.set_variant('cuda_ad_rgb')
import drjit as dr

si = dr.zeros(mi.SurfaceInteraction3f)
color = [0.5, 0.6, 0.7]
alpha = 0.2

bsdf = mi.load_dict({
    'type': 'roughplastic',
    'diffuse_reflectance': { 'type': 'rgb', 'value': color },
    'alpha': alpha
})

assert dr.all(bsdf.has_attribute('diffuse_reflectance')) # Ok
assert dr.all(bsdf.has_attribute('alpha')) # Ok
assert dr.allclose(color, bsdf.eval_attribute('diffuse_reflectance', si)) # Ok
eval_alpha = bsdf.eval_attribute_1('alpha', si)
assert dr.allclose(alpha, eval_alpha), print(eval_alpha) # Not ok, prints [0.0]
```

**Comment by njroussel** [comment]
Hi @joeylitalien 

Thanks for the bug report!
I've pushed a fix to `master`: https://github.com/mitsuba-renderer/mitsuba3/commit/30f788c00adc3eb717be644dbb04a4f2c2b2d015
