### ISSUE TITLE
Memory keep increasing during iterative rendering

### ISSUE THREAD

**Issue by duongnlt** [mitsuba-renderer/mitsuba3#954]
## Summary
I try to render multiple scene with `for` loop and my RAM always increase which eventually crashes the whole program.

## System configuration

System information:

  OS: Ubuntu 20.04
  CPU: 12th Gen Intel(R) Core(TM) i5-12400
  GPU: NVIDIA GeForce RTX 3060
  Python version: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
  LLVM version: 10.0.0
  CUDA version: 12.2
  NVidia driver: 535.104.12

  Dr.Jit version: 0.4.3
  Mitsuba version: 3.4.0
     Compiled with: Clang 10.0.0
     Variants compiled:
       scalar_rgb
        scalar_spectral
        llvm_rgb
        llvm_ad_rgb
        llvm_spectral
        cuda_rgb
        cuda_ad_rgb
        cuda_spectral
        scalar_rgb_polarized
        scalar_rgb_polarized_double
        scalar_spectral_polarized
        scalar_spectral_polarized_double
        cuda_rgb_polarized
        cuda_rgb_polarized_double
        cuda_spectral_polarized
        cuda_spectral_polarized_double
        llvm_spectral_polarized

## Steps to reproduce

```python
from tqdm import tqdm
import mitsuba as mi
import drjit as dr
import numpy as np
import gc
np.random.seed(99)

mi.set_variant('scalar_spectral_polarized')
from mitsuba import ScalarTransform4f as T



BRDF_FILES = {f.split('.')[0]: os.path.join('/mitsuba3/scene/BRDF', f) for f in os.listdir('../scene/BRDF') if not f.startswith('.')}
POLARIZER_ANGLES = [0, 45, 90, 135]

sensor = mi.load_dict({
    'type': 'perspective',
    'fov': 41,
    'fov_axis': 'larger',
    'to_world': T.translate([0,0,-10]),
    'sampler': {
        'type': 'independent',
        'sample_count': 256
    },
    'film': {
        'type': 'hdrfilm',
        'width': 612,
        'height': 512,
        'pixel_format': 'rgba',
        'rfilter': {
            'type': 'gaussian'
        }
    }

    
})
LIGHT_SOURCES = {}
for i in range(20):
    LIGHT_SOURCES[f'light-{i+1}'] = {
        'type': 'point',
        'position': [np.random.uniform(-20, 20), np.random.uniform(-20, 20), np.random.uniform(-30, -5)],
        'intensity': {
            'type': 'spectrum',
            'value': np.random.uniform(50, 500)
        }
    }

import json
with open('../output/diligent/light_sources.json', 'w') as f:
    json.dump(LIGHT_SOURCES, f)

integrator = mi.load_dict({
    'type': 'stokes',
    'integrator': {
        'type': 'path'
    }
})

for obj in ['bear','reading', 'buddha', 'pot2', 'cow']:
    root_folder = f'/mitsuba3/output/diligent/{obj}'
    print(root_folder)
    if not os.path.exists(root_folder):
        os.mkdir(root_folder)
    hp.setrelheap()
    for brdf_name, brdf_file in tqdm(BRDF_FILES.items(), total=len(BRDF_FILES.items())):
        if brdf_file == '':
            continue
        bsdf = {
            'type': 'measured_polarized',
            'filename': brdf_file,
            'alpha_sample': 0.1
        }
        base_name = os.path.join(root_folder, brdf_name)
        if not os.path.exists(base_name):
            os.mkdir(base_name)
        object = mi.load_dict({
                        'type': 'ply',
                        'filename': f'../scene/meshes/{obj}.ply',
                        'bsdf': bsdf,
                        'to_world': T.translate([1.7,-1,0]).scale(0.02).rotate(axis=[1,0,0], angle=-90).rotate(axis=[0,0,1], angle=90),
                    })
        for light, light_val in LIGHT_SOURCES.items():
            folder_name = os.path.join(base_name, light)
            if not os.path.exists(folder_name):
                os.mkdir(folder_name)
            for p_angles in POLARIZER_ANGLES:
                polarizer = mi.load_dict({
                    'type': 'rectangle',
                    'bsdf': {
                        'type': 'polarizer',
                        'theta': {
                            'type': 'spectrum',
                            'value': p_angles
                        }
                    },
                    'to_world': T.translate([0,0,-8]).rotate(axis=[0, 1, 0], angle=-180)
                })
                filename = os.path.join(folder_name, f'{obj}_p{p_angles}')
                scene = mi.load_dict({
                    'type':'scene',
                    'integrator': integrator,
                    'sensor': sensor,
                    'emitter': light_val,
                    'polarizer': polarizer,
                    'object': object
                         
                })
                image = mi.render(scene, seed=np.random.choice(100000,1, replace=False))
                bitmap = mi.Bitmap(image, channel_names=['R', 'G', 'B', 'A'] + scene.integrator().aov_names())
                bitmap.write(f'{filename}.exr')
                channels = dict(bitmap.split())
                mi.Bitmap(channels['S0']).convert(mi.Bitmap.PixelFormat.RGB, mi.Struct.Type.UInt8, True).write(f"{filename}.png")
                print(filename) 
```

**Comment by njroussel** [comment]
Hi @duongnlt 

Thank you for the reproducer. What have you tried so far? 
Have you tried bisecting your code? By slowly removing parts, you should be able to find the culprit.

**Comment by duongnlt** [comment]
> Hi @duongnlt
> 
> Thank you for the reproducer. What have you tried so far? Have you tried bisecting your code? By slowly removing parts, you should be able to find the culprit.

Hello @njroussel

Based on your suggestion, I find that the cause of this problem is the `object` part. When I use the built-in shape `sphere`, the memory is always steady. But when I change it back to `ply`, which requires loading from a PLY file, the memory start increasing again. It seems like at each iteration when the `mi.render()` is called, the PLY object is loaded into the memory again, leading to

**Comment by yugitw** [comment]
Hi @duongnlt, could you post your solution here? We seemed to have a similar memory leak problem as well.

**Comment by duongnlt** [comment]
> Hi @duongnlt, could you post your solution here? We seemed to have a similar memory leak problem as well.

Hi @yugitw, sorry for the late reply. I actually had to update to the latest version and change the variant to `cuda_spectral_polarized` to avoid that memory leak. It seems like the `scalar_spectral_polarized` variant keeps loading the scene again and again after each iteration.

**Comment by tasty0tomato** [comment]
I encountered the same bug. Based on my tests, it seems that the issue is with `mitsuba.load_dict.` It doesn't release memory after each loop iteration. I haven't tested it in a CUDA environment, but since this issue occurs in a CPU environment, it should be considered a bug and needs to be reopened.

**Comment by merlinND** [comment]
Hello @tasty0tomato,

Could you please open a new issue with all the details requested in the issue template and your minimal reproducer code?
