### ISSUE TITLE
Retrieving shape index from intersection

### ISSUE THREAD

**Issue by joeylitalien** [mitsuba-renderer/mitsuba3#955]
## Summary

It doesn't seem possible to retrieve the shape index associated with an intersection point.

## System configuration

System information:

  OS: Ubuntu 20.04.6 LTS
  CPU: Intel(R) Core(TM) i7-9800X CPU @ 3.80GHz
  GPU: NVIDIA TITAN V
  Python: 3.10.13 (main, Aug 25 2023, 13:20:03) [GCC 9.4.0]
  NVidia driver: 535.113.01
  CUDA: 11.6.55
  LLVM: 12.0.0

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? False
     Compiled with: GNU 10.2.1
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb

## Description

Sorry it's me again... I'm a bit confused how `mi.PreliminaryIntersection3f.shape_index` is implemented; is there a way to access it through a `mi.ShapePtr`? I'm currently trying to detect if a certain intersection occurs with a given shape so I can do something on the resulting active lanes. However, the behavior changes depending on the variant. For instance, `cuda_ad_rgb` returns `[0]` all the time even if there are many objects in the scene, while `llvm_ad_rgb` returns 2<sup>32</sup> - 1 (as initialized) or `None` depending on the scene.

Ideally, I would like to be able to do `my_active = active & dr.eq(pi.shape_index, idx)` to select all lanes that intersect shape `idx`. Is this possible? Assuming the backend is indeed wavefront, I would expect `pi.shape_index` to be available somewhere before proceeding to the next bounce but it doesn't seem to be the case.

As a temporary (abomination of a) fix, I'm currently achieving this through a regex on the `PlyMesh` names in `mi.PreliminaryIntersection3f.shape`. AFAIK, `mi.SurfaceInteraction3f` doesn't expose this field either, so I'm a bit stuck here.

## Steps to reproduce

```python
import mitsuba as mi
mi.set_variant('llvm_ad_rgb')
import drjit as dr

class MyIntegrator(mi.SamplingIntegrator):
    def __init__(self, props = mi.Properties()):
        super().__init__(props)

    def sample(
        self,
        scene: mi.Scene,
        sampler: mi.Sampler,
        ray: mi.RayDifferential3f,
        medium: mi.Medium = None,
        active: bool = True,
        ) -> tuple[mi.Color3f, bool, list[float]]:
        
        L = mi.Spectrum(0)
        ray = mi.Ray3f(ray)
        active = mi.Bool(active)

        pi: mi.PreliminaryIntersection3f = scene.ray_intersect_preliminary(ray)
        print(pi.shape_index) # What's going on here?

        return L, mi.Bool(True), []

mi.register_integrator('my_integrator', lambda props: MyIntegrator(props))

scene = mi.load_dict(mi.cornell_box())
integrator = mi.load_dict({'type': 'my_integrator'})

mi.render(scene, integrator=integrator, spp=1)
```

**Edit:** Found [this thread](https://github.com/mitsuba-renderer/mitsuba3/discussions/882) from two months ago, can you confirm that `shape_idx = dr.reinterpret_array_v(mi.UInt, pi.shape)` indeed gets the shape index as wanted?

**Comment by rtabbara** [comment]
Hi @joeylitalien,

There's a few discussions #663 and #813 about why `shape_index` is ill-suited for what you're after and as you've alluded to directly checking shape pointers is one approach you could use to achieve what you're after. e.g.
```python
import mitsuba as mi
mi.set_variant('llvm_ad_rgb')
import drjit as dr

class MyIntegrator(mi.SamplingIntegrator):
    def __init__(self, props = mi.Properties()):
        super().__init__(props)

    def sample(
        self,
        scene: mi.Scene,
        sampler: mi.Sampler,
        ray: mi.RayDifferential3f,
        medium: mi.Medium = None,
        active: bool = True,
        ) -> tuple[mi.Color3f, bool, list[float]]:
        
        L = mi.Spectrum(0)
        ray = mi.Ray3f(ray)
        active = mi.Bool(active)

        pi: mi.PreliminaryIntersection3f = scene.ray_intersect_preliminary(ray)

        # As an example, only interested in the first shape listed in the scene
        my_active = active & dr.eq(pi.shape, sh[0]) 
        
        # How many rays hit this shape
        print(dr.width(dr.compress(my_active)))
        
        return L, mi.Bool(True), []

mi.register_integrator('my_integrator', lambda props: MyIntegrator(props))

scene = mi.load_dict(mi.cornell_box())

#Fetch all unique shape instances here
sh = scene.shapes()

integrator = mi.load_dict({'type': 'my_integrator'})

mi.render(scene, integrator=integrator, spp=1)
```
As mentioned in #663,  there may not be consistent ordering across multiple `load_dict` invocations so please keep that in mind

**Comment by joeylitalien** [comment]
Sounds good, thanks. Do you know why there is no consistent ordering when loading dictionaries? It would be quite convenient to be able to index these shapes by IDs instead. For example, `my_active = active & dr.eq(pi.shape.id, 'my_id')`.

**Comment by rtabbara** [comment]
> Do you know why there is no consistent ordering when loading dictionaries?

By default, scene loading is performed across multiple threads and hence can cause an inconsistent order of instantiation. You can disable this by setting the `load_dict` argument `parallel=false`.

> It would be quite convenient to be able to index these shapes by IDs instead

In this instance, you can use `dr.dispatch`:

```python
import mitsuba as mi
import drjit as dr

mi.set_variant('llvm_ad_rgb')

class MyIntegrator(mi.SamplingIntegrator):
    def __init__(self, props = mi.Properties()):
        super().__init__(props)

    def sample(
        self,
        scene: mi.Scene,
        sampler: mi.Sampler,
        ray: mi.RayDifferential3f,
        medium: mi.Medium = None,
        active: bool = True,
        ) -> tuple[mi.Color3f, bool, list[float]]:
        
        L = mi.Spectrum(0)
        ray = mi.Ray3f(ray)
        active = mi.Bool(active)

        pi: mi.PreliminaryIntersection3f = scene.ray_intersect_preliminary(ray)
        id_idx = 0
        my_active = active & dr.dispatch(pi.shape, check_shape_id, id_idx)

        # How many rays hit this shape
        print(dr.width(dr.compress(my_active)))

        return L, mi.Bool(True), []

mi.register_integrator('my_integrator', lambda props: MyIntegrator(props))

def check_shape_id(self, id_index):
    return mi.Bool(self.id() == sh_ids[id_index])

scene = mi.load_dict(mi.cornell_box())

sh_ids = [x.id() for x in scene.shapes()]

integrator = mi.load_dict({'type': 'my_integrator'})

mi.render(scene, integrator=integrator, spp=1)
```

**Comment by joeylitalien** [comment]
Sounds good! Sorry I forgot to close the issue.
