### ISSUE TITLE
Wrong normal map rendering

### ISSUE THREAD

**Issue by damonhust99** [mitsuba-renderer/mitsuba3#956]
## Summary

Normal map rendered by Mitsuba is different from the expected normal map

## System configuration

System information:

  OS:  Ubuntu 20.04
  CPU: 12th Gen Intel(R) Core(TM) i5-12400
  GPU: NVIDIA GeForce RTX 3060
  Python version: 3.8.10 (default, May 26 2023, 14:05:08) [GCC 9.4.0]
  LLVM version: 10.0.0
  CUDA version: 12.2
  NVidia driver: 535.104.12

  Dr.Jit version: 0.4.3
  Mitsuba version: 3.4.0
     Compiled with: Clang 10.0.0
     Variants compiled:
scalar_rgb
scalar_spectral
llvm_rgb
llvm_ad_rgb
llvm_spectral
cuda_rgb
cuda_ad_rgb
cuda_spectral
scalar_rgb_polarized
scalar_rgb_polarized_double
scalar_spectral_polarized
scalar_spectral_polarized_double

## Description

Normal map render by mitsuba

![image](https://github.com/mitsuba-renderer/mitsuba3/assets/149037233/d54ae603-ad52-4f3f-9d2c-15f9a58b4d91)

Expected normal map

![Normal_gt](https://github.com/mitsuba-renderer/mitsuba3/assets/149037233/061e7537-b431-460e-bdc8-aadba1c16f53)

## Steps to reproduce

```python
import mitsuba as mi
import drjit as dr
import numpy as np

mi.set_variant('scalar_rgb')
from mitsuba import ScalarTransform4f as T

sensor = mi.load_dict({
    'type': 'perspective',
    'fov': 41,
    'fov_axis': 'larger',
    'to_world': T.translate([0,0,-10]),
    'sampler': {
        'type': 'multijitter',
        'sample_count': 128
    },
    'film': {
        'type': 'hdrfilm',
        'width': 612,
        'height': 512,
        'pixel_format': 'rgb',
        'rfilter': {
            'type': 'gaussian'
        }
    }
        
})
integrator = mi.load_dict({
                'type': 'aov',
                'aovs': 'd:depth,nn:geo_normal'
    
            },)

bear = mi.load_dict({
            'type': 'ply',
            'filename': 'bear.ply',
                
            'to_world': T.translate([1.7,-1,0]).scale(0.02).rotate(axis=[1,0,0], angle=-90).rotate(axis=[0,0,1], angle=90),
            'flip_normals': True,
            'bsdf': {
                'type': 'diffuse'
            },
})
scene = mi.load_dict({
            'type':'scene',
            'integrator': integrator,
            'sensor': sensor,
            'object': bear,
            
            'light': {'type': 'constant'},   
    
})

image = mi.render(scene)
bmp = scene.sensors()[0].film().bitmap().split()[2][1]

```

**Comment by rtabbara** [comment]
Hi @ damonhust99, 

It might be worth outputting the shading `sh_normal` rather than geometric normal in the AOVs to see if that aligns with your reference. Otherwise, I would need the `bear.ply` file to try to reproduce the issue locally.

**Comment by damonhust99** [comment]
> Hi @ damonhust99,
> 
> It might be worth outputting the shading `sh_normal` rather than geometric normal in the AOVs to see if that aligns with your reference. Otherwise, I would need the `bear.ply` file to try to reproduce the issue locally.

Hi @rtabbara,

When I switch to `sh_normal` the normal output does not change. Here is my `bear.ply` [file](https://drive.google.com/file/d/1pyjn4pTdpCBIIZhF6LgbPD7mnTbsiUvq/view?usp=sharing)

**Comment by rtabbara** [comment]
Hi @damonhust99,

Thanks for the blender file! I believe in the end this is just a range clipping issue when attempting to visualise negative RGB values. If I manually map the non-zero output normals `(x,y,z) -> (0.5x + 0.5, -0.5y + 0.5, 0.5z + 0.5)` then I get:
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/3273442/7dcc2c5c-7c68-4753-965a-4a1f9f5f829f)



When visualising normals in other 3D tools like Blender that transformation is often implicitly applied.
