### ISSUE TITLE
[🐛bug report] `import mitsuba` fails in Blender's integrated Python environment

### ISSUE THREAD

**Issue by ros-dorian** [mitsuba-renderer/mitsuba3#973]
## Summary

Running `import mitsuba` fails in integrated Python console of Blender 3.6.5 LTS.

## System configuration

System information:

```
  OS: Windows-10
  CPU: Intel64 Family 6 Model 151 Stepping 2, GenuineIntel
  GPU: NVIDIA GeForce RTX 3080
  Python: 3.10.13 (main, Oct 10 2023, 08:34:31) [MSC v.1928 64 bit (AMD64)]
  NVidia driver: 546.01
  LLVM: -1.-1.-1

  Dr.Jit: 0.4.3
  Mitsuba: 3.4.0
     Is custom build? False
     Compiled with: MSVC 19.37.32822.0
     Variants:
        scalar_rgb
        scalar_spectral
        cuda_ad_rgb
        llvm_ad_rgb
```

## Description

In order to make the Mitsuba add-on for Blender work, it is necessary to install the Mitsuba package inside of Blender's integrated Python environment. The Python version bundled with Blender is 3.10.13 which fills Mitsuba's requirements.

However, importing Mitsuba inside of Blender's Python console leads to the following stacktrace:
![image](https://github.com/mitsuba-renderer/mitsuba3/assets/22654601/83d7013c-dc3e-4685-864a-b4b957bb74fa)

Interestingly, this problem does not arise when starting a Python prompt straight from the executable in Blender's installation folder.

I would love to get your input on this issue.

## Steps to reproduce

1. Install Blender 3.6.5 LTS (installer or standalone).
2. Go to Blender installation folder, then `3.6\python\bin`.
3. Run `python.exe pip install mitsuba` to install Mitsuba into Blender's Python environment.
4. Start the prompt with `python.exe` and run `import mitsuba`. This should succeed.
5. Start Blender 3.6.5, then go to the `Scripting` tab and open a new Python console.
6. Run `import mitsuba`. This should fail.

**Comment by bathal1** [comment]
Hi Dorian,

PR #929 should normally have fixed this. The issue was a dynamic library version clash between Blender and Mitsuba. This should be fixed already if using a custom Mitsuba build, and will be in the next release as well.
