### ISSUE TITLE
Inconsistent read behavior between MemoryStream and FileStream

### ISSUE THREAD

**Issue by dvicini** [mitsuba-renderer/mitsuba3#978]
Hi,

I came across an inconsistency between `MemoryStream` and `FileStream`. The `FileStream` allows for reads to go beyond the file size. The internally used `std::fstream` will read as far as the file goes and gracefully stop without an error. The `MemoryStream` on the other hand raises an error if a read goes beyond its size. 

This causes inconsistent behavior when using the MemoryStream in conjunction with the Bitmap class. The following code will raise an error due to the JPEG library reading in chunks of 2^15 bytes:

```python
import os
import mitsuba as mi
import numpy as np
mi.set_variant('llvm_ad_rgb')

img = np.random.rand(64, 64, 3)

fn = '/tmp/img.jpg'
mi.Bitmap(img).convert(mi.Bitmap.PixelFormat.RGB, mi.Struct.Type.UInt8, False).write(fn)

stream = mi.MemoryStream()
with open(fn, 'rb') as f: 
  stream.write(f.read())

# By uncommenting the following line we can get this code to work, but having to manually pad is a bit ugly.
# stream.write(np.zeros(stream.size() % 2**15 , dtype=np.uint8).tobytes())

stream.seek(0)
img = mi.Bitmap(stream)
```
We can make this code work by manually padding the data in the memory stream, but this needs a priori knowledge of the Bitmap's loading behavior. 

Would it make sense to change the implementation of `MemoryStream` to mirror the `FileStream`'s behavior, i.e., to not throw an error when reading beyond the size and simply ensuring that we never perform an actually invalid memory read? Interestingly, the code to compute correct access is already there, but it's followed by an exception.

**Comment by wjakob** [comment]
That would be fine with me. But it could potentially be costly if the memory stream has to be resized many times. One option would be to implement it in terms of a C library operation like `realloc`

**Comment by dvicini** [comment]
What do you mean?

What I am suggesting is to just change the read(...) function to not throw an error. I would just remove the explicit `Log(Error, ...)`. The computation of how many bytes are still available to read is already in there:


```
@@ -23,20 +23,16 @@ void MemoryStream::read(void *p, size_t 
         Throw("Attempted to read from a closed stream: %s", to_string());
 
     if (m_pos + size > m_size) {
-        const auto old_pos = m_pos;
         // Use signed difference since `m_pos` might be beyond `m_size`
         int64_t size_read = m_size - static_cast<int64_t>(m_pos);
         if (size_read > 0) {
             memcpy(p, m_data + m_pos, static_cast<size_t>(size_read));
             m_pos += static_cast<size_t>(size_read);
         }
-        Log(Error, "Reading over the end of a memory stream!"
-                   " (amount requested = %llu, amount actually read = %llu,"
-                   " total size of the stream = %llu, previous position = %llu)",
-            size, size_read, m_size, old_pos);
+    } else {
+        memcpy(p, m_data + m_pos, size);
+        m_pos += size;   
     }
-    memcpy(p, m_data + m_pos, size);
-    m_pos += size;
 }
```

**Comment by wjakob** [comment]
Okay, that makes a ton of sense. I just had a second to look at the comment yesterday and was thinking about writing beyond the end of a stream. Since the `read()` function return show many bytes were actually read, it's perfectly fine to implement the operation in that way (and that exception is weird). Feel free to just directly push the change.

**Comment by dvicini** [comment]
Yes exactly, this is just about reading. I will merge the PR in that case, it also adds a few tests that the memory stream write & read operations for images keep working.
