### ISSUE TITLE
Is it possible to edit Radiance Field Reconstruction scene?

### ISSUE THREAD

**Issue by Lezcool** [mitsuba-renderer/mitsuba3#987]
After using [Radiance Field Reconstruction](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/radiance_field_reconstruction.html) to reconstruct a scene, is there any way to edit it? Like adding a light source?

I know that since it reconstructs a radiance field which is not a mesh, it cannot be edited directly. Is there any feasible way to convert the result into a mesh and render it with mitsuba?

**Comment by njroussel** [comment]
Hi @Lezcool 

No, we don't provide any utilities to perform such operations.
