### ISSUE TITLE
BItmap texture when using metallic or roughness

### ISSUE THREAD

**Issue by ljijjiang1234** [mitsuba-renderer/mitsuba3#991]
Hi , I was editing the metallic or roughness texture Bitmap using Principled BSDF , but seems like the parameters interface when I import was an RGB bitmap , I was confused about how mitsuba do any transform from RGB texture to gray_scale map for them , or simply slice for one of the channel as the map , would you kindly like to tell me about how mitsuba process for rendering when given RGB Bitmap to the roughness map or metallic map.

**Comment by njroussel** [comment]
Hi @ljijjiang1234 

For such use cases, the plugins usually use the `eval_1` interface of the `Texture`: https://mitsuba.readthedocs.io/en/latest/src/api_reference.html#mitsuba.Texture.eval_1
For RGB textures, it will compute the luminance of the pixel value. This typically not what you'd want, and you should be passing a single-channel file to the `bitmap` plugin.

**Comment by njroussel** [comment]
(Here's the relevant part of the source code: https://github.com/mitsuba-renderer/mitsuba3/blob/master/src/bsdfs/principled.cpp#L349)
