### ISSUE TITLE
[bug report] `type_mask_to_string` in `bsdf.cpp` does not work properly

### ISSUE THREAD

**Issue by class255** [mitsuba-renderer/mitsuba3#992]
## Summary

In python `print(ctx)` does not shows its attribute `ctx.type_mask` properly when `ctx` is an instance of `mi.BSDFContext`.

## System configuration

System information:

  OS: Windows 11
  CPU: 12th Gen Intel(R) Core(TM) i9-12900K   3.19 GHz
  GPU: NVIDIA GeForce RTX 4090
  Python version: 3.11
  LLVM version: ...
  CUDA version: 12.0
  NVidia driver: 528.02

  Dr.Jit version: 0.4.2
  Mitsuba version: 3.3.0
     Compiled with: Manually compiled with CMake & Visual Studio
     Variants compiled: ['scalar_rgb', 'scalar_spectral', 'cuda_ad_rgb', 'llvm_ad_rgb', 'scalar_rgb_polarized', 'scalar_spectral_polarized', 'cuda_rgb', 'cuda_spectral', 'cuda_rgb_polarized', 'cuda_spectral_polarized', 'llvm_rgb', 'llvm_spectral', 'llvm_rgb_polarized', 'llvm_spectral_polarized', 'cuda_ad_rgb_polarized', 'cuda_ad_spectral_polarized', 'cuda_ad_spectral_polarized_double', 'llvm_ad_rgb_polarized', 'llvm_ad_spectral_polarized', 'llvm_ad_spectral_polarized_double']

## Description
My code is:
```(python)
import mitsuba as mi
mi.set_variant('scalar_rgb')

ctx = mi.BSDFContext()
print(ctx)
print(f"{ctx.type_mask = }")
print(f"{mi.has_flag(ctx.type_mask, mi.BSDFFlags.All) = }")

print("\n# Set ctx.type_mask = mi.BSDFFlags.DiffuseReflection")
ctx.type_mask = mi.BSDFFlags.DiffuseReflection
print(ctx)
print(f"{ctx.type_mask = }")
print(f"{mi.has_flag(ctx.type_mask, mi.BSDFFlags.All) = }")
```
The printed results are:
```
BSDFContext[
  mode = radiance,
  type_mask = { all },
  component = all
]
ctx.type_mask = 511
mi.has_flag(ctx.type_mask, mi.BSDFFlags.All) = True

# Set ctx.type_mask = mi.BSDFFlags.DiffuseReflection
BSDFContext[
  mode = radiance,
  type_mask = { all },
  component = all
]
ctx.type_mask = 2
mi.has_flag(ctx.type_mask, mi.BSDFFlags.All) = True
```
Even if I set
`ctx.type_mask = mi.BSDFFlags.DiffuseReflection`,
`print(ctx)` shows `... type_mask = { all  }`, while manually printing the attribute `print(ctx.type_mask)` shows the value itself has been properly modified.

It seems due to `mi.has_flag(ctx.type_mask, mi.BSDFFlags.All) = True`.

Is it a bug? or is this code is an unpreferable usage?

Thanks, in advance.

**Comment by njroussel** [comment]
Hi @class255 

Thank you for the reproducer, indeed this is a bug.
